### PR TITLE
firefox: Bump to 107.0.1

### LINKED ISSUE #13013: [Bug]: Firefox homepage fails to load
### Problem description

Last two releases of Firefox have had the failure of the default homepage failing to load. I have done a clean reinstall, including the deletion of .cache, .config .mozilla files etc....  

### What steps will reproduce the bug?

Launch Firefox.
This is the result:-
Screenshot_20221111-214550

### What is the expected behavior?

Homepage is displayed.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=13006
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.utermux.dev/termux/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://mirrors.utermux.dev/termux/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.utermux.dev/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.31.0
Android version:
11
Kernel build information:
Linux localhost 4.9.227-perf+ #1 SMP PREEMPT Fri Nov 26 00:14:01 CST 2021 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6003

```

### PR DESCRIPTION
**Pull request by kawanakaiku**
closes #13013

### CODE REVIEW

File: x11-packages/firefox/build.sh [hunk 1]
```diff
@@ -66,7 +61,7 @@ termux_step_configure() {
 		--with-system-webp \
 		--with-system-zlib \
 		--without-wasm-sandboxed-libraries \
-		--with-branding=browser/branding/aurora \
+		--with-branding=browser/branding/official \
```
Comment (xtkoba) [inline x11-packages/firefox/build.sh:64]: Does not this cause legal issues? (I'm not familiar with the Firefox Branding policy.)

Comment (kawanakaiku) [reply x11-packages/firefox/build.sh:64]: I don't know too. But I doubt that this is illegal.
Seeing build scripts of Debian and Arch Linux, they both enable official branding (```--enable-official-branding```).
```Branding``` seems to be explained here https://firefox-source-docs.mozilla.org/browser/branding/docs/index.html.

Comment (xtkoba) [reply x11-packages/firefox/build.sh:64]: OK then go ahead.
