### PR TITLE
addpkg(x11/spectacle): 6.4.4

### LINKED ISSUE #25838: [Package]: kde-spectacle
### Why is it worth to add this package?

KDE screenshooter utility tool.

Spectacle captures images of the screen. It can capture the whole screen, a specified region, an individual window, or only part of a window

### Home page URL

_No response_

### Source code URL

https://invent.kde.org/plasma/spectacle

### Packaging policy acknowledgement

- [x] The project is actively developed.
- [x] The project has [existing packages](https://repology.org/projects/) and is "well known".
- [x] Licensed under an [open source license](https://spdx.org/licenses/).
- [x] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [x] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [x] Not duplicating the functionality of existing packages.
- [x] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [x] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by BullyMaguire-lol**
This pull request adds the `spectacle` package to the Termux repository.

* Fixes #25838

### CODE REVIEW

File: x11-packages/spectacle/build.sh [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+TERMUX_PKG_MAINTAINER="@termux"
+TERMUX_PKG_VERSION="6.4.4"
+TERMUX_PKG_SRCURL="https://download.kde.org/stable/plasma/${TERMUX_PKG_VERSION}/spectacle-${TERMUX_PKG_VERSION}.tar.xz"
+TERMUX_PKG_SHA256="9108a739c1acc43b23e0a6aa17ba4194a564ab1548c6887328c76a073bf3d373"
+TERMUX_PKG_AUTO_UPDATE=true
+TERMUX_PKG_DEPENDS="libc++, kf6-kconfig, kf6-kconfigwidgets, kf6-kcoreaddons, kf6-kcrash, kf6-kdbusaddons, kf6-kglobalaccel, kf6-kguiaddons, kf6-ki18n, kf6-kio, kf6-kirigami, kf6-kjobwidgets, kf6-knotifications, kpipewire, kf6-kservice, kf6-kstatusnotifieritem, kf6-kwidgetsaddons, kf6-kwindowsystem, kf6-kxmlgui, layer-shell-qt, libxcb, opencv, kf6-prison, kf6-purpose, qt6-qtbase, qt6-qtdeclarative, qt6-qtimageformats, qt6-qtmultimedia, qt6-qtwayland, libwayland, xcb-util, xcb-util-cursor, xcb-util-image"
+TERMUX_PKG_BUILD_DEPENDS="extra-cmake-modules, plasma-wayland-protocols"
+TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
+-DCMAKE_SYSTEM_NAME=Linux
+-DKF6_HOST_TOOLING=$TERMUX_PREFIX/opt/kf6/cross/lib/cmake/
```
Comment (robertkirkman) [inline x11-packages/spectacle/build.sh]: Could you add `-DKF6_HOST_TOOLING` in the same way that Biswa96 has for `konsole` in order to prevent the error during on-device building?

```
-- Build files have been written to: /data/data/com.termux/files/home/.termux-build/spectacle/build
[5/194] Generating settings.h, settings.cpp
FAILED: [code=127] src/settings.h src/settings.cpp /data/data/com.termux/files/home/.termux-build/spectacle/build/src/settings.h /data/data/com.termux/files/home/.termux-build/spectacle/build/src/settings.cpp 
cd /data/data/com.termux/files/home/.termux-build/spectacle/build/src && /data/data/com.termux/files/usr/opt/kf6/cross/lib/libexec/kf6/kconfig_compiler_kf6 /data/data/com.termux/files/home/.termux-build/spectacle/src/src/Gui/SettingsDialog/spectacle.kcfg /data/data/com.termux/files/home/.termux-build/spectacle/src/src/Gui/SettingsDialog/settings.kcfgc -d /data/data/com.termux/files/home/.termux-build/spectacle/build/src/
/data/data/com.termux/files/usr/bin/sh: 1: /data/data/com.termux/files/usr/opt/kf6/cross/lib/libexec/kf6/kconfig_compiler_kf6: not found
[15/194] Automatic MOC for target spectacle-24.02.0-keep_old_save_location
ninja: build stopped: subcommand failed.
```

https://github.com/termux/termux-packages/blob/e87cf7c5df81f41c8b6a47ab756acaa75b479c08/x11-packages/konsole/build.sh#L12-L16

Note that `kdenlive` might also have this problem, but we can eventually fix that separately. Mainly I am interested in attempting to avoid creating further, new instances of packages that fail to build on-device if it's easy to avoid doing so.

**Review by robertkirkman — CHANGES_REQUESTED** [review]

File: x11-packages/libva/build.sh [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+TERMUX_PKG_LICENSE="MIT"
+TERMUX_PKG_MAINTAINER="@termux"
+TERMUX_PKG_VERSION="2.22.0"
+TERMUX_PKG_SRCURL="https://github.com/intel/libva/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz"
+TERMUX_PKG_SHA256="467c418c2640a178c6baad5be2e00d569842123763b80507721ab87eb7af8735"
+TERMUX_PKG_AUTO_UPDATE=true
+TERMUX_PKG_DEPENDS="libc++, libdrm, libx11, libxext, libxfixes, libwayland"
+TERMUX_PKG_BUILD_DEPENDS="libglvnd, mesa, mesa-dev"
+termux_step_pre_configure() {
+termux_setup_wayland_cross_pkg_config_wrapper
```
Comment (robertkirkman) [inline x11-packages/libva/build.sh]: I think that this could be indented with a tab character for consistency with other function definitions.

**Review by robertkirkman — CHANGES_REQUESTED** [review]

**Review by robertkirkman — APPROVED** [review]
Screenshot is working, but screen recording is not working.

That is pretty much OK because the utility's main functionality was originally as a screenshot tool.

There is already a package for recording Termux:X11 that does work, `recordmydesktop` (I don't use it regularly, but I have tested it just now to confirm it is still working and it is), and in my opinion, screen recording inside Termux:X11 is probably not very efficient or high-performance, and if there ever really is a need to do that, the primary software to package should be [OBS](https://obsproject.com/).

The screen recording software APKs on F-Droid, and the ADB softare [scrcpy](https://github.com/Genymobile/scrcpy), are both most likely more efficient and hardware-accelerated for screen recording Android than X11 recorders.

However, if you can ever figure out how to get the screen recording of Spectacle to work, that would still be great, I have just explained that I think it's not a big priority because there are already a lot of other ways to screen record that already work and are designed more specifically for that.

**Comment by BullyMaguire-lol** [comment]
> Screenshot is working, but screen recording is not working.
> 
> That is pretty much OK because the utility's main functionality was originally as a screenshot tool.
> 
> There is already a package for recording Termux:X11 that does work, `recordmydesktop` (I don't use it regularly, but I have tested it just now to confirm it is still working and it is), and in my opinion, screen recording inside Termux:X11 is probably not very efficient or high-performance, and if there ever really is a need to do that for some reason, the primary software to package should be [OBS](https://obsproject.com/).
> 
> The screen recording software APKs on F-Droid, and the ADB software [scrcpy](https://github.com/Genymobile/scrcpy), are both most likely more efficient and hardware-accelerated for screen recording Android than X11 recorders.
> 
> However, if you can ever figure out how to get the screen recording of Spectacle to work, that would still be great, I have just explained that I think it's not a big priority because there are already a lot of other ways to screen record that already work and are designed more specifically for that.


 `spectacle -R screen`

```Screen recording is not available on X11.```

**Comment by robertkirkman** [comment]
I see, I didn't know about this. 

it appears that the entire screen recording functionality of Spectacle only supports Wayland, and not X11.

https://www.omglinux.com/kde-spectacle-adds-screen-recording/

That is fine because, basically, there is already `recordmyscreen` in Termux for very basic recording of the X11 server through the X11 protocol,

and if anyone ever needs a more advanced X11 recorder than that for some reason, the real answer is an OBS for bionic-libc and X11 mode, which does not exist but I have no doubt that it could. Nobody has made one yet because non-X11 Android screen recorders are likely more efficient on most Android devices.

Someone tried but they have not finished. The error doesn't look that troubling to me but the main blocker IMO is just that it might not be worth creating until there is a real-world use-case found for which it would be required which no other Android screen recorder could satisfy, and I don't know of any yet.

https://obsproject.com/forum/threads/im-going-to-build-obs-studio-for-termux-does-anyone-have-any-suggestions-or-experience-with-this-this-is-as-far-as-i-got.181471/

File: x11-packages/kf6-prison/build.sh [hunk 3]
```diff
@@ -0,0 +1,21 @@
+TERMUX_PKG_HOMEPAGE="https://community.kde.org/Frameworks"
```
Comment (TomJo2000) [inline x11-packages/kf6-prison/build.sh]: Since this is a library, consider linking the gitlab repo as the homepage.
```suggestion
TERMUX_PKG_HOMEPAGE="https://invent.kde.org/frameworks/prison"
```

File: x11-packages/kf6-kstatusnotifieritem/build.sh [hunk 4]
```diff
@@ -0,0 +1,17 @@
+TERMUX_PKG_HOMEPAGE="https://community.kde.org/Frameworks"
```
Comment (TomJo2000) [inline x11-packages/kf6-kstatusnotifieritem/build.sh]: Since this is a library, consider linking the gitlab repo as the homepage.
```suggestion
TERMUX_PKG_HOMEPAGE="https://invent.kde.org/frameworks/kstatusnotifieritem"
```

File: x11-packages/kpipewire/build.sh [hunk 5]
```diff
@@ -0,0 +1,15 @@
+TERMUX_PKG_HOMEPAGE="https://kde.org/plasma-desktop/"
```
Comment (TomJo2000) [inline x11-packages/kpipewire/build.sh]: I think linking to the repo instead of the info page for KDE Plasma makes more sense for the pipewire API.

```suggestion
TERMUX_PKG_HOMEPAGE="https://invent.kde.org/plasma/kpipewire"
```

File: x11-packages/spectacle/build.sh [hunk 6]
```diff
@@ -0,0 +1,22 @@
+TERMUX_PKG_HOMEPAGE="https://apps.kde.org/spectacle/"
+TERMUX_PKG_DESCRIPTION="KDE screenshot capture utility"
+TERMUX_PKG_LICENSE="GPL-2.0-or-later"
+TERMUX_PKG_MAINTAINER="@termux"
+TERMUX_PKG_VERSION="6.4.4"
+TERMUX_PKG_SRCURL="https://download.kde.org/stable/plasma/${TERMUX_PKG_VERSION}/spectacle-${TERMUX_PKG_VERSION}.tar.xz"
+TERMUX_PKG_SHA256="9108a739c1acc43b23e0a6aa17ba4194a564ab1548c6887328c76a073bf3d373"
+TERMUX_PKG_AUTO_UPDATE=true
+TERMUX_PKG_DEPENDS="libc++, kf6-kconfig, kf6-kconfigwidgets, kf6-kcoreaddons, kf6-kcrash, kf6-kdbusaddons, kf6-kglobalaccel, kf6-kguiaddons, kf6-ki18n, kf6-kio, kf6-kirigami, kf6-kjobwidgets, kf6-knotifications, kpipewire, kf6-kservice, kf6-kstatusnotifieritem, kf6-kwidgetsaddons, kf6-kwindowsystem, kf6-kxmlgui, layer-shell-qt, libxcb, opencv, kf6-prison, kf6-purpose, qt6-qtbase, qt6-qtdeclarative, qt6-qtimageformats, qt6-qtmultimedia, qt6-qtwayland, libwayland, xcb-util, xcb-util-cursor, xcb-util-image"
```
Comment (TomJo2000) [inline x11-packages/spectacle/build.sh]: The include directory will need to be manually updated if and when `opencv` goes to 5.x, but I don't think it's necessary to worry about that too much right now.
Adding a version gate to the `opencv` dependency could help that get caught automatically when it happens.

```suggestion
TERMUX_PKG_DEPENDS="libc++, kf6-kconfig, kf6-kconfigwidgets, kf6-kcoreaddons, kf6-kcrash, kf6-kdbusaddons, kf6-kglobalaccel, kf6-kguiaddons, kf6-ki18n, kf6-kio, kf6-kirigami, kf6-kjobwidgets, kf6-knotifications, kpipewire, kf6-kservice, kf6-kstatusnotifieritem, kf6-kwidgetsaddons, kf6-kwindowsystem, kf6-kxmlgui, layer-shell-qt, libxcb, opencv (< 5), kf6-prison, kf6-purpose, qt6-qtbase, qt6-qtdeclarative, qt6-qtimageformats, qt6-qtmultimedia, qt6-qtwayland, libwayland, xcb-util, xcb-util-cursor, xcb-util-image"
```

**Review by TomJo2000 — APPROVED** [review]
LGTM just have a couple minor suggestions.

**Comment by TomJo2000** [comment]
Also the commits will need to get squashed to a reasonable set and the commit messages cleaned up, but I can do that.
