### PR TITLE
fix(x11/gtk2): enable xi to let gimp enumerate input devices

### LINKED ISSUE #20247: [Bug]: gimp does not enumerate input devices except core pointer
### Problem description

Proot-distro's version does it, but termux version does not.
image

### What steps will reproduce the bug?

Install gimp in termux, go to Edit->Configure input devices.

### What is the expected behavior?

It should enumerate all devices.

### System information

```shell
Irrelevant, gimp version is irrelevant too.
```

### PR DESCRIPTION
**Pull request by twaik**
Fixes #20247

I'll merge it in 12 hours if nobody minds.

### CODE REVIEW

File: x11-packages/gtk2/build.sh [hunk 1]
```diff
@@ -4,11 +4,11 @@ TERMUX_PKG_LICENSE="LGPL-2.0"
 TERMUX_PKG_MAINTAINER="@termux"
 _MAJOR_VERSION=2.24
 TERMUX_PKG_VERSION=${_MAJOR_VERSION}.33
-TERMUX_PKG_REVISION=4
+TERMUX_PKG_REVISION=5
 TERMUX_PKG_SRCURL=https://download.gnome.org/sources/gtk+/${_MAJOR_VERSION}/gtk+-${TERMUX_PKG_VERSION}.tar.xz
 TERMUX_PKG_SHA256=ac2ac757f5942d318a311a54b0c80b5ef295f299c2a73c632f6bfb1ff49cc6da
 TERMUX_PKG_BUILD_IN_SRC=true
-TERMUX_PKG_DEPENDS="adwaita-icon-theme, atk, coreutils, desktop-file-utils, fontconfig, freetype, glib, glib-bin, gtk-update-icon-cache, harfbuzz, libandroid-shmem, libcairo, librsvg, libx11, libxcomposite, libxcursor, libxdamage, libxext, libxfixes, libxinerama, libxrandr, libxrender, pango, shared-mime-info, ttf-dejavu"
+TERMUX_PKG_DEPENDS="adwaita-icon-theme, atk, coreutils, desktop-file-utils, fontconfig, freetype, glib, glib-bin, gtk-update-icon-cache, harfbuzz, libandroid-shmem, libcairo, librsvg, libx11, libxi, libxcomposite, libxcursor, libxdamage, libxext, libxfixes, libxinerama, libxrandr, libxrender, pango, shared-mime-info, ttf-dejavu"
```
Comment (truboxl) [inline x11-packages/gtk2/build.sh:11]:
```suggestion
TERMUX_PKG_DEPENDS="adwaita-icon-theme, atk, coreutils, desktop-file-utils, fontconfig, freetype, glib, glib-bin, gtk-update-icon-cache, harfbuzz, libandroid-shmem, libcairo, librsvg, libx11, libxcomposite, libxcursor, libxdamage, libxext, libxfixes, libxi, libxinerama, libxrandr, libxrender, pango, shared-mime-info, ttf-dejavu"
```

**Review by truboxl — APPROVED** [review]
