### PR TITLE
fix(main/awscli): use android toolchain utilities

### LINKED ISSUE #28546: Auto update failing for awscli
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [awscli](https://github.com/termux/termux-packages/blob/a627e016c527e871ad5e5df6e0e7a5f17e314f72/packages/awscli) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="console">
INFO: Updating awscli [Current version: 2.33.25]
INFO: package being updated to 2.33.26.
Downloading https://github.com/aws/aws-cli/archive/refs/tags/2.33.26.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 2328k    0 2328k    0     0  3006k      0 --:--:-- --:--:-- --:--:-- 3006k
100 8192k    0 8192k    0     0  4613k      0 --:--:--  0:00:01 --:--:-- 5858k
100 13.7M    0 13.7M    0     0  5073k      0 --:--:--  0:00:02 --:--:-- 5872k
100 16.8M    0 16.8M    0     0  5475k      0 --:--:--  0:00:03 --:--:-- 6282k

You are about to commit these changes:

--------------------
diff --git a/packages/awscli/build.sh b/packages/awscli/build.sh
index b43eaba4cd..fe36085fb0 100644
--- a/packages/awscli/build.sh
+++ b/packages/awscli/build.sh
@@ -2,9 +2,9 @@ TERMUX_PKG_HOMEPAGE=https://aws.amazon.com/cli
 TERMUX_PKG_DESCRIPTION="Universal Command Line Interface for Amazon Web Services"
 TERMUX_PKG_LICENSE="Apache-2.0"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION="2.33.25"
+TERMUX_PKG_VERSION="2.33.26"
 TERMUX_PKG_SRCURL="https://github.com/aws/aws-cli/archive/refs/tags/$TERMUX_PKG_VERSION.tar.gz"
-TERMUX_PKG_SHA256=e5ac917891277cc3ad419449b079d56268970bdaa4f904c3996b423da557d57e
+TERMUX_PKG_SHA256=aa149a21e9a4e0f2a45fc3d8e7d9df5ed345861f7b9a7448d862f86047f831d3
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_UPDATE_VERSION_REGEXP="\d+.\d+.\d+"
 TERMUX_PKG_DEPENDS="libandroid-posix-semaphore, libandroid-support, libbz2, libexpat, libffi, liblzma, libsqlite, mandoc, openssl, readline, zlib"
--------------------

bump(main/awscli): 2.33.26

Not committing to Git!

INFO: Trying to build package.
INFO: Package awscli exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
Creating new container...
Unable to find image 'ghcr.io/termux/package-builder:latest' locally
latest: Pulling from termux/package-builder
01d7766a2e4a: Pulling fs layer
4f4fb700ef54: Pulling fs layer
95147982d42a: Pulling fs layer
2e342f9c859a: Pulling fs layer
cbed11ac28a6: Pulling fs layer
bc0008666e0f: Pulling fs layer
c2aa1df93902: Pulling fs layer
8690d74139aa: Pulling fs layer
323dd0468f65: Pulling fs layer
cbed11ac28a6: Waiting
bc0008666e0f: Waiting
8690d74139aa: Waiting
c2aa1df93902: Waiting
323dd0468f65: Waiting
2e342f9c859a: Waiting
95147982d42a: Verifying Checksum
95147982d42a: Download complete
4f4fb700ef54: Verifying Checksum
4f4fb700ef54: Download complete
2e342f9c859a: Verifying Checksum
2e342f9c859a: Download complete
cbed11ac28a6: Download complete
01d7766a2e4a: Verifying Checksum
01d7766a2e4a: Download complete
bc0008666e0f: Verifying Checksum
bc0008666e0f: Download complete
c2aa1df93902: Verifying Checksum
c2aa1df93902: Download complete
323dd0468f65: Verifying Checksum
323dd0468f65: Download complete
01d7766a2e4a: Pull complete
4f4fb700ef54: Pull complete
95147982d42a: Pull complete
2e342f9c859a: Pull complete
cbed11ac28a6: Pull complete
bc0008666e0f: Pull complete
c2aa1df93902: Pull complete
8690d74139aa: Verifying Checksum
8690d74139aa: Download complete
8690d74139aa: Pull complete
323dd0468f65: Pull complete
Digest: sha256:86bc7ab080249bb8136b9944db4aa27d0c6c9e962de2162aefede17a699b0866
Status: Downloaded newer image for ghcr.io/termux/package-builder:latest
69329d7b93fe7090a125b17fb9f5085b8bf4251165cb4bafb9b4426027c1ed25
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
gpg: key B0076E490B71616B: 18 signatures not checked due to missing keys
gpg: key B0076E490B71616B: public key "Henrik Grimler <henrik@grimler.se>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no ultimately trusted keys found
gpg (GnuPG) 2.4.4; Copyright (C) 2024 g10 Code GmbH
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

gpg: key 5A897D96E57CF20C: public key "Termux Releases (Termux automatic builds) <contact@termux.dev>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   1  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   1  signed:   0  trust: 1-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2026-05-06
gpg (GnuPG) 2.4.4; Copyright (C) 2024 g10 Code GmbH
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

gpg: key 389CEED64573DFCA: public key "termux-pacman (security signature) <pacman@termux.dev>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg (GnuPG) 2.4.4; Copyright (C) 2024 g10 Code GmbH
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

termux - building awscli for arch aarch64...
Downloading https://github.com/termux/termux-elf-cleaner/releases/download/v3.0.1/termux-elf-cleaner
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  175k  100  175k    0     0  1035k      0 --:--:-- --:--:-- --:--:-- 1035k
::group::INFO: Fetching repo metadata
[packages-cf.termux.dev-apt-termux-main]: Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
[packages-cf.termux.dev-apt-termux-main]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-main]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-x11]: Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
[packages-cf.termux.dev-apt-termux-x11]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-x11]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-root]: Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
[packages-cf.termux.dev-apt-termux-root]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-root]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-main]: 
[packages-cf.termux.dev-apt-termux-main]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-main]: 100 13134  100 13134    0     0  24016      0 --:--:-- --:--:-- --:--:-- 24054
[packages-cf.termux.dev-apt-termux-main]: Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
[packages-cf.termux.dev-apt-termux-main]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-main]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-x11]: 
[packages-cf.termux.dev-apt-termux-x11]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-x11]: 100 13120  100 13120    0     0  23199      0 --:--:-- --:--:-- --:--:-- 23221
[packages-cf.termux.dev-apt-termux-x11]: Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
[packages-cf.termux.dev-apt-termux-x11]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-x11]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-root]: 
[packages-cf.termux.dev-apt-termux-root]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-root]: 100 13320  100 13320    0     0  26577      0 --:--:-- --:--:-- --:--:-- 26586
[packages-cf.termux.dev-apt-termux-root]: Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
[packages-cf.termux.dev-apt-termux-root]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-root]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-main]: 
[packages-cf.termux.dev-apt-termux-main]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-main]: 100   833  100   833    0     0   1439      0 --:--:-- --:--:-- --:--:--  1438
[packages-cf.termux.dev-apt-termux-main]: 100   833  100   833    0     0   1439      0 --:--:-- --:--:-- --:--:--  1438
[packages-cf.termux.dev-apt-termux-main]: gpg: Signature made Thu 19 Feb 2026 10:02:57 PM UTC
[packages-cf.termux.dev-apt-termux-main]: gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
[packages-cf.termux.dev-apt-termux-main]: gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
[packages-cf.termux.dev-apt-termux-main]: gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
[packages-cf.termux.dev-apt-termux-main]: Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/main/binary-aarch64/Packages
[packages-cf.termux.dev-apt-termux-main]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-main]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-x11]: 
[packages-cf.termux.dev-apt-termux-x11]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-x11]: 100   833  100   833    0     0   1653      0 --:--:-- --:--:-- --:--:--  1652
[packages-cf.termux.dev-apt-termux-x11]: 100   833  100   833    0     0   1653      0 --:--:-- --:--:-- --:--:--  1652
[packages-cf.termux.dev-apt-termux-x11]: gpg: Signature made Thu 19 Feb 2026 08:44:28 AM UTC
[packages-cf.termux.dev-apt-termux-x11]: gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
[packages-cf.termux.dev-apt-termux-x11]: gpg: checking the trustdb
[packages-cf.termux.dev-apt-termux-x11]: gpg: marginals needed: 3  completes needed: 1  trust model: pgp
[packages-cf.termux.dev-apt-termux-x11]: gpg: depth: 0  valid:   3  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 3u
[packages-cf.termux.dev-apt-termux-x11]: gpg: next trustdb check due at 2026-05-06
[packages-cf.termux.dev-apt-termux-x11]: gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
[packages-cf.termux.dev-apt-termux-x11]: gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
[packages-cf.termux.dev-apt-termux-x11]: Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/main/binary-aarch64/Packages
[packages-cf.termux.dev-apt-termux-x11]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-x11]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-root]: 
[packages-cf.termux.dev-apt-termux-root]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-root]: 100   833  100   833    0     0   1431      0 --:--:-- --:--:-- --:--:--  1431
[packages-cf.termux.dev-apt-termux-root]: 100   833  100   833    0     0   1431      0 --:--:-- --:--:-- --:--:--  1431
[packages-cf.termux.dev-apt-termux-root]: gpg: Signature made Thu 19 Feb 2026 01:03:41 AM UTC
[packages-cf.termux.dev-apt-termux-root]: gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
[packages-cf.termux.dev-apt-termux-root]: gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
[packages-cf.termux.dev-apt-termux-root]: gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
[packages-cf.termux.dev-apt-termux-root]: Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/stable/binary-aarch64/Packages
[packages-cf.termux.dev-apt-termux-root]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-root]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-main]: 
[packages-cf.termux.dev-apt-termux-main]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-main]: 100 1688k  100 1688k    0     0  2681k      0 --:--:-- --:--:-- --:--:-- 2685k
[packages-cf.termux.dev-apt-termux-root]: 
[packages-cf.termux.dev-apt-termux-root]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-root]: 100 60712  100 60712    0     0   101k      0 --:--:-- --:--:-- --:--:--  101k
[packages-cf.termux.dev-apt-termux-x11]: 
[packages-cf.termux.dev-apt-termux-x11]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-x11]:   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
[packages-cf.termux.dev-apt-termux-x11]:   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
[packages-cf.termux.dev-apt-termux-x11]:   0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
[packages-cf.termux.dev-apt-termux-x11]:   0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
[packages-cf.termux.dev-apt-termux-x11]:  10  662k   10 67931    0     0  13380      0  0:00:50  0:00:05  0:00:45 13382
[packages-cf.termux.dev-apt-termux-x11]: 100  662k  100  662k    0     0   129k      0  0:00:05  0:00:05 --:--:--  170k
::endgroup::
Downloading dependency aosp-libs@9.0.0-r76-2 if necessary...
Found aosp-libs in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/a/aosp-libs/aosp-libs_9.0.0-r76-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 9424k  100 9424k    0     0  46.2M      0 --:--:-- --:--:-- --:--:-- 46.4M
extracting aosp-libs to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency aosp-utils@9.0.0-r76-2 if necessary...
Found aosp-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/a/aosp-utils/aosp-utils_9.0.0-r76-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  319k  100  319k    0     0  5122k      0 --:--:-- --:--:-- --:--:-- 5154k
extracting aosp-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libc++@29 if necessary...
Found libc++ in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libc/libc++/libc++_29_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  326k  100  326k    0     0  2495k      0 --:--:-- --:--:-- --:--:-- 2515k
extracting libc++ to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency jsoncpp@1.9.6-2 if necessary...
Found jsoncpp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/j/jsoncpp/jsoncpp_1.9.6-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 94168  100 94168    0     0   966k      0 --:--:-- --:--:-- --:--:--  968k
extracting jsoncpp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libbz2@1.0.8-8 if necessary...
Found libbz2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libb/libbz2/libbz2_1.0.8-8_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 26116  100 26116    0     0   333k      0 --:--:-- --:--:-- --:--:--  335k
extracting libbz2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency bzip2@1.0.8-8 if necessary...
Found bzip2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/bzip2/bzip2_1.0.8-8_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 26152  100 26152    0     0   460k      0 --:--:-- --:--:-- --:--:--  464k
extracting bzip2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libiconv@1.18-1 if necessary...
Found libiconv in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libi/libiconv/libiconv_1.18-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 74  548k   74  407k    0     0  4947k      0 --:--:-- --:--:-- --:--:-- 4914k
100  548k  100  548k    0     0  6496k      0 --:--:-- --:--:-- --:--:-- 6447k
extracting libiconv to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency iconv@1.18-1 if necessary...
Found iconv in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/i/iconv/iconv_1.18-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 10024  100 10024    0     0   180k      0 --:--:-- --:--:-- --:--:--  181k
extracting iconv to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency liblzma@5.8.2 if necessary...
Found liblzma in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libl/liblzma/liblzma_5.8.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  187k  100  187k    0     0  2896k      0 --:--:-- --:--:-- --:--:-- 2936k
extracting liblzma to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xz-utils@5.8.2 if necessary...
Found xz-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/x/xz-utils/xz-utils_5.8.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 71220  100 71220    0     0  1161k      0 --:--:-- --:--:-- --:--:-- 1178k
extracting xz-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libandroid-glob@0.6-3 if necessary...
Found libandroid-glob in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libandroid-glob/libandroid-glob_0.6-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  7032  100  7032    0     0   108k      0 --:--:-- --:--:-- --:--:--  109k
extracting libandroid-glob to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libicu@78.2 if necessary...
Found libicu in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libi/libicu/libicu_78.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 9973k  100 9973k    0     0  57.2M      0 --:--:-- --:--:-- --:--:-- 57.6M
extracting libicu to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency icu-devtools@78.2 if necessary...
Found icu-devtools in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/i/icu-devtools/icu-devtools_78.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  205k  100  205k    0     0   392k      0 --:--:-- --:--:-- --:--:--  392k
extracting icu-devtools to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libandroid-support@29-1 if necessary...
Found libandroid-support in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libandroid-support/libandroid-support_29-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 10880  100 10880    0     0   185k      0 --:--:-- --:--:-- --:--:--  183k
extracting libandroid-support to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses@6.6.20260124+really6.5.20250830 if necessary...
Found ncurses in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/n/ncurses/ncurses_6.6.20260124+really6.5.20250830_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  544k  100  544k    0     0  6648k      0 --:--:-- --:--:-- --:--:-- 6727k
extracting ncurses to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-utils@6.6.20260124+really6.5.20250830 if necessary...
Found ncurses-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/n/ncurses-utils/ncurses-utils_6.6.20260124+really6.5.20250830_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 88988  100 88988    0     0   822k      0 --:--:-- --:--:-- --:--:--  827k
extracting ncurses-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-ui-libs@6.6.20260124+really6.5.20250830 if necessary...
Found ncurses-ui-libs in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/n/ncurses-ui-libs/ncurses-ui-libs_6.6.20260124+really6.5.20250830_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 32940  100 32940    0     0   425k      0 --:--:-- --:--:-- --:--:--  428k
extracting ncurses-ui-libs to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-ui-libs-static@6.6.20260124+really6.5.20250830 if necessary...
Found ncurses-ui-libs-static in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/n/ncurses-ui-libs-static/ncurses-ui-libs-static_6.6.20260124+really6.5.20250830_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 39524  100 39524    0     0   642k      0 --:--:-- --:--:-- --:--:--  654k
extracting ncurses-ui-libs-static to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency readline@8.3.1-2 if necessary...
Found readline in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/r/readline/readline_8.3.1-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  286k  100  286k    0     0  3938k      0 --:--:-- --:--:-- --:--:-- 3985k
extracting readline to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency gdbm@1.26-1 if necessary...
Found gdbm in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/gdbm/gdbm_1.26-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  146k  100  146k    0     0  2574k      0 --:--:-- --:--:-- --:--:-- 2620k
extracting gdbm to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libandroid-posix-semaphore@0.1-4 if necessary...
Found libandroid-posix-semaphore in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libandroid-posix-semaphore/libandroid-posix-semaphore_0.1-4_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4076  100  4076    0     0  63380      0 --:--:-- --:--:-- --:--:-- 62707
extracting libandroid-posix-semaphore to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ca-certificates@1:2025.12.02 if necessary...
Found ca-certificates in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/c/ca-certificates/ca-certificates_1:2025.12.02_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  121k  100  121k    0     0  1825k      0 --:--:-- --:--:-- --:--:-- 1838k
extracting ca-certificates to /home/builder/.termux-build/_cache-all...
Downloading dependency ca-certificates-java@1:2025.12.02 if necessary...
Found ca-certificates-java in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/c/ca-certificates-java/ca-certificates-java_1:2025.12.02_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  111k  100  111k    0     0  1768k      0 --:--:-- --:--:-- --:--:-- 1792k
extracting ca-certificates-java to /home/builder/.termux-build/_cache-all...
Downloading dependency zlib@1.3.2 if necessary...
Found zlib in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/z/zlib/zlib_1.3.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 62840  100 62840    0     0   909k      0 --:--:-- --:--:-- --:--:--  915k
extracting zlib to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency openssl@1:3.6.1 if necessary...
Found openssl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/o/openssl/openssl_1:3.6.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  2 2417k    2 67759    0     0  11977      0  0:03:26  0:00:05  0:03:21 15250
100 2417k  100 2417k    0     0   394k      0  0:00:06  0:00:06 --:--:--  618k
extracting openssl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency openssl-tool@1:3.6.1 if necessary...
Found openssl-tool in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/o/openssl-tool/openssl-tool_1:3.6.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  270k  100  270k    0     0  3865k      0 --:--:-- --:--:-- --:--:-- 3922k
extracting openssl-tool to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libcrypt@0.2-6 if necessary...
Found libcrypt in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libc/libcrypt/libcrypt_0.2-6_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  8880  100  8880    0     0   143k      0 --:--:-- --:--:-- --:--:--  144k
extracting libcrypt to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libexpat@2.7.4 if necessary...
Found libexpat in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libe/libexpat/libexpat_2.7.4_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 92100  100 92100    0     0  1602k      0 --:--:-- --:--:-- --:--:-- 1577k
extracting libexpat to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libffi@3.4.7-1 if necessary...
Found libffi in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libf/libffi/libffi_3.4.7-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 30672  100 30672    0     0   192k      0 --:--:-- --:--:-- --:--:--  193k
extracting libffi to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency tcl@8.6.14-1 if necessary...
Found tcl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/tcl/tcl_8.6.14-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2204k  100 2204k    0     0  21.0M      0 --:--:-- --:--:-- --:--:-- 21.1M
extracting tcl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libsqlite@3.51.2 if necessary...
Found libsqlite in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libs/libsqlite/libsqlite_3.51.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  694k  100  694k    0     0  10.3M      0 --:--:-- --:--:-- --:--:-- 10.4M
extracting libsqlite to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency sqlite@3.51.2 if necessary...
Found sqlite in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/s/sqlite/sqlite_3.51.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  603k  100  603k    0     0  6330k      0 --:--:-- --:--:-- --:--:-- 6354k
extracting sqlite to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libsqlite-tcl@3.51.2 if necessary...
Found libsqlite-tcl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libs/libsqlite-tcl/libsqlite-tcl_3.51.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 83  498k   83  415k    0     0  6472k      0 --:--:-- --:--:-- --:--:-- 6398k
100  498k  100  498k    0     0  7354k      0 --:--:-- --:--:-- --:--:-- 7330k
extracting libsqlite-tcl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency brotli@1.2.0 if necessary...
Found brotli in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/brotli/brotli_1.2.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  332k  100  332k    0     0  5223k      0 --:--:-- --:--:-- --:--:-- 5279k
extracting brotli to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libpng@1.6.55 if necessary...
Found libpng in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libp/libpng/libpng_1.6.55_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  190k  100  190k    0     0  3112k      0 --:--:-- --:--:-- --:--:-- 3127k
extracting libpng to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency freetype@2.14.1 if necessary...
Found freetype in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/f/freetype/freetype_2.14.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  402k  100  402k    0     0   800k      0 --:--:-- --:--:-- --:--:--  802k
extracting freetype to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ttf-dejavu@2.37-8 if necessary...
Found ttf-dejavu in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/ttf-dejavu/ttf-dejavu_2.37-8_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2410k  100 2410k    0     0  29.8M      0 --:--:-- --:--:-- --:--:-- 30.1M
extracting ttf-dejavu to /home/builder/.termux-build/_cache-all...
Downloading dependency fontconfig@2.17.1-1 if necessary...
Found fontconfig in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/f/fontconfig/fontconfig_2.17.1-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  120k  100  120k    0     0  2208k      0 --:--:-- --:--:-- --:--:-- 2226k
extracting fontconfig to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency fontconfig-utils@2.17.1-1 if necessary...
Found fontconfig-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/f/fontconfig-utils/fontconfig-utils_2.17.1-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 14468  100 14468    0     0   181k      0 --:--:-- --:--:-- --:--:--  183k
extracting fontconfig-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xorg-util-macros@1.20.2 if necessary...
Found xorg-util-macros in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/x/xorg-util-macros/xorg-util-macros_1.20.2_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 21948  100 21948    0     0   422k      0 --:--:-- --:--:-- --:--:--  428k
extracting xorg-util-macros to /home/builder/.termux-build/_cache-all...
Downloading dependency xorgproto@2025.1 if necessary...
Found xorgproto in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/x/xorgproto/xorgproto_2025.1_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  243k  100  243k    0     0  3731k      0 --:--:-- --:--:-- --:--:-- 3751k
extracting xorgproto to /home/builder/.termux-build/_cache-all...
Downloading dependency libxau@1.0.12-2 if necessary...
Found libxau in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxau/libxau_1.0.12-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  9120  100  9120    0     0   170k      0 --:--:-- --:--:-- --:--:--  171k
extracting libxau to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxdmcp@1.1.5-2 if necessary...
Found libxdmcp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxdmcp/libxdmcp_1.1.5-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 24460  100 24460    0     0  50729      0 --:--:-- --:--:-- --:--:-- 50641
100 24460  100 24460    0     0  50722      0 --:--:-- --:--:-- --:--:-- 50641
extracting libxdmcp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xcb-proto@1.17.0-1 if necessary...
Found xcb-proto in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/x/xcb-proto/xcb-proto_1.17.0-1_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 78616  100 78616    0     0  1401k      0 --:--:-- --:--:-- --:--:-- 1421k
extracting xcb-proto to /home/builder/.termux-build/_cache-all...
Downloading dependency python-xcbgen@1.17.0-1 if necessary...
Found python-xcbgen in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/python-xcbgen/python-xcbgen_1.17.0-1_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 44572  100 44572    0     0   786k      0 --:--:-- --:--:-- --:--:--  791k
extracting python-xcbgen to /home/builder/.termux-build/_cache-all...
Downloading dependency libxcb@1.17.0-1 if necessary...
Found libxcb in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxcb/libxcb_1.17.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  892k  100  892k    0     0  11.2M      0 --:--:-- --:--:-- --:--:-- 11.3M
extracting libxcb to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xtrans@1.6.0 if necessary...
Found xtrans in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/x/xtrans/xtrans_1.6.0_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 39892  100 39892    0     0   635k      0 --:--:-- --:--:-- --:--:--  638k
extracting xtrans to /home/builder/.termux-build/_cache-all...
Downloading dependency libx11@1.8.13 if necessary...
Found libx11 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libx11/libx11_1.8.13_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1865k  100 1865k    0     0  3686k      0 --:--:-- --:--:-- --:--:-- 3686k
extracting libx11 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxrender@0.9.12-1 if necessary...
Found libxrender in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxrender/libxrender_0.9.12-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 24572  100 24572    0     0   427k      0 --:--:-- --:--:-- --:--:--  428k
extracting libxrender to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxft@2.3.9-1 if necessary...
Found libxft in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxft/libxft_2.3.9-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 47968  100 47968    0     0   899k      0 --:--:-- --:--:-- --:--:--  918k
extracting libxft to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxext@1.3.7 if necessary...
Found libxext in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxext/libxext_1.3.7_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 98008  100 98008    0     0  1596k      0 --:--:-- --:--:-- --:--:-- 1622k
extracting libxext to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxss@1.2.5 if necessary...
Found libxss in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxss/libxss_1.2.5_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 11920  100 11920    0     0   244k      0 --:--:-- --:--:-- --:--:--  247k
extracting libxss to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency tk@8.6.14-1 if necessary...
Found tk in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/tk/tk_8.6.14-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1713k  100 1713k    0     0  21.8M      0 --:--:-- --:--:-- --:--:-- 21.7M
extracting tk to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency python@3.12.12-1 if necessary...
Found python in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/python/python_3.12.12-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 4369k  100 4369k    0     0  39.6M      0 --:--:-- --:--:-- --:--:-- 39.8M
extracting python to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency python-tkinter@3.12.12-1 if necessary...
Found python-tkinter in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/python-tkinter/python-tkinter_3.12.12-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  506k  100  506k    0     0  7205k      0 --:--:-- --:--:-- --:--:-- 7230k
extracting python-tkinter to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency python-ensurepip-wheels@3.12.12-1 if necessary...
Found python-ensurepip-wheels in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/python-ensurepip-wheels/python-ensurepip-wheels_3.12.12-1_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1759k  100 1759k    0     0  22.7M      0 --:--:-- --:--:-- --:--:-- 22.9M
extracting python-ensurepip-wheels to /home/builder/.termux-build/_cache-all...
Downloading dependency libxml2@2.15.1-1 if necessary...
Found libxml2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxml2/libxml2_2.15.1-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  430k  100  430k    0     0  5531k      0 --:--:-- --:--:-- --:--:-- 5521k
extracting libxml2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxml2-utils@2.15.1-1 if necessary...
Found libxml2-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxml2-utils/libxml2-utils_2.15.1-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 33944  100 33944    0     0   559k      0 --:--:-- --:--:-- --:--:--  561k
extracting libxml2-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxml2-python@2.15.1-1 if necessary...
Found libxml2-python in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxml2-python/libxml2-python_2.15.1-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 47212  100 47212    0     0   802k      0 --:--:-- --:--:-- --:--:--  808k
extracting libxml2-python to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libarchive@3.8.5 if necessary...
Found libarchive in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libarchive/libarchive_3.8.5_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  381k  100  381k    0     0  3024k      0 --:--:-- --:--:-- --:--:-- 3027k
extracting libarchive to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency bsdtar@3.8.5 if necessary...
Found bsdtar in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/bsdtar/bsdtar_3.8.5_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  339k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  339k  100  339k    0     0   706k      0 --:--:-- --:--:-- --:--:--  705k
extracting bsdtar to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libnghttp2@1.68.0-1 if necessary...
Found libnghttp2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libn/libnghttp2/libnghttp2_1.68.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 95472  100 95472    0     0  1255k      0 --:--:-- --:--:-- --:--:-- 1259k
extracting libnghttp2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libnghttp3@1.15.0 if necessary...
Found libnghttp3 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libn/libnghttp3/libnghttp3_1.15.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 67848  100 67848    0     0   917k      0 --:--:-- --:--:-- --:--:--  920k
extracting libnghttp3 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libngtcp2@1.20.0 if necessary...
Found libngtcp2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libn/libngtcp2/libngtcp2_1.20.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  160k  100  160k    0     0  2195k      0 --:--:-- --:--:-- --:--:-- 2204k
extracting libngtcp2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libssh2@1.11.1-1 if necessary...
Found libssh2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libs/libssh2/libssh2_1.11.1-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  213k  100  213k    0     0  3111k      0 --:--:-- --:--:-- --:--:-- 3137k
extracting libssh2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libcurl@8.18.0-1 if necessary...
Found libcurl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libc/libcurl/libcurl_8.18.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  973k  100  973k    0     0  10.5M      0 --:--:-- --:--:-- --:--:-- 10.5M
extracting libcurl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency curl@8.18.0-1 if necessary...
Found curl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/c/curl/curl_8.18.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  231k  100  231k    0     0  3563k      0 --:--:-- --:--:-- --:--:-- 3622k
extracting curl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libuv@1.52.0 if necessary...
Found libuv in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libu/libuv/libuv_1.52.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 82028  100 82028    0     0  1385k      0 --:--:-- --:--:-- --:--:-- 1405k
extracting libuv to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency rhash@1.4.6-1 if necessary...
Found rhash in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/r/rhash/rhash_1.4.6-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  159k  100  159k    0     0  2691k      0 --:--:-- --:--:-- --:--:-- 2702k
extracting rhash to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency cmake@4.2.3 if necessary...
Found cmake in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/c/cmake/cmake_4.2.3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 9587k  100 9587k    0     0  81.5M      0 --:--:-- --:--:-- --:--:-- 82.1M
extracting cmake to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency cmake-curses-gui@4.2.3 if necessary...
Found cmake-curses-gui in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/c/cmake-curses-gui/cmake-curses-gui_4.2.3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2243k  100 2243k    0     0  22.9M      0 --:--:-- --:--:-- --:--:-- 23.0M
extracting cmake-curses-gui to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency pcre2@10.47 if necessary...
Found pcre2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/pcre2/pcre2_10.47_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  938k  100  938k    0     0  11.8M      0 --:--:-- --:--:-- --:--:-- 11.9M
extracting pcre2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency pcre2grep@10.47 if necessary...
Found pcre2grep in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/pcre2grep/pcre2grep_10.47_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 34068  100 34068    0     0   503k      0 --:--:-- --:--:-- --:--:--  511k
extracting pcre2grep to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libandroid-selinux@14.0.0.11-1 if necessary...
Found libandroid-selinux in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libandroid-selinux/libandroid-selinux_14.0.0.11-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 59624  100 59624    0     0  1115k      0 --:--:-- --:--:-- --:--:-- 1119k
extracting libandroid-selinux to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libgmp@6.3.0-2 if necessary...
Found libgmp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libg/libgmp/libgmp_6.3.0-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  320k  100  320k    0     0  4992k      0 --:--:-- --:--:-- --:--:-- 5010k
extracting libgmp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency coreutils@9.10-1 if necessary...
Found coreutils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/c/coreutils/coreutils_9.10-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  790k  100  790k    0     0  11.0M      0 --:--:-- --:--:-- --:--:-- 11.1M
extracting coreutils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency dash@0.5.12-2 if necessary...
Found dash in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/d/dash/dash_0.5.12-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 65836  100 65836    0     0  1076k      0 --:--:-- --:--:-- --:--:-- 1089k
extracting dash to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency dialog@1.3-20240307-1 if necessary...
Found dialog in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/d/dialog/dialog_1.3-20240307-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   97k  100   97k    0     0  1693k      0 --:--:-- --:--:-- --:--:-- 1716k
extracting dialog to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency diffutils@3.12-2 if necessary...
Found diffutils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/d/diffutils/diffutils_3.12-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  158k  100  158k    0     0  2685k      0 --:--:-- --:--:-- --:--:-- 2692k
extracting diffutils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency findutils@4.10.0-1 if necessary...
Found findutils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/f/findutils/findutils_4.10.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  245k  100  245k    0     0  3745k      0 --:--:-- --:--:-- --:--:-- 3776k
extracting findutils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libmpfr@4.2.1-1 if necessary...
Found libmpfr in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libm/libmpfr/libmpfr_4.2.1-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  265k  100  265k    0     0  4142k      0 --:--:-- --:--:-- --:--:-- 4152k
extracting libmpfr to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency gawk@5.3.1-2 if necessary...
Found gawk in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/gawk/gawk_5.3.1-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  763k  100  763k    0     0  8804k      0 --:--:-- --:--:-- --:--:-- 8879k
extracting gawk to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency grep@3.12-3 if necessary...
Found grep in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/grep/grep_3.12-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  125k  100  125k    0     0  2255k      0 --:--:-- --:--:-- --:--:-- 2278k
extracting grep to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency gzip@1.14-1 if necessary...
Found gzip in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/gzip/gzip_1.14-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 87548    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 87548  100 87548    0     0  1344k      0 --:--:-- --:--:-- --:--:-- 1335k
extracting gzip to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency less@692 if necessary...
Found less in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/l/less/less_692_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  131k  100  131k    0     0  1797k      0 --:--:-- --:--:-- --:--:-- 1806k
extracting less to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency procps@3.3.17-6 if necessary...
Found procps in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/procps/procps_3.3.17-6_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  139k  100  139k    0     0  2216k      0 --:--:-- --:--:-- --:--:-- 2250k
extracting procps to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency psmisc@23.7-1 if necessary...
Found psmisc in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/psmisc/psmisc_23.7-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 41188  100 41188    0     0   715k      0 --:--:-- --:--:-- --:--:--  718k
extracting psmisc to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency sed@4.9-2 if necessary...
Found sed in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/s/sed/sed_4.9-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  114k  100  114k    0     0  1869k      0 --:--:-- --:--:-- --:--:-- 1883k
extracting sed to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency attr@2.5.2-1 if necessary...
Found attr in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/a/attr/attr_2.5.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 52596  100 52596    0     0   749k      0 --:--:-- --:--:-- --:--:--  755k
extracting attr to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libacl@2.3.2 if necessary...
Found libacl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libacl/libacl_2.3.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  113k  100  113k    0     0  1948k      0 --:--:-- --:--:-- --:--:-- 1953k
extracting libacl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency tar@1.35-2 if necessary...
Found tar in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/tar/tar_1.35-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  337k  100  337k    0     0  4960k      0 --:--:-- --:--:-- --:--:-- 5035k
extracting tar to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency termux-am@0.8.0-2 if necessary...
Found termux-am in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/termux-am/termux-am_0.8.0-2_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  563k  100  563k    0     0  8036k      0 --:--:-- --:--:-- --:--:-- 8053k
extracting termux-am to /home/builder/.termux-build/_cache-all...
Downloading dependency termux-am-socket@1.5.0-1 if necessary...
Found termux-am-socket in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/termux-am-socket/termux-am-socket_1.5.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 16132  100 16132    0     0   284k      0 --:--:-- --:--:-- --:--:--  286k
extracting termux-am-socket to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency termux-core@0.4.0-1 if necessary...
Found termux-core in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/termux-core/termux-core_0.4.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  193k  100  193k    0     0  2515k      0 --:--:-- --:--:-- --:--:-- 2547k
extracting termux-core to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency termux-core-static@0.4.0-1 if necessary...
Found termux-core-static in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/termux-core-static/termux-core-static_0.4.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 20176  100 20176    0     0  42131      0 --:--:-- --:--:-- --:--:-- 42209
extracting termux-core-static to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency termux-exec@1:2.4.0-1 if necessary...
Found termux-exec in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/termux-exec/termux-exec_1:2.4.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  281k  100  281k    0     0  4675k      0 --:--:-- --:--:-- --:--:-- 4688k
extracting termux-exec to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libblkid@2.41.2-1 if necessary...
Found libblkid in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libb/libblkid/libblkid_2.41.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  122k  100  122k    0     0  1889k      0 --:--:-- --:--:-- --:--:-- 1916k
extracting libblkid to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libmount@2.41.2-1 if necessary...
Found libmount in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libm/libmount/libmount_2.41.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  149k  100  149k    0     0  2191k      0 --:--:-- --:--:-- --:--:-- 2195k
extracting libmount to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libsmartcols@2.41.2-1 if necessary...
Found libsmartcols in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libs/libsmartcols/libsmartcols_2.41.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   98k  100   98k    0     0  1852k      0 --:--:-- --:--:-- --:--:-- 1886k
extracting libsmartcols to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libuuid@2.41.2-1 if necessary...
Found libuuid in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libu/libuuid/libuuid_2.41.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 15464  100 15464    0     0   256k      0 --:--:-- --:--:-- --:--:--  260k
extracting libuuid to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libfdisk@2.41.2-1 if necessary...
Found libfdisk in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libf/libfdisk/libfdisk_2.41.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  153k  100  153k    0     0  2615k      0 --:--:-- --:--:-- --:--:-- 2650k
extracting libfdisk to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libcap-ng@2:0.9.1 if necessary...
Found libcap-ng in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libc/libcap-ng/libcap-ng_2:0.9.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 33932  100 33932    0     0   670k      0 --:--:-- --:--:-- --:--:--  676k
extracting libcap-ng to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency util-linux@2.41.2-1 if necessary...
Found util-linux in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/u/util-linux/util-linux_2.41.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  719k  100  719k    0     0  9382k      0 --:--:-- --:--:-- --:--:-- 9471k
extracting util-linux to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency uuid-utils@2.41.2-1 if necessary...
Found uuid-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/u/uuid-utils/uuid-utils_2.41.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 41004  100 41004    0     0   803k      0 --:--:-- --:--:-- --:--:--  817k
extracting uuid-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency mount-utils@2.41.2-1 if necessary...
Found mount-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/m/mount-utils/mount-utils_2.41.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  139k  100  139k    0     0  2138k      0 --:--:-- --:--:-- --:--:-- 2143k
extracting mount-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency fdisk@2.41.2-1 if necessary...
Found fdisk in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/f/fdisk/fdisk_2.41.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  112k  100  112k    0     0  1729k      0 --:--:-- --:--:-- --:--:-- 1708k
extracting fdisk to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency blk-utils@2.41.2-1 if necessary...
Found blk-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/blk-utils/blk-utils_2.41.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  175k  100  175k    0     0  2242k      0 --:--:-- --:--:-- --:--:-- 2255k
extracting blk-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency termux-tools@1.46.0+really1.45.0-1 if necessary...
Found termux-tools in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/termux-tools/termux-tools_1.46.0+really1.45.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 33592  100 33592    0     0   640k      0 --:--:-- --:--:-- --:--:--  643k
extracting termux-tools to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency bash@5.3.9 if necessary...
Found bash in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/bash/bash_5.3.9_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  932k  100  932k    0     0  12.5M      0 --:--:-- --:--:-- --:--:-- 12.6M
extracting bash to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency zstd@1.5.7-1 if necessary...
Found zstd in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/z/zstd/zstd_1.5.7-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  352k  100  352k    0     0  4369k      0 --:--:-- --:--:-- --:--:-- 4400k
extracting zstd to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency pzstd@1.5.7-1 if necessary...
Found pzstd in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/pzstd/pzstd_1.5.7-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 42176  100 42176    0     0   751k      0 --:--:-- --:--:-- --:--:--  762k
extracting pzstd to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency binutils@2.46.0-1 if necessary...
Found binutils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/binutils/binutils_2.46.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1145k  100 1145k    0     0  14.3M      0 --:--:-- --:--:-- --:--:-- 14.5M
extracting binutils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency binutils-cross@2.46.0-1 if necessary...
Found binutils-cross in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/binutils-cross/binutils-cross_2.46.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 35 2250k   35  799k    0     0   796k      0  0:00:02  0:00:01  0:00:01  796k
100 2250k  100 2250k    0     0  1863k      0  0:00:01  0:00:01 --:--:-- 1862k
extracting binutils-cross to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency binutils-bin@2.46.0-1 if necessary...
Found binutils-bin in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/binutils-bin/binutils-bin_2.46.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1292k  100 1292k    0     0  13.6M      0 --:--:-- --:--:-- --:--:-- 13.7M
extracting binutils-bin to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ldd@0.3 if necessary...
Found ldd in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/l/ldd/ldd_0.3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1844  100  1844    0     0  37839      0 --:--:-- --:--:-- --:--:-- 38416
extracting ldd to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency mandoc@1.14.6-6 if necessary...
Found mandoc in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/m/mandoc/mandoc_1.14.6-6_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  270k  100  270k    0     0  4600k      0 --:--:-- --:--:-- --:--:-- 4666k
extracting mandoc to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency python-pip@26.0.1 if necessary...
Found python-pip in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/python-pip/python-pip_26.0.1_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1143k  100 1143k    0     0  15.3M      0 --:--:-- --:--:-- --:--:-- 15.5M
extracting python-pip to /home/builder/.termux-build/_cache-all...
Downloading awscli@2.33.26 source from 'https://github.com/aws/aws-cli/archive/refs/tags/2.33.26.tar.gz' if necessary...
Downloading https://github.com/aws/aws-cli/archive/refs/tags/2.33.26.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 3596k    0 3596k    0     0  4202k      0 --:--:-- --:--:-- --:--:-- 4202k
100 9232k    0 9232k    0     0  4970k      0 --:--:--  0:00:01 --:--:-- 5630k
100 16.0M    0 16.0M    0     0  5732k      0 --:--:--  0:00:02 --:--:-- 6387k
100 16.8M    0 16.8M    0     0  5731k      0 --:--:--  0:00:03 --:--:-- 6341k
Applying ndk-patch: bits-struct_file.h.patch
Applying ndk-patch: dirent.h.patch
Applying ndk-patch: fcntl.h.patch
Applying ndk-patch: grp.h.patch
Applying ndk-patch: linux-fcntl.h.patch
Applying ndk-patch: paths.h.patch
Applying ndk-patch: pwd.h.patch
Applying ndk-patch: redefine-TCSAFLUSH.patch
Applying ndk-patch: semaphore.h.patch
Applying ndk-patch: stdio.h.patch
Applying ndk-patch: stdlib.h.patch
Applying ndk-patch: sys-cdefs.h.patch
Applying ndk-patch: syslog.patch
Applying ndk-patch: sys-time.h.patch
Applying ndk-patch: time.h.patch
Applying ndk-patch: unistd.h.patch
Applying ndk-patch: utmp.h.patch
::group::Applying `termux-elf-cleaner`
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/21/libandroid.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/21/libc.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/21/libdl.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/21/libEGL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/21/libGLESv1_CM.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/21/libGLESv2.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/21/libGLESv3.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/21/libjnigraphics.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/21/liblog.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/21/libmediandk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/21/libm.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/21/libOpenMAXAL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/21/libOpenSLES.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/21/libstdc++.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/21/libz.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/22/libandroid.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/22/libc.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/22/libdl.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/22/libEGL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/22/libGLESv1_CM.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/22/libGLESv2.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/22/libGLESv3.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/22/libjnigraphics.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/22/liblog.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/22/libm.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/22/libmediandk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/22/libOpenMAXAL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/22/libOpenSLES.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/22/libstdc++.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/22/libz.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/23/libandroid.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/23/libc.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/23/libdl.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/23/libEGL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/23/libGLESv1_CM.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/23/libGLESv2.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/23/libGLESv3.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/23/libjnigraphics.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/23/liblog.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/23/libmediandk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/23/libm.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/23/libOpenMAXAL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/23/libOpenSLES.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/23/libstdc++.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/23/libz.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/24/libandroid.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/24/libcamera2ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/24/libc.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/24/libdl.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/24/libEGL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/24/libGLESv1_CM.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/24/libGLESv2.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/24/libGLESv3.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/24/libjnigraphics.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/24/liblog.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/24/libmediandk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/24/libm.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/24/libOpenMAXAL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/24/libOpenSLES.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/24/libstdc++.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/24/libvulkan.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/24/libz.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/25/libandroid.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/25/libcamera2ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/25/libc.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/25/libdl.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/25/libEGL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/25/libGLESv1_CM.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/25/libGLESv2.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/25/libGLESv3.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/25/libjnigraphics.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/25/liblog.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/25/libmediandk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/25/libm.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/25/libOpenMAXAL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/25/libOpenSLES.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/25/libstdc++.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/25/libvulkan.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/25/libz.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libaaudio.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libandroid.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libcamera2ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libc.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libdl.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libEGL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libGLESv1_CM.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libGLESv2.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libGLESv3.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libjnigraphics.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/liblog.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libmediandk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libm.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libnativewindow.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libOpenMAXAL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libOpenSLES.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libstdc++.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libsync.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libvulkan.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/26/libz.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libaaudio.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libandroid.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libcamera2ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libc.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libdl.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libEGL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libGLESv1_CM.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libGLESv2.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libGLESv3.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libjnigraphics.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/liblog.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libmediandk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libm.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libnativewindow.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libneuralnetworks.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libOpenMAXAL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libOpenSLES.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libstdc++.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libsync.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libvulkan.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/27/libz.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libaaudio.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libandroid.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libcamera2ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libc.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libdl.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libEGL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libGLESv1_CM.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libGLESv2.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libGLESv3.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libjnigraphics.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/liblog.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libmediandk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libm.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libnativewindow.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libneuralnetworks.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libOpenSLES.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libstdc++.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libOpenMAXAL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libsync.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libvulkan.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/28/libz.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libaaudio.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libamidi.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libandroid.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libbinder_ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libcamera2ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libc.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libdl.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libEGL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libGLESv1_CM.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libGLESv2.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libGLESv3.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libjnigraphics.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/liblog.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libmediandk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libm.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libnativewindow.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libneuralnetworks.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libOpenMAXAL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libOpenSLES.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libstdc++.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libsync.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libvulkan.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/29/libz.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libaaudio.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libamidi.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libandroid.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libbinder_ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libcamera2ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libc.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libdl.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libEGL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libGLESv1_CM.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libGLESv2.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libGLESv3.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libjnigraphics.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/liblog.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libmediandk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libm.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libnativewindow.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libneuralnetworks.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libOpenMAXAL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libOpenSLES.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libstdc++.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libsync.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libvulkan.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/30/libz.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libaaudio.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libamidi.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libandroid.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libbinder_ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libcamera2ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libc.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libdl.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libEGL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libGLESv1_CM.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libGLESv2.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libGLESv3.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libicu.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libjnigraphics.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/liblog.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libmediandk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libm.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libnativehelper.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libnativewindow.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libneuralnetworks.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libOpenMAXAL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libOpenSLES.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libstdc++.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libsync.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libvulkan.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/31/libz.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libaaudio.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libamidi.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libandroid.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libbinder_ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libcamera2ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libc.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libdl.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libEGL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libGLESv1_CM.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libGLESv2.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libGLESv3.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libicu.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libjnigraphics.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/liblog.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libmediandk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libm.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libnativehelper.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libnativewindow.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libneuralnetworks.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libOpenMAXAL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libOpenSLES.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libstdc++.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libsync.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libvulkan.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/32/libz.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libaaudio.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libamidi.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libandroid.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libbinder_ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libcamera2ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libc.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libdl.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libEGL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libGLESv1_CM.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libGLESv2.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libGLESv3.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libicu.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libjnigraphics.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/liblog.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libmediandk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libm.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libnativehelper.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libnativewindow.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libneuralnetworks.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libOpenMAXAL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libOpenSLES.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libstdc++.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libsync.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libvulkan.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/33/libz.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libaaudio.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libamidi.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libandroid.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libbinder_ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libcamera2ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libc.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libdl.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libEGL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libGLESv1_CM.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libGLESv2.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libGLESv3.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libicu.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libjnigraphics.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/liblog.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libmediandk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libm.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libnativehelper.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libnativewindow.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libneuralnetworks.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libOpenMAXAL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libOpenSLES.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libstdc++.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libsync.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libvulkan.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/34/libz.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libaaudio.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libamidi.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libandroid.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libbinder_ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libcamera2ndk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libc.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libdl.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libEGL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libGLESv1_CM.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libGLESv2.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libGLESv3.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libicu.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libjnigraphics.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/liblog.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libmediandk.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libm.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libnativehelper.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libnativewindow.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libneuralnetworks.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libOpenMAXAL.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libOpenSLES.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libstdc++.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libsync.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libvulkan.so'
termux-elf-cleaner: Removing the DT_AARCH64_BTI_PLT dynamic section entry from 'usr/lib/aarch64-linux-android/35/libz.so'
::endgroup::
Downloading https://github.com/proot-me/proot/releases/download/v5.3.0/proot-v5.3.0-x86_64-static
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 1856k  100 1856k    0     0  7425k      0 --:--:-- --:--:-- --:--:-- 7425k
Downloading https://github.com/multiarch/qemu-user-static/releases/download/v7.2.0-1/qemu-aarch64-static
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  9.9M  100  9.9M    0     0  44.5M      0 --:--:-- --:--:-- --:--:-- 44.5M
configure: error: sources are in /home/builder/.termux-build/awscli/src, but `cd /home/builder/.termux-build/awscli/src' does not work
checking whether /data/data/com.termux/files/usr/bin/python version is >= 3.8... yes
checking for /data/data/com.termux/files/usr/bin/python version... 3.12
checking for /data/data/com.termux/files/usr/bin/python platform... linux
checking for GNU default /data/data/com.termux/files/usr/bin/python prefix... ${prefix}
checking for GNU default /data/data/com.termux/files/usr/bin/python exec_prefix... ${exec_prefix}
checking for /data/data/com.termux/files/usr/bin/python script directory (pythondir)... ${PYTHON_PREFIX}/lib/python3.12/site-packages
checking for /data/data/com.termux/files/usr/bin/python extension module directory (pyexecdir)... ${PYTHON_EXEC_PREFIX}/lib/python3.12/site-packages
checking for sqlite3... yes
checking for --with-install-type... portable-exe
checking for --with-download-deps... yes
configure: creating ./config.status
config.status: creating Makefile
Collecting flit-core==3.9.0 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/bootstrap-lock.txt (line 9))
  Downloading flit_core-3.9.0-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB 4.3 MB/s eta 0:00:00
Collecting pip==25.3 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/bootstrap-lock.txt (line 13))
  Downloading pip-25.3-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 17.6 MB/s eta 0:00:00
Collecting setuptools==78.1.1 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/bootstrap-lock.txt (line 17))
  Downloading setuptools-78.1.1-py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 28.8 MB/s eta 0:00:00
Collecting wheel==0.38.4 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/bootstrap-lock.txt (line 21))
  Downloading wheel-0.38.4-py3-none-any.whl (36 kB)
Collecting altgraph==0.17.5 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 7))
  Downloading altgraph-0.17.5-py2.py3-none-any.whl (21 kB)
Collecting awscrt==0.31.1 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 13))
  Downloading awscrt-0.31.1.tar.gz (38.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.1/38.1 MB 38.2 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting colorama==0.4.6 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 55))
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting distro==1.8.0 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 59))
  Downloading distro-1.8.0-py3-none-any.whl (20 kB)
Collecting docutils==0.19 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 63))
  Downloading docutils-0.19-py3-none-any.whl (570 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.5/570.5 kB 106.1 MB/s eta 0:00:00
Collecting importlib-metadata==7.1.0 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 67))
  Downloading importlib_metadata-7.1.0-py3-none-any.whl (24 kB)
Collecting jmespath==1.0.1 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 71))
  Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting macholib==1.16.4 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 75))
  Downloading macholib-1.16.4-py2.py3-none-any.whl (38 kB)
Collecting packaging==26.0 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 79))
  Downloading packaging-26.0-py3-none-any.whl (74 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.4/74.4 kB 27.7 MB/s eta 0:00:00
Collecting prompt-toolkit==3.0.51 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 85))
  Downloading prompt_toolkit-3.0.51-py3-none-any.whl (387 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 387.8/387.8 kB 89.6 MB/s eta 0:00:00
Collecting pyinstaller==6.11.1 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 89))
  Downloading pyinstaller-6.11.1.tar.gz (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 72.4 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting pyinstaller-hooks-contrib==2026.0 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 103))
  Downloading pyinstaller_hooks_contrib-2026.0-py3-none-any.whl (452 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 452.3/452.3 kB 88.4 MB/s eta 0:00:00
Collecting python-dateutil==2.9.0 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 107))
  Downloading python_dateutil-2.9.0-py2.py3-none-any.whl (230 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 230.5/230.5 kB 59.5 MB/s eta 0:00:00
Collecting ruamel-yaml==0.17.21 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 111))
  Downloading ruamel.yaml-0.17.21-py3-none-any.whl (109 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.5/109.5 kB 38.2 MB/s eta 0:00:00
Collecting ruamel-yaml-clib==0.2.12 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 115))
  Downloading ruamel.yaml.clib-0.2.12.tar.gz (225 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.3/225.3 kB 69.0 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting six==1.17.0 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 163))
  Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Collecting urllib3==2.6.3 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 167))
  Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.6/131.6 kB 47.5 MB/s eta 0:00:00
Collecting wcwidth==0.2.14 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 171))
  Downloading wcwidth-0.2.14-py2.py3-none-any.whl (37 kB)
Collecting zipp==3.23.0 (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 177))
  Downloading zipp-3.23.0-py3-none-any.whl (10 kB)
Saved ./wheelhouse/flit_core-3.9.0-py3-none-any.whl
Saved ./wheelhouse/pip-25.3-py3-none-any.whl
Saved ./wheelhouse/setuptools-78.1.1-py3-none-any.whl
Saved ./wheelhouse/wheel-0.38.4-py3-none-any.whl
Saved ./wheelhouse/altgraph-0.17.5-py2.py3-none-any.whl
Saved ./wheelhouse/awscrt-0.31.1.tar.gz
Saved ./wheelhouse/colorama-0.4.6-py2.py3-none-any.whl
Saved ./wheelhouse/distro-1.8.0-py3-none-any.whl
Saved ./wheelhouse/docutils-0.19-py3-none-any.whl
Saved ./wheelhouse/importlib_metadata-7.1.0-py3-none-any.whl
Saved ./wheelhouse/jmespath-1.0.1-py3-none-any.whl
Saved ./wheelhouse/macholib-1.16.4-py2.py3-none-any.whl
Saved ./wheelhouse/packaging-26.0-py3-none-any.whl
Saved ./wheelhouse/prompt_toolkit-3.0.51-py3-none-any.whl
Saved ./wheelhouse/pyinstaller-6.11.1.tar.gz
Saved ./wheelhouse/pyinstaller_hooks_contrib-2026.0-py3-none-any.whl
Saved ./wheelhouse/python_dateutil-2.9.0-py2.py3-none-any.whl
Saved ./wheelhouse/ruamel.yaml-0.17.21-py3-none-any.whl
Saved ./wheelhouse/ruamel.yaml.clib-0.2.12.tar.gz
Saved ./wheelhouse/six-1.17.0-py2.py3-none-any.whl
Saved ./wheelhouse/urllib3-2.6.3-py3-none-any.whl
Saved ./wheelhouse/wcwidth-0.2.14-py2.py3-none-any.whl
Saved ./wheelhouse/zipp-3.23.0-py3-none-any.whl
Successfully downloaded flit-core pip setuptools wheel altgraph awscrt colorama distro docutils importlib-metadata jmespath macholib packaging prompt-toolkit pyinstaller pyinstaller-hooks-contrib python-dateutil ruamel-yaml ruamel-yaml-clib six urllib3 wcwidth zipp
PYTHONDONTWRITEBYTECODE=1 "/data/data/com.termux/files/usr/bin/python" "/home/builder/.termux-build/awscli/src/backends/build_system" \
	build \
	--artifact "portable-exe" \
	--build-dir "./build" --download-deps
Looking in links: file:///home/builder/.termux-build/awscli/build/wheelhouse
Processing ./wheelhouse/flit_core-3.9.0-py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/bootstrap-lock.txt (line 9))
Processing ./wheelhouse/pip-25.3-py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/bootstrap-lock.txt (line 13))
Processing ./wheelhouse/setuptools-78.1.1-py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/bootstrap-lock.txt (line 17))
Processing ./wheelhouse/wheel-0.38.4-py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/bootstrap-lock.txt (line 21))
Installing collected packages: wheel, setuptools, pip, flit-core
  Attempting uninstall: pip
    Found existing installation: pip 25.0.1
    Uninstalling pip-25.0.1:
      Successfully uninstalled pip-25.0.1
Successfully installed flit-core-3.9.0 pip-25.3 setuptools-78.1.1 wheel-0.38.4
Looking in links: file:///home/builder/.termux-build/awscli/build/wheelhouse
Processing ./wheelhouse/altgraph-0.17.5-py2.py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 7))
Processing ./wheelhouse/awscrt-0.31.1.tar.gz (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 13))
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Processing ./wheelhouse/colorama-0.4.6-py2.py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 55))
Processing ./wheelhouse/distro-1.8.0-py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 59))
Processing ./wheelhouse/docutils-0.19-py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 63))
Processing ./wheelhouse/importlib_metadata-7.1.0-py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 67))
Processing ./wheelhouse/jmespath-1.0.1-py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 71))
Processing ./wheelhouse/macholib-1.16.4-py2.py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 75))
Processing ./wheelhouse/packaging-26.0-py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 79))
Processing ./wheelhouse/prompt_toolkit-3.0.51-py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 85))
Processing ./wheelhouse/pyinstaller-6.11.1.tar.gz (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 89))
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Processing ./wheelhouse/pyinstaller_hooks_contrib-2026.0-py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 103))
Processing ./wheelhouse/python_dateutil-2.9.0-py2.py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 107))
Processing ./wheelhouse/ruamel.yaml-0.17.21-py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 111))
Processing ./wheelhouse/ruamel.yaml.clib-0.2.12.tar.gz (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 115))
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Processing ./wheelhouse/six-1.17.0-py2.py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 163))
Processing ./wheelhouse/urllib3-2.6.3-py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 167))
Processing ./wheelhouse/wcwidth-0.2.14-py2.py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 171))
Processing ./wheelhouse/zipp-3.23.0-py3-none-any.whl (from -r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 177))
Requirement already satisfied: setuptools>=42.0.0 in ./build/venv/lib/python3.12/site-packages (from pyinstaller==6.11.1->-r /home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt (line 89)) (78.1.1)
Building wheels for collected packages: awscrt, pyinstaller, ruamel-yaml-clib
  Building wheel for awscrt (pyproject.toml): started
  Building wheel for awscrt (pyproject.toml): still running...
  Building wheel for awscrt (pyproject.toml): still running...
  Building wheel for awscrt (pyproject.toml): still running...
  Building wheel for awscrt (pyproject.toml): still running...
  Building wheel for awscrt (pyproject.toml): still running...
  Building wheel for awscrt (pyproject.toml): finished with status 'done'
  Created wheel for awscrt: filename=awscrt-0.31.1-cp311-abi3-linux_aarch64.whl size=3888259 sha256=a5ffa52601717f41aa41d5b5260149860822f718e3411c99639ffa7a37a15075
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/a6/ea/d9/40977fc06a1c152e0fffc02596c9580e1d5086967de70cbd12
  Building wheel for pyinstaller (pyproject.toml): started
  Building wheel for pyinstaller (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for pyinstaller (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [128 lines of output]
      /home/builder/.termux-build/awscli/build/build/venv/lib/python3.12/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
      !!
      
              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:
      
              License :: OSI Approved :: GNU General Public License v2 (GPLv2)
      
              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************
      
      !!
        self._finalize_license_expression()
      /home/builder/.termux-build/awscli/build/build/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py:280: _IncompatibleBdistWheel: wheel.bdist_wheel is deprecated, please import it from setuptools
      !!
      
              ********************************************************************************
              Ensure that any custom bdist_wheel implementation is a subclass of
              setuptools.command.bdist_wheel.bdist_wheel.
      
              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
      
              See https://github.com/pypa/wheel/pull/631 for details.
              ********************************************************************************
      
      !!
        return _build_backend().build_wheel(
      /home/builder/.termux-build/awscli/build/build/venv/lib/python3.12/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
      !!
      
              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:
      
              License :: OSI Approved :: GNU General Public License v2 (GPLv2)
      
              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************
      
      !!
        self._finalize_license_expression()
      running bdist_wheel
      running clean
      'build/lib' does not exist -- can't clean it
      'build/bdist.linux-aarch64' does not exist -- can't clean it
      'build/scripts-3.12' does not exist -- can't clean it
      running build
      running build_bootloader
      No precompiled bootloader found or compile forced. Trying to compile the bootloader for you ...
      Setting top to                           : /data/data/com.termux/files/usr/tmp/pip-install-i0cv9zyf/pyinstaller_63bfddca79234a73aac63ddc9338d715/bootloader
      Setting out to                           : /data/data/com.termux/files/usr/tmp/pip-install-i0cv9zyf/pyinstaller_63bfddca79234a73aac63ddc9338d715/bootloader/build
      Python Version                           : 3.12.12 (main, Jan 18 2026, 04:37:25) [Clang 21.0.0 (https://android.googlesource.com/toolchain/llvm-project 5e96669f0
      MSVC target(s)                           : not found
      Checking for 'gcc' (C compiler)          : not found
      Checking for 'clang' (C compiler)        : aarch64-linux-android-clang
      Checking size of pointer                 : 8
      Platform                                 : Linux-64bit-arm detected based on compiler
      Checking for compiler flags -m64         : yes
      Checking for linker flags -m64           : yes
      Checking for library dl                  : yes
      Checking for library pthread             : yes
      Checking for library m                   : yes
      Checking for library z                   : yes
      Build tests                              : disabled
      Checking for header stdbool.h            : yes
      Checking for function unsetenv           : yes
      Checking for function mkdtemp            : yes
      Checking for function dirname            : yes
      Checking for function basename           : yes
      Checking for linker flags -Wl,--as-needed : yes
      Checking for program 'strip'              : /usr/bin/strip
      Checking for program 'strip'              : /usr/bin/strip
      'configure' finished successfully (13.431s)
      'all' finished successfully (0.003s)
      'distclean' finished successfully (0.023s)
      Setting top to                           : /data/data/com.termux/files/usr/tmp/pip-install-i0cv9zyf/pyinstaller_63bfddca79234a73aac63ddc9338d715/bootloader
      Setting out to                           : /data/data/com.termux/files/usr/tmp/pip-install-i0cv9zyf/pyinstaller_63bfddca79234a73aac63ddc9338d715/bootloader/build
      Python Version                           : 3.12.12 (main, Jan 18 2026, 04:37:25) [Clang 21.0.0 (https://android.googlesource.com/toolchain/llvm-project 5e96669f0
      MSVC target(s)                           : not found
      Checking for 'gcc' (C compiler)          : not found
      Checking for 'clang' (C compiler)        : aarch64-linux-android-clang
      Checking size of pointer                 : 8
      Platform                                 : Linux-64bit-arm detected based on compiler
      Checking for compiler flags -m64         : yes
      Checking for linker flags -m64           : yes
      Checking for library dl                  : yes
      Checking for library pthread             : yes
      Checking for library m                   : yes
      Checking for library z                   : yes
      Build tests                              : disabled
      Checking for header stdbool.h            : yes
      Checking for function unsetenv           : yes
      Checking for function mkdtemp            : yes
      Checking for function dirname            : yes
      Checking for function basename           : yes
      Checking for linker flags -Wl,--as-needed : yes
      Checking for program 'strip'              : /usr/bin/strip
      Checking for program 'strip'              : /usr/bin/strip
      'configure' finished successfully (8.257s)
      'make_all' finished successfully (0.189s)
      Waf: Entering directory `/data/data/com.termux/files/usr/tmp/pip-install-i0cv9zyf/pyinstaller_63bfddca79234a73aac63ddc9338d715/bootloader/build/debug'
      [ 1/21] Compiling src/pyi_utils.c
      [ 2/21] Compiling src/pyi_main.c
      [ 3/21] Compiling src/pyi_exception_dialog.c
      [ 4/21] Compiling src/pyi_apple_events.c
      [ 5/21] Compiling src/pyi_splashlib.c
      [ 6/21] Compiling src/pyi_global_posix.c
      [ 7/21] Compiling src/pyi_multipkg.c
      [ 8/21] Compiling src/pyi_utils_posix.c
      [ 9/21] Compiling src/pyi_splash.c
      [10/21] Compiling src/pyi_pythonlib.c
      [11/21] Compiling src/pyi_launch.c
      [12/21] Compiling src/pyi_archive.c
      [13/21] Compiling src/pyi_pyconfig.c
      [14/21] Compiling src/pyi_path.c
      [15/21] Compiling src/pyi_utils_win32.c
      [16/21] Compiling src/pyi_utils_win32_low_level.c
      [17/21] Compiling src/pyi_python.c
      [18/21] Compiling src/pyi_global_win32.c
      [19/21] Compiling src/main.c
      [20/21] Linking build/debug/run_d
      [21/21] Processing build/debug/run_d
      /usr/bin/strip: Unable to recognise the format of the input file `run_d'
      
      Waf: Leaving directory `/data/data/com.termux/files/usr/tmp/pip-install-i0cv9zyf/pyinstaller_63bfddca79234a73aac63ddc9338d715/bootloader/build/debug'
      Build failed
       -> task in 'run_d' failed with exit status 1 (run with -v to display more information)
      ERROR: Failed compiling the bootloader. Please compile manually and rerun
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyinstaller
  Building wheel for ruamel-yaml-clib (pyproject.toml): started
  Building wheel for ruamel-yaml-clib (pyproject.toml): finished with status 'done'
  Created wheel for ruamel-yaml-clib: filename=ruamel.yaml.clib-0.2.12-cp312-cp312-linux_aarch64.whl size=149071 sha256=39a93dd59b216bff64dfa25555bdb330d4c66b7870a37dac37b6ca6e0b69c16a
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/f7/b5/ff/f73f1ccbfb42f75e488e22ed14c3ff6368aa3c91235c2cc47a
Successfully built awscrt ruamel-yaml-clib
Failed to build pyinstaller
error: failed-wheel-build-for-install

× Failed to build installable wheels for some pyproject.toml based projects
╰─> pyinstaller
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/builder/.termux-build/awscli/src/backends/build_system/__main__.py", line 127, in <module>
    main()
  File "/home/builder/.termux-build/awscli/src/backends/build_system/__main__.py", line 123, in main
    parsed_args.func(parsed_args)
  File "/home/builder/.termux-build/awscli/src/backends/build_system/__main__.py", line 41, in build
    aws_venv = _bootstap_venv(
               ^^^^^^^^^^^^^^^
  File "/home/builder/.termux-build/awscli/src/backends/build_system/__main__.py", line 76, in _bootstap_venv
    aws_venv.bootstrap(artifact_type, download_deps)
  File "/home/builder/.termux-build/awscli/src/backends/build_system/awscli_venv.py", line 56, in bootstrap
    self._install_requirements(PORTABLE_EXE_REQUIREMENTS_LOCK)
  File "/home/builder/.termux-build/awscli/src/backends/build_system/awscli_venv.py", line 79, in _install_requirements
    self._pip_install(
  File "/home/builder/.termux-build/awscli/src/backends/build_system/awscli_venv.py", line 135, in _pip_install
    self._utils.run(args, **run_kwargs)
  File "/home/builder/.termux-build/awscli/src/backends/build_system/utils.py", line 235, in run
    return subprocess.run(args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/builder/.termux-build/awscli/build/build/venv/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '-r', PosixPath('/home/builder/.termux-build/awscli/src/requirements/download-deps/portable-exe-lock.txt')]' returned non-zero exit status 1.
make: *** [Makefile:20: build] Error 1
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occurred when I last tried to update at 2026-02-20 01:49:55 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/22205581448">22205581448</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

### PR DESCRIPTION
**Pull request by Kapral67**
- fixes #28546

### CODE REVIEW

**Comment by Kapral67** [comment]
Noticed in the builds `CMAKE_MAKE_PROGRAM=/usr/bin/gmake` not sure if this causing the issue or something else

**Comment by robertkirkman** [comment]
> Noticed in the builds `CMAKE_MAKE_PROGRAM=/usr/bin/gmake` not sure if this causing the issue or something else

`/usr/bin/gmake` should be fine to use

**Comment by robertkirkman** [comment]
> `SystemError: objcopy Failure: 1 objcopy: Unable to recognise the format of the input file '/home/runner/.termux-build/awscli/build/build/exe/build/aws/aws'`

I think this means the same thing will be necessary for `$OBJCOPY` also

**Comment by Kapral67** [comment]
> > `SystemError: objcopy Failure: 1 objcopy: Unable to recognise the format of the input file '/home/runner/.termux-build/awscli/build/build/exe/build/aws/aws'`
> 
> I think this means the same thing will be necessary for `$OBJCOPY` also

added everything from this toolchain https://github.com/termux/termux-packages/blob/master/scripts/build/toolchain/termux_setup_toolchain_29.sh#L6-L18

**Comment by robertkirkman** [comment]
Good idea

**Comment by Kapral67** [comment]
probably need to put these toolchain utilities on the path somehow https://github.com/pyinstaller/pyinstaller/blob/a7a674af7fd4505b36007709962206c4d3e77e08/PyInstaller/building/api.py#L836-L839

**Comment by robertkirkman** [comment]
> probably need to put these toolchain utilities on the path somehow https://github.com/pyinstaller/pyinstaller/blob/a7a674af7fd4505b36007709962206c4d3e77e08/PyInstaller/building/api.py#L836-L839

That code will need to be patched to work, it uses "`objcopy`" directly but we need to run `llvm-objcopy` instead (`$OBJCOPY`)

**Comment by Kapral67** [comment]
patching may be tricky since currently it only downloads pyinstaller as a wheel

**Comment by Kapral67** [comment]
maybe proot bind `/data/data/com.termux/files/usr/bin/objcopy` -> llvm-objcopy ?

**Comment by robertkirkman** [comment]
> maybe proot bind `/data/data/com.termux/files/usr/bin/objcopy` -> llvm-objcopy ?

I think you can try, it sounds like a good idea

**Comment by robertkirkman** [comment]
well, that or maybe also this

**Comment by robertkirkman** [comment]
```bash
mkdir -p "$TERMUX_PKG_TMPDIR/bin"
ln -sf "$(command -v "$OBJCOPY")" "$TERMUX_PKG_TMPDIR/bin/objcopy"
export PATH="$TERMUX_PKG_TMPDIR/bin:$PATH"
```

File: packages/awscli/build.sh [hunk 1]
```diff
@@ -27,15 +28,53 @@ termux_step_pre_configure() {
 
 	local PYTHON_INCLUDE="$TERMUX_PREFIX/include/python$TERMUX_PYTHON_VERSION"
 
+	rm -rf "${TERMUX_PKG_TMPDIR:?}/bin"
```
Comment (TomJo2000) [inline packages/awscli/build.sh]: We don't usually use the `:?` errors within build scripts.
Builds run in a `set -e -u` context so a null value already raises an error.
If you wanna be more specfic with the error message you can catch it with `termux_error_exit`.
```suggestion
	rm -rf "${TERMUX_PKG_TMPDIR}/bin" || termux_error_exit "failed to remove build tool temp directory"
```

I can only find one other instance of the `:?` expansion being used in a build.
https://github.com/termux/termux-packages/blob/64e221ce576374fb80c177d31052f7eb97b0d6b8/packages/git-credential-manager/build.sh#L39
And I don't why I *[(according to `git blame`)](https://github.com/termux/termux-packages/blob/64e221ce576374fb80c177d31052f7eb97b0d6b8/packages/git-credential-manager/build.sh#L39)* did that.

File: packages/awscli/build.sh [hunk 2]
```diff
@@ -27,15 +28,53 @@ termux_step_pre_configure() {
...
+		[ranlib]=RANLIB
+		[readelf]=READELF
+		[strip]=STRIP
+		[nm]=NM
+		[cxxfilt]=CXXFILT
+	)
+
+	local target cmd path
+	for target in "${!tools[@]}"; do
+		cmd="${!tools[$target]}"
```
Comment (TomJo2000) [inline packages/awscli/build.sh:55]: Isn't the *key* of `tools[$target]` the same thing as `$target` here,
since `$target` is already the sequence of keys of the `$tools` array.

Unless this is actually parameter indirection[^1]...
[^1]: https://man.archlinux.org/man/bash.1#Parameter_Expansion:~:text=If%20the%20first%20character%20of%20parameter%20is%20an%20exclamation%20point%20(!)%2C%20and%20parameter%20is%20not%20a%20nameref%2C%20it%20introduces%20a%20level%20of%20indirection.%20Bash%20uses%20the%20value%20formed%20by%20expanding%20the%20rest%20of%20parameter%20as%20the%20new%20parameter

<h1><em></em></h1> 

Actually, reading that section closely.
```console
If the first character of parameter is an exclamation point (!), and
parameter is not a nameref, it introduces a level of indirection.  Bash
uses the value formed by expanding the rest of parameter as the new
parameter; this new parameter is then expanded and that value is used
in the rest of the expansion, rather than the expansion of the original
parameter.  This is known as indirect expansion.
# [...]
The exceptions to this
are the expansions of ${!prefix*} and ${!name[@]} described below.
```
`${!array[$idx]}` is not mentioned as an exception to the indirection, so does it actually indirect here?
If so then that is a very subtle and non-obvious behavior and should be explained in a comment.

File: packages/awscli/build.sh [hunk 3]
```diff
@@ -27,15 +28,53 @@ termux_step_pre_configure() {
...
+		path=$(command -v "$cmd") || continue
+		ln -sf "$path" "$TERMUX_PKG_TMPDIR/bin/$target"
+	done
+
+	chmod +x "$TERMUX_PKG_TMPDIR/bin/"*
```
Comment (TomJo2000) [inline packages/awscli/build.sh]: I don't believe changing the permissions of the symlink should have any effect since it is a pointer to the underlying file, which is what ultimately matters permission-wise when accessed.

#### Quote:
```console
The permissions of a symbolic link are irrelevant; the ownership is
ignored when following the link (except when the protected_symlinks
feature is enabled, as explained in proc(5)), but is checked when
removal or renaming of the link is requested and the link is in a
directory with the sticky bit (S_ISVTX) set.
```
<sup>https://man.archlinux.org/man/symlink.2#DESCRIPTION</sup>

Although... `chmod` does operate on the targets of symlinks as its default behavior.

#### Quote 2:
```
chmod doesn't change the permissions of symbolic links; the chmod
system call cannot change their permissions on most systems, and most
systems ignore permissions of symbolic links.  However, for each
symbolic link listed on the command line, chmod changes the permissions
of the pointed-to file.  In contrast, chmod ignores symbolic links
encountered during recursive directory traversals. Options that modify
this behavior are described in the OPTIONS section.
```
<sup>https://man.archlinux.org/man/chmod.1#DESCRIPTION</sup>

So this would be modifying the paths returned from `command -v` above...
*Which would have failed if the requested command wasn't already executable*

Image

So this `chmod` *is* redundant, but not for the reason I initially thought.

File: packages/awscli/build.sh [hunk 4]
```diff
@@ -27,15 +28,53 @@ termux_step_pre_configure() {
...
+		[readelf]=READELF
+		[strip]=STRIP
+		[nm]=NM
+		[cxxfilt]=CXXFILT
+	)
+
+	local target cmd path
+	for target in "${!tools[@]}"; do
+		cmd="${!tools[$target]}"
+		path=$(command -v "$cmd") || continue
```
Comment (TomJo2000) [inline packages/awscli/build.sh]: This should be quoted just in case.
<sup>And to shut `shellcheck` up.</sup>
```suggestion
		path="$(command -v "$cmd")" || continue
```

File: packages/awscli/build.sh (hunk 1 above)
Comment (Kapral67) [reply packages/awscli/build.sh]: Does `set -e -u` make sure it would not to execute as `rm -rf ””/bin`?

File: packages/awscli/build.sh (hunk 3 above)
Comment (Kapral67) [reply packages/awscli/build.sh]: good point, will update

File: packages/awscli/build.sh (hunk 2 above)
Comment (Kapral67) [reply packages/awscli/build.sh:55]: Here trying to treat tools[target] as an environment variable instead of a string. can update to leave a comment about it.

Something like `${${array[$idx]}}`

File: packages/awscli/build.sh (hunk 1 above)
Comment (TomJo2000) [reply packages/awscli/build.sh]: Yeah I hadn't thought that far ahead at the time I wrote that comment.
I did find out *why* I used that though, it's what Shellcheck recommends for that warning.
https://www.shellcheck.net/wiki/SC2115

The way I decided to resolve it for `git-credential-manager` was by manually sanity checking the variables before use.
https://github.com/termux/termux-packages/pull/28553/changes

File: packages/awscli/build.sh (hunk 2 above)
Comment (TomJo2000) [reply packages/awscli/build.sh:55]: Okay so this is using the indirection syntax.
It's unfortunate that `${!arr[@]}` and `${!arr[idx]}` have completely separate purposes.

File: packages/awscli/build.sh (hunk 1 above)
Comment (Kapral67) [reply packages/awscli/build.sh]: sounds good. will update to do the same pattern

Comment (TomJo2000) [reply packages/awscli/build.sh]: Please also include the `# shellcheck disable=SC2115` comment immediately above the function declaration to tell Shellcheck that we're aware of this and don't wanna consider it an error in this function.
The comment further above may also be useful.
