### PR TITLE
addpkg(x11/zen-browser): 1.19.9b

### LINKED ISSUE #27821: [Package]: Zen-browser
### Why is it worth to add this package?

> Zen is a firefox-based browser with the aim of pushing your productivity to a new level!\
Zen Browser is a beautifully designed firefox-based browser

### Home page URL

https://zen-browser.app/

### Source code URL

https://github.com/zen-browser/desktop

### Packaging policy acknowledgement

- [x] The project is actively developed.
- [x] The project has [existing packages](https://repology.org/projects/) and is "well known".
- [x] Licensed under an [open source license](https://spdx.org/licenses/).
- [x] Not available through a language package manager: cargo, cpan, dotnet tool, gem, npm, pip, etc.

- [x] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [x] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [x] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sabamdarif**
* Fixes #27821

### CODE REVIEW

**Review by robertkirkman — APPROVED** [review]
Good job

**Comment by robertkirkman** [comment]
Like the maintainer of librewolf package 3ls-it also agreed, do you promise to manually copy and paste all changes I make to the firefox package that can also apply to zen-browser but which are not automatically applied, from firefox to zen-browser and PR them in the future in the event that changes appear in the firefox package without appearing simultaneously in the zen-browser package?

**Comment by sabamdarif** [comment]
yes i can maintain it

File: x11-packages/zen-browser/build.sh [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+	./mach build -j "$TERMUX_PKG_MAKE_PROCESSES"
+	./mach buildsymbols
+}
+
+termux_step_make_install() {
+	./mach install
+
+	# Create binary launcher links
+	if [ -e "${TERMUX_PREFIX}/lib/${TERMUX_PKG_NAME}/${TERMUX_PKG_NAME}" ]; then
+		ln -sf "${TERMUX_PREFIX}/lib/${TERMUX_PKG_NAME}/${TERMUX_PKG_NAME}" "${TERMUX_PREFIX}/bin/${TERMUX_PKG_NAME}"
```
Comment (sabamdarif) [inline x11-packages/zen-browser/build.sh]: i have a question about this zen and any firefox based browser generate two launcher file one is (for zen) zen-browser and zen-browser-bin , so i just go with zen-browser . should i need to add a fallback so if zen-browser isn't available but zen-browser-bin available then link zen-browser-bin . you see if in case that ever happened or is this good ? 
Also should i check if ${TERMUX_PREFIX}/bin/${TERMUX_PKG_NAME} doesn't exist then make a symlink ? 
the reason i did this last time when i checked it it created a broken symlink in ${TERMUX_PREFIX}/bin that's why i did it manually

Comment (robertkirkman) [reply x11-packages/zen-browser/build.sh]: > i have a question about this zen and any firefox based browser generate two launcher file one is (for zen) zen-browser and zen-browser-bin , so i just go with zen-browser .

The reason why firefox upstream, by default, has 2 identical copies in every package of itself, originally many years ago was a vestigial legacy quirk having to do with the auto updating behavior of the official version of firefox where it updates itself if you download it from the mozilla website instead of compiling it. therefore, from the start, the `firefox-bin` extra binary was never necessary on distros that compile their own firefox packages, but it is just there as legacy backwards compatibility for some reason.

https://bugzilla.mozilla.org/show_bug.cgi?id=658850

```
~ $ file $PREFIX/bin/firefox
/data/data/com.termux/files/usr/bin/firefox: symbolic link to /data/data/com.termux/files/usr/lib/firefox/firefox
~ $ file $PREFIX/lib/firefox/firefox
/data/data/com.termux/files/usr/lib/firefox/firefox: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, for Android 24, built by NDK r29 (14206865), BuildID[sha1]=ccb12b6a618b9e68e969e7ea8cb1163bb601c7e9, stripped
~ $ file $PREFIX/lib/firefox/firefox-bin
/data/data/com.termux/files/usr/lib/firefox/firefox-bin: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, for Android 24, built by NDK r29 (14206865), BuildID[sha1]=ccb12b6a618b9e68e969e7ea8cb1163bb601c7e9, stripped
~ $ diff $PREFIX/lib/firefox/firefox $PREFIX/lib/firefox/firefox-bin
~ $ 
```

They are identical so it really is just a copy of the browser executable in the same folder.

Arch Linux Firefox packages actually remove that extra one `firefox-bin` and replace it with a wrapper script that runs the normal one `firefox`, and that saves a lot of space in the package,

https://gitlab.archlinux.org/archlinux/packaging/packages/firefox/-/blob/79485441f8b5875d618f0a121fd6c4b5e0c9bbd2/PKGBUILD#L294

that would be completely fine to do in Termux, but if done it should happen in the `firefox` package first and then be copied to the forks. I have never done that while editing Termux `firefox` because I just didn't worry about it very much, it didn't seem like a big problem to me, and I believe upstream knows that it's a space-inefficient default, so if they want to they'll eventually remove the extra binary upstream and that would fix it everywhere (so I just thought "if it's not broken i won't fix it")

> should i need to add a fallback so if zen-browser isn't available but zen-browser-bin available then link zen-browser-bin

I think changes that are not specific to zen-browser should be in firefox first, then copied to the forks. Currently there is only one link in `$TERMUX_PREFIX/bin` for both `firefox` and `zen-browser`, `firefox` and `zen-browser` respectively, so I don't think it's necessary to add other link for `zen-browser-bin`.

Comment (robertkirkman) [reply x11-packages/zen-browser/build.sh]: Does that explanation answer all your questions?

Comment (sabamdarif) [reply x11-packages/zen-browser/build.sh]: ok i shouldn't touch it then 👍

Comment (robertkirkman) [reply x11-packages/zen-browser/build.sh]: Oh, @sabamdarif  also I have a review for this version, this should not have an `if` statement in your added code, if it's necessary to manually create a executable in `$TERMUX_PREFIX/bin` if zen-browser doesn't automatically create one.

The symbolic link should always be created regardless of any condition, and if you are concerned that the browser excutable will not be in `lib/zen-browser`, make a condition that checks that and uses **`termux_error_exit "zen-browser executable must exist"`** if it is not found. however I would advise against that because Firefox doesn't currently need that.

Comment (robertkirkman) [reply x11-packages/zen-browser/build.sh]: So basically I would prefer if you change it to just this:

```bash
ln -sf "${TERMUX_PREFIX}/lib/${TERMUX_PKG_NAME}/${TERMUX_PKG_NAME}" "${TERMUX_PREFIX}/bin/${TERMUX_PKG_NAME}"
```

or if you really want the check, this:

```bash
if [[ ! -e "${TERMUX_PREFIX}/lib/${TERMUX_PKG_NAME}/${TERMUX_PKG_NAME}" ]]; then
    termux_error_exit "No zen-browser binary found in ${TERMUX_PREFIX}/lib/${TERMUX_PKG_NAME}/${TERMUX_PKG_NAME}"
fi
ln -sf "${TERMUX_PREFIX}/lib/${TERMUX_PKG_NAME}/${TERMUX_PKG_NAME}" "${TERMUX_PREFIX}/bin/${TERMUX_PKG_NAME}"
```

Comment (sabamdarif) [reply x11-packages/zen-browser/build.sh]: ok

File: x11-packages/zen-browser/build.sh [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+}
+
+termux_step_make_install() {
+	./mach install
+
+	# Create binary launcher links
+	if [[ ! -e "${TERMUX_PREFIX}/lib/${TERMUX_PKG_NAME}/${TERMUX_PKG_NAME}" ]]; then
+		termux_error_exit "No zen-browser binary found in ${TERMUX_PREFIX}/lib/${TERMUX_PKG_NAME}/${TERMUX_PKG_NAME}"
+	fi
+	ln -sf "${TERMUX_PREFIX}/lib/${TERMUX_PKG_NAME}/${TERMUX_PKG_NAME}" "${TERMUX_PREFIX}/bin/${TERMUX_PKG_NAME}"
```
Comment (robertkirkman) [inline x11-packages/zen-browser/build.sh]: @sabamdarif sorry to complain about this, but, in our previous discussion, I assumed that this line was necessary because of a `$TERMUX_PREFIX/bin/zen-browser` link not getting created automatically.

however, I thought to check myself by downloading and building this PR on my computer with this line removed, and when I do that and I check the resulting package, for me it already automatically creates this symbolic link.

Could you explain why you added this from the start?

Comment (sabamdarif) [reply x11-packages/zen-browser/build.sh]: so i added this because at first i found that there isn't any command called zen-browser so i symlink lib/firefox/firefox to zen-browser

Comment (sabamdarif) [reply x11-packages/zen-browser/build.sh]: wait i think i find the issue we don't need this because back then i didn't did this https://github.com/termux/termux-packages/pull/29575/changes#diff-705095a43722620080e6d9b3e030b8f8a85a88e2bd3d19e7f6ebbb3a82e3fb2cR15-R16

let me build one without the symlink part

Comment (robertkirkman) [reply x11-packages/zen-browser/build.sh]: Yes I think so, that is what I was wondering about, I hope it can just be the same as firefox here and not have this part about making the symbolic link

Comment (sabamdarif) [reply x11-packages/zen-browser/build.sh]: @robertkirkman  it's working without the symlink part

**Comment by robertkirkman** [comment]
I will merge it in 24 hours if nobody objects to this.

**Comment by robertkirkman** [comment]
@sabamdarif in the releases of the zen-browser github, there is a newer version 1.19.10b, I was wondering do you know why it didn't get auto updated to that version yet? https://github.com/zen-browser/desktop/releases

**Comment by robertkirkman** [comment]
Oh, you did not enable auto update.

Would you want to enable auto update?

**Comment by sabamdarif** [comment]
yes I will
