### PR TITLE
addpkg(main/opustags): Ogg Opus tags editor

### LINKED ISSUE #25659: [Package]: opustags
### Why is it worth to add this package?

makes it really easy to edit opus tags instead of using ffmpeg's complex syntax

### Home page URL

_No response_

### Source code URL

https://github.com/fmang/opustags

### Packaging policy acknowledgement

- [x] The project is actively developed.
- [x] The project has [existing packages](https://repology.org/projects/) and is "well known".
- [x] Licensed under an [open source license](https://spdx.org/licenses/).
- [x] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [x] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [x] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [x] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

https://aur.archlinux.org/packages/opustags
https://aur.archlinux.org/packages/opustags-git

### PR DESCRIPTION
**Pull request by murataslan1**
A command-line tool to view and edit Ogg Opus comments/tags.

**Features:**
- Interactive editing using your preferred text editor
- Batch editing with command-line flags
- Tags exporting and importing through text files
- Fast and conservative (bit-perfect copies when reverting changes)

**Package details:**
- Homepage: https://github.com/fmang/opustags
- License: BSD-3-Clause
- Version: 1.10.1
- Dependencies: libogg
- Build system: CMake

Closes #25659

### CODE REVIEW

File: packages/opustags/build.sh [hunk 1]
```diff
@@ -0,0 +1,9 @@
+TERMUX_PKG_HOMEPAGE=https://github.com/fmang/opustags
+TERMUX_PKG_DESCRIPTION="Ogg Opus tags editor"
+TERMUX_PKG_LICENSE="BSD-3-Clause"
```
Comment (robertkirkman) [inline packages/opustags/build.sh]: oh sorry, I thought it had passed CI already for some reason.

In order to specify this license in Termux, write the line like this:

```
TERMUX_PKG_LICENSE="BSD 3-Clause"
```

**Comment by robertkirkman** [comment]
> `fatal error: 'iconv.h' file not found`

This means that `libiconv` needs to be added to `TERMUX_PKG_DEPENDS`, in order to fix that error

File: packages/opustags/build.sh [hunk 2]
```diff
@@ -0,0 +1,10 @@
+TERMUX_PKG_HOMEPAGE=https://github.com/fmang/opustags
+TERMUX_PKG_DESCRIPTION="Ogg Opus tags editor"
+TERMUX_PKG_LICENSE="BSD 3-Clause"
+TERMUX_PKG_MAINTAINER="@termux"
+TERMUX_PKG_VERSION="1.10.1"
+TERMUX_PKG_SRCURL=https://github.com/fmang/opustags/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
+TERMUX_PKG_SHA256=703096e9c41481e30ab90eefdd8fafc4c3a138998b3f8281aa4f023e7058bc86
+TERMUX_PKG_AUTO_UPDATE=true
+TERMUX_PKG_DEPENDS="libiconv, libogg"
+TERMUX_PKG_BUILD_DEPENDS="libiconv"
```
Comment (robertkirkman) [inline packages/opustags/build.sh]: Also, `libiconv` only needs to be in `TERMUX_PKG_DEPENDS`, not also in `TERMUX_PKG_BUILD_DEPENDS`.

**Comment by robertkirkman** [comment]
> Well? Just need to push again to get CI going, right?

Yes, unfortunately my account doesn't have permission to push other people's PRs, but when murataslan1 comes back I am sure they will

**Review by robertkirkman — APPROVED** [review]

**Comment by murataslan1** [comment]
Hi! Thanks for the approval. Is there anything else needed before this can be merged? Happy to address any remaining feedback.

**Comment by robertkirkman** [comment]
Yes, I was about to merge it but now you edited it again and there is a failure, you can read the log and the notification message that you can expand at the top of the log to see what you are supposed to do

image
