### PR TITLE
addpkg(root/btop): 1.4.5 

### LINKED ISSUE #8566: [Package]: btop
### Package description

Resource monitor that shows usage and stats for processor, memory, disks, network and processes.

### Home page URL

_No response_

### Source code URL

https://github.com/aristocratos/btop

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

_No response_

### LINKED ISSUE #22111: [Package]: Btop
### Why is it worth to add this package?

Modern and colorful command line resource monitor that shows usage and stats.

### Home page URL

https://github.com/aristocratos/btop

### Source code URL

https://github.com/aristocratos/btop

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tstein**
- closes #8566
- closes #22111
- supersedes #27110

### CODE REVIEW

File: root-packages/btop/build.sh [hunk 1]
```diff
@@ -0,0 +1,31 @@
+TERMUX_PKG_HOMEPAGE=https://github.com/aristocratos/btop
+TERMUX_PKG_DESCRIPTION="Resource monitor that shows usage and stats for processor, memory, disks, network and processes."
+TERMUX_PKG_LICENSE="Apache-2.0"
+TERMUX_PKG_MAINTAINER="@tstein"
```
Comment (TomJo2000) [inline root-packages/btop/build.sh]: I think we've generally started using "Git style" identification for maintainer fields.
e.g. `"Pseudonym or @GH_Username <email@domain.ext>"`

Might be nice to change it to
```suggestion
TERMUX_PKG_MAINTAINER="@tstein <ted@termux.dev>"
```
###### I actually don't know what email you use for commits/point of contact.

Comment (tstein) [reply root-packages/btop/build.sh]: Added the one that's in the actual commit.

**Comment by tstein** [comment]
@TomJo2000 I removed the `/proc/stat` fakeout stuff - since we're shipping this as root only, there's actually no changes required for the upstream code to work here. :)

File: root-packages/btop/build.sh [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+TERMUX_PKG_BUILD_DEPENDS="aosp-libs, lowdown"
+TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
+	-DBTOP_LTO=OFF
+	-DBTOP_GPU=OFF
+	-DLOWDOWN_EXECUTABLE="${TERMUX_PKG_TMPDIR}/bin/lowdown"
+"
+TERMUX_PKG_AUTO_UPDATE=true
+
+termux_step_pre_configure() {
+	[[ "$TERMUX_ON_DEVICE_BUILD" == "false" ]] && termux_setup_proot
```
Comment (robertkirkman) [inline root-packages/btop/build.sh]: If this is going to have a reference to `$TERMUX_ON_DEVICE_BUILD` in it, that generally implies that it would support on-device building, and if you don't want it to support on-device building that would be fine but, if you do, then you can make this change, which fixes the on-device build. Without the change, this error occurs:

```
/data/data/com.termux/files/home/.termux-build/btop/tmp/bin/lowdown: 2: termux-proot-run: not found
```

```diff
--- a/root-packages/btop/build.sh
+++ b/root-packages/btop/build.sh
@@ -9,12 +9,15 @@ TERMUX_PKG_BUILD_DEPENDS="aosp-libs, lowdown"
 TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
 	-DBTOP_LTO=OFF
 	-DBTOP_GPU=OFF
-	-DLOWDOWN_EXECUTABLE="${TERMUX_PKG_TMPDIR}/bin/lowdown"
 "
 TERMUX_PKG_AUTO_UPDATE=true
 
 termux_step_pre_configure() {
-	[[ "$TERMUX_ON_DEVICE_BUILD" == "false" ]] && termux_setup_proot
+	if [[ "$TERMUX_ON_DEVICE_BUILD" == "true" ]]; then
+		return
+	fi
+
+	termux_setup_proot
 	mkdir "${TERMUX_PKG_TMPDIR}/bin"
 	printf '%s\ntermux-proot-run %s "$@"\n' \
 		"#!/bin/sh" \
@@ -23,4 +26,6 @@ termux_step_pre_configure() {
 	chmod +x "${TERMUX_PKG_TMPDIR}/bin/lowdown"
 
 	PATH="${TERMUX_PKG_TMPDIR}/bin:$PATH"
+
+	TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" -DLOWDOWN_EXECUTABLE=${TERMUX_PKG_TMPDIR}/bin/lowdown"
 }
```

Comment (tstein) [reply root-packages/btop/build.sh]: Applied, but I can't test the on-device build.

**Review by robertkirkman — APPROVED** [review]

File: root-packages/btop/exit-early-when-unprivileged.patch [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+--- a/src/btop.cpp
++++ b/src/btop.cpp
+@@ -844,6 +844,13 @@ static auto configure_tty_mode(std::optional<bool> force_tty) {
+ 		}
+ 	}
+ 
++	// Few of btop's inputs are visible to unprivileged processes on android,
++	// and it handles those failures by quitting.
++	if (Global::set_uid != 0) {
++		Global::exit_error_msg = "btop can't do anything useful on Termux without root. Quitting!";
```
Comment (Nikitf777) [inline root-packages/btop/exit-early-when-unprivileged.patch:12]: Btop should be able to monitor RAM and swap usage, and also the processes, laughed from Termux, without root (just like gotop, that already works without root). I saw people in the btop repo reporting exactly that (https://github.com/aristocratos/btop/issues/235#issuecomment-2811864680). Why did you hardcode it?

Comment (tstein) [reply root-packages/btop/exit-early-when-unprivileged.patch:12]: The comment and error message correctly describe the btop we are shipping. That person patched enough valid-for-linux-but-not-android assumptions to get a half-blank interface, which they don't sound like they're that happy with.

You're welcome to send a PR if you think btop can be made useful when run unprivileged on termux, though I don't think I'd merge it myself if it's going to have huge pieces of the TUI missing.

Comment (Nikitf777) [reply root-packages/btop/exit-early-when-unprivileged.patch:12]: But gotop is already in the repos and it works the same way without root. Why should we treat btop differently?

Comment (tstein) [reply root-packages/btop/exit-early-when-unprivileged.patch:12]: Because *btop* handles the unavailability of this information by throwing a fatal error. The patch here causes it to print a useful high-level reason instead of a low-level one; the thread you linked changes those behaviors to handle those failures and show blanks instead.

gotop is a different program that handles the failure to collect that info in the second way.
