### PR TITLE
upgpkg(main/vtm): 0.9.8o

### LINKED ISSUE #14700: Auto update failing for vtm
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the vtm package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating vtm [Current version: 0.9.8n]
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.9.8n is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.9.8o is an invalid version and will not be supported in a future release
  warnings.warn(
INFO: package being updated to 0.9.8o.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 13208    0 13208    0     0  41752      0 --:--:-- --:--:-- --:--:-- 41752
100 1326k    0 1326k    0     0  3089k      0 --:--:-- --:--:-- --:--:-- 11.4M

You are about to commit these changes:

--------------------
diff --git a/packages/vtm/build.sh b/packages/vtm/build.sh
index 546426851..7ed343e62 100644
--- a/packages/vtm/build.sh
+++ b/packages/vtm/build.sh
@@ -3,9 +3,9 @@ TERMUX_PKG_DESCRIPTION="Terminal multiplexer with TUI window manager and multi-p
 TERMUX_PKG_LICENSE="MIT"
 TERMUX_PKG_LICENSE_FILE="../LICENSE"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION="0.9.8n"
+TERMUX_PKG_VERSION="0.9.8o"
 TERMUX_PKG_SRCURL=https://github.com/netxs-group/vtm/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
-TERMUX_PKG_SHA256=dca521f2d72e2b5e147341036cb774139daa54a8205e03d92c17b42c091b7d9b
+TERMUX_PKG_SHA256=f1a3e769c2de82bb14d56c490d2a9d3f15512e3b346244a3dcd93fc3ea22881e
 TERMUX_PKG_DEPENDS="libandroid-spawn, libc++"
 TERMUX_PKG_BUILD_IN_SRC=true
 TERMUX_PKG_AUTO_UPDATE=true
--------------------

bump(main/vtm): 0.9.8o

Not committing to Git!

INFO: Trying to build package.
INFO: Package vtm exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building vtm for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0  31964      0 --:--:-- --:--:-- --:--:-- 32034
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1945      0 --:--:-- --:--:-- --:--:--  1941
gpg: Signature made Sun 22 Jan 2023 12:33:45 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/main/binary-aarch64/Packages
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 1507k    0  7681    0     0  12201      0  0:02:06 --:--:--  0:02:06 12192
100 1507k  100 1507k    0     0  1461k      0  0:00:01  0:00:01 --:--:-- 1461k
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  31595      0 --:--:-- --:--:-- --:--:-- 31638
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1990      0 --:--:-- --:--:-- --:--:--  1988
gpg: Signature made Sat 21 Jan 2023 06:20:59 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  29374      0 --:--:-- --:--:-- --:--:-- 29417
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1990      0 --:--:-- --:--:-- --:--:--  1988
gpg: Signature made Sat 21 Jan 2023 04:21:44 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading dependency libc++@25b if necessary...
Skipping already built dependency libc++@25b
Downloading dependency libandroid-spawn@0.3 if necessary...
Found libandroid-spawn in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libandroid-spawn/libandroid-spawn_0.3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 15216  100 15216    0     0   128k      0 --:--:-- --:--:-- --:--:--  129k
extracting libandroid-spawn to /home/builder/.termux-build/_cache-aarch64...
Downloading https://github.com/netxs-group/vtm/archive/refs/tags/v0.9.8o.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 1225k    0 1225k    0     0  4077k      0 --:--:-- --:--:-- --:--:-- 4077k
100 1326k    0 1326k    0     0  4235k      0 --:--:-- --:--:-- --:--:-- 8427k
Applying patch: netxs-console-ansi.hpp.patch
The text leading up to this was:
--------------------------
|https://github.com/termux/termux-packages/issues/13594
|
|--- a/src/netxs/console/ansi.hpp
|+++ b/src/netxs/console/ansi.hpp
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2023-01-22 00:38:12 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/3977230801">3977230801</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

### PR DESCRIPTION
**Pull request by 2096779623**
```bash
~/storage/downloads $ vtm
  os: terminal type "xterm-256color"
  os: color mode: true-color
  os: mouse mode: vt-style
 vtm: v0.9.8o
apps: loading configuration from $VTM_CONFIG...
apps: loading configuration from ~/.config/vtm/settings.xml...
      no configuration found, try another source
      fallback to hardcoded configuration
main: new desktopio environment for 10321
  os: process forked
~/storage/downloads $
```
Close #14700 .

### CODE REVIEW

File: packages/vtm/netxs-os-system.hpp.patch [hunk 1]
```diff
@@ -10,3 +10,10 @@ diff -uNr vtm-0.8.0/src/netxs/os/system.hpp vtm-0.8.0.mod/src/netxs/os/system.hp
                          auto size = socklen_t{ sizeof(cred) };
                      #else
                          auto size = unsigned{ sizeof(cred) };
+@@ -4052,4 +4052,4 @@
+             std::this_thread::sleep_for(200ms); // Pause to complete consuming/receiving buffered input (e.g. mouse tracking) that has just been canceled.
+         }
+     };
+-}
+\ No newline at end of file
++}
```
Comment (xtkoba) [inline packages/vtm/netxs-os-system.hpp.patch:19]: Please remove this part of patch. This only adds a newline at the end of the file, and can be a cause of rejection with a future update.
