### PR TITLE
tree-wide: port debpython to termux 

### LINKED ISSUE #21658: [Bug]: mesa & mesa-vulkan-icd-freedreno-dri3 build error
### Problem description

I've been trying to build `mesa` and `mesa-vulkan-icd-freedreno-dri3` in the `Termux environment`, but I keep encountering failures.

The build fails with the following error, and I wonder if there's something I'm missing.

I've installed most of the dependency packages and applied the patches included in the packages.

Could you please help?

### What steps will reproduce the bug?

`mesa` build error
```
./build-package.sh ./packages/mesa
``` 

```
llvm-config found: NO need ['>= 5.0.0']
Run-time dependency LLVM found: NO (tried config-tool)
Looking for a fallback subproject for the dependency llvm (modules: bitwriter, engine, mcdisassembler, mcjit, core, executionengine, scalaropts, transformutils, instcombine, native)
Building fallback subproject with default_library=shared

../src/meson.build:1766:13: ERROR: Neither a subproject directory nor a llvm.wrap file was found.

A full log can be found at /data/data/com.termux/files/home/.termux-build/mesa/build/meson-logs/meson-log.txt
``` 
`mesa-vulkan-icd-freedreno-dri3` build error
```
./build-package.sh ./packages/mesa-vulkan-icd-freedreno-dri3
``` 

```
Found ninja-1.12.1 at /data/data/com.termux/files/usr/bin/ninja
[70/557] Compiling C object src/util/libmesa_util.a.p/anon_file.c.o
FAILED: src/util/libmesa_util.a.p/anon_file.c.o
aarch64-linux-android-clang -Isrc/util/libmesa_util.a.p -Isrc/util -I../src/src/util -Iinclude -I../src/include -Isrc -I../src/src -Isrc/util/format -I../src/src/util/format -I/data/data/com.termux/files/usr/include -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c11 -Oz -g -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS '-DPACKAGE_VERSION="24.0.4"' '-DPACKAGE_BUGREPORT="https://gitlab.freedesktop.org/mesa/mesa/-/issues"' -DHAVE_OPENGL=0 -DHAVE_OPENGL_ES_1=1 -DHAVE_OPENGL_ES_2=1 -DUSE_VK_COMPILER=1 -DVIDEO_CODEC_VC1DEC=0 -DVIDEO_CODEC_H264DEC=0 -DVIDEO_CODEC_H264ENC=0 -DVIDEO_CODEC_H265DEC=0 -DVIDEO_CODEC_H265ENC=0 -DVIDEO_CODEC_AV1DEC=1 -DVIDEO_CODEC_AV1ENC=1 -DVIDEO_CODEC_VP9DEC=1 -DHAVE_X11_PLATFORM -DHAVE_WAYLAND_PLATFORM -DHAVE_XCB_PLATFORM -DENABLE_ST_OMX_BELLAGIO=0 -DENABLE_ST_OMX_TIZONIA=0 -DGLX_INDIRECT_RENDERING -DGLX_DIRECT_RENDERING -DGLX_USE_DRM -DGLAPI_EXPORT_PROTO_ENTRY_POINTS=0 -DALLOW_KCMP -DENABLE_SHADER_CACHE -DHAVE___BUILTIN_BSWAP32 -DHAVE___BUILTIN_BSWAP64 -DHAVE___BUILTIN_CLZ -DHAVE___BUILTIN_CLZLL -DHAVE___BUILTIN_CTZ -DHAVE___BUILTIN_EXPECT -DHAVE___BUILTIN_FFS -DHAVE___BUILTIN_FFSLL -DHAVE___BUILTIN_POPCOUNT -DHAVE___BUILTIN_POPCOUNTLL -DHAVE___BUILTIN_UNREACHABLE -DHAVE___BUILTIN_TYPES_COMPATIBLE_P -DHAVE_FUNC_ATTRIBUTE_CONST -DHAVE_FUNC_ATTRIBUTE_FLATTEN -DHAVE_FUNC_ATTRIBUTE_MALLOC -DHAVE_FUNC_ATTRIBUTE_PURE -DHAVE_FUNC_ATTRIBUTE_UNUSED -DHAVE_FUNC_ATTRIBUTE_WARN_UNUSED_RESULT -DHAVE_FUNC_ATTRIBUTE_WEAK -DHAVE_FUNC_ATTRIBUTE_FORMAT -DHAVE_FUNC_ATTRIBUTE_PACKED -DHAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL -DHAVE_FUNC_ATTRIBUTE_ALIAS -DHAVE_FUNC_ATTRIBUTE_NORETURN -DHAVE_FUNC_ATTRIBUTE_VISIBILITY -DHAVE_UINT128 -DHAVE_REALLOCARRAY -DHAVE_FMEMOPEN -D_GNU_SOURCE -DUSE_GCC_ATOMIC_BUILTINS -DUSE_AARCH64_ASM -DMAJOR_IN_SYSMACROS -DHAS_SCHED_H -DHAS_SCHED_GETAFFINITY -DHAVE_LINUX_FUTEX_H -DHAVE_ENDIAN_H -DHAVE_DLFCN_H -DHAVE_SYS_SHM_H -DHAVE_CET_H -DHAVE_SYS_INOTIFY_H -DHAVE_STRTOF -DHAVE_MKOSTEMP -DHAVE_MEMFD_CREATE -DHAVE_FLOCK -DHAVE_STRTOK_R -DHAVE_GETRANDOM -DHAVE_POSIX_FALLOCATE -DHAVE_STRUCT_TIMESPEC -DHAVE_POSIX_MEMALIGN -DHAVE_DIRENT_D_TYPE -DHAVE_STRTOD_L -DHAVE_DLADDR -DHAVE_DL_ITERATE_PHDR -DHAVE_ZLIB -DHAVE_ZSTD -DHAVE_COMPRESSION -DHAVE_PTHREAD -DHAVE_LIBDRM -DLLVM_AVAILABLE=0 -DDRAW_LLVM_AVAILABLE=0 -DWL_HIDE_DEPRECATED -DXCB_KEYSYMS_AVAILABLE -DHAVE_DRI2 -DHAVE_DRI3 -DHAVE_DRI3_MODIFIERS -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=return-type -Werror=empty-body -Werror=incompatible-pointer-types -Werror=int-conversion -Wimplicit-fallthrough -Wmisleading-indentation -Wno-missing-field-initializers -Wno-format-truncation -fno-math-errno -fno-trapping-math -Qunused-arguments -fno-common -Wno-unknown-pragmas -Wno-microsoft-enum-value -Wno-unused-function -Werror=format -Wformat-security -Werror=thread-safety -ffunction-sections -fdata-sections -fstack-protector-strong -Oz -D__USE_GNU -fPIC -pthread -Werror=pointer-arith -Werror=vla -Werror=gnu-empty-initializer -MD -MQ src/util/libmesa_util.a.p/anon_file.c.o -MF src/util/libmesa_util.a.p/anon_file.c.o.d -o src/util/libmesa_util.a.p/anon_file.c.o -c ../src/src/util/anon_file.c
../src/src/util/anon_file.c:122:9: error: call to undeclared function 'memfd_create'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  122 |    fd = memfd_create(debug_name, MFD_CLOEXEC | MFD_ALLOW_SEALING);
      |         ^
1 error generated.
[77/557] Compiling C object src/util/libmesa_util.a.p/meson-generated_.._format_u_format_table.c.o
ninja: build stopped: subcommand failed.
``` 

### What is the expected behavior?

_No response_

### System information

```shell
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=12681
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.sdu.edu.cn/termux/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.sdu.edu.cn/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.43.6
Android version:
14
Kernel build information:
Linux localhost 6.1.57-android14-11-29543898-abS928NKSU3AXH7 #1 SMP PREEMPT Mon Aug 19 04:02:36 UTC 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-S928N
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.widget versionCode:13
com.termux.x11 versionCode:14
com.termux.api versionCode:51
```

### LINKED ISSUE #25621: [Bug]: `python-llvmlite` conflict with `libllvm`
### Problem description

It is very great that there is now `python-llvmlite` available, but unfortunately, attempting to install it while the normal `libllvm` package is installed does not work.

```
The following NEW packages will be installed:
  python-llvmlite
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 19.8 MB of archives.
After this operation, 117 MB of additional disk space will be used.
Get:1 https://packages.termux.dev/apt/termux-main stable/main aarch64 python-llvmlite aarch64 0.44.0 [19.8 MB]
Fetched 19.8 MB in 5s (3901 kB/s)          
Selecting previously unselected package python-llvmlite.
(Reading database ... 363731 files and directories currently installed.)
Preparing to unpack .../python-llvmlite_0.44.0_aarch64.deb ...
Unpacking python-llvmlite (0.44.0) ...
dpkg: error processing archive /data/data/com.termux/cache/apt/archives/python-llvmlite_0.44.0_aarch64.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/include/llvm/ADT/APFixedPoint.h', which is also in package libllvm 20.1.8
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /data/data/com.termux/cache/apt/archives/python-llvmlite_0.44.0_aarch64.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
```

### What steps will reproduce the bug?

```bash
pkg upgrade
pkg install python-llvmlite
```

### What is the expected behavior?

`python-llvmlite` should either cause `apt` to remove `libllvm` automatically when it is installed, or be installed into a different folder so that it can be installed at the same time as `libllvm`.

### System information

```shell
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__APK_FILE=/data/app/~~gVwKanLEt3onhDQBKcUZQA==/com.termux-Jepd-I809CuxEnnuONZ6_Q==/base.apk
TERMUX_APP__APK_RELEASE=F_DROID
TERMUX_APP__APP_VERSION_CODE=1020
TERMUX_APP__APP_VERSION_NAME=0.119.0-beta.1
TERMUX_APP__DATA_DIR=/data/user/0/com.termux
TERMUX_APP__IS_DEBUGGABLE_BUILD=false
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PID=12106
TERMUX_APP__TARGET_SDK=28
TERMUX_VERSION=0.119.0-beta.1
TERMUX__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c237,c256,c512,c768
TERMUX__SE_INFO=default:targetSdkVersion=28:complete
TERMUX__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c237,c256,c512,c768
TERMUX__UID=10237
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# apt(sources.list) [legacy]
deb https://packages.termux.dev/apt/termux-main stable main
# glibc-repo(sources.list.d/glibc.list) [legacy]
# The glibc termux repository, with cloudflare cache
deb https://packages-cf.termux.dev/apt/termux-glibc/ glibc stable
# The glibc termux repository, without cloudflare cache
# deb https://packages.termux.dev/apt/termux-glibc/ glibc stable
# root-repo(sources.list.d/root.list) [legacy]
deb https://packages.termux.dev/apt/termux-root root stable
# sources.list.d/termux-adb.list [legacy]
deb https://nohajc.github.io termux extras
# x11-repo(sources.list.d/x11.list) [legacy]
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
audacity-ffmpeg/x11 3.7.5 aarch64 [upgradable from: 3.7.4-1]
audacity/x11 3.7.5 aarch64 [upgradable from: 3.7.4-1]
chezmoi/stable 2.64.0 aarch64 [upgradable from: 2.63.1]
cmake-curses-gui/stable 4.1.0 aarch64 [upgradable from: 4.0.3]
cmake/stable 4.1.0 aarch64 [upgradable from: 4.0.3]
dpkg-perl/stable 1.22.6-4 all [upgradable from: 1.22.6-3]
dpkg-scanpackages/stable 1.22.6-4 all [upgradable from: 1.22.6-3]
dpkg/stable 1.22.6-4 aarch64 [upgradable from: 1.22.6-3]
ed/stable 1.22.1 aarch64 [upgradable from: 1.22]
firefox/x11 141.0.2 aarch64 [upgradable from: 141.0]
flameshot/x11 13.0.1 aarch64 [upgradable from: 13.0.0]
frida-dev/root 17.2.14-1 aarch64 [upgradable from: 17.2.14]
frida-python/root 17.2.14-1 aarch64 [upgradable from: 17.2.14]
frida/root 17.2.14-1 aarch64 [upgradable from: 17.2.14]
krb5/stable 1.22 aarch64 [upgradable from: 1.21.3]
libapt-pkg-perl/stable 0.1.40-11 aarch64 [upgradable from: 0.1.40-10]
libheif-progs/stable 1.20.2 aarch64 [upgradable from: 1.20.1]
libheif/stable 1.20.2 aarch64 [upgradable from: 1.20.1]
libjasper-utils/stable 4.2.8 aarch64 [upgradable from: 4.2.7]
libjasper/stable 4.2.8 aarch64 [upgradable from: 4.2.7]
libraqm/stable 0.10.3 aarch64 [upgradable from: 0.10.2]
libregexp-assemble-perl/stable 0.38-7 all [upgradable from: 0.38-6]
luanti-common/x11 1:5.13.0-1 all [upgradable from: 1:5.13.0]
luanti-server/x11 1:5.13.0-1 aarch64 [upgradable from: 1:5.13.0]
lux-cli/stable 0.13.1 aarch64 [upgradable from: 0.13.0]
oh-my-posh/stable 26.18.0 aarch64 [upgradable from: 26.17.3]
ollama/stable 0.11.3 aarch64 [upgradable from: 0.10.1]
oxc-language-server/stable 1.10.0 aarch64 [upgradable from: 1.9.0]
oxlint/stable 1.10.0 aarch64 [upgradable from: 1.9.0]
perl/stable 5.40.3 aarch64 [upgradable from: 5.40.3]
python-cryptography/stable 45.0.6 aarch64 [upgradable from: 45.0.5]
strace/stable 6.16 aarch64 [upgradable from: 6.15]
subversion-perl-static/stable 1.14.5-1 aarch64 [upgradable from: 1.14.5]
subversion-perl/stable 1.14.5-1 aarch64 [upgradable from: 1.14.5]
subversion/stable 1.14.5-1 aarch64 [upgradable from: 1.14.5]
w3m-img/stable 0.5.4 aarch64 [upgradable from: 0.5.3.20230121-3]
w3m/stable 0.5.4 aarch64 [upgradable from: 0.5.3.20230121-3]
yosys/stable 0.56 aarch64 [upgradable from: 0.55-1]
termux-tools version:
1.46.0
Android version:
13
Kernel build information:
Linux localhost 4.14.190-lineage-gef0cb31b13 #4 SMP PREEMPT Fri Jun 23 13:11:47 CEST 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A705FN
Supported ABIs:
SUPPORTED_ABIS: arm64-v8a,armeabi-v7a,armeabi
SUPPORTED_32_BIT_ABIS: armeabi-v7a,armeabi
SUPPORTED_64_BIT_ABIS: arm64-v8a
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec-ld-preload.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.x11 versionCode:15
```

### LINKED ISSUE #25921: [Bug]: Conflicts: `asciidoc` and `tinysparql`
### Problem description

The below files exist on both packages: 

lib/python3.12/site-packages/asciidoc/__pycache__/a2x.cpython-312.pyc
lib/python3.12/site-packages/asciidoc/__pycache__/asciidoc.cpython-312.pyc

### What steps will reproduce the bug?

Installation

### What is the expected behavior?

_No response_

### System information

```shell
NA
```

### LINKED ISSUE #26687: Auto update failing for python-onnxruntime
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [python-onnxruntime](https://github.com/termux/termux-packages/blob/2fb2496635e1739604dd02d2e324d1e27525d023/packages/python-onnxruntime) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="console">
INFO: Updating python-onnxruntime [Current version: 1.22.2]
INFO: package being updated to 1.23.0.
INFO: Trying to build package.
INFO: Package python-onnxruntime exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building python-onnxruntime for arch aarch64...
::group::INFO: Fetching repo metadata
[packages-cf.termux.dev-apt-termux-main]: Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
[packages-cf.termux.dev-apt-termux-main]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-main]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-main]: 
[packages-cf.termux.dev-apt-termux-main]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-main]: 100 13134  100 13134    0     0   169k      0 --:--:-- --:--:-- --:--:--  171k
[packages-cf.termux.dev-apt-termux-main]: Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
[packages-cf.termux.dev-apt-termux-main]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-main]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-main]: 
[packages-cf.termux.dev-apt-termux-main]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-main]: 100   833  100   833    0     0  14619      0 --:--:-- --:--:-- --:--:-- 14875
[packages-cf.termux.dev-apt-termux-main]: gpg: Signature made Fri 26 Sep 2025 06:25:04 AM UTC
[packages-cf.termux.dev-apt-termux-main]: gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
[packages-cf.termux.dev-apt-termux-main]: gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
[packages-cf.termux.dev-apt-termux-main]: gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
[packages-cf.termux.dev-apt-termux-root]: Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
[packages-cf.termux.dev-apt-termux-root]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-root]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-root]: 
[packages-cf.termux.dev-apt-termux-root]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-root]: 100 13320  100 13320    0     0   264k      0 --:--:-- --:--:-- --:--:--  265k
[packages-cf.termux.dev-apt-termux-root]: Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
[packages-cf.termux.dev-apt-termux-root]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-root]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-root]: 
[packages-cf.termux.dev-apt-termux-root]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-root]: 100   833  100   833    0     0  18012      0 --:--:-- --:--:-- --:--:-- 18108
[packages-cf.termux.dev-apt-termux-root]: gpg: Signature made Wed 24 Sep 2025 07:14:32 PM UTC
[packages-cf.termux.dev-apt-termux-root]: gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
[packages-cf.termux.dev-apt-termux-root]: gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
[packages-cf.termux.dev-apt-termux-root]: gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
[packages-cf.termux.dev-apt-termux-x11]: Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
[packages-cf.termux.dev-apt-termux-x11]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-x11]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-x11]: 
[packages-cf.termux.dev-apt-termux-x11]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-x11]: 100 13120  100 13120    0     0   221k      0 --:--:-- --:--:-- --:--:--  224k
[packages-cf.termux.dev-apt-termux-x11]: Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
[packages-cf.termux.dev-apt-termux-x11]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-x11]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-x11]: 
[packages-cf.termux.dev-apt-termux-x11]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-x11]: 100   833  100   833    0     0  11557      0 --:--:-- --:--:-- --:--:-- 11569
[packages-cf.termux.dev-apt-termux-x11]: gpg: Signature made Thu 25 Sep 2025 11:41:02 AM UTC
[packages-cf.termux.dev-apt-termux-x11]: gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
[packages-cf.termux.dev-apt-termux-x11]: gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
[packages-cf.termux.dev-apt-termux-x11]: gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
::endgroup::
Downloading dependency libc++@28c if necessary...
Found libc++ in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libc++ to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency abseil-cpp@20250814.0 if necessary...
Found abseil-cpp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/a/abseil-cpp/abseil-cpp_20250814.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 1091k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1091k  100 1091k    0     0  16.9M      0 --:--:-- --:--:-- --:--:-- 16.9M
extracting abseil-cpp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libre2@2025-08-12-1 if necessary...
Found libre2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libr/libre2/libre2_2025-08-12-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 26  160k   26 43363    0     0  49862      0  0:00:03 --:--:--  0:00:03 49842
100  160k  100  160k    0     0   155k      0  0:00:01  0:00:01 --:--:--  155k
extracting libre2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency zlib@1.3.1-1 if necessary...
Found zlib in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting zlib to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libprotobuf@2:32.0 if necessary...
Found libprotobuf in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libp/libprotobuf/libprotobuf_2:32.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1290k  100 1290k    0     0  24.2M      0 --:--:-- --:--:-- --:--:-- 24.7M
extracting libprotobuf to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency protobuf-dev@2:32.0 if necessary...
Found protobuf-dev in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/protobuf-dev/protobuf-dev_2:32.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3176  100  3176    0     0   5877      0 --:--:-- --:--:-- --:--:--  5870
100  3176  100  3176    0     0   5876      0 --:--:-- --:--:-- --:--:--  5870
extracting protobuf-dev to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency protobuf@2:32.0 if necessary...
Found protobuf in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/protobuf/protobuf_2:32.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  8 1149k    8 94248    0     0  95602      0  0:00:12 --:--:--  0:00:12 95586
100 1149k  100 1149k    0     0   787k      0  0:00:01  0:00:01 --:--:--  787k
extracting protobuf to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libandroid-support@29-1 if necessary...
Found libandroid-support in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libandroid-support to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses@6.5.20240831-3 if necessary...
Found ncurses in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-utils@6.5.20240831-3 if necessary...
Found ncurses-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-ui-libs@6.5.20240831-3 if necessary...
Found ncurses-ui-libs in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-ui-libs to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-ui-libs-static@6.5.20240831-3 if necessary...
Found ncurses-ui-libs-static in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-ui-libs-static to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency readline@8.3.1-1 if necessary...
Found readline in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting readline to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency gdbm@1.26-1 if necessary...
Found gdbm in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting gdbm to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libandroid-posix-semaphore@0.1-4 if necessary...
Found libandroid-posix-semaphore in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libandroid-posix-semaphore to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libbz2@1.0.8-8 if necessary...
Found libbz2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libbz2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency bzip2@1.0.8-8 if necessary...
Found bzip2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting bzip2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ca-certificates@1:2025.09.09 if necessary...
Found ca-certificates in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ca-certificates to /home/builder/.termux-build/_cache-all...
Downloading dependency ca-certificates-java@1:2025.09.09 if necessary...
Found ca-certificates-java in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ca-certificates-java to /home/builder/.termux-build/_cache-all...
Downloading dependency openssl@1:3.5.2 if necessary...
Found openssl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting openssl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency openssl-tool@1:3.5.2 if necessary...
Found openssl-tool in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting openssl-tool to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libcrypt@0.2-6 if necessary...
Found libcrypt in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libcrypt to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libexpat@2.7.3 if necessary...
Found libexpat in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libexpat to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libffi@3.4.7-1 if necessary...
Found libffi in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libffi to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency liblzma@5.8.1-1 if necessary...
Found liblzma in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting liblzma to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xz-utils@5.8.1-1 if necessary...
Found xz-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting xz-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency tcl@8.6.14-1 if necessary...
Found tcl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting tcl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libsqlite@3.50.4-1 if necessary...
Found libsqlite in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libsqlite to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency sqlite@3.50.4-1 if necessary...
Found sqlite in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting sqlite to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libsqlite-tcl@3.50.4-1 if necessary...
Found libsqlite-tcl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libsqlite-tcl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency brotli@1.1.0-3 if necessary...
Found brotli in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting brotli to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libpng@1.6.50-1 if necessary...
Found libpng in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libpng to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency freetype@2.14.1 if necessary...
Found freetype in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting freetype to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ttf-dejavu@2.37-8 if necessary...
Found ttf-dejavu in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ttf-dejavu to /home/builder/.termux-build/_cache-all...
Downloading dependency fontconfig@2.17.1-1 if necessary...
Found fontconfig in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting fontconfig to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency fontconfig-utils@2.17.1-1 if necessary...
Found fontconfig-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting fontconfig-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xorg-util-macros@1.20.2 if necessary...
Found xorg-util-macros in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting xorg-util-macros to /home/builder/.termux-build/_cache-all...
Downloading dependency xorgproto@2024.1 if necessary...
Found xorgproto in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting xorgproto to /home/builder/.termux-build/_cache-all...
Downloading dependency libxau@1.0.12-2 if necessary...
Found libxau in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libxau to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxdmcp@1.1.5-2 if necessary...
Found libxdmcp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libxdmcp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xcb-proto@1.17.0-1 if necessary...
Found xcb-proto in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting xcb-proto to /home/builder/.termux-build/_cache-all...
Downloading dependency python-xcbgen@1.17.0-1 if necessary...
Found python-xcbgen in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting python-xcbgen to /home/builder/.termux-build/_cache-all...
Downloading dependency libxcb@1.17.0-1 if necessary...
Found libxcb in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libxcb to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xtrans@1.6.0 if necessary...
Found xtrans in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting xtrans to /home/builder/.termux-build/_cache-all...
Downloading dependency libx11@1.8.12-1 if necessary...
Found libx11 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libx11 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxrender@0.9.12-1 if necessary...
Found libxrender in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libxrender to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxft@2.3.9-1 if necessary...
Found libxft in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libxft to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxext@1.3.6-1 if necessary...
Found libxext in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libxext to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxss@1.2.5 if necessary...
Found libxss in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libxss to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency tk@8.6.14-1 if necessary...
Found tk in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting tk to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency python@3.12.11-1 if necessary...
Found python in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting python to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency python-tkinter@3.12.11-1 if necessary...
Found python-tkinter in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting python-tkinter to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency python-ensurepip-wheels@3.12.11-1 if necessary...
Found python-ensurepip-wheels in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting python-ensurepip-wheels to /home/builder/.termux-build/_cache-all...
Downloading dependency libopenblas@0.3.30-1 if necessary...
Found libopenblas in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libo/libopenblas/libopenblas_0.3.30-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2456k  100 2456k    0     0  37.6M      0 --:--:-- --:--:-- --:--:-- 38.0M
extracting libopenblas to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency blas-openblas@0.3.30-1 if necessary...
Found blas-openblas in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/blas-openblas/blas-openblas_0.3.30-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   984  100   984    0     0   1879      0 --:--:-- --:--:-- --:--:--  1877
100   984  100   984    0     0   1879      0 --:--:-- --:--:-- --:--:--  1877
extracting blas-openblas to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency python-numpy@2.2.5-1 if necessary...
Found python-numpy in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/python-numpy/python-numpy_2.2.5-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 5382k  100 5382k    0     0  72.6M      0 --:--:-- --:--:-- --:--:-- 73.0M
extracting python-numpy to /home/builder/.termux-build/_cache-aarch64...
Downloading python-onnxruntime@1.23.0 git source from 'git+https://github.com/microsoft/onnxruntime' if necessary...
Downloading git source with branch 'v1.23.0' from 'https://github.com/microsoft/onnxruntime'
Cloning into '/home/builder/.termux-build/python-onnxruntime/cache/tmp-checkout'...
Note: switching to 'be835efc56aca19b8e810538ec93c8e150e0fc61'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Updating files:  44% (4171/9420)
Updating files:  45% (4239/9420)
Updating files:  46% (4334/9420)
Updating files:  47% (4428/9420)
Updating files:  48% (4522/9420)
Updating files:  49% (4616/9420)
Updating files:  50% (4710/9420)
Updating files:  51% (4805/9420)
Updating files:  52% (4899/9420)
Updating files:  53% (4993/9420)
Updating files:  54% (5087/9420)
Updating files:  55% (5181/9420)
Updating files:  56% (5276/9420)
Updating files:  57% (5370/9420)
Updating files:  58% (5464/9420)
Updating files:  59% (5558/9420)
Updating files:  60% (5652/9420)
Updating files:  61% (5747/9420)
Updating files:  62% (5841/9420)
Updating files:  63% (5935/9420)
Updating files:  64% (6029/9420)
Updating files:  65% (6123/9420)
Updating files:  66% (6218/9420)
Updating files:  67% (6312/9420)
Updating files:  68% (6406/9420)
Updating files:  69% (6500/9420)
Updating files:  70% (6594/9420)
Updating files:  71% (6689/9420)
Updating files:  72% (6783/9420)
Updating files:  73% (6877/9420)
Updating files:  74% (6971/9420)
Updating files:  75% (7065/9420)
Updating files:  76% (7160/9420)
Updating files:  77% (7254/9420)
Updating files:  78% (7348/9420)
Updating files:  79% (7442/9420)
Updating files:  80% (7536/9420)
Updating files:  81% (7631/9420)
Updating files:  82% (7725/9420)
Updating files:  83% (7819/9420)
Updating files:  84% (7913/9420)
Updating files:  85% (8007/9420)
Updating files:  86% (8102/9420)
Updating files:  87% (8196/9420)
Updating files:  88% (8290/9420)
Updating files:  89% (8384/9420)
Updating files:  90% (8478/9420)
Updating files:  91% (8573/9420)
Updating files:  92% (8667/9420)
Updating files:  93% (8761/9420)
Updating files:  94% (8855/9420)
Updating files:  95% (8949/9420)
Updating files:  96% (9044/9420)
Updating files:  97% (9138/9420)
Updating files:  98% (9232/9420)
Updating files:  99% (9326/9420)
Updating files: 100% (9420/9420)
Updating files: 100% (9420/9420), done.
~/.termux-build/python-onnxruntime/cache/tmp-checkout ~/.termux-build/python-onnxruntime/cache
Submodule 'cmake/external/emsdk' (https://github.com/emscripten-core/emsdk.git) registered for path 'cmake/external/emsdk'
Submodule 'cmake/external/libprotobuf-mutator' (https://github.com/google/libprotobuf-mutator.git) registered for path 'cmake/external/libprotobuf-mutator'
Submodule 'cmake/external/onnx' (https://github.com/onnx/onnx.git) registered for path 'cmake/external/onnx'
Cloning into '/home/builder/.termux-build/python-onnxruntime/cache/tmp-checkout/cmake/external/emsdk'...
Cloning into '/home/builder/.termux-build/python-onnxruntime/cache/tmp-checkout/cmake/external/libprotobuf-mutator'...
Cloning into '/home/builder/.termux-build/python-onnxruntime/cache/tmp-checkout/cmake/external/onnx'...
From https://github.com/emscripten-core/emsdk
 * branch            419021fa040428bc69ef1559b325addb8e10211f -> FETCH_HEAD
Submodule path 'cmake/external/emsdk': checked out '419021fa040428bc69ef1559b325addb8e10211f'
From https://github.com/google/libprotobuf-mutator
 * branch            7a2ed51a6b682a83e345ff49fc4cfd7ca47550db -> FETCH_HEAD
Submodule path 'cmake/external/libprotobuf-mutator': checked out '7a2ed51a6b682a83e345ff49fc4cfd7ca47550db'
From https://github.com/onnx/onnx
 * branch            e709452ef2bbc1d113faf678c24e6d3467696e83 -> FETCH_HEAD
Submodule path 'cmake/external/onnx': checked out 'e709452ef2bbc1d113faf678c24e6d3467696e83'
Submodule 'third_party/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'cmake/external/onnx/third_party/pybind11'
Cloning into '/home/builder/.termux-build/python-onnxruntime/cache/tmp-checkout/cmake/external/onnx/third_party/pybind11'...
From https://github.com/pybind/pybind11
 * branch            a2e59f0e7065404b44dfe92a28aca47ba1378dc4 -> FETCH_HEAD
Submodule path 'cmake/external/onnx/third_party/pybind11': checked out 'a2e59f0e7065404b44dfe92a28aca47ba1378dc4'
~/.termux-build/python-onnxruntime/cache
Requirement already satisfied: setuptools==78.1.0 in /home/builder/.termux-build/python3.12-crossenv-prefix-bionic-aarch64/build/lib/python3.12/site-packages (78.1.0)
Requirement already satisfied: wheel==0.46.1 in /home/builder/.termux-build/python3.12-crossenv-prefix-bionic-aarch64/build/lib/python3.12/site-packages (0.46.1)
Requirement already satisfied: packaging>=24.0 in /home/builder/.termux-build/python3.12-crossenv-prefix-bionic-aarch64/build/lib/python3.12/site-packages (from wheel==0.46.1) (25.0)
Requirement already satisfied: setuptools==78.1.0 in /home/builder/.termux-build/python3.12-crossenv-prefix-bionic-aarch64/build/lib/python3.12/site-packages (78.1.0)
Requirement already satisfied: wheel==0.46.1 in /home/builder/.termux-build/python3.12-crossenv-prefix-bionic-aarch64/build/lib/python3.12/site-packages (0.46.1)
Requirement already satisfied: packaging>=24.0 in /home/builder/.termux-build/python3.12-crossenv-prefix-bionic-aarch64/build/lib/python3.12/site-packages (from wheel==0.46.1) (25.0)
Installing the dependency python module wheel if necessary...
Skipping the already installed dependency python module wheel
Installing the dependency python module build if necessary...
Collecting build
  Downloading build-1.3.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: packaging>=19.1 in /home/builder/.termux-build/python3.12-crossenv-prefix-bionic-aarch64/build/lib/python3.12/site-packages (from build) (25.0)
Collecting pyproject_hooks (from build)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Downloading build-1.3.0-py3-none-any.whl (23 kB)
Downloading pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Installing collected packages: pyproject_hooks, build
Successfully installed build-1.3.0 pyproject_hooks-1.2.0
Installing the dependency python module packaging if necessary...
Skipping the already installed dependency python module packaging
Applying patch: 0001-use-system-abseil.patch
1 out of 2 hunks FAILED -- saving rejects to file cmake/external/abseil-cpp.cmake.rej
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2025-09-26 06:27:54 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/18029284137">18029284137</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

### PR DESCRIPTION
**Pull request by robertkirkman**
- Fixes https://github.com/termux/termux-packages/issues/25921

- Fixes https://github.com/termux/termux-packages/issues/21658

- Fixes https://github.com/termux/termux-packages/issues/26687

- Fixes https://github.com/termux/termux-packages/issues/25621

#### What is debpython?

- debpython is the commands `py3compile` and `py3clean` from Debian. I
  am calling them that because a large chunk of their source code is
  found inside a folder inside Debian's source code named "debpython"
  - https://salsa.debian.org/cpython-team/python3-defaults/-/tree/5348f704668c0b6c360b6c6fb10153b9c2898af5

- rather than packaging `.pyc` files into packages, `py3compile` and
  `py3clean` can be called from `postinst` and `prerm` scripts to
  generate all `.pyc` for the `.py` files in the package immediately
  after the package is installed, and remove all `.pyc` files immediately
  before uninstalling the package, respectively

- fixes the error `trying to overwrite '/data/data/com.termux/files/usr/lib/python3.12/__pycache__/cProfile.cpython-312.pyc'` when packages were built on-device, but at the same time, also:

- prevents the warnings `dpkg: warning: while removing python, directory '/data/data/com.termux/files/usr/lib/python3.12/site-packages' not empty so not removed` as long as no packages were installed using `pip`

- The `termux_step_create_python_debscripts.sh` can configure work on debpython (i.e. its `py3copile` and `py3clean` commands) from the glibc package `python-glibc`, if some glibc package is being compiled.

- New variables have been implemented:
  - `TERMUX_PYTHON_CROSSENV_BUILDHOME` - location of crossenv's python build libraries.
  - `TERMUX_PKG_PYTHON_RUNTIME_DEPS` - configures the installation of the python modules via pip3 in the pkg's debscripts. If not configured in the package, it will use the value from `TERMUX_PKG_PYTHON_TARGET_DEPS`. If the variable is set to `false`, then the customization of installing python modules will be disabled, even if the `TERMUX_PKG_PYTHON_TARGET_DEPS` variable is set in the package.
  - `TERMUX_SUBPKG_PYTHON_RUNTIME_DEPS` - configures the installation of the python modules via pip3 in the subpkg's debscripts.

- Implemented reconfiguration of prefixes in python module `sysconfig` and setting in `TERMUX_PYTHON_CROSSENV_BUILDHOME`, so that python modules from crossenv building can specify system paths of termux for correct compilation.

- Added automatic addition of `python-glibc{-glibc}` dependency when using the `TERMUX_PKG_PYTHON_RUNTIME_DEPS` (for pkg; will be disabled, i.e. will not be added, if the variable is set to `false`) or `TERMUX_SUBPKG_PYTHON_RUNTIME_DEPS` (for subpkg) value.

#### How to add a new Python package after this?

Everything is the same, except, now, this block is no longer necessary in `build.sh`.

```bash
termux_step_create_debscripts() {
	cat <<- EOF > ./postinst
	#!$TERMUX_PREFIX/bin/sh
	echo "Installing dependencies through pip..."
	pip3 install ${TERMUX_PKG_PYTHON_TARGET_DEPS//, / }
	EOF
}
```

- Instead, `scripts/build/termux_step_create_python_debscripts.sh` can now detect the presence of `pip` package lists in `$TERMUX_PKG_PYTHON_TARGET_DEPS`, `$TERMUX_SUBPKG_PYTHON_TARGET_DEPS`, and the `METADATA` file of the Python package if it exists, and automatically insert them as a block into the `postinst` script for all relevant packages.
- `$TERMUX_PKG_PYTHON_TARGET_DEPS` is used for `pip` dependencies that are both on-device build-time and on-device run-time dependencies, and `$TERMUX_PKG_PYTHON_RUNTIME_DEPS` is used for runtime-only `pip` dependencies. `$TERMUX_PKG_PYTHON_RUNTIME_DEPS` overrides `$TERMUX_PKG_PYTHON_TARGET_DEPS` for runtime dependencies,
  - i.e. if `TERMUX_PKG_PYTHON_RUNTIME_DEPS` is not specified, but `TERMUX_PKG_PYTHON_TARGET_DEPS` is, then `TERMUX_PKG_PYTHON_TARGET_DEPS` will be used as both on-device build and on-device runtime dependencies,
  - but if `TERMUX_PKG_PYTHON_RUNTIME_DEPS` is specified, then `TERMUX_PKG_PYTHON_TARGET_DEPS`, if specified, is used only for on-device build-time dependencies.
- If `python-pip` is not already in the dependencies of any package that needs it, the build will fail with an error instructing maintainers to add `python-pip` to the dependencies of the package that needs it.

### CODE REVIEW

**Comment by licy183** [comment]
This folder should only be excluded only when performing on-device build. In some packages, like python, this content in this folder is managed by apt. It is quite annoying to see some warnings like `xxx directory is not empty`.

**Comment by robertkirkman** [comment]
> This folder should only be excluded only when performing on-device build. In some packages, like python, this content in this folder is managed by apt

Should the content in these folders remain managed by apt in any case?

In Debian, I believe this folders are **not** managed by `apt`.

https://packages.debian.org/sid/amd64/libpython3.12-minimal/filelist

In Arch Linux, I believe these folders **are** managed by `pacman`.

https://archlinux.org/packages/core/x86_64/python/ (file list)

Fedora also ships them

https://packages.fedoraproject.org/pkgs/python3.12/python3-libs/fedora-40.html

it seems to me like it is optional whether to include them in the package, because I think Python can automatically generate them, but this problem is very difficult because, I think Arch Linux and Fedora might ship them for performance.

At least this does not break Python, I think, because 

> It is quite annoying to see some warnings like `xxx directory is not empty`.

I do not think there is any way to get rid of this warning, because on Termux `python-pip` generates and stores the `__pycache__` folders into the `site-packages` folder in the same `$PREFIX/lib/python3.12/` folder where the `$PREFIX/lib/zoneinfo/_zoneinfo.py` files are, etc.

Example: warning always reproducible with current packages
```bash
pkg install python-pip
pip install setuptools
pkg remove python
```

```
Removing python-pip (25.0.1) ...
Removing python-ensurepip-wheels (3.12.9) ...
Removing python (3.12.9) ...
dpkg: warning: while removing python, directory '/data/data/com.termux/files/usr/lib/python3.12/site-packages' not empty so not removed
Processing triggers for man (1.14.6-1) ...
```

That happens without this change.

Can you think of any way to:

- prevent the `__pycache__` folders from being included in the package during on-device `build-package.sh`, to fix `trying to overwrite '/data/data/com.termux/files/usr/lib/python3.12/__pycache__/cProfile.cpython-312.pyc', which is also in package python 3.12.9`
- but still make sure `__pycache__` folders are included in the package _only_ when they actually belong to the package currently being built, so they can be shipped for performance boost?

For the record: I **do** notice the performance loss at startup of `python` package built from this change - very slightly.

**Comment by licy183** [comment]
In Debain, they have a postinst script to compile the modules when new packages are installed, and a prerm script to clean up `__pycache__` dir and *.pyc files. I have done the same cleanup logic in pypy3 on Termux.

See `/usr/share/python3/runtime.d/public_modules.rt{install,remove}` in Debain.

**Comment by robertkirkman** [comment]
> In Debain, they have a postinst script to compile the modules when new packages are installed, and a prerm script to clean up `__pycache__` dir and *.pyc files. I have done the same cleanup logic in pypy3 on Termux.
> 
> See `/usr/share/python3/runtime.d/public_modules.rt{install,remove}` in Debain.

ok I did it, is this what you meant?

**Comment by robertkirkman** [comment]
@Maxython 
Ok, to continue the discussion here,

now I have:

- unified almost all python debscript creation into a single function, removing the duplicated code involving `$TERMUX_PKG_PYTHON_TARGET_DEPS` from many packages and also making it not necessary to explicitly call `termux_step_create_python_debscripts()` from any `build.sh` anymore
- tried to make this debpython compatible with `pacman` by making it try to use the `pacman -Qql` command if the `dpkg` command is not found

however, I am not sure whether the `pacman -Qql` command is completely compatible to the point that it will work in all cases without problems. `pacman -Qql` does print equivalent data in very similar formatting to `dpkg -L`, but it is **not _100% identical formatting_** to `dpkg -L`, so I am not sure whether it will work perfectly without a lot of testing.

**Review by TomJo2000 — APPROVED** [review]
Thanks for putting in the effort.
Looks like I accidentally created a merge conflict for you with one of my earlier PRs, sorry about that.

**Comment by robertkirkman** [comment]
That's ok,
something I have noticed is that, licy183 told me somewhere else that `TERMUX_PKG_REVISION` should not be incremented for PRs that are excluded from CI. The reason I excluded the PR from CI is because I previously learned [here](https://github.com/termux/termux-packages/pull/21835#issuecomment-2447031658) that if too many packages are built in a single PR, sometimes the behavior will diverge from the behavior of the same large build command run in the docker builder locally (even when packages are not polluting the builds of other packages)

However, the reason why many packages are marked with revision-bumps in this is because, that is marking all packages that a test I did indicates will have **changed `control.tar.xz` contents** if they are rebuilt after this PR is merged.

Because of that, I think probably what I need to do is split this into several PRs one after another that do not have CI disabled.

**Comment by Maxython** [comment]
**Update:** The provided list of packages that need to be rebuilt is incomplete, i.e. it does not include all the packages that need to be rebuilt with debpython.

**Comment by TomJo2000** [comment]
> The following packages need to be recompiled using debpython:

I would suggest either opening a staging PR for this purpose, or adding the commits for rebuilding those packages to this PR.

**Comment by Maxython** [comment]
> I would suggest either opening a staging PR for this purpose, or adding the commits for rebuilding those packages to this PR.

It is planned to rebuild these packages in each PRs. If rebuild all the packages in one PR (for example on this one), there are risks that can break the compilation.

**Comment by TomJo2000** [comment]
> It is planned to rebuild these packages in each PRs. If rebuild all the packages in one PR (for example on this one), there are risks that can break the compilation.

I'm not sure I understand that concern.

**Comment by Maxython** [comment]
> I'm not sure I understand that concern.

Well, there are quite a lot of packages that need to be rebuilt. And one of the risks I see is that the packages may not have time to be built, i.e. their compilation may take more than six hours.

**Comment by TomJo2000** [comment]
Those 18 packages should get nowhere near 6 hours.
The largest one there is `pyqt5` which took ~20 minutes the last time it was built.

File: packages/nala/build.sh [hunk 1]
```diff
@@ -42,7 +43,5 @@ termux_step_create_debscripts() {
 	mkdir -p $TERMUX_PREFIX/var/lib/nala
 	mkdir -p $TERMUX_PREFIX/var/log/nala
 	mkdir -p $TERMUX_PREFIX/var/lock
-	echo "Installing dependencies through pip..."
-	pip3 install nala python-debian
```
Comment (licy183) [inline packages/nala/build.sh:46]: This is necessary for `nala` to work properly. `nala` should depend on `python-debian` but it is not mentioned in the dependency list, and `nala` should also depend on specified version of `httpx`.

I think it is better to use `pip3 install package_name` to let pip handle the version of dependencies automatically rather than use `TERMUX_PKG_PYTHON_TARGET_DEPS`.

Comment (robertkirkman) [reply packages/nala/build.sh:46]: Correct, I do understand that for packages that use `pip3` to install **a `pip` equivalent of the same package as the current package**, moving their `pip3` argument for their same-package `pip` equivalent package to `TERMUX_PKG_PYTHON_TARGET_DEPS` would not work properly during on-device builds,

so I have intentionally not edited packages that do that, like `matplotlib` for example, in this PR, since they should not be changed.

The way this is currently for `nala` in this PR is incorrect and needs to be adjusted. I believe this must be a typo, and it was meant to be a different change, `pip3 install nala python-debian` -> `pip3 install nala`.

Thank you for pointing this out. The commit history of this PR has shifted and that change is now labeled under Maxython's commit, but I believe the original responsibility for this typo is with me, and it was just copied and pasted around several times without being noticed.

> I think it is better to use `pip3 install package_name` to let pip handle the version of dependencies automatically rather than use `TERMUX_PKG_PYTHON_TARGET_DEPS`.

The issue with doing it that way for _all_ packages is that a few packages are not on PyPi, but have runtime dependencies that _are_ on PyPi, so `pip3 install package_name` would not work in those situations. Therefore, there has to be a mixture of both kinds of python debscripts.

Comment (robertkirkman) [reply packages/nala/build.sh:46]: I have added a fix for this typo into the current version of this PR

Comment (robertkirkman) [reply packages/nala/build.sh:46]: I can see that this would undo your commit,

https://github.com/termux/termux-packages/commit/1c39b4632b62aa044912579c1bc04949c36480bb

This is an unfortunate situation.

Could you explain a little more how to reproduce the specific problem that https://github.com/termux/termux-packages/commit/1c39b4632b62aa044912579c1bc04949c36480bb has resolved, so that this PR can be tested for the same problem?

File: scripts/build/termux_step_create_python_debscripts.sh [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+	# pre-rm script to cleanup runtime-generated files.
+	cat <<- PRERM_EOF >> prerm
+	if [ -f "${TERMUX_PREFIX}/bin/py3clean" ]; then
+		LD_PRELOAD='' "${TERMUX_PREFIX}/bin/py3clean" -p "$_package_name"
+	fi
+	PRERM_EOF
+
+	# running py3compile in a package for pacman during a package update
+	if [ "$TERMUX_PACKAGE_FORMAT" = "pacman" ] && ! grep -qs 'post_install' postupg; then
+		echo "post_install" >> postupg
```
Comment (robertkirkman) [inline scripts/build/termux_step_create_python_debscripts.sh]: > [!NOTE]
> This part is loosely related to this
> - https://github.com/termux/termux-packages/pull/25222
>
> however, they probably do not conflict at all with each other even slightly, because the other check checks for a preexisting `postupg` that could be from this check, and does nothing in that case except use the contents `post_install` from this `postupg`.

File: packages/nala/build.sh (hunk 1 above)
Comment (Maxython) [reply packages/nala/build.sh:46]: > I think it is better to use pip3 install package_name to let pip handle the version of dependencies automatically rather than use TERMUX_PKG_PYTHON_TARGET_DEPS.

Could you explain in more detail why it is better to leave the `nala` module installation setting in `termux_step_create_debscripts`, since when configuring the `nala` module in the `TERMUX_PKG_PYTHON_TARGET_DEPS` variable, its installation in debscripts will be automatically added?

File: packages/python/debpython.patch [hunk 3]
```diff
@@ -37,34 +33,6 @@ index 39ef978..5899a7a 100644
                           stderr=PIPE, env=env)
      stdout, stderr = process.communicate()
      if process.returncode != 0:
-diff --git a/debpython/debpython/interpreter.py b/debpython/debpython/interpreter.py
-index 45b14db..6334661 100644
---- a/debpython/debpython/interpreter.py
-+++ b/debpython/debpython/interpreter.py
-@@ -171,16 +171,16 @@ class Interpreter:
```
Comment (Maxython) [inline packages/python/debpython.patch]: Why do you think these changes are not necessary? These changes are made so that the `sitedir` function can return the actual path to python's `site-packages` in Termux. And although this function is not used anywhere in the debpython system, it can be used by users or projects.

Comment (robertkirkman) [reply packages/python/debpython.patch]: Could you provide an example of how to activate and test this code?

I was interested in finding a way to activate it as well, but I couldn't find one.

File: packages/nala/build.sh (hunk 1 above)
Comment (robertkirkman) [reply packages/nala/build.sh:46]: In the case of `nala` specifically, it could be done and still work, yes. I have just tested that now. 

However, I just didn't remove the manual debscript from the packages which did that (install a package from PyPi with a similar name to the package name) because I thought there would be a possibility of an error with some of them during on-device builds, if the package from PyPi that has a similar name to the package name were placed into `TERMUX_PKG_PYTHON_TARGET_DEPS`.

If you would like, I guess we can test and try to revise all existing main packages (not subpackages) that have `pip` debscripts, and see whether they can all be removed definitively without causing an error anywhere, and maybe if some cause errors, only the ones that can be removed without causing errors could be removed.

File: packages/python/debpython.patch (hunk 3 above)
Comment (Maxython) [reply packages/python/debpython.patch]: Screenshot_20250701-135133_Termux

Comment (robertkirkman) [reply packages/python/debpython.patch]: Ok thanks a lot, that's very interesting and I didn't really know that was a meaningful use-case. I will undo the change that messes up those commands.

Comment (robertkirkman) [reply packages/python/debpython.patch]: I think it is very helpful that there is now a note here that it's possible to just use `from debpython import` and it will work in Python after this.

File: packages/nala/build.sh (hunk 1 above)
Comment (licy183) [reply packages/nala/build.sh:46]: > Could you explain in more detail why it is better to leave the `nala` module installation setting in `termux_step_create_debscripts`, since when configuring the `nala` module in the `TERMUX_PKG_PYTHON_TARGET_DEPS` variable, its installation in debscripts will be automatically added?

`nala` should depend on specified version of `httpx` (`httpx<0.24.0,>=0.23.0`). If `postinst` has `pip3 install anyio httpx jsbeautifier pexpect python-debian rich tomli typer typing-extensions` and user has installed `httpx>=0.24.0` themselves (or by the `postinst` script of other packages), `pip` will not resolve the dependencies automatically and will show an ERROR message every time `pip` is executed. So, if one package is managed by `pip`, it is better to use `pip install package_name` to let pip resolve these dependencies rather than `pip install some_deps`.


This error is reported in #22686:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nala 0.15.4 requires anyio<4.0.0,>=3.6.1, but you have anyio 4.7.0 which is incompatible.
nala 0.15.4 requires httpx<0.24.0,>=0.23.0, but you have httpx 0.28.1 which is incompatible.
nala 0.15.4 requires rich<13.0.0,>=12.4.4, but you have rich 13.9.4 which is incompatible.
nala 0.15.4 requires typer<0.5.0,>=0.4.1, but you have typer 0.15.1 which is incompatible.
```

Comment (robertkirkman) [reply packages/nala/build.sh:46]: ok that makes a lot of sense thank you!
I need to make another change here.

Comment (Maxython) [reply packages/nala/build.sh:46]: > nala should depend on specified version of httpx

We can specify which version of `httpx` needs to be installed by `pip`. And I also did a test installation of these modules, and I did not get any errors.

Comment (robertkirkman) [reply packages/nala/build.sh:46]: The version you just added @Maxython might be sufficient to prevent all errors in `nala`, because of it putting all dependencies in one `pip` command. however, for the other packages, it might not be as easy. let's test all of them to check if any have errors like this. I will check them when I can

Comment (licy183) [reply packages/nala/build.sh:46]: > We can specify which version of `httpx` needs to be installed by `pip`. And I also did a test installation of these modules, and I did not get any errors.

Even so, there is still an unresolved issue, which has always existed since the start. If auto-update is enabled, there is no viable way to guarantee that the dependency versions declared in `build.sh`'s `TARGET_DEPS` are consistent with those declared in the actual `pyproject.toml` or `setup.py`.

File: packages/python-torchvision/build.sh [hunk 4]
```diff
@@ -3,11 +3,11 @@ TERMUX_PKG_DESCRIPTION="Datasets, Transforms and Models specific to Computer Vis
...
 TERMUX_PKG_MAINTAINER="@termux"
 TERMUX_PKG_VERSION=0.21.0
-TERMUX_PKG_REVISION=1
+TERMUX_PKG_REVISION=2
 TERMUX_PKG_SRCURL=https://github.com/pytorch/vision/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
 TERMUX_PKG_SHA256=0a4a967bbb7f9810f792cd0289a07fb98c8fb5d1303fae8b63e3a6b05d720058
-TERMUX_PKG_DEPENDS="libc++, ffmpeg, python, python-numpy, python-pillow, python-pip, python-torch, libjpeg-turbo, libpng, libwebp, zlib"
-TERMUX_PKG_SETUP_PYTHON=true
+TERMUX_PKG_DEPENDS="libc++, ffmpeg, python, python-numpy, python-pillow, python-torch, libjpeg-turbo, libpng, libwebp, zlib"
+TERMUX_PKG_PYTHON_TARGET_DEPS="torchvision"
```
Comment (robertkirkman) [inline packages/python-torchvision/build.sh]: ~~I have determined that the reason why the CI has failed at the moment is because of `TERMUX_PKG_PYTHON_TARGET_DEPS="torchvision"` being added to `python-torchvision`,~~

~~and this is a good example of one of the reasons I didn't originally plan to interfere with the packages which used `pip3 install` on a PyPi package with a very similar name to the package name.~~

~~One way to explain this particular error is, that `TERMUX_PKG_PYTHON_TARGET_DEPS` causes `termux_step_get_dependencies_python()` to attempt to build `torchvision` through its Pip package, _before_ the  correct `CXXFLAGS` can be set down below later in `termux_step_pre_configure()`.~~

https://github.com/termux/termux-packages/blob/c8e204d66241902a29a9f261803b0ffacb74df75/scripts/build/termux_step_get_dependencies_python.sh#L12

~~Now that you have seen what happens here by running this test, what would you like to do here regarding `python-torchvision`? @Maxython~~

~~EDIT: actually never mind, I am wrong and I realized that this error happened because of something else, I have found a way to resolve that error locally, so I have uploaded the fix here and will continue other testing~~

~~EDIT 2: well we'll see, locally I am seeing inconsistent behavior with `python-torchvision`, but currently the CI error is with `matplotlib` and I didn't get any error with `matplotlib` locally. Maybe `python-torchvision` will fail in CI also eventually.~~

Comment (robertkirkman) [reply packages/python-torchvision/build.sh]: Ok, I have figured out what is wrong with `python-torchvision` here.

Just ignore my previous message, it's pretty incoherent.

The short explanation is, the changes in this PR for `python-torchvision` that you added do unfortunately cause an error, but the `python-torchvision` in master branch builds fine. So, my plan was just to not edit `python-torchvision` in this PR, so that it keeps working undisturbed.

**Comment by robertkirkman** [comment]
Unfortunately, I'm unable to reproduce the `matplotlib` build error here locally. For me locally, all packages other than `python-torchvision` cross-compile successfully, but in CI, every time it fails to build `matplotlib`. This means there is a difference between my computer and CI for that package, I will try to find out what it is.

**Comment by robertkirkman** [comment]
Yes so, Tomjo2000, what we're interested in is whether all these packages will install and work successfully on-device after building here, and without showing the message:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
```

File: scripts/build/termux_step_create_python_debscripts.sh [hunk 5]
```diff
@@ -0,0 +1,113 @@
...
+	# make this script install them there is not currently
+	# any such thing as $TERMUX_SUBPKG_PYTHON_TARGET_DEPS.
+	# so skip this for subpackages at this time
+	# (those cases remain manually created per-subpackage)
+	if [ -z "${SUB_PKG_NAME-}" ] && [ -n "${TERMUX_PKG_PYTHON_TARGET_DEPS}" ]; then
+		cat <<- POSTINST_EOF >> postinst
+		echo "Installing dependencies for ${_package_name} through pip..."
+		LD_PRELOAD='' "${TERMUX_PREFIX}/bin/pip3" install --upgrade ${TERMUX_PKG_PYTHON_TARGET_DEPS//,/}
+		POSTINST_EOF
+	fi
```
Comment (TomJo2000) [inline scripts/build/termux_step_create_python_debscripts.sh]: Consider using `[[` bash test `]]` on the parts of this script that are not going into the debscripts.
```suggestion
	if [[ -z "${SUB_PKG_NAME-}" && -n "${TERMUX_PKG_PYTHON_TARGET_DEPS}" ]]; then
		cat <<- POSTINST_EOF >> postinst
		echo "Installing dependencies for ${_package_name} through pip..."
		LD_PRELOAD='' "${TERMUX_PREFIX}/bin/pip3" install --upgrade ${TERMUX_PKG_PYTHON_TARGET_DEPS//,/}
		POSTINST_EOF
	fi
```
I find that the visual separation helps visually distinguish it.

**Comment by robertkirkman** [comment]
> `Compatibility with CMake < 3.5 has been removed from CMake.`

After

- #25014 

CMake in all of Termux is now CMake 4, so packages that require CMake 3 cannot build anymore until they receive updates.

**Comment by robertkirkman** [comment]
I have been testing this PR more and adding more necessary changes in certain places, I have added my newest changes as an additional temporary commit here so that Maxython can easily distinguish this version of the PR from the previous version of the PR.

After the latest changes, there are no fatal errors during cross-compilation of all packages, installation of all packages on-device, and basic launch tests of some of the programs,

but there are still some non-fatal errors during installation, and some fatal errors during on-device building, and not all of those fatal errors during on-device building are exactly the same with and without this PR - meaning that unfortunately, **this PR does add some additional errors to on-device building, but only to packages that couldn't be built on-device previously anyway**.

Since on-device building is lower-priority than cross-compilation, it seems unclear how big of a problem it is that this adds additional errors to the on-device builds of packages that already wouldn't build on-device - (all packages modified here that could already build successfully on-device, still seem to build successfully on-device in this PR),

but in my opinion, probably it will be best to at least try to figure out some things about the unique, new errors being added for on-device building to three packages (`python-onnxruntime`, `python-torch`, `python-torchvision`) and try to do something to prevent the errors.


### Fatal errors during standard cross-compilation and installation through package manager

- No known fatal errors currently remaining in this category at the most recent commit

### Errors during on-device building

#### Packages that have the same error during on-device building both with and without this PR

- `python`
- `pyqt5`
- `matplotlib`

#### Packages that have an error during on-device building both with and without this PR, but **the error is different between them**

> [!TIP]
> these errors are the ones that I knew about that were the reasons I didn't originally touch packages like `python-onnxruntime` in this PR, but there are a bit fewer than I originally hypothesized.
> Only three packages seem to be truly affected by the frightening problem that discouraged me from
> changing these packages for risk of breaking them any further than they already are (I had expected more).
> 
> The errors are **related to the detail that on-device building of packages installs `$TERMUX_PKG_PYTHON_TARGET_DEPS` _before_ the building and installation of the package itself**.
> I am not yet completely sure what the best changes to this PR to prevent these errors should be
> (assuming that changes should attempt to preserve the idea of Maxython of putting all pip dependencies
> in the `$TERMUX_PKG_PYTHON_TARGET_DEPS` variable of these affected packages)

- `python-onnxruntime`
- `python-torch`
- `python-torchvision`

### Other non-fatal errors

As licy183 explained, there is a large amount of messages like this:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nala 0.16.0 requires anyio<5.0.0,>=4.9.0, which is not installed.
nala 0.16.0 requires httpx==0.28.1, which is not installed.
nala 0.16.0 requires pexpect<5.0.0,>=4.9.0, which is not installed.
nala 0.16.0 requires rich<14.0.0,>=13.9.4, which is not installed.
nala 0.16.0 requires tomli<3.0.0,>=2.2.1, which is not installed.
nala 0.16.0 requires typer<0.16.0,>=0.15.2, which is not installed.
manim 0.19.0 requires av<14.0.0,>=9.0.0, which is not installed.
manim 0.19.0 requires beautifulsoup4>=4.12, which is not installed.
manim 0.19.0 requires click>=8.0, which is not installed.
manim 0.19.0 requires cloup>=2.0.0, which is not installed.
manim 0.19.0 requires decorator>=4.3.2, which is not installed.
manim 0.19.0 requires isosurfaces>=0.1.0, which is not installed.
manim 0.19.0 requires manimpango<1.0.0,>=0.5.0, which is not installed.
manim 0.19.0 requires mapbox-earcut>=1.0.0, which is not installed.
manim 0.19.0 requires moderngl<6.0.0,>=5.0.0, which is not installed.
manim 0.19.0 requires moderngl-window>=2.0.0, which is not installed.
manim 0.19.0 requires pydub>=0.20.0, which is not installed.
manim 0.19.0 requires rich>=12.0.0, which is not installed.
manim 0.19.0 requires screeninfo>=0.7, which is not installed.
manim 0.19.0 requires srt>=3.0.0, which is not installed.
manim 0.19.0 requires svgelements>=1.8.0, which is not installed.
manim 0.19.0 requires tqdm>=4.0.0, which is not installed.
manim 0.19.0 requires watchdog>=2.0.0, which is not installed.
tldp 0.7.5 requires nose, which is not installed.
```

Despite that, installation does not fail and the programs _seem_ to run successfully, however, whether they have subtle errors with certain actions or not as a result of the pip errors, is unknown. The above messages do not appear when installing the current version of `nala` using `apt install nala`, but would begin appearing after this PR, I think.

File: packages/nala/build.sh (hunk 1 above)
Comment (Maxython) [reply packages/nala/build.sh:46]: I have reconfigured the method for configuring the installation of python modules in debscripts, and now you can use the variable `TERMUX_PKG_PYTHON_SCRIPT_DEPS` for this, instead of `TERMUX_PKG_PYTHON_TARGET_DEPS`. That is, now in the `nala` package, the installation of the `nala` module occurs through `TERMUX_PKG_PYTHON_SCRIPT_DEPS`, separately from the modules in `TERMUX_PKG_PYTHON_TARGET_DEPS`

File: packages/nala/build.sh [hunk 6]
```diff
@@ -3,15 +3,17 @@ TERMUX_PKG_DESCRIPTION="Commandline frontend for the apt package manager"
...
 TERMUX_PKG_SHA256=49e384aa3b94597d09c61b7accc41d1cf10cb6beea85d4620c80c28d7cdc4d5f
-TERMUX_PKG_DEPENDS="python-apt, python-pip"
+TERMUX_PKG_DEPENDS="python-apt"
 TERMUX_PKG_PLATFORM_INDEPENDENT=true
 TERMUX_PKG_BUILD_IN_SRC=true
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
 TERMUX_PKG_PYTHON_COMMON_DEPS="poetry"
 TERMUX_PKG_PYTHON_TARGET_DEPS="anyio, httpx, jsbeautifier, pexpect, python-debian, rich, tomli, typer, typing-extensions"
+TERMUX_PKG_PYTHON_SCRIPT_DEPS="nala"
```
Comment (licy183) [inline packages/nala/build.sh]:
```suggestion
TERMUX_PKG_PYTHON_SCRIPT_DEPS="nala, python-debian"
```

File: packages/matplotlib/build.sh [hunk 7]
```diff
@@ -15,12 +15,14 @@ LICENSE/LICENSE_STIX
...
 TERMUX_PKG_VERSION="3.10.3"
+TERMUX_PKG_REVISION=1
 TERMUX_PKG_SRCURL=https://github.com/matplotlib/matplotlib/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
 TERMUX_PKG_SHA256=d581d3cec14478a0347631f93d534c2acf11bf554670eedd0a200f56ec979d12
 TERMUX_PKG_AUTO_UPDATE=true
-TERMUX_PKG_DEPENDS="freetype, libc++, patchelf, ninja, python, python-contourpy, python-numpy, python-pillow, python-pip"
+TERMUX_PKG_DEPENDS="freetype, libc++, patchelf, ninja, python, python-contourpy, python-numpy, python-pillow"
 _NUMPY_VERSION=$(. $TERMUX_SCRIPTDIR/packages/python-numpy/build.sh; echo $TERMUX_PKG_VERSION)
 TERMUX_PKG_PYTHON_COMMON_DEPS="build, 'meson-python>=0.13.1', wheel, 'numpy==$_NUMPY_VERSION', 'pybind11>=2.6.0', 'setuptools>=64', 'setuptools_scm>=7'"
+TERMUX_PKG_PYTHON_TARGET_DEPS="matplotlib"
```
Comment (licy183) [inline packages/matplotlib/build.sh]:
```suggestion
TERMUX_PKG_PYTHON_SCRIPT_DEPS="matplotlib"
```

File: scripts/build/termux_step_setup_variables.sh [hunk 8]
```diff
@@ -173,7 +173,9 @@ termux_step_setup_variables() {
 	TERMUX_PKG_PYTHON_TARGET_DEPS="" # python modules to be installed via pip3
```
Comment (licy183) [inline scripts/build/termux_step_setup_variables.sh:180]: I really don't think the design of `TERMUX_PKG_PYTHON_TARGET_DEPS` is correct.

Currently, `TERMUX_PKG_PYTHON_TARGET_DEPS` is used in two places, one is for the on-device build, before compiling the current python wheel, as a pre-build dependency, and the other is in the `postinst` script, as a runtime dependency. In fact, the dependencies which are necessary for the on-device build are not the same as the runtime dependencies. The design of this variable should be reconsidered.

Comment (robertkirkman) [reply scripts/build/termux_step_setup_variables.sh:180]: I agree, in fact, I believe that, for Termux to be a good example of the only/one of the only distros that installs system python packages and pip python packages into the same folder, and makes system packages depend on pip packages,

the names and use of all four variables should be renamed and reorganized into more accurate and more easily manageable categories:

### current variable names (confusing, used inconsistently)

- `TERMUX_PKG_PYTHON_BUILD_DEPS`
- `TERMUX_PKG_PYTHON_TARGET_DEPS`
- `TERMUX_PKG_PYTHON_COMMON_DEPS`
- `TERMUX_PKG_PYTHON_SCRIPT_DEPS`

### variable names I suggest (I think the meaning is clearer and the categories are better suited to be used consistently for the purposes needed by Termux)


- `TERMUX_PKG_PYTHON_CROSS_BUILD_DEPS`: dependencies for `build-package.sh` to make the Ubuntu cross-compiler container install using `pip` before cross-compiling the package
- `TERMUX_PKG_PYTHON_NATIVE_BUILD_DEPS`: dependencies for `build-package.sh` to make Termux install using `pip` inside Termux, before non-cross-compiling the package
- `TERMUX_PKG_PYTHON_COMMON_BUILD_DEPS`: dependencies that should be installed by `build-package.sh` before building the package in both of the above cases
- `TERMUX_PKG_PYTHON_RUNTIME_DEPS`: dependencies for the package `postinst` script to install. For some cases, I believe that putting the PyPi equivalent name of the package of the same software in this list by itself or with, for example in the case of `nala`, one or two other dependencies that must have a matching version, might be sufficient to pull in the entire necessary dependency tree of PyPi runtime dependencies during `postinst`.



In many distros, the way this is set up is viewed as incorrect, but in Termux, since this practice has a precedent of being viewed as normal, and it does seem to have been working ok so far, if we make the code more organized and readable, then this can help people reading Termux code understand **how a distro that makes system packages depend on pip packages** should look, and make Termux a good example of this kind of distro.

File: scripts/build/termux_step_create_python_debscripts.sh [hunk 9]
```diff
@@ -0,0 +1,112 @@
+termux_step_create_python_debscripts() {
+	if [[ -n "${SUB_PKG_NAME-}" ]]; then
+		local _package_name="$SUB_PKG_NAME"
+		local _package_massagedir="$SUB_PKG_DIR/massage/$TERMUX_PREFIX"
+		local _package_python_deps="$TERMUX_SUBPKG_PYTHON_SCRIPT_DEPS"
```
Comment (robertkirkman) [inline scripts/build/termux_step_create_python_debscripts.sh]: These are now the first instances of `TERMUX_SUBPKG_PYTHON_SCRIPT_DEPS` to be found in the repository (`SUBPKG` as opposed to `PKG`), so it would be necessary to add this variable to some subpackages, to replace the `termux_step_create_subpkg_debscripts()` functions in them,

Also, it will be necessary to make adaptations for many packages in the repository and test them with `TERMUX_PKG_PYTHON_SCRIPT_DEPS`, or if the name I suggested is chosen, `TERMUX_PKG_PYTHON_RUNTIME_DEPS`,

had you already started doing that, or would you like me to help you find and change packages to this new variable and test them, @Maxython ?

File: packages/matplotlib/build.sh (hunk 7 above)
Comment (robertkirkman) [reply packages/matplotlib/build.sh]: There are many other places where this kind of change will be necessary, and I would also like to change the names of all the variables, but I believe Maxython has chosen the original names of the variables, so unfortunately, it might be necessary to reach a consensus on variable names before deciding exactly which changes to make, and where. I have written more information about this in one of my other messages

File: scripts/build/termux_step_setup_variables.sh (hunk 8 above)
Comment (Maxython) [reply scripts/build/termux_step_setup_variables.sh:180]: > I really don't think the design of `TERMUX_PKG_PYTHON_TARGET_DEPS` is correct.
> 
> Currently, `TERMUX_PKG_PYTHON_TARGET_DEPS` is used in two places, one is for the on-device build, before compiling the current python wheel, as a pre-build dependency, and the other is in the `postinst` script, as a runtime dependency. In fact, the dependencies which are necessary for the on-device build are not the same as the runtime dependencies. The design of this variable should be reconsidered.

Technically, using the `TERMUX_PKG_PYTHON_TARGET_DEPS` variable in `postinst` makes sense, because the variable itself is supposed to store python modules that need to be installed in the Termux application (i.e. in the native), and most often the python modules from this variable are needed for compilation (i.e. they are like a dependency for building) and for operation (i.e. they are like a normal dependency) so that python packages can work normally. 

> the names and use of all four variables should be renamed and reorganized into more accurate and more easily manageable categories

The `TERMUX_PKG_PYTHON_SCRIPT_DEPS` variable needs some more thought. Your suggestion to use the `TERMUX_PKG_PYTHON_RUNTIME_DEPS` variable instead of `TERMUX_PKG_PYTHON_SCRIPT_DEPS` looks interesting. As for other python variables (`TERMUX_PKG_PYTHON_BUILD_DEPS`, `TERMUX_PKG_PYTHON_TARGET_DEPS` and `TERMUX_PKG_PYTHON_COMMON_DEPS`), I'm not sure that this is necessary.

File: scripts/build/termux_step_create_python_debscripts.sh (hunk 9 above)
Comment (Maxython) [reply scripts/build/termux_step_create_python_debscripts.sh]: > These are now the first instances of TERMUX_SUBPKG_PYTHON_SCRIPT_DEPS to be found in the repository (SUBPKG as opposed to PKG), so it would be necessary to add this variable to some subpackages, to replace the termux_step_create_subpkg_debscripts() functions in them

I seem to have updated all subpackages and now they all use this variable (`TERMUX_SUBPKG_PYTHON_SCRIPT_DEPS`).

> Also, it will be necessary to make adaptations for many packages in the repository and test them with TERMUX_PKG_PYTHON_SCRIPT_DEPS, or if the name I suggested is chosen, TERMUX_PKG_PYTHON_RUNTIME_DEPS

I will change the `TERMUX_PKG_PYTHON_SCRIPT_DEPS` variable to `TERMUX_PKG_PYTHON_RUNTIME_DEPS` after the packages in the PR are compiled.

File: scripts/build/termux_step_setup_variables.sh (hunk 8 above)
Comment (robertkirkman) [reply scripts/build/termux_step_setup_variables.sh:180]: > Technically, using the TERMUX_PKG_PYTHON_TARGET_DEPS variable in postinst makes sense, because the variable itself is supposed to store python modules that need to be installed in the Termux application (i.e. in the native), and most often the python modules from this variable are needed for compilation (i.e. they are like a dependency for building) and for operation (i.e. they are like a normal dependency) so that python packages can work normally.

I Believe that this is not quite 100% correct, because as we have seen, there are certain packages like `nala`, `python-onnxruntime`, where the idea of installing the exact same PyPi dependencies list at build-time and run-time does not work on-device. so, on-device build-time and run-time PyPi dependencies must have fully separate lists in at least some cases, so we need to figure out some way to consistently specify this. In my opinion, four variables is probably a sufficient number to store the necessary set of possible configurations for the PyPi portions of the dependency trees of packages.

> As for other python variables (TERMUX_PKG_PYTHON_BUILD_DEPS, TERMUX_PKG_PYTHON_TARGET_DEPS and TERMUX_PKG_PYTHON_COMMON_DEPS), I'm not sure that this is necessary.

From the first time I saw these variables, I have to admit that I wanted to try to change their names to be easier to understand, but I have always known that you have set their names and prefer to use the current names. Would it be possible to maybe have a discussion with some others eventually, about whether it would be more readable to change the names of these variables, or not?

Comment (Maxython) [reply scripts/build/termux_step_setup_variables.sh:180]: > I Believe that this is not quite 100% correct, because as we have seen, there are certain packages like nala, python-onnxruntime, where the idea of installing the exact same PyPi dependencies list at build-time and run-time does not work on-device. so, on-device build-time and run-time PyPi dependencies must have fully separate lists in at least some cases, so we need to figure out some way to consistently specify this.

So for this purpose, to separate the installation of python modules before and after compilation, the variable `TERMUX_PKG_PYTHON_RUNTIME_DEPS` was implemented. The variable `TERMUX_PKG_PYTHON_TARGET_DEPS` plays as the second variable `TERMUX_PKG_PYTHON_RUNTIME_DEPS`, if the variable `TERMUX_PKG_PYTHON_RUNTIME_DEPS` is not configured in `build.sh`. Let me show you how I see the current structure of specifying python module dependencies to make it clear:
- `TERMUX_PKG_PYTHON_COMMON_DEPS` - common (general) dependencies (for cross-compilation and for native compilation) of python modules, which are installed only before compiling the package. Mainly used to specify build dependencies for proper compilation of packages.
- `TERMUX_PKG_PYTHON_BUILD_DEPS` - dependencies of python modules that are installed only before cross-compiling the package. Mainly used to specify build dependencies so that cross-compilation features build the package correctly.
- `TERMUX_PKG_PYTHON_TARGET_DEPS` - dependencies of python modules that are always installed before native compilation (i.e. on the device) of the package, and also sometimes after installing the package via the package manager. It is mainly used to specify the regular dependencies for the correct operation of packages, and can also be used to specify build dependencies for the correct assembly of the package. I would like to note that this type of functioning existed before your PR.
- `TERMUX_PKG_PYTHON_RUNTIME_DEPS` - dependencies of python modules that are installed via the `postinst` script (debscripts), i.e. after installing the package via the package manager. Mainly used to split the dependency from `TERMUX_PKG_PYTHON_TARGET_DEPS` into build dependencies in `TERMUX_PKG_PYTHON_TARGET_DEPS` and into regular dependencies in `TERMUX_PKG_PYTHON_RUNTIME_DEPS` to avoid problems with python module installation when installing package via package manager.

So I don't see any need to change/reconfigure the functionality of these variables since they already occupy enough spectrum of the function to flexibly specify python modules, while their configuration is quite compact for `build.sh`. 

The only thing is that there is one undefined point: if the `TERMUX_PKG_PYTHON_TARGET_DEPS` variable needs to specify a build dependency that does not need to be installed after installing the package via the package manager, what should you do? (PS: I have an idea how to fix this).

> From the first time I saw these variables, I have to admit that I wanted to try to change their names to be easier to understand, but I have always known that you have set their names and prefer to use the current names. Would it be possible to maybe have a discussion with some others eventually, about whether it would be more readable to change the names of these variables, or not?

I think there is sense in the question of renaming them (so that they become more understandable, as you noted). As for the question of reconfiguring their function, as I already said, I think there is no need.

It is worth noting that it was not me who came up with these names for these variables, but @licy183 - https://github.com/termux/termux-packages/pull/13611#discussion_r1044936933

Comment (licy183) [reply scripts/build/termux_step_setup_variables.sh:180]: The variable name I proposed at the time was misleading, and it turns out that the variable has been misused because of its name.

File: scripts/build/termux_step_create_python_debscripts.sh (hunk 9 above)
Comment (Maxython) [reply scripts/build/termux_step_create_python_debscripts.sh]: > I will change the TERMUX_PKG_PYTHON_SCRIPT_DEPS variable to TERMUX_PKG_PYTHON_RUNTIME_DEPS after the packages in the PR are compiled.

Done

File: scripts/build/termux_step_setup_variables.sh (hunk 8 above)
Comment (Maxython) [reply scripts/build/termux_step_setup_variables.sh:180]: > The variable name I proposed at the time was misleading, and it turns out that the variable has been misused because of its name.

If you are talking about the `TERMUX_PKG_PYTHON_TARGET_DEPS` variable and mean that it is incorrect to use this variable (i.e. its value) to customize installation of python modules in the `postinst` of a package, then I think that such a restriction of this variable will harm most packages today. As I said, technically, installing python modules from `TERMUX_PKG_PYTHON_TARGET_DEPS` before compiling on the device, or during installation of the package, is the correct action. Since most packages, in the `TERMUX_PKG_PYTHON_TARGET_DEPS` variable specify the usual (basic) dependencies for correct assembly of packages and also for their correct operation on the device. In the end, although insignificantly, but still thanks to such functionality of the `TERMUX_PKG_PYTHON_TARGET_DEPS` variable allows you to save `build.sh` lines of packages.

Comment (robertkirkman) [reply scripts/build/termux_step_setup_variables.sh:180]: > The variable TERMUX_PKG_PYTHON_TARGET_DEPS plays as the second variable TERMUX_PKG_PYTHON_RUNTIME_DEPS, if the variable TERMUX_PKG_PYTHON_RUNTIME_DEPS is not configured in build.sh.

I am ok with this, this makes sense to me and if this works well when testing, then let's do it that way, yes.

> I think there is sense in the question of renaming them (so that they become more understandable, as you noted). As for the question of reconfiguring their function, as I already said, I think there is no need.

I would be ok with renaming two of the remaining variables to the names I proposed, without changing their functionality.

I think that `TERMUX_PKG_PYTHON_COMMON_DEPS` should be named `TERMUX_PKG_PYTHON_COMMON_BUILD_DEPS` and `TERMUX_PKG_PYTHON_BUILD_DEPS` should be named `TERMUX_PKG_PYTHON_CROSS_BUILD_DEPS`, because these are both groups that are never runtime dependencies and these names more clearly explain the difference between them.

Originally when I first used these variables while editing packages, I was confused about the difference between the variables, and I had to read the code carefully and test the behavior of the variables to find out what really happens.

I was confused whether the `TERMUX_PKG_PYTHON_BUILD_DEPS` variable would make dependencies get installed during on-device builds, and whether `TERMUX_PKG_PYTHON_COMMON_DEPS` variable's list would be installed during package installation or not.

I think if the names `TERMUX_PKG_PYTHON_CROSS_BUILD_DEPS` and `TERMUX_PKG_PYTHON_COMMON_BUILD_DEPS` are used, they would make it easier for developers from other projects who have not made Termux packages before, to read and understand the purpose of the variable contents without having to read all the code in the `scripts` folder related to these variables.

Comment (robertkirkman) [reply scripts/build/termux_step_setup_variables.sh:180]: I think bulk renaming without changing behavior can be done another time separately, since too much renaming of preexisting variables would make this PR harder to read.

**Comment by robertkirkman** [comment]
After some more testing and consideration, I have decided to add some more changes into another temporary commit here,
Maxython, you can read my most recent commit in order to review my newest changes and decide whether you agree with them.

**Comment by Maxython** [comment]
LGTM

**Comment by robertkirkman** [comment]
I had been testing this and encountering this error during installation of `nala`

```
Errno 2] No such file or directory: '/data/data/com.termux/files/usr/lib/python3.12/site-packages/nala/cache.py'
dpkg: error processing package nala (--configure):
```

since this was technically an error producing a failing result, I created a way to prevent this error and have applied it to the recent commit, and you can let me know if you agree with the solution I created.

This will make `py3compile` skip compiling `.py` files if `dpkg` reports they are in the package, but they end up not being present when `py3compile` runs because of `pip install` deleting those files for some reason if the PyPi equivalent name of the software being packageed is in `TERMUX_PKG_PYTHON_RUNTIME_DEPS`.

After this, I think this PR content is ready, and the commits can be squashed into a single commit. What do you think @Maxython ?

I had some other ideas for additional features or changes that change even more than this, but they are too big for this PR and if I still want them I will make other PRs for them later.

**Comment by Maxython** [comment]
> `pip install` deleting those files for some reason if the PyPi equivalent name of the software being packageed is in `TERMUX_PKG_PYTHON_RUNTIME_DEPS`.

It seems that this happens because during the installation of the module, `pip` updates it to the latest version (i.e. this happens because `pip` has the `--upgrade` flag set). And due to this update, the contents of the module's `*.py` files may change (i.e. they may be deleted or new ones may be created).

> After this, I think this PR content is ready, and the commits can be squashed into a single commit. What do you think @Maxython ?

I think we should first reconsider the method for solving this problem you found. Then this PR can be merged with two commits (in one commit the implementation of debpython, in the other recompilation of some packages).

**Comment by robertkirkman** [comment]
> I think we should first reconsider the method for solving this problem you found. Then this PR can be merged with two commits (in one commit the implementation of debpython, in the other recompilation of some packages).

Ok sure, sounds great. If you have a specific idea for how to fix the problem of `Errno 2] No such file or directory: '/data/data/com.termux/files/usr/lib/python3.12/site-packages/nala/cache.py'` in a better way, then feel free to force push this branch with any change you want to show, and we can see how that way looks

**Comment by Maxython** [comment]
> If you have a specific idea for how to fix the problem of Errno 2] No such file or directory: '/data/data/com.termux/files/usr/lib/python3.12/site-packages/nala/cache.py' in a better way, then feel free to force push this branch with any change you want to show, and we can see how that way looks

The idea for solving the problem: if in the list of modules to install during the installation of packages there is a module whose name matches the name of the package, then the `--upgrade` flag will be disabled.

File: scripts/build/termux_step_create_python_debscripts.sh [hunk 10]
```diff
@@ -0,0 +1,116 @@
...
+			exit 0
+		fi
+		POSTINST_EOF
+	fi
+
+	# if the package has runtime dependencies requiring pip,
+	# make this script install them
+	if [[ -n "${_package_python_deps}" ]]; then
+		local upgrade_flag="--upgrade"
+		if [[ " $(tr ' ' '\n' <<< "${_package_python_deps}" | sed "s/'//g; s/</ /g; s/>/ /g; s/=/ /g" | awk '{printf $1 " "}')" =~ " ${_package_name//python-/} " ]]; then
```
Comment (robertkirkman) [inline scripts/build/termux_step_create_python_debscripts.sh]: @Maxython It is correct that this will prevent the error during `apt` upgrades and installation,

but this would not be sufficient to convert the error into a warning, if the user runs a 3rd-party script that runs this series of commands:

```
pkg install -y nala
pip install --upgrade nala
py3compile -p nala $PREFIX/lib/python3.12
```

Do you think the conversion of the error message into a warning that I created should be kept **in addition to this**, just in case the user wants to do something similar to that, and just as a precaution in case this condition ever fails to detect a package, for example, if someone accidentally names a package with a name that doesn't exactly contain the name of the equivalent PyPi package as a substring?

Comment (licy183) [reply scripts/build/termux_step_create_python_debscripts.sh]: The `nala` package on PyPI is not the one packaged by Termux...

https://pypi.org/project/nala/

Comment (robertkirkman) [reply scripts/build/termux_step_create_python_debscripts.sh]: I see, but it seems like you added this dependency earlier,

- https://github.com/termux/termux-packages/issues/22686

maybe that should be changed, and maybe the dependencies of the Termux `nala` package should be rewritten to be more like the dependencies of the current Debian `nala` package?

https://gitlab.com/volian/nala/-/blob/7784856980039ecb5f1a4449fd03dd569889ec60/debian/control#L33

Comment (licy183) [reply scripts/build/termux_step_create_python_debscripts.sh]: Without `--upgrade`, `pip install` will try to resolve the dependencies and install them automatically.

Comment (robertkirkman) [reply scripts/build/termux_step_create_python_debscripts.sh]: Oh ok, so do you mean that `pip install nala` will install PyPi dependencies for the current (_local_) package in `site-packages/nala`, which is different from the PyPi package, but `pip install --upgrade nala` will install the PyPi `nala`, which is different software?

Thank you for explaining this, I really did not know that before. I assumed that `pip` would always treat _all_ package names passed as PyPi packages.

Comment (Maxython) [reply scripts/build/termux_step_create_python_debscripts.sh]: > if someone accidentally names a package with a name that doesn't exactly contain the name of the equivalent PyPi package as a substring?

This is an undesirable action because the package content is expected to be the same as a module that has the same name as the package and will be installed during package installation.

**Comment by robertkirkman** [comment]
Ok, I have tested installing the current version on two termux-apt devices with two different CPU architectures, and one clean installed and one not clean installed, and I can confirm there are no more **fatal errors** anywhere in this PR.

However, the one remaining possible problem I see is, I still frequently see these errors:

Screenshot_20250718-150218_Termux

licy183 mentioned these errors first, but unfortunately, I don't know how to fix these.

They are non-fatal errors, because after they show, "Successfully installed" prints anyway.

Also, they do not necessarily produce runtime errors in the python programs, because for example, after this I tested commands like `manim --show-splash init project`, and they appear to work without errors.

On the other hand, I am not sure whether these errors indicate that subtle, hard-to-find crashes in some programs might appear.

Do you think it is acceptable to allow these errors, or do you know of any way to prevent them?

**Comment by robertkirkman** [comment]
I checked and noticed that the dependencies logged as "not installed", do actually appear as installed at the end after all debscripts finish running.

Screenshot_20250718-153821_Termux

for example, `mapbox-earcut` 1.0.2 is installed after the `apt install` command finishes, but I didn't manually install it.

This suggests the error might be spurious, or also, it could be a coincidence, and maybe `mapbox-earcut` was installed by a different debscript somehow, from the one that printed that message. I'm not sure which is the case.

**Comment by licy183** [comment]
> Do you think it is acceptable to allow these errors, or do you know of any way to prevent them?

As I commented before, if you install some package manually (`pip install manim`), `pip` will automatically change these dependencies to correct version.

**Comment by robertkirkman** [comment]
Thank you for explaining, I am sorry for being dense about this detail. I think I am beginning to get an idea of what should be done. I will think about this and make a solution.

**Comment by robertkirkman** [comment]
After the most recent changes, when I test fully recompiling and reinstalling every single package here at once into a clean Termux installation, **the amount of visible instances of `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed` has not been 100% completely eliminated, but they have been greatly reduced,** and all of the instances remaining seem to occur because `apt` installs all the python package _files_ into `$PREFIX` _before_ ever running any debscripts, then runs the `postinst` scripts one by one for each package, so these messages sometimes print temporarily while not all packages have had their `postinst` scripts run yet - but **I believe that all PyPi dependencies are now installed correctly by the time all `postinst` scripts have finished running.**

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
borgbackup 1.4.1 requires msgpack<=1.1.0,>=1.0.3, which is not installed.
matplotlib 3.10.3 requires cycler>=0.10, which is not installed.
matplotlib 3.10.3 requires fonttools>=4.22.0, which is not installed.
matplotlib 3.10.3 requires kiwisolver>=1.3.1, which is not installed.
matplotlib 3.10.3 requires pyparsing>=2.3.1, which is not installed.
matplotlib 3.10.3 requires python-dateutil>=2.7, which is not installed.
torch 2.6.0 requires filelock, which is not installed.
torch 2.6.0 requires fsspec, which is not installed.
torch 2.6.0 requires jinja2, which is not installed.
torch 2.6.0 requires networkx, which is not installed.
torch 2.6.0 requires setuptools; python_version >= "3.12", which is not installed.
torch 2.6.0 requires typing-extensions>=4.10.0, which is not installed.
torch 2.6.0 requires sympy==1.13.1; python_version >= "3.9", but you have sympy 1.14.0 which is incompatible.
Successfully installed coloredlogs-15.0.1 flatbuffers-25.2.10 humanfriendly-10.0 mpmath-1.3.0 packaging-25.0 protobuf-6.31.1 sympy-1.14.0
Setting up ffmpeg (7.1.1-4) ...
Setting up python-torch (2.6.0-1) ...
Installing dependencies for python-torch through pip...
Requirement already satisfied: torch in /data/data/com.termux/files/usr/lib/python3.12/site-packages (2.6.0)
Collecting filelock (from torch)
  Downloading filelock-3.18.0-py3-none-any.whl.metadata (2.9 kB)
Collecting typing-extensions>=4.10.0 (from torch)
  Downloading typing_extensions-4.14.1-py3-none-any.whl.metadata (3.0 kB)
Collecting setuptools (from torch)
  Downloading setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy==1.13.1 (from torch)
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch)
  Downloading networkx-3.5-py3-none-any.whl.metadata (6.3 kB)
Collecting jinja2 (from torch)
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec (from torch)
  Downloading fsspec-2025.7.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from sympy==1.13.1->torch) (1.3.0)
```

In particular, I noticed by looking closely that I think all of the dependencies are now being resolved as well as possible for every single package, one by one as the `postinst` scripts for each package explicitly install the `pip`-facing package name without `--upgrade`:

```
torch 2.6.0 requires filelock, which is not installed.
```
...

```
Setting up python-torch (2.6.0-1) ...
Installing dependencies for python-torch through pip...
Requirement already satisfied: torch in /data/data/com.termux/files/usr/lib/python3.12/site-packages (2.6.0)
Collecting filelock (from torch)
  Downloading filelock-3.18.0-py3-none-any.whl.metadata (2.9 kB)
```

@Maxython The amount of changes I have made to do this is quite large, and I am not sure whether you agree with all of the changes. Please let me know if you think everything I have done here is a good idea.

however, after you have finished reviewing my new changes, and any follow-up changes have finished, I believe this PR will be ready.

File: scripts/buildorder.py [hunk 11]
```diff
@@ -39,7 +39,7 @@ def parse_build_file_dependencies_with_vars(path, vars):
     with open(path, encoding="utf-8") as build_script:
         for line in build_script:
             if line.startswith(vars):
-                dependencies_string = line.split('DEPENDS=')[1]
+                dependencies_string = line.split('DEPS=' if 'DEPS=' in line else 'DEPENDS=')[1]
```
Comment (robertkirkman) [inline scripts/buildorder.py]: @Maxython I am a little bit confused about this line, and I don't know if I need to change it to match my other recent changes somehow. If it's easy for you to explain, could you explain a little bit about what this line is supposed to do?

**Review by robertkirkman — COMMENTED** [review]
EDIT: this comment is an accident, please ignore this comment and read the other one below.
```
          |
          v
```
image

**Comment by robertkirkman** [comment]
The calcurse.org website is currently down, so I cannot build this PR at the moment, but it should build after that resolves eventually. EDIT: now resolved

**Comment by robertkirkman** [comment]
Basically, I need it and it's really inconvenient for me not to have all the necessary changes in one branch, so I've now added **all additional changes that are required to fix**

- https://github.com/termux/termux-packages/issues/21658

This means that after 10 months in development, during which many other fixes have been merged in other PRs that have whittled down more and more of the errors here and there, this PR is now a 100% solution to that issue (`./build-package.sh -I -f mesa` on-device), instead of only part of the solution.

> [!TIP]
> This PR that was recently merged globally fixed a large number of on-device build errors that I had been aware of for years,
> - https://github.com/termux/termux-packages/pull/25627
> 
> and it makes up a portion of the fixes for that issue, but I was unfortunately a bit too unassertive to believe that I could convincingly argue for that change to be made for a long time (which ended up being until NDK r28c broke the existing code further, giving me the opportunity to prove that my approach is better in a high-priority situation)
> 
> - https://github.com/termux/termux-packages/issues/25622

**Comment by robertkirkman** [comment]
@hansm629 I believe this PR should now form an implementation of a 100% solution to your October 4 2024 issue,

if you would like to, you can try testing it to just confirm that on your end, by using these commands, which should ideally be **100% successful without any other manual intervention, with no errors**.

```bash
git clone -b exclude-pycache-during-extract-into-massagedir https://github.com/robertkirkman/termux-packages.git
cd termux-packages/
scripts/setup-termux.sh
./build-package.sh -I -f mesa
cd output/
apt reinstall ./*.deb
```

**Comment by robertkirkman** [comment]
@TomJo2000 Unfortunately, it seems like another problem related to

- #26786 

has occurred in this PR,

I rebased this PR past

- #26930 

just now, and this happened:

image

It seems to "think" that the current version is still Python 3.12.11-1, when it's definitely not. The current version is Python 3.12.12, and the diff shows that:

image

Do you know what might be going wrong here?

**Comment by TomJo2000** [comment]
Looking into it.

**Comment by robertkirkman** [comment]
I force-pushed the branch again with no other changes today, and now it's passing the linter instead of failing, so the problem is intermittent. This is the run where it failed: https://github.com/termux/termux-packages/actions/runs/18621788032/job/53093893130 I will watch in the future for if it happens again.

**Review by Maxython — APPROVED** [review]

**Comment by robertkirkman** [comment]
I have finished final testing and it is working, so I will merge it in 24 hours if there are no more reviews.

I historically wrote a great amount of words discussing this message in this thread:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
```

To recap concisely: thorough testing indicates that the reason this message occurs is because, when multiple packages are being installed at once, their `postinst` scripts run one at a time in order,

and each time `pip install` runs during a `postinst` script, other Python packages whose `postinst` scripts have not run yet, but whose files have already been unpacked, are detected as not having their dependencies from PyPi installed yet, which is a temporary state.

Once all the `postinst` scripts finish running and the `apt install` command completes, manual `pip install` commands from the shell after that do not show that message anymore, confirming that all of the necessary PyPi dependencies of all of the installed Python packages have been automatically installed.

**Review by licy183 — APPROVED** [review]

**Review by TomJo2000 — APPROVED** [review]

**Comment by robertkirkman** [comment]
Today I saw this for the first time,

image

I needed to make a note that I don't know what that is, and we don't currently support removing it, and I don't know if it should be or not.

**Comment by robertkirkman** [comment]
Well, it is part of a larger message which is a failure of `__pycache__` folders to be removed during the upgrade from Python 3.13 to 3.14,

image

I think that the reason this occurs is because this logic I made prevents the `py3clean` from being run if the package is only being upgraded, rather than removed.

https://github.com/termux/termux-packages/blob/21d63fc8f127c169054634c51aa310582295c9bc/scripts/build/termux_step_create_python_debscripts.sh#L132-L136

so I think this means `py3clean` won't currently remove `__pycache__` folders from the previous Python version when it's upgraded to a newer minor version, even if the folder location changes because of the Python version changing.

Should this be changed before Python 3.15 so that future Python minor versions have their `__pycache__` files removed, even if it would mean running of `py3clean` during every upgrade of all Python packages?
