### PR TITLE
ndk-multilib: add libcompiler-rt files for cross-compile

### LINKED ISSUE #9308: [Bug]: clang-13 cannot cross compile
### Problem description

`clang 13` seems cannot perform cross-compilation.

### What steps will reproduce the bug?

```
pkg install build-essential ndk-multilib
echo -e '#include <stdio.h>\nint main(){\n    puts("Hello World");\n}' > main.c
clang --target=aarch64 main.c
```
and then the error occurs
```
In file included from main.c:1:
In file included from /data/data/com.termux/files/usr/include/stdio.h:42:
In file included from /data/data/com.termux/files/usr/include/sys/types.h:36:
/data/data/com.termux/files/usr/include/linux/types.h:21:10: fatal error: 'asm/types.h' file not found
#include <asm/types.h>
         ^~~~~~~~~~~~~
1 error generated.
```

### What is the expected behavior?

A binary should be generated with `file` outputs `a.out: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, not stripped`.

### System information

termux-info:

```
u0_a63@localhost> termux-info
Application version:
0.118.0
Packages CPU architecture:
x86_64
Subscribed repositories:
# sources.list
deb https://mirrors.ustc.edu.cn/termux/apt/termux-main stable main
Updatable packages:
All packages up to date
Android version:
7.1.1
Kernel build information:
Linux localhost 4.14.67-android #1 SMP Mon Jan 10 15:40:27 IST 2022 x86_64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A5000
```

### PR DESCRIPTION
**Pull request by licy183**
Closes #9308.

### CODE REVIEW

File: packages/ndk-multilib/build.sh [hunk 1]
```diff
@@ -37,11 +37,27 @@ prepare_libs() {
...
+
+add_cross_compiler_rt() {
+	# FIXME: Should we get libcompiler-rt from libllvm package?
+	RT_PREFIX=$NDK/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/*/lib/linux
+	LIBLLVM_VERSION=$(. $TERMUX_SCRIPTDIR/packages/libllvm/build.sh; echo $TERMUX_PKG_VERSION)
+	RT_TMP=$TERMUX_PKG_TMPDIR/cross-compiler-rt
+	RT_PATH=$TERMUX_PKG_MASSAGEDIR/$TERMUX_PREFIX/lib/clang/$LIBLLVM_VERSION/lib/android/
+	mkdir -p $RT_TMP
+	cp $RT_PREFIX/* $RT_TMP/ || true
+	rm -rf $RT_TMP/*$TERMUX_ARCH*
```
Comment (xtkoba) [inline packages/ndk-multilib/build.sh:52]: This removal seems to prevent the package from being platform-independent. Is this necessary? What happens if not removed?

Comment (licy183) [reply packages/ndk-multilib/build.sh:52]: Some of them are provided by package `libcompiler-rt`. If we don't remove them, `dpkg -i` will fail to install this package due to file conflict.

File: packages/ndk-multilib/build.sh [hunk 2]
```diff
@@ -2,10 +2,10 @@ TERMUX_PKG_HOMEPAGE=https://developer.android.com/tools/sdk/ndk/index.html
 TERMUX_PKG_DESCRIPTION="Multilib binaries for cross-compilation"
 TERMUX_PKG_LICENSE="NCSA"
 TERMUX_PKG_MAINTAINER="@termux"
+TERMUX_PKG_DEPENDS="libcompiler-rt"
```
Comment (xtkoba) [inline packages/ndk-multilib/build.sh:5]: Can't this be `TERMUX_PKG_BUILD_DEPENDS` instead?

Also would you please move dependency-related definitions just below the source-related definitions (`TERMUX_PKG_SKIP_SRC_EXTRACT` in this case)?

Comment (licy183) [reply packages/ndk-multilib/build.sh:5]: OK. I will fix that.

File: packages/ndk-multilib/build.sh (hunk 1 above)
Comment (xtkoba) [reply packages/ndk-multilib/build.sh:52]: Then I propose that `libclang_rt.*`s be installed to another directory, and that `postinst` script be used to symlink to them (except for the ones targeting the native arch).

Comment (licy183) [reply packages/ndk-multilib/build.sh:52]: And then this package can be platform-independent again. That sounds great!

File: packages/ndk-multilib/build.sh (hunk 2 above)
Comment (truboxl) [reply packages/ndk-multilib/build.sh]: I think dependency on libcompiler-rt should be removed. In fact, ndk-multilib should not depend on anything since its source is from NDK. Postinst can take care of symlinks stuff.

File: packages/ndk-multilib/build.sh [hunk 3]
```diff
@@ -37,11 +37,60 @@ prepare_libs() {
 	fi
 
 	cp $LIBATOMIC/libatomic.a $TERMUX_PKG_MASSAGEDIR/$TERMUX_PREFIX/$SUFFIX/lib/
+
+	cp $LIBATOMIC/libunwind.a $TERMUX_PKG_MASSAGEDIR/$TERMUX_PREFIX/$SUFFIX/lib/
+}
+
+add_cross_compiler_rt() {
+	# FIXME: Should we get libcompiler-rt from libllvm package?
```
Comment (buttaface) [inline packages/ndk-multilib/build.sh:45]: No need, the one from the NDK is fine.

Comment (licy183) [reply packages/ndk-multilib/build.sh:45]: OK. I will remove this line from the `build.sh`.

File: packages/ndk-multilib/build.sh [hunk 4]
```diff
@@ -37,11 +37,59 @@ prepare_libs() {
...
+	LIBLLVM_VERSION=$(. $TERMUX_SCRIPTDIR/packages/libllvm/build.sh; echo $TERMUX_PKG_VERSION)
+	RT_PATH=$TERMUX_PREFIX/lib/clang/$LIBLLVM_VERSION/lib/android
+	# Install the symlinks.
+	cat <<- POSTINST_EOF > ./postinst
+	#!$TERMUX_PREFIX/bin/sh
+
+	echo "Installing symlinks to $RT_PATH..."
+
+	mkdir -p $RT_PATH
+	find $RT_OPT_DIR -type f ! -name "libclang_rt*\$(uname -m)*" -exec ln -sfr "{}" $RT_PATH \;
```
Comment (xtkoba) [inline packages/ndk-multilib/build.sh:69]: This won't work in some environments. In my 32-bit ARM phone `uname -m` prints `armv7l`.

For an alternative way, see:

https://github.com/termux/termux-packages/blob/b3d94b5399078aa07f33294ca7bc40343a3fb6a7/build-package.sh#L285-L286

Comment (licy183) [reply packages/ndk-multilib/build.sh]: OK, fixed.

File: packages/ndk-multilib/build.sh [hunk 5]
```diff
@@ -37,11 +37,51 @@ prepare_libs() {
...
+	cat <<- PRERM_EOF > ./prerm
+	#!$TERMUX_PREFIX/bin/sh
+	if [ "$TERMUX_PACKAGE_FORMAT" != "pacman" ] && [ "\$1" != "remove" ]; then
+	    exit 0
+	fi
+	echo "Uninstalling symlinks..."
+	find $RT_PATH -type l ! -name "libclang_rt*\$(dpkg --print-architecture)*" -exec rm -rf "{}" \;
+	if [ ! "\$(ls -A $RT_PATH)" ]; then
+	    # $RT_PATH is empty. Package libcompiler-rt should have been removed. Remove this folder.
+	    rm -rf $TERMUX_PREFIX/lib/clang
```
Comment (xtkoba) [inline packages/ndk-multilib/build.sh:81]: This smells dangerous to me. Is the removal needed in the first place? If so, then can this be more graceful?

File: packages/ndk-multilib/build.sh [hunk 6]
```diff
@@ -37,11 +37,51 @@ prepare_libs() {
...
+
+termux_step_create_debscripts() {
+	LIBLLVM_VERSION=$(. $TERMUX_SCRIPTDIR/packages/libllvm/build.sh; echo $TERMUX_PKG_VERSION)
+	RT_PATH=$TERMUX_PREFIX/lib/clang/$LIBLLVM_VERSION/lib/android
+	# Install the symlinks.
+	cat <<- POSTINST_EOF > ./postinst
+	#!$TERMUX_PREFIX/bin/sh
+	echo "Installing symlinks to $RT_PATH..."
+	mkdir -p $RT_PATH
+	find $RT_OPT_DIR -type f ! -name "libclang_rt*\$(dpkg --print-architecture)*" -exec ln -sfr "{}" $RT_PATH \;
```
Comment (xtkoba) [inline packages/ndk-multilib/build.sh:67]: Is the `-r` option for `ln` command necessary here? This is a GNU extension and IMO should be avoided if possible.

File: packages/ndk-multilib/build.sh (hunk 5 above)
Comment (licy183) [reply packages/ndk-multilib/build.sh:81]: Maybe we should create a `prerm` script in `libcompiler-rt` to check and remove these symlinks.

Comment (xtkoba) [reply packages/ndk-multilib/build.sh:81]: Not symlinks but directories. Symlink removal should be handled here.

Comment (licy183) [reply packages/ndk-multilib/build.sh:81]: Emmm... In my point of view, this folder should be handled by `dpkg` when `libcompiler-rt` installs.
`prerm` in `libcompiler-rt` and `prerm` in `ndk-multilib` should remove these symlinks if they exist.
`postinst` in `libcompiler-rt` should install these symlinks if `ndk-multilib` is installed.
`postinst` in `ndk-multilib` should install these symlinks if `libcompiler-rt` is installed.
The solution above seems more graceful. Any ideas?

Comment (xtkoba) [reply packages/ndk-multilib/build.sh:81]: Note that there is no dependency between `libcompiler-rt` and `ndk-multilib`.

I'm strongly against

```bash
rm -rf $TERMUX_PREFIX/lib/clang
```

because there is no assurance that this directory does not contain any other files. It would be much more tolerable if this directory were kept unremoved.

Comment (xtkoba) [reply packages/ndk-multilib/build.sh:81]: How about using `-p` option for `rmdir`:

```bash
rmdir -p $RT_PATH || :
```

With this emptyness check can be omitted.

Comment (licy183) [reply packages/ndk-multilib/build.sh:81]: Maybe we can touch a random-named file like this?
```
mkdir -p $TERMUX_PKG_MASSAGEDIR/$RT_PATH
touch $TERMUX_PKG_MASSAGEDIR/$RT_PATH/".termux-$(cat /proc/sys/kernel/random/uuid)"
```
Then this folder should be able to create/remove by `dpkg`.

File: packages/ndk-multilib/build.sh (hunk 6 above)
Comment (licy183) [reply packages/ndk-multilib/build.sh]: `-r` is not necessary. We can remove it.

File: packages/ndk-multilib/build.sh (hunk 5 above)
Comment (xtkoba) [reply packages/ndk-multilib/build.sh]: No need to be random, unless conflicting with other packages. I wonder if there is any convention, but I would prefer `.keep-ndk-multilib` or something that has package name as suffix.

Comment (licy183) [reply packages/ndk-multilib/build.sh]: OK. I will fix it.
