### PR TITLE
enhance(x11/libime): Build dictionary files

### LINKED ISSUE #22121: [Package]: 编译了libime和fcitx5-chinese-addons如何传至仓里
### Why is it worth to add this package?

需要中文输入法，目前已经编译并安装libime和fcitx5-Chinese-addons，需要递交到x11-repo代码仓

### Home page URL

https://fcitx-im.org

### Source code URL

https://github.com/fcitx/fcitx5-chinese-adsons

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [ ] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [ ] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Biswa96**
* Fixes #22121

### CODE REVIEW

**Comment by Biswa96** [comment]
Please let me know if there is any better way to do this.

**Review by robertkirkman — APPROVED** [review]
I was wondering if it might be possible to hostbuild and use hostbuild binaries in a way that is better than this, but I tried, and actually these programs running in `termux-proot-run` have a huge number of dependencies, that could technically be manually fetched and set up for a hostbuild, but I believe it would cause the `build.sh` to actually be longer and messier than this one, so this way is better.

File: x11-packages/libime/build.sh [hunk 1]
```diff
@@ -3,14 +3,43 @@ TERMUX_PKG_DESCRIPTION="A library to support generic input method implementation
...
+	termux_step_make
+
+	# from add_custom_commands in data/CMakeLists.txt
+	if [[ "$TERMUX_ON_DEVICE_BUILD" == "false" ]]; then
+		pushd data
+		termux-proot-run ../tools/libime_slm_build_binary -s -a 22 -q 8 trie lm_sc.arpa sc.lm
+		termux-proot-run ../tools/libime_prediction sc.lm lm_sc.arpa sc.lm.predict
+		termux-proot-run ../tools/libime_pinyindict dict_sc.txt sc.dict
+		termux-proot-run ../tools/libime_pinyindict dict_extb.txt extb.dict
+		declare -a files=(db.txt erbi.txt qxm.txt wanfeng.txt wbpy.txt wbx.txt zrm.txt cj.txt)
```
Comment (robertkirkman) [inline x11-packages/libime/build.sh:37]: There is one suggestion I would make:

If you agree it would be beneficial for future maintenance, 

there is a section of `data/CMakeLists.txt` which contains the hardcoded list of files that you copied this list from.

```cmake
set(TABLE_TXT_FILES db.txt erbi.txt qxm.txt wanfeng.txt
                      wbpy.txt wbx.txt zrm.txt cj.txt)
```

https://github.com/fcitx/libime/blob/61f8246f608f2e46d217f0562b30d9cbd355c876/data/CMakeLists.txt#L54-L55

Your patch to stub the invocations of the programs inside the `CMakeLists.txt` touches more or less every other hardcoded file operation, _except_ that it does not touch the hardcoded list of files that are passed to `libime_tabledict`.

If you want to make an explicit build failure happen if files are added to this list in a future upstream version (to make the maintainer reminded that the hardcoded list in `build.sh` must be updated manually),

you could add a comment inside the `data-CMakeLists.txt.diff` file near that list, so that a build failure is forced if upstream changes that list in a future version without making other nearby changes.

like this,


```cmake
# if this list changes, rebase this patch and modify the matching list in build.sh
set(TABLE_TXT_FILES db.txt erbi.txt qxm.txt wanfeng.txt
                      wbpy.txt wbx.txt zrm.txt cj.txt)
```

Comment (Biswa96) [reply x11-packages/libime/build.sh:37]: Thanks. I agree it would be beneficial for future maintenance.
