### PR TITLE
maxima: fix to working

### LINKED ISSUE #20206: [Bug]: Maxima spews garbage when started
### Problem description

It looks like some file broke in the Maxima package.

### What steps will reproduce the bug?

Install maxima then run the `maxima` command. 

```
$ maxima

Condition of type: SIMPLE-PROGRAM-ERROR
Wrong number of arguments passed to function #<compiled-function SI:KILLPID 0x7665722800>.
No restarts available.

Top level in: #<process TOP-LEVEL 0x7903408f00>.
> 5*2;

Debugger received error of type: UNBOUND-VARIABLE
The variable 5*2 is unbound.
Error flushed.
> quit();

Debugger received error of type: UNBOUND-VARIABLE
The variable QUIT is unbound.
Error flushed.
>
```

I need to kill Termux to close Maxima. I assume that killing it within Termux would work too if I used tmux or similiar to get a prompt to do so 

### What is the expected behavior?

On an Ubuntu installation (until recently it worked similarly in Termux):
```
$ maxima

Maxima 5.45.1 https://maxima.sourceforge.io
using Lisp GNU Common Lisp (GCL) GCL 2.6.12
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1) 5*5;
(%o1)                                 25
(%i2) quit();
$
```

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=4909
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://is.mirror.flokinet.net/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://is.mirror.flokinet.net/termux/termux-x11 x11 main
Updatable packages:
gdk-pixbuf/stable 2.42.12 aarch64 [upgradable from: 2.42.11]
termux-tools version:
1.42.1
Android version:
14
Kernel build information:
Linux localhost 5.10.189-android13-4-00012-g1217bb583cc5-ab11174560 #1 SMP PREEMPT Mon Dec 4 18:59:42 UTC 2023 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 6a
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

### PR DESCRIPTION
**Pull request by kawanakaiku**
Fixes #20206

### CODE REVIEW

File: packages/maxima/build.sh [hunk 1]
```diff
@@ -4,12 +4,12 @@ TERMUX_PKG_LICENSE="GPL-2.0"
 TERMUX_PKG_MAINTAINER="Marlin Sööse <marlin.soose@laro.se>"
 TERMUX_PKG_VERSION=()
 TERMUX_PKG_VERSION+=(5.47.0)
-TERMUX_PKG_VERSION+=(23.9.9) # ECL version
-TERMUX_PKG_REVISION=1
+TERMUX_PKG_VERSION+=(24.5.10) # ECL version
+TERMUX_PKG_REVISION=2
```
Comment (Biswa96) [inline packages/maxima/build.sh:8]:
```suggestion
```

pkg revision should be removed after version upgrade.

**Comment by licy183** [comment]
Thanks!
