### PR TITLE
fix(x11/vim-gtk): correct filename of share/man/man1/xxd.1 in $TERMUX_PKG_RM_AFTER_INSTALL

### LINKED ISSUE #22489: [Bug]: xxd.1.gz not completely removed from vim-gtk package, causing conflict with new xxd subpackage
### Problem description

After https://github.com/termux/termux-packages/pull/22420/files#diff-4816def4beb077bab4254c4637fb1cdc95ac28da7bece78df805f6576a0067d4R55 , there is now an `xxd` package, but the `vim-gtk` package conflicts with it with this error, preventing a smooth installation of `vim-gtk`: 

```
Selecting previously unselected package vim-gtk.
(Reading database ... 41754 files and directories currently installed.)
Preparing to unpack .../vim-gtk_9.1.0900_aarch64.deb ...
Unpacking vim-gtk (9.1.0900) ...
Selecting previously unselected package xxd.
Preparing to unpack .../xxd_9.1.0900_aarch64.deb ...
Unpacking xxd (9.1.0900) ...
dpkg: error processing archive /data/data/com.termux/cache/apt/archives/xxd_9.1.0900_aarch64.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/share/man/man1/xxd.1.gz', which is also in package vim-gtk 9.1.0900
Errors were encountered while processing:
 /data/data/com.termux/cache/apt/archives/xxd_9.1.0900_aarch64.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
```

In my opinion, the root cause of this problem is that files named "`/data/data/com.termux/files/usr/share/man/man1/$NAME.gz`", unfortunately, cannot be directly removed from the resulting package by just writing their full names into `$TERMUX_PKG_RM_AFTER_INSTALL`:

https://github.com/termux/termux-packages/blob/760b22ec0d857a31d5eda7f2d1abe50328ef6ce1/x11-packages/vim-gtk/build.sh#L52-L56

The reason for this phenomenon is because the file that `termux_step_make_install()` produces is not actually named with the "`.gz`"  extension at the time that `$TERMUX_PKG_RM_AFTER_INSTALL` is processed. At that time, it is still named "`xxd.1`". A few lines later, after `$TERMUX_PKG_RM_AFTER_INSTALL` is processed, the command `gzip -9 -n` converts the file into a compressed file, and renames it (`-n` argument) to `xxd.1.gz`.

https://github.com/termux/termux-packages/blob/760b22ec0d857a31d5eda7f2d1abe50328ef6ce1/scripts/build/termux_step_massage.sh#L98-L108

Therefore, the issue can hopefully be resolved by specifying the `xxd.1` filename, instead of `xxd.1.gz`, to match the name of the file as it is at the `$TERMUX_PKG_RM_AFTER_INSTALL` point of the build process. 

I don't think I would consider that the problem is that `rm -Rf $TERMUX_PKG_RM_AFTER_INSTALL` should be moved somewhere else, though, since numerous other packages are already written to avoid specifying the `.gz` extension in `$TERMUX_PKG_RM_AFTER_INSTALL`, so if this behavior were changed, all existing packages that rely on this behavior would have to be modified at the same time.

https://github.com/termux/termux-packages/blob/760b22ec0d857a31d5eda7f2d1abe50328ef6ce1/packages/weechat/build.sh#L14-L18

### What steps will reproduce the bug?
```bash
pkg install x11-repo
pkg install vim-gtk
```
### What is the expected behavior?

Successful installation of `vim-gtk` and `xxd` simultaneously without conflict

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=5078
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
firefox/x11 132.0.2-1 aarch64 [upgradable from: 132.0.2]
luanti/x11 1:5.10.0-4 aarch64 [upgradable from: 1:5.10.0-3]
termux-tools version:
1.44.5
Android version:
8.0.0
Kernel build information:
Linux localhost 3.18.71-14970140 #1 SMP PREEMPT Thu Feb 6 19:00:42 KST 2020 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G930U
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:15
```

### PR DESCRIPTION
**Pull request by robertkirkman**
Fixes #22489

### CODE REVIEW

File: x11-packages/vim-gtk/build.sh [hunk 1]
```diff
@@ -52,7 +53,7 @@ share/vim/vim91/tools
 # Avoid overlap with the `xxd` subpackage of `vim`
 TERMUX_PKG_RM_AFTER_INSTALL+="
 bin/xxd
-share/man/man1/xxd.1.gz
+share/man/man1/xxd.1
```
Comment (TomJo2000) [inline x11-packages/vim-gtk/build.sh:56]: Oh right it isn't compressed yet at that point.
Thanks for catching that.
