### PR TITLE
addpkg(main/git-extras): 7.4.0

### LINKED ISSUE #25139: [Package]: git-extras
### Why is it worth to add this package?

This adds a lot of useful git subcommands

### Home page URL

_No response_

### Source code URL

https://github.com/tj/git-extras

### Packaging policy acknowledgement

- [x] The project is actively developed.
- [x] The project has [existing packages](https://repology.org/projects) and is "well known".
- [x] Licensed under an [open source license](https://spdx.org/licenses/).
- [x] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [x] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [x] Not duplicating the functionality of existing packages.
- [x] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [x] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

Although that repo contains shell completion scripts for bash, zsh and fish, only bash is vendor autoloadable. fish and zsh requires manually sourcing them in the config file. **Btw, I didn't manually test those completion scripts, but rather read about that in the aur for git-extras**

### PR DESCRIPTION
**Pull request by Juhan280**
Closes #25139

### CODE REVIEW

File: packages/git-extras/build.sh [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+TERMUX_PKG_SHA256=aaab3bab18709ec6825a875961e18a00e0c7d8214c39d6e3a63aeb99fa11c56e
+TERMUX_PKG_DEPENDS="bash, git, util-linux, gawk, findutils, ncurses-utils"
+TERMUX_PKG_RECOMENDS="curl, procps, rsync"
+TERMUX_PKG_AUTO_UPDATE=true
+TERMUX_PKG_BUILD_IN_SRC=true
+
+termux_step_make() {
+	# `make` and `make install` does the same thing
+	# So, this is an empty function
+	:
```
Comment (robertkirkman) [inline packages/git-extras/build.sh:21]: This looks pretty good! But, I was wondering, does any measurable error or problem happen if `termux_step_make()` is just removed here, or could this function be removed completely instead of being defined and just empty?

Comment (Juhan280) [reply packages/git-extras/build.sh:21]: If `termux_step_make()` is not overriden, there is no error. It just installs twice, once in `termux_step_make` and another time in `termux_step_make_install` (i think)

Comment (robertkirkman) [reply packages/git-extras/build.sh:21]: Would you be able to double check that to, for example, confirm that if you changed `termux_step_make() { : }` here to `termux_step_make_install() { : }`, it would do the same thing?

Comment (Juhan280) [reply packages/git-extras/build.sh:21]: here is the build https://github.com/Juhan280/termux-packages/actions/runs/16648608261

(idk why it also included apr and apr-static in the build)

Comment (robertkirkman) [reply packages/git-extras/build.sh:21]: Thank you very much for checking, I was so shocked that I had to quickly also check in GNU/Linux, I can confirm that even in GNU/Linux, `make` with no arguments causes it to attempt to install,

image


I've never seen any software ever do that before, so this is a first for me. Thank you for paying attention to that!

> (idk why it also included apr and apr-static in the build)

Don't worry about this, it is harmless and It happens because I merged a PR related to `apr` after you opened this PR, but you haven't rebased your branch to match the `master` branch of termux-packages yet. It's not usually necessary to rebase and force push PRs that are less than a few days old, but you could if you want to.

**Review by robertkirkman — APPROVED** [review]
I think it's good, but I'm not very familiar with git-extras, so it might be good for the maintainer of the `git` package, Tomjo2000, to also review this PR.

File: packages/git-extras/build.sh [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+	install -Dm644 etc/git-extras.fish "$TERMUX_PREFIX"/share/git-extras/completion.fish
+}
+
+termux_step_create_debscripts() {
+	(
+		echo "echo \"If you are a zsh user, you may want to 'source ${TERMUX_PREFIX}/share/git-extras/completion.zsh'\" \\"
+		echo "	\"and put this line into ~/.zshrc to enable zsh completion\""
+		echo "echo \"If you are a fish user, you may want to copy or link '${TERMUX_PREFIX}/share/git-extras/completion.fish'\" \\"
+		echo "	\"to '~/.config/fish/completions/'\""
+	) >./postinst
```
Comment (TomJo2000) [inline packages/git-extras/build.sh]: This should be a brace group.
```suggestion
	{
		echo "echo \"If you are a zsh user, you may want to 'source ${TERMUX_PREFIX}/share/git-extras/completion.zsh'\" \\"
		echo "	\"and put this line into ~/.zshrc to enable zsh completion\""
		echo "echo \"If you are a fish user, you may want to copy or link '${TERMUX_PREFIX}/share/git-extras/completion.fish'\" \\"
		echo "	\"to '~/.config/fish/completions/'\""
	} > ./postinst
```

File: packages/git-extras/build.sh [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+
+termux_step_make() {
+	# `make` and `make install` does the same thing
+	# So, this is an empty function
+	:
+}
+
+termux_step_post_make_install() {
+	install -Dm644 etc/git-extras-completion.zsh "$TERMUX_PREFIX"/share/git-extras/completion.zsh
+	install -Dm644 etc/git-extras.fish "$TERMUX_PREFIX"/share/git-extras/completion.fish
```
Comment (TomJo2000) [inline packages/git-extras/build.sh:26]: It would be nice if we could dentangle these to just install them into the normal completions directories.

Also what about the Bash completions?
https://github.com/tj/git-extras/blob/main/etc/bash_completion.sh

File: packages/git-extras/build.sh [hunk 4]
```diff
@@ -0,0 +1,31 @@
+TERMUX_PKG_HOMEPAGE="https://github.com/tj/git-extras"
+TERMUX_PKG_DESCRIPTION="Little git extras."
+TERMUX_PKG_LICENSE="MIT"
+TERMUX_PKG_MAINTAINER="@termux"
+TERMUX_PKG_VERSION="7.4.0"
+TERMUX_PKG_SRCURL=https://github.com/tj/git-extras/archive/${TERMUX_PKG_VERSION}.tar.gz
+TERMUX_PKG_SHA256=aaab3bab18709ec6825a875961e18a00e0c7d8214c39d6e3a63aeb99fa11c56e
+TERMUX_PKG_DEPENDS="bash, git, util-linux, gawk, findutils, ncurses-utils"
+TERMUX_PKG_RECOMENDS="curl, procps, rsync"
```
Comment (TomJo2000) [inline packages/git-extras/build.sh:9]: `TERMUX_PKG_RECOMENDS` packages are installed alongside the package are they attached to by default.
<sup>https://github.com/termux/termux-packages/wiki/Creating-new-package#package-build-script-variables:~:text=TERMUX_PKG_RECOMMENDS</sup>

Is that what we want here?
Otherwise this should be `TERMUX_PKG_SUGGESTS`.

File: packages/git-extras/build.sh (hunk 3 above)
Comment (Juhan280) [reply packages/git-extras/build.sh:26]: Here is the explanation for why zsh is not autoloaded into the completion directories.
https://github.com/tj/git-extras/issues/376#issuecomment-554700223

As for fish, i don't use `fish` myself, and since this is what upstream suggest, I assumed the same case as `zsh`.

And for bash, the `make` command actually automatically puts it in the file system. But since you mentioned it, I realized it is maybe putting the file at the wrong location (`/data/data/com.termux/files/usr/etc/bash-completion/completions/git-extras`). It should be at `/data/data/com.termux/files/usr/share/bash-completion/completions/git-extras`. ~But when I tried to test it, I realized none of my bash completion is working (idk maybe I broke something)~(i had to install `bash-completion` package). I tested it, it works

File: packages/git-extras/build.sh (hunk 4 above)
Comment (Juhan280) [reply packages/git-extras/build.sh:9]: Some of the git-extras commands needs these dependencies to work (https://github.com/tj/git-extras/blob/main/Installation.md#dependencies). But rest will work without them. Maybe it should be `SUGGESTS` instead of `RECOMMENDS`. Should I switch?

Comment (TomJo2000) [reply packages/git-extras/build.sh:9]: If they're required, shouldn't they be in `TERMUX_PKG_DEPENDS`?

File: packages/git-extras/build.sh (hunk 3 above)
Comment (TomJo2000) [reply packages/git-extras/build.sh:26]: Okay so it's just a non-standard completions script.

File: packages/git-extras/build.sh (hunk 4 above)
Comment (Juhan280) [reply packages/git-extras/build.sh:9]: They are required only for a few commands. Rest of th ecommands don't need them. So if the user is not trying to use those commands, its optional for them.

Comment (TomJo2000) [reply packages/git-extras/build.sh:9]: `RECOMMENDS` is probably fine then.
Don't wanna break parts of the package out of the box, but those aren't hard dependencies so users can remove them if they want to.

Comment (Juhan280) [reply packages/git-extras/build.sh:9]: Ok sure

**Comment by robertkirkman** [comment]
Is this ready now? I think that if all of the problems TomJo2000 pointed out have been fixed, this will be ready.

**Comment by Juhan280** [comment]
I do believe its ready

**Comment by TomJo2000** [comment]
I thought I'd already merged this.
