### PR TITLE
libvpx: add ABI version check

### LINKED ISSUE #22153: [Bug]: ffmpeg Failed to initialize encoder: ABI version mismatch
### Problem description

ffmpeg trying to use libvpx-vp9 as encoder fails and exits with error message `Failed to initialize encoder: ABI version mismatch`

I don't know what package upgrade caused this, but it's definitely been working sometime ago.

### What steps will reproduce the bug?

I tried to encode a h264+aac .mp4 file into a vp9+opus .webm file using the command `ffmpeg -loglevel warning -i "$argv[1]" -c:a libopus -c:v vp9 "$outputFilename"`. Replace `-i …` and `"$outputFilename"` as necessary.

### What is the expected behavior?

_No response_

### System information

```shell
Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.50.1+cff225e
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~idSD6SejITJynQCUAo4zUg==/com.termux-6geDixRU7wdXVh1Z7f-JLQ==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=5064
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c133,c257,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c133,c257,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10389
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+062c977
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+062c977
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.bouwhuis.network/termux/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.44.3
Android version:
14
Kernel build information:
Linux localhost 5.10.198-android12-9-29544049-abS908BXXSCEXI4 #1 SMP PREEMPT Fri Sep 27 15:39:58 KST 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-S908B
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
```

### PR DESCRIPTION
**Pull request by licy183**
Closes #22153

### CODE REVIEW

File: packages/libvpx/build.sh [hunk 1]
```diff
@@ -24,6 +25,25 @@ termux_pkg_auto_update() {
...
+	# Should revbump ffmpeg if ABI is changed
+	local abi=9
+	local encabi=36
+	local decabi=12
+
+	mkdir -p termux-abi-test && cd termux-abi-test
+	gcc "$TERMUX_PKG_BUILDER_DIR"/abi-test.c -o abi-test -I../
+	local abi_got="$(./abi-test | cut -d' ' -f 1)"
+	local eabi_got="$(./abi-test | cut -d' ' -f 2)"
+	local dabi_got="$(./abi-test | cut -d' ' -f 3)"
```
Comment (TomJo2000) [inline packages/libvpx/build.sh:39]:
```suggestion
	local abi_got eabi_gotdabi_got
	IFS=' ' read -r abi_got eabi_got dabi_got < <(./abi-test)
```

**Review by TomJo2000 — APPROVED** [review]
