### PR TITLE
fix(main/lastpass-cli): Fix directory for temporary file

### LINKED ISSUE #27811: [Bug]: lastpass binary doesn't work
### Problem description

Lastpass-cli (`lpass` binary) doesn't work interactively or noninteractively

### What steps will reproduce the bug?

1. `lpass login username` (sign in) 
2. `lpass add identifier` (errors `Error: No such file or directory: mkdtemp`, looks like an shmem issue)
3. `lpass add identifier --non-interactive` (hangs)

### What is the expected behavior?

2 - should add the new entry interactively
3 - should open $EDITOR to fill out fields

### System information

```shell
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__APK_FILE=/data/app/~~s_E0IalINEEhC7jNaMX1DQ==/com.termux-qiTYbYV5EMzpuhbn5F_dYA==/base.apk
TERMUX_APP__APK_RELEASE=F_DROID
TERMUX_APP__APP_VERSION_CODE=1022
TERMUX_APP__APP_VERSION_NAME=0.119.0-beta.3
TERMUX_APP__DATA_DIR=/data/user/0/com.termux
TERMUX_APP__IS_DEBUGGABLE_BUILD=false
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__LEGACY_DATA_DIR=/data/data/com.termux
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PID=25027
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c149,c261,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__TARGET_SDK=28
TERMUX_VERSION=0.119.0-beta.3
TERMUX__APPS_DIR=/data/user/0/com.termux/termux/apps
TERMUX__HOME=/data/data/com.termux/files/home
TERMUX__PREFIX=/data/data/com.termux/files/usr
TERMUX__ROOTFS_DIR=/data/data/com.termux/files
TERMUX__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c149,c261,c512,c768
TERMUX__UID=11429
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.quantum5.ca/termux/termux-main stable main
# dichvucoder-repo (sources.list.d/dichvucoder.list)
deb https://repo.dgbaodev.com dvc-packages dvc
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# glibc-repo (sources.list.d/glibc.list)
deb https://packages-cf.termux.dev/apt/termux-glibc/ glibc stable
# sources.list.d/efreak.list
deb https://raw.rawgit.net/Efreak/my-termux-repo/main/ termux extras
# x11-repo (sources.list.d/x11.list)
deb https://mirror.quantum5.ca/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.45.0
Android version:
12
Kernel build information:
Linux localhost 4.14.190-26178195-abT860XXS5DWH1 #2 SMP PREEMPT Thu Aug 3 15:32:09 +07 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T860
Supported ABIs:
SUPPORTED_ABIS: arm64-v8a,armeabi-v7a,armeabi
SUPPORTED_32_BIT_ABIS: armeabi-v7a,armeabi
SUPPORTED_64_BIT_ABIS: arm64-v8a
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec-ld-preload.so
Installed termux plugins:
com.termux.api versionCode:1002
com.termux.nix versionCode:188037
com.termux.x11 versionCode:14
com.termux.styling versionCode:1000
com.termux.widget versionCode:1001
```

### PR DESCRIPTION
**Pull request by Biswa96**
* Fixes #27811

### CODE REVIEW

File: packages/lastpass-cli/edit.c.patch [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+ {
+ 	return xstrdup("/dev/shm");
+@@ -108,7 +108,7 @@ static char *shared_memory_dir(void)
+ 	char *tmpdir = getenv("SECURE_TMPDIR");
+ 	if (!tmpdir) {
+ 		if (!(tmpdir = getenv("TMPDIR")))
+-			tmpdir = "/tmp";
++			tmpdir = "@TERMUX_PREFIX@/tmp";
+ 
+ 		fprintf(stderr,
```
Comment (robertkirkman) [inline packages/lastpass-cli/edit.c.patch]: Should the warning be suppressed by default in Termux, since the Termux `tmp` folder is not accessible to other Android apps (and also there is no other place to have a temporary folder in Termux)?

Is it an annoying warning, or does not not appear too often?

Comment (Biswa96) [reply packages/lastpass-cli/edit.c.patch]: Done.

**Review by robertkirkman — APPROVED** [review]
