### PR TITLE
usql: bump to 0.19.4

### LINKED ISSUE #21924: Auto update failing for usql
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [usql](https://github.com/termux/termux-packages/blob/53bb4bfcd8740365eba710be106295c1b3b20c02/packages/usql) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="console">
INFO: Updating usql [Current version: 0.19.3]
INFO: package being updated to 0.19.4.
Downloading https://github.com/xo/usql/archive/v0.19.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  349k    0  349k    0     0  1233k      0 --:--:-- --:--:-- --:--:-- 1233k

You are about to commit these changes:

--------------------
diff --git a/packages/usql/build.sh b/packages/usql/build.sh
index ff4e5c0966..e6b29e80f0 100644
--- a/packages/usql/build.sh
+++ b/packages/usql/build.sh
@@ -2,9 +2,9 @@ TERMUX_PKG_HOMEPAGE=https://github.com/xo/usql
 TERMUX_PKG_DESCRIPTION="A universal command-line interface for SQL databases"
 TERMUX_PKG_LICENSE="MIT"
 TERMUX_PKG_MAINTAINER="@flipee"
-TERMUX_PKG_VERSION="0.19.3"
+TERMUX_PKG_VERSION="0.19.4"
 TERMUX_PKG_SRCURL=https://github.com/xo/usql/archive/v$TERMUX_PKG_VERSION.tar.gz
-TERMUX_PKG_SHA256=3955e13c7108cb4a3ebb968dafa501db72d4f4fa0ddf6fb128cceb84e5a3d4c4
+TERMUX_PKG_SHA256=61aff0f9448ca9d90894bdf99276186f87b5a91ab196ff45133f34c61475b717
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_BUILD_IN_SRC=true
 
--------------------

bump(main/usql): 0.19.4

Not committing to Git!

INFO: Trying to build package.
INFO: Package usql exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building usql for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0  16754      0 --:--:-- --:--:-- --:--:-- 16752
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   5024      0 --:--:-- --:--:-- --:--:--  5048
gpg: Signature made Mon 21 Oct 2024 06:15:37 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  79044      0 --:--:-- --:--:-- --:--:-- 79285
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   4602      0 --:--:-- --:--:-- --:--:--  4627
gpg: Signature made Mon 14 Oct 2024 11:50:11 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  76410      0 --:--:-- --:--:-- --:--:-- 76725
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1014      0 --:--:-- --:--:-- --:--:--  1013
100   833  100   833    0     0   1014      0 --:--:-- --:--:-- --:--:--  1013
gpg: Signature made Mon 21 Oct 2024 12:32:39 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://github.com/xo/usql/archive/v0.19.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  349k    0  349k    0     0  1401k      0 --:--:-- --:--:-- --:--:-- 1401k
go: warning: ignoring go.mod in $GOPATH /home/builder/.termux-build/usql/src
go: downloading github.com/go-git/go-billy/v5 v5.5.0
go: downloading github.com/mattn/go-isatty v0.0.20
go: downloading github.com/spf13/cobra v1.8.1
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/spf13/viper v1.19.0
go: downloading github.com/xo/dburl v0.23.2
go: downloading golang.org/x/sys v0.26.0
go: downloading github.com/cyphar/filepath-securejoin v0.2.4
go: downloading github.com/jeandeaual/go-locale v0.0.0-20240223122105-ce5225dcaa49
go: downloading github.com/kenshaw/rasterm v0.1.11
go: downloading github.com/xo/terminfo v0.0.0-20220910002029-abceb7e1c41e
go: downloading github.com/yookoala/realpath v1.0.0
go: downloading github.com/alecthomas/chroma/v2 v2.14.0
go: downloading github.com/xo/echartsgoja v0.1.1
go: downloading github.com/xo/resvg v0.6.0
go: downloading github.com/xo/tblfmt v0.13.2
go: downloading github.com/gohxs/readline v0.0.0-20171011095936-a780388e6e7c
go: downloading golang.org/x/exp v0.0.0-20241009180824-f66d83c29e7c
go: downloading github.com/fsnotify/fsnotify v1.7.0
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/sagikazarmark/slog-shim v0.1.0
go: downloading github.com/spf13/afero v1.11.0
go: downloading github.com/spf13/cast v1.7.0
go: downloading github.com/dlclark/regexp2 v1.11.4
go: downloading github.com/mattn/go-sixel v0.0.5
go: downloading golang.org/x/term v0.25.0
go: downloading github.com/kenshaw/colors v0.1.6
go: downloading github.com/mattn/go-runewidth v0.0.16
go: downloading github.com/nathan-fiscaletti/consolesize-go v0.0.0-20220204101620-317176b6684d
go: downloading golang.org/x/text v0.19.0
go: downloading github.com/uber/athenadriver v1.1.15
go: downloading github.com/apache/calcite-avatica-go/v5 v5.3.0
go: downloading gorm.io/driver/bigquery v1.2.0
go: downloading github.com/MichaelS11/go-cql-driver v0.1.1
go: downloading github.com/gocql/gocql v1.7.0
go: downloading github.com/chaisql/chai v0.16.1-0.20240218103834-23e406360fd2
go: downloading github.com/ClickHouse/clickhouse-go/v2 v2.30.0
go: downloading github.com/btnguyen2k/gocosmos v1.1.0
go: downloading github.com/couchbase/go_n1ql v0.0.0-20220303011133-0ed4bf93e31d
go: downloading github.com/mithrandie/csvq-driver v1.7.0
go: downloading github.com/mithrandie/csvq v1.18.1
go: downloading github.com/datafuselabs/databend-go v0.7.1
go: downloading github.com/databricks/databricks-sql-go v1.6.1
go: downloading github.com/btnguyen2k/godynamo v1.3.0
go: downloading github.com/exasol/exasol-driver-go v1.0.10
go: downloading github.com/nakagami/firebirdsql v0.9.11
go: downloading github.com/apache/arrow/go/v17 v17.0.0
go: downloading github.com/jmrobles/h2go v0.5.0
go: downloading sqlflow.org/gohive v0.0.0-20240730014249-8960223660e2
go: downloading github.com/amsokol/ignite-go-client v0.12.2
go: downloading sqlflow.org/gomaxcompute v0.0.0-20210805062559-c14ae028b44c
go: downloading modernc.org/sqlite v1.33.1
go: downloading github.com/ziutek/mymysql v1.5.4
go: downloading github.com/IBM/nzgo/v12 v12.0.9
go: downloading github.com/go-sql-driver/mysql v1.8.1
go: downloading github.com/sijms/go-ora/v2 v2.8.22
go: downloading github.com/aliyun/aliyun-tablestore-go-sql-driver v0.0.0-20220418015234-4d337cb3eed9
go: downloading github.com/jackc/pgx/v5 v5.7.1
go: downloading github.com/lib/pq v1.10.9
go: downloading github.com/proullon/ramsql v0.1.4
go: downloading github.com/prestodb/presto-go-client v0.0.0-20240426182841-905ac40a1783
go: downloading modernc.org/ql v1.4.7
go: downloading github.com/thda/tds v0.1.7
go: downloading github.com/SAP/go-hdb v1.12.4
go: downloading github.com/googleapis/go-sql-spanner v1.7.4
go: downloading github.com/mattn/go-sqlite3 v1.14.24
go: downloading github.com/microsoft/go-mssqldb v1.7.2
go: downloading github.com/trinodb/trino-go-client v0.319.0
go: downloading github.com/vertica/vertica-sql-go v1.3.3
go: downloading github.com/VoltDB/voltdb-client-go v1.0.16
go: downloading github.com/ydb-platform/ydb-go-sdk/v3 v3.84.1
go: downloading github.com/dop251/goja v0.0.0-20241009100908-5f46f2705ca3
go: downloading github.com/dop251/goja_nodejs v0.0.0-20240728170619-29b559befffc
go: downloading github.com/subosito/gotenv v1.6.0
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/magiconair/properties v1.8.7
go: downloading github.com/pelletier/go-toml/v2 v2.2.3
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/soniakeys/quant v1.0.0
go: downloading github.com/rivo/uniseg v0.4.7
go: downloading github.com/kenshaw/snaker v0.3.0
go: downloading github.com/DATA-DOG/go-sqlmock v1.5.2
go: downloading github.com/aws/aws-sdk-go v1.55.5
go: downloading github.com/jedib0t/go-pretty/v6 v6.6.1
go: downloading github.com/uber-go/tally v3.5.10+incompatible
go: downloading github.com/xwb1989/sqlparser v0.0.0-20180606152119-120387863bf2
go: downloading go.uber.org/zap v1.27.0
go: downloading github.com/hashicorp/go-uuid v1.0.3
go: downloading github.com/icholy/digest v0.1.23
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.4
go: downloading google.golang.org/protobuf v1.35.1
go: downloading cloud.google.com/go/bigquery v1.63.1
go: downloading github.com/sirupsen/logrus v1.9.3
go: downloading google.golang.org/api v0.201.0
go: downloading cloud.google.com/go v0.116.0
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/hailocab/go-hostpool v0.0.0-20160125115350-e80d13ce29ed
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/ClickHouse/ch-go v0.63.0
go: downloading github.com/andybalholm/brotli v1.1.1
go: downloading github.com/pkg/errors v0.9.1
go: downloading go.opentelemetry.io/otel/trace v1.31.0
go: downloading go.opentelemetry.io/otel v1.31.0
go: downloading github.com/btnguyen2k/consu/checksum v1.1.1
go: downloading github.com/btnguyen2k/consu/g18 v0.1.0
go: downloading github.com/btnguyen2k/consu/gjrc v0.2.2
go: downloading github.com/btnguyen2k/consu/olaf v0.1.3
go: downloading github.com/btnguyen2k/consu/reddo v0.1.9
go: downloading github.com/btnguyen2k/consu/semita v0.1.5
go: downloading github.com/mithrandie/ternary v1.1.1
go: downloading github.com/cockroachdb/errors v1.11.3
go: downloading github.com/couchbase/go-couchbase v0.1.1
go: downloading github.com/BurntSushi/toml v1.4.0
go: downloading github.com/avast/retry-go v3.0.0+incompatible
go: downloading github.com/google/uuid v1.6.0
go: downloading go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.56.0
go: downloading github.com/apache/thrift v0.21.0
go: downloading github.com/aws/aws-sdk-go-v2 v1.32.2
go: downloading github.com/aws/aws-sdk-go-v2/credentials v1.17.41
go: downloading github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue v1.15.12
go: downloading github.com/aws/aws-sdk-go-v2/service/dynamodb v1.36.2
go: downloading github.com/aws/smithy-go v1.22.0
go: downloading github.com/mithrandie/go-text v1.6.0
go: downloading golang.org/x/crypto v0.28.0
go: downloading github.com/kardianos/osext v0.0.0-20190222173326-2bc1f35cddc0
go: downloading github.com/shopspring/decimal v1.4.0
go: downloading gitlab.com/nyarla/go-crypt v0.0.0-20160106005555-d9a5dc2b789b
go: downloading modernc.org/mathutil v1.6.0
go: downloading github.com/beltran/gohive v1.7.0
go: downloading github.com/Masterminds/semver v1.5.0
go: downloading filippo.io/edwards25519 v1.1.0
go: downloading google.golang.org/grpc v1.67.1
go: downloading github.com/golang-jwt/jwt/v5 v5.2.1
go: downloading github.com/aliyun/aliyun-tablestore-go-sdk v1.7.17
go: downloading github.com/jackc/pgpassfile v1.0.0
go: downloading github.com/jackc/pgservicefile v0.0.0-20240606120523-5a60cdf6a761
go: downloading modernc.org/b v1.1.0
go: downloading modernc.org/db v1.0.10
go: downloading modernc.org/file v1.0.8
go: downloading modernc.org/golex v1.1.0
go: downloading modernc.org/internal v1.1.0
go: downloading modernc.org/lldb v1.0.8
go: downloading modernc.org/strutil v1.2.0
go: downloading gopkg.in/jcmturner/gokrb5.v6 v6.1.1
go: downloading cloud.google.com/go/spanner v1.70.0
go: downloading google.golang.org/genproto v0.0.0-20241015192408-796eee8c2d53
go: downloading golang.org/x/net v0.30.0
go: downloading github.com/Azure/azure-sdk-for-go/sdk/azcore v1.16.0
go: downloading github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.8.0
go: downloading github.com/golang-sql/civil v0.0.0-20220223132316-b832511892a9
go: downloading github.com/golang-sql/sqlexp v0.1.0
go: downloading github.com/google/pprof v0.0.0-20241017200806-017d972448fc
go: downloading github.com/go-sourcemap/sourcemap v2.1.4+incompatible
go: downloading github.com/ydb-platform/ydb-go-genproto v0.0.0-20241002120727-5acc94bcb119
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading modernc.org/libc v1.61.0
go: downloading github.com/golang/mock v1.6.0
go: downloading go.uber.org/atomic v1.11.0
go: downloading go.uber.org/multierr v1.11.0
go: downloading github.com/jcmturner/dnsutils/v2 v2.0.0
go: downloading github.com/jcmturner/gofork v1.7.6
go: downloading github.com/jcmturner/goidentity/v6 v6.0.1
go: downloading cloud.google.com/go/iam v1.2.1
go: downloading github.com/apache/arrow/go/v15 v15.0.2
go: downloading github.com/googleapis/gax-go/v2 v2.13.0
go: downloading golang.org/x/sync v0.8.0
go: downloading github.com/go-faster/city v1.0.1
go: downloading github.com/go-faster/errors v0.7.1
go: downloading github.com/klauspost/compress v1.17.11
go: downloading github.com/pierrec/lz4/v4 v4.1.21
go: downloading github.com/paulmach/orb v0.11.1
go: downloading github.com/segmentio/asm v1.2.0
go: downloading github.com/mithrandie/go-file/v2 v2.1.0
go: downloading github.com/buger/jsonparser v1.1.1
go: downloading github.com/golang-module/carbon/v2 v2.4.1
go: downloading github.com/cockroachdb/logtags v0.0.0-20230118201751-21c54148d20b
go: downloading github.com/cockroachdb/redact v1.1.5
go: downloading github.com/getsentry/sentry-go v0.29.1
go: downloading github.com/couchbase/gomemcached v0.3.2
go: downloading github.com/couchbase/goutils v0.1.2
go: downloading github.com/felixge/httpsnoop v1.0.4
go: downloading go.opentelemetry.io/otel/metric v1.31.0
go: downloading github.com/rs/zerolog v1.33.0
go: downloading golang.org/x/oauth2 v0.23.0
go: downloading github.com/hashicorp/go-retryablehttp v0.7.7
go: downloading github.com/gorilla/websocket v1.5.3
go: downloading github.com/aws/aws-sdk-go-v2/service/dynamodbstreams v1.24.2
go: downloading github.com/aws/aws-sdk-go-v2/internal/configsources v1.3.21
go: downloading github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.12.0
go: downloading github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery v1.10.2
go: downloading github.com/jmespath/go-jmespath v0.4.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/remyoudompheng/bigfft v0.0.0-20230129092748-24d4a6f8daec
go: downloading golang.org/x/xerrors v0.0.0-20240903120638-7835f813f4da
go: downloading github.com/beltran/gosasl v0.0.0-20241020113154-d984219623d1
go: downloading github.com/go-zookeeper/zk v1.0.4
go: downloading github.com/jackc/puddle/v2 v2.2.2
go: downloading modernc.org/fileutil v1.3.0
go: downloading modernc.org/sortutil v1.2.0
go: downloading modernc.org/zappy v1.1.0
go: downloading github.com/golang/protobuf v1.5.4
go: downloading github.com/google/flatbuffers/go v0.0.0-20230110200425-62e4d2e5b215
go: downloading github.com/hashicorp/golang-lru v1.0.2
go: downloading cloud.google.com/go/auth v0.9.8
go: downloading cloud.google.com/go/monitoring v1.21.1
go: downloading github.com/GoogleCloudPlatform/grpc-gcp-go/grpcgcp v1.5.1
go: downloading go.opencensus.io v0.24.0
go: downloading go.opentelemetry.io/contrib/detectors/gcp v1.31.0
go: downloading go.opentelemetry.io/otel/sdk/metric v1.31.0
go: downloading google.golang.org/genproto/googleapis/api v0.0.0-20241015192408-796eee8c2d53
go: downloading go.opentelemetry.io/otel/sdk v1.31.0
go: downloading google.golang.org/genproto/googleapis/rpc v0.0.0-20241015192408-796eee8c2d53
go: downloading cloud.google.com/go/longrunning v0.6.1
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading github.com/Azure/azure-sdk-for-go/sdk/internal v1.10.0
go: downloading github.com/AzureAD/microsoft-authentication-library-for-go v1.2.2
go: downloading github.com/elastic/go-sysinfo v1.14.2
go: downloading github.com/golang-jwt/jwt/v4 v4.5.0
go: downloading github.com/jonboulle/clockwork v0.4.0
go: downloading github.com/twmb/murmur3 v1.1.8
go: downloading github.com/dustin/go-humanize v1.0.1
go: downloading modernc.org/memory v1.8.0
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/kr/pretty v0.3.1
go: downloading github.com/go-logr/logr v1.4.2
go: downloading github.com/coreos/go-oidc/v3 v3.11.0
go: downloading github.com/hashicorp/go-cleanhttp v0.5.2
go: downloading github.com/pkg/browser v0.0.0-20240102092130-5ac0b6a4141c
go: downloading github.com/apache/arrow/go/v12 v12.0.1
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/stretchr/testify v1.9.0
go: downloading github.com/exasol/error-reporting-go v0.2.0
go: downloading github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.6.21
go: downloading github.com/goccy/go-json v0.10.3
go: downloading github.com/zeebo/xxh3 v1.0.2
go: downloading github.com/edsrzf/mmap-go v1.2.0
go: downloading cloud.google.com/go/compute/metadata v0.5.2
go: downloading cloud.google.com/go/auth/oauth2adapt v0.2.4
go: downloading github.com/google/s2a-go v0.1.8
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading github.com/GoogleCloudPlatform/opentelemetry-operations-go/detectors/gcp v1.24.3
go: downloading go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.56.0
go: downloading golang.org/x/time v0.7.0
go: downloading github.com/kylelemons/godebug v1.1.0
go: downloading github.com/jcmturner/aescts/v2 v2.0.0
go: downloading github.com/jcmturner/rpc/v2 v2.0.3
go: downloading github.com/cockroachdb/pebble v1.1.2
go: downloading github.com/kr/text v0.2.0
go: downloading github.com/rogpeppe/go-internal v1.13.1
go: downloading github.com/go-logr/stdr v1.2.2
go: downloading github.com/go-jose/go-jose/v4 v4.0.4
go: downloading github.com/davecgh/go-spew v1.1.2-0.20180830191138-d8f796af33cc
go: downloading github.com/pmezard/go-difflib v1.0.1-0.20181226105442-5d4384ee4fb2
go: downloading github.com/stretchr/objx v0.5.2
go: downloading github.com/googleapis/enterprise-certificate-proxy v0.3.4
go: downloading github.com/envoyproxy/go-control-plane v0.13.1
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
go: downloading howett.net/plist v1.0.1
go: downloading github.com/prometheus/procfs v0.15.1
go: downloading github.com/cockroachdb/fifo v0.0.0-20240816210425-c5d0cb0b6fc0
go: downloading github.com/cockroachdb/tokenbucket v0.0.0-20230807174530-cc333fc44b06
go: downloading github.com/prometheus/client_golang v1.20.5
go: downloading github.com/cespare/xxhash/v2 v2.3.0
go: downloading github.com/cncf/xds/go v0.0.0-20240905190251-b4127c9b8d78
go: downloading github.com/DataDog/zstd v1.5.6
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/prometheus/common v0.60.0
go: downloading github.com/prometheus/client_model v0.6.1
go: downloading github.com/envoyproxy/protoc-gen-validate v1.1.0
go: downloading cel.dev/expr v0.16.2
go: downloading github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822
go: downloading github.com/census-instrumentation/opencensus-proto v0.4.1
# github.com/xo/usql
/home/builder/.termux-build/_cache/go1.23.2-r1/pkg/tool/linux_amd64/link: running aarch64-linux-android-clang failed: exit status 1
/home/builder/.termux-build/_cache/android-r27b-api-24-v1/bin/aarch64-linux-android-clang -Wl,-z,relro -pie -o $WORK/b001/exe/a.out -Wl,--export-dynamic-symbol=_cgo_panic -Wl,--export-dynamic-symbol=_cgo_topofstack -Wl,--export-dynamic-symbol=authorizerTrampoline -Wl,--export-dynamic-symbol=callbackTrampoline -Wl,--export-dynamic-symbol=commitHookTrampoline -Wl,--export-dynamic-symbol=compareTrampoline -Wl,--export-dynamic-symbol=crosscall2 -Wl,--export-dynamic-symbol=doneTrampoline -Wl,--export-dynamic-symbol=main.main -Wl,--export-dynamic-symbol=preUpdateHookTrampoline -Wl,--export-dynamic-symbol=rollbackHookTrampoline -Wl,--export-dynamic-symbol=stepTrampoline -Wl,--export-dynamic-symbol=updateHookTrampoline -Qunused-arguments -Wl,--compress-debug-sections=zlib /tmp/go-link-1680568823/go.o /tmp/go-link-1680568823/000000.o /tmp/go-link-1680568823/000001.o /tmp/go-link-1680568823/000002.o /tmp/go-link-1680568823/000003.o /tmp/go-link-1680568823/000004.o /tmp/go-link-1680568823/000005.o /tmp/go-link-1680568823/000006.o /tmp/go-link-1680568823/000007.o /tmp/go-link-1680568823/000008.o /tmp/go-link-1680568823/000009.o /tmp/go-link-1680568823/000010.o /tmp/go-link-1680568823/000011.o /tmp/go-link-1680568823/000012.o /tmp/go-link-1680568823/000013.o /tmp/go-link-1680568823/000014.o /tmp/go-link-1680568823/000015.o /tmp/go-link-1680568823/000016.o /tmp/go-link-1680568823/000017.o /tmp/go-link-1680568823/000018.o /tmp/go-link-1680568823/000019.o /tmp/go-link-1680568823/000020.o /tmp/go-link-1680568823/000021.o /tmp/go-link-1680568823/000022.o /tmp/go-link-1680568823/000023.o /tmp/go-link-1680568823/000024.o /tmp/go-link-1680568823/000025.o /tmp/go-link-1680568823/000026.o /tmp/go-link-1680568823/000027.o /tmp/go-link-1680568823/000028.o /tmp/go-link-1680568823/000029.o /tmp/go-link-1680568823/000030.o /tmp/go-link-1680568823/000031.o /tmp/go-link-1680568823/000032.o /tmp/go-link-1680568823/000033.o /tmp/go-link-1680568823/000034.o /tmp/go-link-1680568823/000035.o /tmp/go-link-1680568823/000036.o /tmp/go-link-1680568823/000037.o /tmp/go-link-1680568823/000038.o /tmp/go-link-1680568823/000039.o /tmp/go-link-1680568823/000040.o /tmp/go-link-1680568823/000041.o /tmp/go-link-1680568823/000042.o /tmp/go-link-1680568823/000043.o /tmp/go-link-1680568823/000044.o /tmp/go-link-1680568823/000045.o /tmp/go-link-1680568823/000046.o /tmp/go-link-1680568823/000047.o /tmp/go-link-1680568823/000048.o /tmp/go-link-1680568823/000049.o /tmp/go-link-1680568823/000050.o /tmp/go-link-1680568823/000051.o /tmp/go-link-1680568823/000052.o /tmp/go-link-1680568823/000053.o /tmp/go-link-1680568823/000054.o /tmp/go-link-1680568823/000055.o /tmp/go-link-1680568823/000056.o /tmp/go-link-1680568823/000057.o /tmp/go-link-1680568823/000058.o /tmp/go-link-1680568823/000059.o /tmp/go-link-1680568823/000060.o /tmp/go-link-1680568823/000061.o /tmp/go-link-1680568823/000062.o /tmp/go-link-1680568823/000063.o /tmp/go-link-1680568823/000064.o /tmp/go-link-1680568823/000065.o /tmp/go-link-1680568823/000066.o /tmp/go-link-1680568823/000067.o /tmp/go-link-1680568823/000068.o /tmp/go-link-1680568823/000069.o /tmp/go-link-1680568823/000070.o /tmp/go-link-1680568823/000071.o /tmp/go-link-1680568823/000072.o /tmp/go-link-1680568823/000073.o /tmp/go-link-1680568823/000074.o /tmp/go-link-1680568823/000075.o /tmp/go-link-1680568823/000076.o /tmp/go-link-1680568823/000077.o /tmp/go-link-1680568823/000078.o /tmp/go-link-1680568823/000079.o /tmp/go-link-1680568823/000080.o /tmp/go-link-1680568823/000081.o /tmp/go-link-1680568823/000082.o /tmp/go-link-1680568823/000083.o /tmp/go-link-1680568823/000084.o /tmp/go-link-1680568823/000085.o /tmp/go-link-1680568823/000086.o /tmp/go-link-1680568823/000087.o -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -Wl,--enable-new-dtags -Wl,--as-needed -L/home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64 -lresvg -lm -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -Wl,--enable-new-dtags -Wl,--as-needed -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -Wl,--enable-new-dtags -Wl,--as-needed -landroid -llog -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -Wl,--enable-new-dtags -Wl,--as-needed -llog -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -Wl,--enable-new-dtags -Wl,--as-needed -ldl -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -Wl,--enable-new-dtags -Wl,--as-needed -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -Wl,--enable-new-dtags -Wl,--as-needed -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -Wl,--enable-new-dtags -Wl,--as-needed
ld.lld: error: undefined symbol: bcmp
>>> referenced by cmp.rs:92 (library/core/src/slice/cmp.rs:92)
>>>               core-35a42ff49c607596.core.cd507df62a5ba63c-cgu.0.rcgu.o:(core::str::pattern::StrSearcher::new::h2e94cc569bb6dae1) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a
>>> referenced by cmp.rs:92 (library/core/src/slice/cmp.rs:92)
>>>               core-35a42ff49c607596.core.cd507df62a5ba63c-cgu.0.rcgu.o:(_$LT$core..num..bignum..Big32x40$u20$as$u20$core..cmp..PartialEq$GT$::eq::h2adb150b4d6a2507) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a
>>> referenced by cmp.rs:92 (/rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/slice/cmp.rs:92)
>>>               rustc_demangle-96c0f7f888ec0de3.rustc_demangle.72063a0bc839fb38-cgu.0.rcgu.o:(_$LT$core..str..pattern..CharSearcher$u20$as$u20$core..str..pattern..Searcher$GT$::next_match::h4a6a372e807703b9) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a
>>> referenced 321 more times

ld.lld: error: undefined symbol: __errno_location
>>> referenced by os.rs:84 (library/std/src/sys/pal/unix/os.rs:84)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::rt::lang_start_internal::h74cf3ce250a141d9) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a
>>> referenced by os.rs:84 (library/std/src/sys/pal/unix/os.rs:84)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::rt::lang_start_internal::h74cf3ce250a141d9) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a
>>> referenced by os.rs:84 (library/std/src/sys/pal/unix/os.rs:84)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::rt::lang_start_internal::h74cf3ce250a141d9) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a
>>> referenced 316 more times

ld.lld: error: undefined symbol: __xpg_strerror_r
>>> referenced by os.rs:139 (library/std/src/sys/pal/unix/os.rs:139)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::io::error::_$LT$impl$u20$core..fmt..Debug$u20$for$u20$std..io..error..repr_bitpacked..Repr$GT$::fmt::hed74cf1af340a324) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a
>>> referenced by os.rs:139 (library/std/src/sys/pal/unix/os.rs:139)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(_$LT$std..io..error..Error$u20$as$u20$core..fmt..Display$GT$::fmt::h1cc9a5f4ac336997) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a

ld.lld: error: undefined symbol: gnu_get_libc_version
>>> referenced by os.rs:766 (library/std/src/sys/pal/unix/os.rs:766)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::sys::pal::unix::os::glibc_version::h99a66e93e8607426) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a

ld.lld: error: undefined symbol: posix_spawnattr_init
>>> referenced by process_unix.rs:580 (library/std/src/sys/pal/unix/process/process_unix.rs:580)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::sys::pal::unix::process::process_inner::_$LT$impl$u20$std..sys..pal..unix..process..process_common..Command$GT$::spawn::hd31aa4f466e879db) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a

ld.lld: error: undefined symbol: posix_spawn_file_actions_init
>>> referenced by process_unix.rs:586 (library/std/src/sys/pal/unix/process/process_unix.rs:586)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::sys::pal::unix::process::process_inner::_$LT$impl$u20$std..sys..pal..unix..process..process_common..Command$GT$::spawn::hd31aa4f466e879db) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a

ld.lld: error: undefined symbol: posix_spawn_file_actions_adddup2
>>> referenced by process_unix.rs:590 (library/std/src/sys/pal/unix/process/process_unix.rs:590)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::sys::pal::unix::process::process_inner::_$LT$impl$u20$std..sys..pal..unix..process..process_common..Command$GT$::spawn::hd31aa4f466e879db) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a
>>> referenced by process_unix.rs:597 (library/std/src/sys/pal/unix/process/process_unix.rs:597)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::sys::pal::unix::process::process_inner::_$LT$impl$u20$std..sys..pal..unix..process..process_common..Command$GT$::spawn::hd31aa4f466e879db) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a
>>> referenced by process_unix.rs:604 (library/std/src/sys/pal/unix/process/process_unix.rs:604)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::sys::pal::unix::process::process_inner::_$LT$impl$u20$std..sys..pal..unix..process..process_common..Command$GT$::spawn::hd31aa4f466e879db) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a

ld.lld: error: undefined symbol: posix_spawnattr_setpgroup
>>> referenced by process_unix.rs:616 (library/std/src/sys/pal/unix/process/process_unix.rs:616)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::sys::pal::unix::process::process_inner::_$LT$impl$u20$std..sys..pal..unix..process..process_common..Command$GT$::spawn::hd31aa4f466e879db) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a

ld.lld: error: undefined symbol: posix_spawnattr_setflags
>>> referenced by process_unix.rs:641 (library/std/src/sys/pal/unix/process/process_unix.rs:641)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::sys::pal::unix::process::process_inner::_$LT$impl$u20$std..sys..pal..unix..process..process_common..Command$GT$::spawn::hd31aa4f466e879db) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a
>>> referenced by process_unix.rs:641 (library/std/src/sys/pal/unix/process/process_unix.rs:641)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::sys::pal::unix::process::process_inner::_$LT$impl$u20$std..sys..pal..unix..process..process_common..Command$GT$::spawn::hd31aa4f466e879db) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a

ld.lld: error: undefined symbol: posix_spawnp
>>> referenced by process_unix.rs:652 (library/std/src/sys/pal/unix/process/process_unix.rs:652)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::sys::pal::unix::process::process_inner::_$LT$impl$u20$std..sys..pal..unix..process..process_common..Command$GT$::spawn::hd31aa4f466e879db) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a

ld.lld: error: undefined symbol: posix_spawnattr_setsigdefault
>>> referenced by process_unix.rs:634 (library/std/src/sys/pal/unix/process/process_unix.rs:634)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::sys::pal::unix::process::process_inner::_$LT$impl$u20$std..sys..pal..unix..process..process_common..Command$GT$::spawn::hd31aa4f466e879db) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a

ld.lld: error: undefined symbol: posix_spawn_file_actions_destroy
>>> referenced by process_unix.rs:563 (library/std/src/sys/pal/unix/process/process_unix.rs:563)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::sys::pal::unix::process::process_inner::_$LT$impl$u20$std..sys..pal..unix..process..process_common..Command$GT$::spawn::hd31aa4f466e879db) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a
>>> referenced by process_unix.rs:563 (library/std/src/sys/pal/unix/process/process_unix.rs:563)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::sys::pal::unix::process::process_inner::_$LT$impl$u20$std..sys..pal..unix..process..process_common..Command$GT$::spawn::hd31aa4f466e879db) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a
>>> referenced by process_unix.rs:563 (library/std/src/sys/pal/unix/process/process_unix.rs:563)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::sys::pal::unix::process::process_inner::_$LT$impl$u20$std..sys..pal..unix..process..process_common..Command$GT$::spawn::hd31aa4f466e879db) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a
>>> referenced 1 more times

ld.lld: error: undefined symbol: posix_spawnattr_destroy
>>> referenced by process_unix.rs:573 (library/std/src/sys/pal/unix/process/process_unix.rs:573)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::sys::pal::unix::process::process_inner::_$LT$impl$u20$std..sys..pal..unix..process..process_common..Command$GT$::spawn::hd31aa4f466e879db) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a
>>> referenced by process_unix.rs:573 (library/std/src/sys/pal/unix/process/process_unix.rs:573)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::sys::pal::unix::process::process_inner::_$LT$impl$u20$std..sys..pal..unix..process..process_common..Command$GT$::spawn::hd31aa4f466e879db) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a
>>> referenced by process_unix.rs:573 (library/std/src/sys/pal/unix/process/process_unix.rs:573)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(std::sys::pal::unix::process::process_inner::_$LT$impl$u20$std..sys..pal..unix..process..process_common..Command$GT$::spawn::hd31aa4f466e879db) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a
>>> referenced 1 more times

ld.lld: error: undefined symbol: __res_init
>>> referenced by net.rs:585 (library/std/src/sys/pal/unix/net.rs:585)
>>>               std-6bfb7a472f07eca0.std.86bf0646e50f8a48-cgu.0.rcgu.o:(_$LT$std..sys_common..net..LookupHost$u20$as$u20$core..convert..TryFrom$LT$$LP$$RF$str$C$u16$RP$$GT$$GT$::try_from::_$u7b$$u7b$closure$u7d$$u7d$::had09cd12217788f8) in archive /home/builder/.termux-build/usql/src/pkg/mod/github.com/xo/resvg@v0.6.0/libresvg/linux_arm64/libresvg.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)

ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-10-21 18:28:52 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/11445995557">11445995557</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

### PR DESCRIPTION
**Pull request by licy183**
Closes #21924

### CODE REVIEW

File: packages/usql/build.sh [hunk 1]
```diff
@@ -2,20 +2,42 @@ TERMUX_PKG_HOMEPAGE=https://github.com/xo/usql
...
+	go mod vendor
+}
+
 termux_step_make() {
 	termux_setup_golang
-	export GOPATH=$TERMUX_PKG_BUILDDIR
 
-	cd $TERMUX_PKG_SRCDIR
+	# Build and replace resvg
+	local _resvg_go_url="$(cat go.mod | grep resvg | awk '{print $1}')"
```
Comment (TomJo2000) [inline packages/usql/build.sh:21]: Bash does have built-in syntax for grabbing the contents of a file in the form of `$(</path/to/file)`

Quote:[^1]
```bash
The command substitution $(cat file) can be replaced by the
equivalent but faster $(< file).
```
Though I don't think this would make any practical difference in this instance or the one below.

[^1]: https://www.man7.org/linux/man-pages/man1/bash.1.html#EXPANSION:~:text=%24(%3C

**Review by TomJo2000 — APPROVED** [review]
