### PR TITLE
pypy: bump to 7.3.18

### LINKED ISSUE #23466: Auto update failing for pypy
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [pypy](https://github.com/termux/termux-packages/blob/c2de1129da927100d8e232a025b11d84be96fed2/packages/pypy) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="console">
INFO: Updating pypy [Current version: 7.3.17]
INFO: package being updated to 7.3.18.
Downloading https://downloads.python.org/pypy/pypy2.7-v7.3.18-src.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 20.0M    0 20652    0     0  19099      0  0:18:19  0:00:01  0:18:18 19104
100 20.0M  100 20.0M    0     0  17.5M      0  0:00:01  0:00:01 --:--:-- 17.5M
Downloading https://downloads.python.org/pypy/pypy2.7-v7.3.18-linux64.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 29.7M  100 29.7M    0     0   211M      0 --:--:-- --:--:-- --:--:--  212M
Downloading https://downloads.python.org/pypy/pypy2.7-v7.3.18-linux32.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 25.4M    0 19274    0     0  16941      0  0:26:17  0:00:01  0:26:16 16951
100 25.4M  100 25.4M    0     0  20.7M      0  0:00:01  0:00:01 --:--:-- 20.7M

You are about to commit these changes:

--------------------
diff --git a/packages/pypy/build.sh b/packages/pypy/build.sh
index 89dc3b086e..c4aada54a6 100644
--- a/packages/pypy/build.sh
+++ b/packages/pypy/build.sh
@@ -3,13 +3,15 @@ TERMUX_PKG_DESCRIPTION="A fast, compliant alternative implementation of Python"
 TERMUX_PKG_LICENSE="MIT"
 TERMUX_PKG_MAINTAINER="@licy183"
 _MAJOR_VERSION=2.7
-TERMUX_PKG_VERSION="7.3.17"
+TERMUX_PKG_VERSION="7.3.18"
 TERMUX_PKG_SRCURL=(https://downloads.python.org/pypy/pypy$_MAJOR_VERSION-v$TERMUX_PKG_VERSION-src.tar.bz2
                    https://downloads.python.org/pypy/pypy2.7-v$TERMUX_PKG_VERSION-linux64.tar.bz2
                    https://downloads.python.org/pypy/pypy2.7-v$TERMUX_PKG_VERSION-linux32.tar.bz2)
-TERMUX_PKG_SHA256=(50e06840f4bbde91448080a4118068a89b8fbcae25ff8da1e2bb1402dc9a0346
-                   9f3497f87b3372d17e447369e0016a4bec99a6b4d2a59aba774a25bfe4353474
-                   a3aa0867cc837a34941047ece0fbb6ca190410fae6ad35fae4999d03bf178750)
+TERMUX_PKG_SHA256=(
+	737435ddfc5afa5b97a7209c87d70d5f1062426c053b9bb8b99a0347cb4891fa
+	1da34354e5fa59400609e94c00ba6feccf5aa575abb26fb6caf9c2ac16100ff4
+	54990fb1ae2266c260a7ce694b84ab91a8d0d298da440cd5695ac671dc5615e2
+)
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_DEPENDS="gdbm, libandroid-posix-semaphore, libandroid-support, libbz2, libcrypt, libexpat, libffi, liblzma, libsqlite, ncurses, ncurses-ui-libs, openssl, zlib"
 TERMUX_PKG_BUILD_DEPENDS="bionic-host, tk, xorgproto"
--------------------

bump(main/pypy): 7.3.18

Not committing to Git!

INFO: Trying to build package.
INFO: Package pypy exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building pypy for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13134  100 13134    0     0  57259      0 --:--:-- --:--:-- --:--:-- 57353
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   3802      0 --:--:-- --:--:-- --:--:--  3821
gpg: Signature made Mon 24 Feb 2025 08:53:33 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0  59265      0 --:--:-- --:--:-- --:--:-- 59464
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   3782      0 --:--:-- --:--:-- --:--:--  3769
gpg: Signature made Mon 24 Feb 2025 07:50:37 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13120  100 13120    0     0  57254      0 --:--:-- --:--:-- --:--:-- 57292
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   2561      0 --:--:-- --:--:-- --:--:--  2563
gpg: Signature made Mon 24 Feb 2025 08:07:58 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading dependency bionic-host@8.0.0-r51-5 if necessary...
Found bionic-host in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/bionic-host/bionic-host_8.0.0-r51-5_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 8211k    0 30612    0     0  35782      0  0:03:54 --:--:--  0:03:54 35761
 37 8211k   37 3085k    0     0  1715k      0  0:00:04  0:00:01  0:00:03 1715k
100 8211k  100 8211k    0     0  4104k      0  0:00:02  0:00:02 --:--:-- 4105k
extracting bionic-host to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libandroid-support@29 if necessary...
Found libandroid-support in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libandroid-support to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses@6.5.20240831-2 if necessary...
Found ncurses in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-utils@6.5.20240831-2 if necessary...
Found ncurses-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-ui-libs@6.5.20240831-2 if necessary...
Found ncurses-ui-libs in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-ui-libs to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-ui-libs-static@6.5.20240831-2 if necessary...
Found ncurses-ui-libs-static in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-ui-libs-static to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency readline@8.2.13 if necessary...
Found readline in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting readline to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency gdbm@1.24 if necessary...
Found gdbm in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting gdbm to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libandroid-posix-semaphore@0.1-3 if necessary...
Found libandroid-posix-semaphore in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libandroid-posix-semaphore to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libbz2@1.0.8-6 if necessary...
Found libbz2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libbz2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency bzip2@1.0.8-6 if necessary...
Found bzip2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting bzip2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ca-certificates@1:2024.12.31 if necessary...
Found ca-certificates in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ca-certificates to /home/builder/.termux-build/_cache-all...
Downloading dependency ca-certificates-java@1:2024.12.31 if necessary...
Found ca-certificates-java in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ca-certificates-java to /home/builder/.termux-build/_cache-all...
Downloading dependency zlib@1.3.1 if necessary...
Found zlib in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting zlib to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency openssl@1:3.4.1 if necessary...
Found openssl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting openssl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency openssl-tool@1:3.4.1 if necessary...
Found openssl-tool in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting openssl-tool to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libcrypt@0.2-5 if necessary...
Found libcrypt in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libcrypt to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libexpat@2.6.4 if necessary...
Found libexpat in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libexpat to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libffi@3.4.7 if necessary...
Found libffi in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libffi to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency liblzma@5.6.4 if necessary...
Found liblzma in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting liblzma to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xz-utils@5.6.4 if necessary...
Found xz-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting xz-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency tcl@8.6.14 if necessary...
Found tcl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting tcl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libsqlite@3.48.0 if necessary...
Found libsqlite in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libsqlite to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency sqlite@3.48.0 if necessary...
Found sqlite in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting sqlite to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libsqlite-tcl@3.48.0 if necessary...
Found libsqlite-tcl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libsqlite-tcl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency brotli@1.1.0 if necessary...
Found brotli in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting brotli to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libpng@1.6.47 if necessary...
Found libpng in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libpng to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency freetype@2.13.3 if necessary...
Found freetype in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting freetype to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ttf-dejavu@2.37-8 if necessary...
Found ttf-dejavu in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ttf-dejavu to /home/builder/.termux-build/_cache-all...
Downloading dependency fontconfig@2.16.0 if necessary...
Found fontconfig in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting fontconfig to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency fontconfig-utils@2.16.0 if necessary...
Found fontconfig-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting fontconfig-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xorg-util-macros@1.20.2 if necessary...
Found xorg-util-macros in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting xorg-util-macros to /home/builder/.termux-build/_cache-all...
Downloading dependency xorgproto@2024.1 if necessary...
Found xorgproto in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting xorgproto to /home/builder/.termux-build/_cache-all...
Downloading dependency libxau@1.0.12 if necessary...
Found libxau in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libxau to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxdmcp@1.1.5 if necessary...
Found libxdmcp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libxdmcp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xcb-proto@1.17.0-1 if necessary...
Found xcb-proto in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting xcb-proto to /home/builder/.termux-build/_cache-all...
Downloading dependency python-xcbgen@1.17.0-1 if necessary...
Found python-xcbgen in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting python-xcbgen to /home/builder/.termux-build/_cache-all...
Downloading dependency libxcb@1.17.0 if necessary...
Found libxcb in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libxcb to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xtrans@1.5.2 if necessary...
Found xtrans in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting xtrans to /home/builder/.termux-build/_cache-all...
Downloading dependency libx11@1.8.11 if necessary...
Found libx11 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libx11 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxrender@0.9.12 if necessary...
Found libxrender in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libxrender to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxft@2.3.8 if necessary...
Found libxft in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libxft to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxext@1.3.6 if necessary...
Found libxext in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libxext to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxss@1.2.4 if necessary...
Found libxss in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libxss to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency tk@8.6.14 if necessary...
Found tk in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting tk to /home/builder/.termux-build/_cache-aarch64...
Downloading https://downloads.python.org/pypy/pypy2.7-v7.3.18-src.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 20.0M  100 20.0M    0     0   150M      0 --:--:-- --:--:-- --:--:--  151M
Downloading https://downloads.python.org/pypy/pypy2.7-v7.3.18-linux64.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 29.7M  100 29.7M    0     0   120M      0 --:--:-- --:--:-- --:--:--  120M
Downloading https://downloads.python.org/pypy/pypy2.7-v7.3.18-linux32.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 25.4M  100 25.4M    0     0   234M      0 --:--:-- --:--:-- --:--:--  236M
Applying 9999-add-ANDROID_API_LEVEL-for-sysconfigdata.diff
Applying patch: 0001-add-wait3-function-for-resource-module.patch
Applying patch: 0002-add-getprotobyname.patch
Applying patch: 0003-fix-hardcoded-paths.patch
Applying patch: 0004-fix-loaded-libs.patch
Applying patch: 0005-fix-unavailable-functions.patch
1 out of 1 hunk FAILED -- saving rejects to file rpython/rlib/rvmprof/cintf.py.rej
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2025-02-24 22:53:08 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/13507214029">13507214029</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

### PR DESCRIPTION
**Pull request by licy183**
Closes #23466

### CODE REVIEW

File: packages/pypy/build.sh [hunk 1]
```diff
@@ -88,6 +92,7 @@ termux_step_make() {
 -b $HOME
 -b $TERMUX_PKG_TMPDIR
 -b /proc -b /dev -b /sys
+-b $TERMUX_PREFIX/opt/bionic-host:/system
```
Comment (robertkirkman) [inline packages/pypy/build.sh:95]: Very good, since this appears to be working, should this line elsewhere in the codebase be removed, and `pypy3` also adjusted to have a `-b` argument like this?

https://github.com/termux/termux-packages/blob/c444bffde58b0d1f60f216dd85930c53d0db0558/scripts/setup-ubuntu.sh#L345

This behavior was not clearly revealed by the `proot` non-detailed help command,
but it _is_ clearly documented by the detailed `proot --help` and `man proot` commands. I did not know that `proot` supports this until now.

https://github.com/termux/proot/blob/60485d2646c1e09105099772da4a20deda8d020d/src/cli/cli.c#L61

Comment (robertkirkman) [reply packages/pypy/build.sh:95]: meaning, the references to `/system` in `pypy3` could be replaced with `$TERMUX_PREFIX/opt/bionic-host`, and then that line removed?

https://github.com/termux/termux-packages/blob/49e37c67d64c9eaae0bd7dc582b2f526f000d622/packages/pypy3/build.sh#L164

**Comment by robertkirkman** [comment]
About this in the build for `arm` here:

```
Traceback (most recent call last):
  File "../../rpython/bin/rpython", line 20, in <module>
    main()
  File "/home/builder/.termux-build/pypy/src/rpython/translator/goal/translate.py", line 219, in main
    targetspec_dic, translateconfig, config, args = parse_options_and_load_target()
  File "/home/builder/.termux-build/pypy/src/rpython/translator/goal/translate.py", line 155, in parse_options_and_load_target
    targetspec_dic = load_target(targetspec)
  File "/home/builder/.termux-build/pypy/src/rpython/translator/goal/translate.py", line 97, in load_target
    mod = __import__(specname)
  File "targetpypystandalone.py", line 12, in <module>
    from pypy.tool.option import make_objspace
  File "/home/builder/.termux-build/pypy/src/pypy/tool/option.py", line 3, in <module>
    from pypy.config.pypyoption import get_pypy_config
  File "/home/builder/.termux-build/pypy/src/pypy/config/pypyoption.py", line 43, in <module>
    import rpython.rlib.rvmprof.cintf
  File "/home/builder/.termux-build/pypy/src/rpython/rlib/rvmprof/__init__.py", line 2, in <module>
    from rpython.rlib.rvmprof.rvmprof import _get_vmprof, VMProfError
  File "/home/builder/.termux-build/pypy/src/rpython/rlib/rvmprof/rvmprof.py", line 3, in <module>
    from rpython.rlib import jit, rposix, rgc
  File "/home/builder/.termux-build/pypy/src/rpython/rlib/rposix.py", line 343, in <module>
    assert OFF_T_SIZE == rffi.sizeof(rffi.LONGLONG)
AssertionError
```

I have bisected it to this commit https://github.com/pypy/pypy/commit/00120114309a57b32223e58a508f7ab470b674ce

I have not calculated the absolute best patch yet to fix the error, but at the very least, if we cannot find any better way, one option is to revert that whole commit with a patch.

The commit indicates that it was for this issue, which is an Alpine-Linux-related issue. https://github.com/pypy/pypy/issues/5071

File: packages/pypy/build.sh (hunk 1 above)
Comment (licy183) [reply packages/pypy/build.sh:95]: If `/system` is symlinked to `$TERMUX_PREFIX/opt/bionic-host`, this line can be removed.

Comment (robertkirkman) [reply packages/pypy/build.sh:95]: Well, what I was trying to ask is, do you think it is better for `/system` to be symlinked to `$TERMUX_PREFIX/opt/bionic-host`, or instead for all `proot` invocations to have `$TERMUX_PREFIX/opt/bionic-host` mounted in the place where `/system` was mounted before?
I am not sure which you think is better.

Comment (robertkirkman) [reply packages/pypy/build.sh:95]: After you edited the message, now the same line is linked twice, and it is a little bit confusing, I am not sure which specific line you are saying is best to remove in the future.

image

Did you mean to link a different line in one of the two links?

Comment (licy183) [reply packages/pypy/build.sh:95]: Ahhh.. The first one should be https://github.com/termux/termux-packages/blob/acca5f93cdc7458ad563a30dd67aaed45b7ebc6b/packages/pypy/build.sh#L95
