### PR TITLE
fix(main/libimobiledevice): Patch hardcoded paths with TERMUX_PREFIX

### LINKED ISSUE #27538: [Bug]: libimobiledevice searches for pairing files in a different dir from the save dir
### Problem description

When using `idevicepair pair`, you acquire a `.plist` file, this is the so called "pairing file" which apps like Sidestore and StikDebug use to get permissions to sideload and activate JIT respectively.

This file is saved in `/var/lib/lockdown` in linux systems, but this dir was not patched for termux, so it tries to save the plist file in an invalid directory and fails, causing it to not save the file at all.

https://github.com/libimobiledevice/libimobiledevice/blob/master/common/userpref.c#L174-L178

### What steps will reproduce the bug?

1. Running `idevicepair pair`
2. Running `idevicepair list`
3. Finding your so called paired device is missing

### What is the expected behavior?

1. Running `idevicepair pair`
2. Running `idevicepair list`
3.  `idevicepair list` finding your paired device in $PREFIX/var/lib/lockdown

### System information

```shell
Termux Variables:
TERMUX_API_VERSION=0.50.1+4c6a519
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=27582
TERMUX_APP__DATA_DIR=/data/user/0/com.termux
TERMUX_APP__LEGACY_DATA_DIR=/data/data/com.termux
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c175,c257,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.3
TERMUX__HOME=/data/data/com.termux/files/home
TERMUX__PREFIX=/data/data/com.termux/files/usr
TERMUX__ROOTFS_DIR=/data/data/com.termux/files
TERMUX__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c175,c257,c512,c768
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# glibc-repo (sources.list.d/glibc.list)
deb https://packages-cf.termux.dev/apt/termux-glibc/ glibc stable
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.dev/apt/termux-root root stable
Updatable packages:
aspell/stable 0.60.8.1-2 aarch64 [upgradable from: 0.60.8.1-1]
at-spi2-core/stable 2.58.2 aarch64 [upgradable from: 2.58.1]
bash/stable 5.3.8 aarch64 [upgradable from: 5.3.3-1]
bsdtar/stable 3.8.4 aarch64 [upgradable from: 3.8.3]
ca-certificates-java/stable 1:2025.12.02 all [upgradable from: 1:2025.11.04]
ca-certificates/stable 1:2025.12.02 all [upgradable from: 1:2025.11.04]
clang/stable 21.1.6 aarch64 [upgradable from: 21.1.5-1]
cmocka/stable 2.0.0 aarch64 [upgradable from: 1.1.8-2]
command-not-found/stable 3.2-6 aarch64 [upgradable from: 3.2-4]
cups/stable 2.4.16 aarch64 [upgradable from: 2.4.14]
ed/stable 1.22.3 aarch64 [upgradable from: 1.22.2-1]
fastfetch/stable 2.56.0 aarch64 [upgradable from: 2.55.1]
ffmpeg/stable 8.0.1 aarch64 [upgradable from: 7.1.1-6]
ffplay/x11 8.0.1 aarch64 [upgradable from: 8.0]
firefox/x11 145.0.2-1 aarch64 [upgradable from: 145.0.1-1]
freerdp/x11 3.19.0 aarch64 [upgradable from: 3.18.0-1]
graphviz/stable 14.0.5 aarch64 [upgradable from: 14.0.4]
gspell/x11 1.14.2 aarch64 [upgradable from: 1.14.1-1]
gst-libav/stable 1.26.9 aarch64 [upgradable from: 1.26.8-1]
gst-plugins-bad/stable 1.26.9 aarch64 [upgradable from: 1.26.8]
gst-plugins-base/stable 1.26.9 aarch64 [upgradable from: 1.26.8]
gst-plugins-good/stable 1.26.9 aarch64 [upgradable from: 1.26.8]
gst-plugins-ugly/stable 1.26.9 aarch64 [upgradable from: 1.26.8]
gstreamer/stable 1.26.9 aarch64 [upgradable from: 1.26.8]
gtk4/x11 4.20.3 aarch64 [upgradable from: 4.20.2]
guile/stable 3.0.11 aarch64 [upgradable from: 3.0.10-2]
haproxy/stable 3.3.0 aarch64 [upgradable from: 3.2.9]
harfbuzz-icu/stable 12.2.0-2 aarch64 [upgradable from: 12.2.0-1]
harfbuzz/stable 12.2.0-2 aarch64 [upgradable from: 12.2.0-1]
imagemagick/stable 7.1.2.9 aarch64 [upgradable from: 7.1.2.8-1]
iproute2/stable 6.18.0 aarch64 [upgradable from: 6.17.0]
jadx-x/stable 1.5.3-1 all [upgradable from: 1.5.3]
jadx/stable 1.5.3-1 all [upgradable from: 1.5.3]
libandroid-stub/stable 29-1 aarch64 [upgradable from: 28c]
libarchive/stable 3.8.4 aarch64 [upgradable from: 3.8.3]
libc++/stable 29 aarch64 [upgradable from: 28c-1]
libcompiler-rt/stable 21.1.6 aarch64 [upgradable from: 21.1.5-1]
libevdev/x11 1.13.6 aarch64 [upgradable from: 1.13.5]
libfm-qt/x11 2.3.1 aarch64 [upgradable from: 2.3.0]
libjxl/stable 0.11.1-6 aarch64 [upgradable from: 0.11.1-5]
libllvm/stable 21.1.6 aarch64 [upgradable from: 21.1.5-1]
libneon/stable 0.36.0 aarch64 [upgradable from: 0.35.0-1]
libnfs/stable 6.0.2-2 aarch64 [upgradable from: 6.0.2-1]
libnghttp3/stable 1.13.1 aarch64 [upgradable from: 1.12.0]
libnl/stable 3.12.0 aarch64 [upgradable from: 3.11.0-1]
libnss/stable 3.119 aarch64 [upgradable from: 3.118.1]
libpaper/stable 2.2.7 aarch64 [upgradable from: 2.2.6-1]
libpng/stable 1.6.53 aarch64 [upgradable from: 1.6.51]
libqtxdg/x11 4.3.0-1 aarch64 [upgradable from: 4.3.0]
libseat/stable 0.9.1-3 aarch64 [upgradable from: 0.9.1-2]
libsqlite/stable 3.51.1 aarch64 [upgradable from: 3.51.0]
libunbound/stable 1.24.2 aarch64 [upgradable from: 1.24.1-1]
libvte/x11 2:0.82.2 aarch64 [upgradable from: 2:0.82.1-1]
libxkbcommon/x11 1.13.1 aarch64 [upgradable from: 1.13.0]
libxslt/stable 1.1.45 aarch64 [upgradable from: 1.1.43-3]
lld/stable 21.1.6 aarch64 [upgradable from: 21.1.5-1]
llvm/stable 21.1.6 aarch64 [upgradable from: 21.1.5-1]
lxqt-archiver/x11 1.3.0-1 aarch64 [upgradable from: 1.3.0]
lxqt-notificationd/x11 2.3.1 aarch64 [upgradable from: 2.3.0]
lxqt-panel/x11 2.3.1 aarch64 [upgradable from: 2.3.0]
lxqt-qtplugin/x11 2.3.0-1 aarch64 [upgradable from: 2.3.0]
mesa-dev/stable 25.3.1 all [upgradable from: 25.3.0]
mesa/stable 25.3.1 aarch64 [upgradable from: 25.3.0]
ndk-sysroot-gcc-compact/tur-packages 29 aarch64 [upgradable from: 28c-1]
nodejs-lts/stable 22.21.1 aarch64 [upgradable from: 22.20.0-1]
ollama/stable 0.13.1 aarch64 [upgradable from: 0.12.11]
openssl-tool/stable 1:3.6.0 aarch64 [upgradable from: 1:3.5.2]
openssl/stable 1:3.6.0 aarch64 [upgradable from: 1:3.5.2]
pinentry/stable 1.3.2-2 aarch64 [upgradable from: 1.3.2-1]
proot-distro/stable 4.34.2 all [upgradable from: 4.32.0]
qt6-qtbase/x11 6.10.1-2 aarch64 [upgradable from: 6.10.1-1]
sqlite/stable 3.51.1 aarch64 [upgradable from: 3.51.0]
tmux/stable 3.6a aarch64 [upgradable from: 3.5a-1]
tree-sitter-query/stable 0.8.0 aarch64 [upgradable from: 0.7.0-1]
unbound/stable 1.24.2 aarch64 [upgradable from: 1.24.1-1]
utf8proc/stable 2.11.2 aarch64 [upgradable from: 2.11.1]
uv/stable 0.9.15 aarch64 [upgradable from: 0.9.11]
vtm/stable 2025.12.03 aarch64 [upgradable from: 2025.11.13-1]
vulkan-loader-android/stable 29 aarch64 [upgradable from: 28c-2]
vulkan-tools/stable 1.4.335 aarch64 [upgradable from: 1.4.333]
webkitgtk-6.0/x11 2.51.2 aarch64 [upgradable from: 2.48.0-3]
xorg-xkbcomp/x11 1.5.0 aarch64 [upgradable from: 1.4.7]
zenity/x11 4.2.1-1 aarch64 [upgradable from: 4.2.1]
termux-tools version:
1.45.0
Android version:
13
Kernel build information:
Linux localhost 5.10.136-android12-9-27106858-abA536EXXS7CWI1 #1 SMP PREEMPT Thu Sep 21 10:11:43 +07 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A536E
Supported ABIs:
SUPPORTED_ABIS: arm64-v8a,armeabi-v7a,armeabi
SUPPORTED_32_BIT_ABIS: armeabi-v7a,armeabi
SUPPORTED_64_BIT_ABIS: arm64-v8a
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec-ld-preload.so
Installed termux plugins:
com.termux.widget versionCode:13
com.termux.x11 versionCode:15
com.termux.gui versionCode:8
com.termux.api versionCode:51
com.termux.tasker versionCode:6
```

### PR DESCRIPTION
**Pull request by alexytomi**
Should fix #27538. I tested it.

### CODE REVIEW

File: packages/libimobiledevice/common-userpref.c.patch [hunk 1]
```diff
@@ -0,0 +1,16 @@
+diff --git a/common/userpref.c b/common/userpref.c
+index 76945e1..4daffb3 100644
+--- a/common/userpref.c
++++ b/common/userpref.c
+@@ -172,9 +172,9 @@ const char *userpref_get_config_dir()
+ 	}
+ #else
+ #ifdef __APPLE__
+-	base_config_dir = strdup("/var/db");
++	base_config_dir = strdup("@TERMUX_PREFIX@/var/db");
```
Comment (robertkirkman) [inline packages/libimobiledevice/common-userpref.c.patch:10]: `#ifdef __APPLE__` is typically considered unreachable in Termux, because Termux is not portable to any Apple products. I suggest not patching this part, for clarity, especially since if Termux ever were portable to an Apple product, I have no idea whether `/var/db` would be necessary to prepend anything to on that Apple product, and there is currently no way to test that either. If you really don't want to ignore the `#ifdef __APPLE__` block, though, then it technically doesn't matter and the patch could be left like this, since it's unreachable anyway and will have no impact on the result for users.

Comment (alexytomi) [reply packages/libimobiledevice/common-userpref.c.patch:10]: I did think of that however Biswa's commit https://github.com/termux/termux-packages/commit/ce9b1ba0ada363218ef642a3d50debb4a4de95ab doing the same thing in `usbmuxd` did that so I opted to just copy it instead so it's consistent.

Comment (robertkirkman) [reply packages/libimobiledevice/common-userpref.c.patch:10]: ok that's fine because there is precedent @Biswa96 for future reference, `#ifdef __APPLE__` is unreachable in Termux

**Review by robertkirkman — APPROVED** [review]

**Comment by robertkirkman** [comment]
I will merge this in 24 hours
