### PR TITLE
upgpkg(main/v2ray): update to 5.1.0

### LINKED ISSUE #12087: [Bug]: v2ray build failed
### Problem description

# github.com/lucas-clemente/quic-go/internal/qtls
../../../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.24.0/internal/qtls/go118.go:6:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration
builder@ab6a0afe2fbf:~/termux-packages$

[v2ray.txt](https://github.com/termux/termux-packages/files/9637362/v2ray.txt)

### What steps will reproduce the bug?

building

### What is the expected behavior?

_No response_

### System information

termux-info:

```

```

### PR DESCRIPTION
**Pull request by 2096779623**
Close #12087 .

### CODE REVIEW

File: packages/v2ray/common-platform-others.go.patch [hunk 1]
```diff
@@ -1,15 +0,0 @@
---- a/common/platform/others.go
-+++ b/common/platform/others.go
-@@ -31,9 +31,9 @@
- 	defPath := filepath.Join(assetPath, file)
```
Comment (licy183) [inline packages/v2ray/common-platform-others.go.patch:4]: It uses `adrg/xdg` package to search for pathes, in which pathes are hard-coded. I think extra patches on `adrg/xdg` are needed.

File: packages/v2ray/0001-fix-config-pathes.patch [hunk 2]
```diff
@@ -0,0 +1,132 @@
+--- a/go/pkg/mod/github.com/adrg/xdg@v0.4.0/paths_unix.go	2022-09-24 18:18:29.907660821 +0800
++++ b/go/pkg/mod/github.com/adrg/xdg@v0.4.0/paths_unix.go	2022-09-24 18:34:47.217660448 +0800
+@@ -27,27 +27,27 @@
+ func initBaseDirs(home string) {
+ 	// Initialize standard directories.
+ 	baseDirs.dataHome = xdgPath(envDataHome, filepath.Join(home, ".local", "share"))
+-	baseDirs.data = xdgPaths(envDataDirs, "/usr/local/share", "/usr/share")
++	baseDirs.data = xdgPaths(envDataDirs, "@TERMUX_PREFIX@/local/share", "@TERMUX_PREFIX@/share")
+ 	baseDirs.configHome = xdgPath(envConfigHome, filepath.Join(home, ".config"))
+ 	baseDirs.config = xdgPaths(envConfigDirs, "/etc/xdg")
```
Comment (Grimler91) [inline packages/v2ray/0001-fix-config-pathes.patch:10]: Probably this should be updated as well to @TERMUX_PREFIX@/etc/xdg

File: packages/v2ray/0001-fix-config-pathes.patch [hunk 3]
```diff
@@ -0,0 +1,132 @@
...
+ 	baseDirs.stateHome = xdgPath(envStateHome, filepath.Join(home, ".local", "state"))
+ 	baseDirs.cacheHome = xdgPath(envCacheHome, filepath.Join(home, ".cache"))
+-	baseDirs.runtime = xdgPath(envRuntimeDir, filepath.Join("/run/user", strconv.Itoa(os.Getuid())))
++	baseDirs.runtime = xdgPath(envRuntimeDir, filepath.Join("@TERMUX_PREFI@/var/run/user", strconv.Itoa(os.Getuid())))
```
Comment (Grimler91) [inline packages/v2ray/0001-fix-config-pathes.patch:14]: Since termux is a single user environment we can use just `baseDirs.runtime = xdgPath(envRuntimeDir, "@TERMUX_PREFIX@/var/run")`

(also note typo PREFI -> PREFIX)

File: packages/v2ray/0001-fix-config-pathes.patch [hunk 4]
```diff
@@ -0,0 +1,132 @@
...
++			expected: []string{"@TERMUX_PREFIX@/etc/xdg"},
+ 			actual:   &xdg.ConfigDirs,
+ 		},
+ 		&envSample{
+@@ -49,15 +49,15 @@
+ 		},
+ 		&envSample{
+ 			name:     "XDG_RUNTIME_DIR",
+-			expected: filepath.Join("/run/user", strconv.Itoa(os.Getuid())),
++			expected: filepath.Join("@TERMUX_PREFIX@/var/run/user", strconv.Itoa(os.Getuid())),
```
Comment (Grimler91) [inline packages/v2ray/0001-fix-config-pathes.patch:62]: Can use just `"@TERMUX_PREFIX@/var/run"` here as well

**Review by Grimler91 — CHANGES_REQUESTED** [review]
Thanks, some suggestions for improvements on the patch paths

**Comment by 2096779623** [comment]
> Thanks, some suggestions for improvements on the patch paths

Fixed,thanks.

File: packages/v2ray/0001-fix-config-paths.patch [hunk 5]
```diff
@@ -0,0 +1,152 @@
...
+ 	"github.com/adrg/xdg/internal/pathutil"
+ )
+@@ -27,27 +26,27 @@
+ func initBaseDirs(home string) {
+ 	// Initialize standard directories.
+ 	baseDirs.dataHome = xdgPath(envDataHome, filepath.Join(home, ".local", "share"))
+-	baseDirs.data = xdgPaths(envDataDirs, "/usr/local/share", "/usr/share")
++	baseDirs.data = xdgPaths(envDataDirs, "@TERMUX_PREFIX@/etc/xdg")
+ 	baseDirs.configHome = xdgPath(envConfigHome, filepath.Join(home, ".config"))
+ 	baseDirs.config = xdgPaths(envConfigDirs, "/etc/xdg")
```
Comment (Grimler91) [inline packages/v2ray/0001-fix-config-paths.patch:47]: /etc/xdg here should probably be changed as well
