### PR TITLE
telegram-desktop: bump to 5.14.2

### LINKED ISSUE #24662: Auto update failing for telegram-desktop
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [telegram-desktop](https://github.com/termux/termux-packages/blob/bb381b573d55b379943a8129ed29f2599d73cb44/x11-packages/telegram-desktop) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="console">
INFO: Updating telegram-desktop [Current version: 5.14.1]
INFO: package being updated to 5.14.2.
Downloading https://github.com/telegramdesktop/tdesktop/releases/download/v5.14.2/tdesktop-5.14.2-full.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

 17 69.4M   17 12.3M    0     0  53.8M      0  0:00:01 --:--:--  0:00:01 53.8M
100 69.4M  100 69.4M    0     0   175M      0 --:--:-- --:--:-- --:--:--  344M

You are about to commit these changes:

--------------------
diff --git a/x11-packages/telegram-desktop/build.sh b/x11-packages/telegram-desktop/build.sh
index d50b087c7a..f748b5da02 100644
--- a/x11-packages/telegram-desktop/build.sh
+++ b/x11-packages/telegram-desktop/build.sh
@@ -4,9 +4,9 @@ TERMUX_PKG_DESCRIPTION="Telegram Desktop Client"
 TERMUX_PKG_LICENSE="custom"
 TERMUX_PKG_LICENSE_FILE="LICENSE, LEGAL"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION=5.14.1
+TERMUX_PKG_VERSION="5.14.2"
 TERMUX_PKG_SRCURL=https://github.com/telegramdesktop/tdesktop/releases/download/v$TERMUX_PKG_VERSION/tdesktop-$TERMUX_PKG_VERSION-full.tar.gz
-TERMUX_PKG_SHA256=42d3130292b21928f04e39539f4e7358206bde913ea6e5171b0ffdeb38b9872e
+TERMUX_PKG_SHA256=8a3b2570475584317651c76407176ad884f073b1eacaf07333c9037806279f02
 TERMUX_PKG_DEPENDS="abseil-cpp, boost, ffmpeg, glib, hicolor-icon-theme, hunspell, kf6-kcoreaddons, libandroid-shmem, libc++, libdispatch, libdrm, liblz4, libminizip, protobuf, librnnoise, libsigc++-3.0, libx11, libxcomposite, libxdamage, libxrandr, libxtst, openal-soft, opengl, openh264, openssl, pipewire, pulseaudio, qt6-qtbase, qt6-qtimageformats, qt6-qtsvg, xxhash, zlib"
 TERMUX_PKG_BUILD_DEPENDS="ada, boost-headers, glib-cross, qt6-qtbase-cross-tools"
 TERMUX_PKG_VERSIONED_GIR=false
--------------------

bump(x11/telegram-desktop): 5.14.2


Not committing to Git!

INFO: Trying to build package.
INFO: Package telegram-desktop exists in x11 repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building telegram-desktop for arch aarch64...
::group::INFO: Fetching repo metadata
[packages-cf.termux.dev-apt-termux-main]: Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
[packages-cf.termux.dev-apt-termux-main]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-main]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-main]: 
[packages-cf.termux.dev-apt-termux-main]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-main]: 100 13133  100 13133    0     0   174k      0 --:--:-- --:--:-- --:--:--  175k
[packages-cf.termux.dev-apt-termux-main]: Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
[packages-cf.termux.dev-apt-termux-main]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-main]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-main]: 
[packages-cf.termux.dev-apt-termux-main]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-main]: 100   833  100   833    0     0   8837      0 --:--:-- --:--:-- --:--:--  8861
[packages-cf.termux.dev-apt-termux-main]: gpg: Signature made Fri 09 May 2025 12:19:33 PM UTC
[packages-cf.termux.dev-apt-termux-main]: gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
[packages-cf.termux.dev-apt-termux-main]: gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
[packages-cf.termux.dev-apt-termux-main]: gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
[packages-cf.termux.dev-apt-termux-x11]: Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
[packages-cf.termux.dev-apt-termux-x11]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-x11]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-x11]: 
[packages-cf.termux.dev-apt-termux-x11]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-x11]: 100 13119  100 13119    0     0  83637      0 --:--:-- --:--:-- --:--:-- 84096
[packages-cf.termux.dev-apt-termux-x11]: Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
[packages-cf.termux.dev-apt-termux-x11]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-x11]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-root]: Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
[packages-cf.termux.dev-apt-termux-root]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-root]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-root]: 
[packages-cf.termux.dev-apt-termux-root]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-root]: 100 13319  100 13319    0     0   216k      0 --:--:-- --:--:-- --:--:--  220k
[packages-cf.termux.dev-apt-termux-root]: Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
[packages-cf.termux.dev-apt-termux-root]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[packages-cf.termux.dev-apt-termux-root]:                                  Dload  Upload   Total   Spent    Left  Speed
[packages-cf.termux.dev-apt-termux-root]: 
[packages-cf.termux.dev-apt-termux-root]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-root]: 100   833  100   833    0     0  13136      0 --:--:-- --:--:-- --:--:-- 13222
[packages-cf.termux.dev-apt-termux-root]: gpg: Signature made Wed 07 May 2025 12:32:36 PM UTC
[packages-cf.termux.dev-apt-termux-root]: gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
[packages-cf.termux.dev-apt-termux-root]: gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
[packages-cf.termux.dev-apt-termux-root]: gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
[packages-cf.termux.dev-apt-termux-x11]: 
[packages-cf.termux.dev-apt-termux-x11]:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[packages-cf.termux.dev-apt-termux-x11]: 100   833  100   833    0     0   2191      0 --:--:-- --:--:-- --:--:--  2186
[packages-cf.termux.dev-apt-termux-x11]: 100   833  100   833    0     0   2190      0 --:--:-- --:--:-- --:--:--  2186
[packages-cf.termux.dev-apt-termux-x11]: gpg: Signature made Thu 08 May 2025 06:47:09 PM UTC
[packages-cf.termux.dev-apt-termux-x11]: gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
[packages-cf.termux.dev-apt-termux-x11]: gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
[packages-cf.termux.dev-apt-termux-x11]: gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
::endgroup::
Downloading dependency libc++@27c if necessary...
Found libc++ in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libc++ to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency abseil-cpp@20250127.1 if necessary...
Found abseil-cpp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/a/abseil-cpp/abseil-cpp_20250127.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1082k  100 1082k    0     0  12.8M      0 --:--:-- --:--:-- --:--:-- 12.8M
extracting abseil-cpp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ada@3.2.4 if necessary...
Found ada in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/a/ada/ada_3.2.4_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 90  195k   90  175k    0     0   250k      0 --:--:-- --:--:-- --:--:--  250k
100  195k  100  195k    0     0   243k      0 --:--:-- --:--:-- --:--:--  243k
extracting ada to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libandroid-wordexp@0.1 if necessary...
Found libandroid-wordexp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libandroid-wordexp/libandroid-wordexp_0.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3566  100  3566    0     0   9114      0 --:--:-- --:--:-- --:--:--  9120
extracting libandroid-wordexp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libbz2@1.0.8-6 if necessary...
Found libbz2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libb/libbz2/libbz2_1.0.8-6_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 26634  100 26634    0     0  53615      0 --:--:-- --:--:-- --:--:-- 53589
100 26634  100 26634    0     0  53605      0 --:--:-- --:--:-- --:--:-- 53589
extracting libbz2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency bzip2@1.0.8-6 if necessary...
Found bzip2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/bzip2/bzip2_1.0.8-6_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 25506  100 25506    0     0  52611      0 --:--:-- --:--:-- --:--:-- 52698
extracting bzip2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libiconv@1.18 if necessary...
Found libiconv in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libi/libiconv/libiconv_1.18_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  548k  100  548k    0     0  8129k      0 --:--:-- --:--:-- --:--:-- 8193k
extracting libiconv to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency iconv@1.18 if necessary...
Found iconv in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/i/iconv/iconv_1.18_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 10020  100 10020    0     0   184k      0 --:--:-- --:--:-- --:--:--  188k
extracting iconv to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency liblzma@5.8.1 if necessary...
Found liblzma in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libl/liblzma/liblzma_5.8.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  187k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  187k  100  187k    0     0  2514k      0 --:--:-- --:--:-- --:--:-- 2496k
extracting liblzma to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xz-utils@5.8.1 if necessary...
Found xz-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/x/xz-utils/xz-utils_5.8.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 71040  100 71040    0     0   943k      0 --:--:-- --:--:-- --:--:--  950k
extracting xz-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libandroid-support@29 if necessary...
Found libandroid-support in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libandroid-support/libandroid-support_29_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 10852  100 10852    0     0   178k      0 --:--:-- --:--:-- --:--:--  179k
extracting libandroid-support to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses@6.5.20240831-2 if necessary...
Found ncurses in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-utils@6.5.20240831-2 if necessary...
Found ncurses-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-ui-libs@6.5.20240831-2 if necessary...
Found ncurses-ui-libs in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-ui-libs to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-ui-libs-static@6.5.20240831-2 if necessary...
Found ncurses-ui-libs-static in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ncurses-ui-libs-static to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency readline@8.2.13 if necessary...
Found readline in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/r/readline/readline_8.2.13_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  228k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  228k  100  228k    0     0   287k      0 --:--:-- --:--:-- --:--:--  286k
extracting readline to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency gdbm@1.25 if necessary...
Found gdbm in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/gdbm/gdbm_1.25_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  146k  100  146k    0     0  2652k      0 --:--:-- --:--:-- --:--:-- 2659k
extracting gdbm to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libandroid-posix-semaphore@0.1-3 if necessary...
Found libandroid-posix-semaphore in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libandroid-posix-semaphore/libandroid-posix-semaphore_0.1-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4128  100  4128    0     0  72760      0 --:--:-- --:--:-- --:--:-- 73714
extracting libandroid-posix-semaphore to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ca-certificates@1:2025.02.25 if necessary...
Found ca-certificates in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ca-certificates to /home/builder/.termux-build/_cache-all...
Downloading dependency ca-certificates-java@1:2025.02.25 if necessary...
Found ca-certificates-java in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ca-certificates-java to /home/builder/.termux-build/_cache-all...
Downloading dependency zlib@1.3.1 if necessary...
Found zlib in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting zlib to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency openssl@1:3.4.1 if necessary...
Found openssl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting openssl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency openssl-tool@1:3.4.1 if necessary...
Found openssl-tool in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting openssl-tool to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libcrypt@0.2-5 if necessary...
Found libcrypt in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libc/libcrypt/libcrypt_0.2-5_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  8720  100  8720    0     0   186k      0 --:--:-- --:--:-- --:--:--  189k
extracting libcrypt to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libexpat@2.7.1 if necessary...
Found libexpat in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libe/libexpat/libexpat_2.7.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 87760  100 87760    0     0  1576k      0 --:--:-- --:--:-- --:--:-- 1587k
extracting libexpat to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libffi@3.4.7 if necessary...
Found libffi in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libf/libffi/libffi_3.4.7_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 30588  100 30588    0     0   555k      0 --:--:-- --:--:-- --:--:--  563k
extracting libffi to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency tcl@8.6.14 if necessary...
Found tcl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/tcl/tcl_8.6.14_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2209k  100 2209k    0     0  26.7M      0 --:--:-- --:--:-- --:--:-- 26.9M
extracting tcl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libsqlite@3.49.2 if necessary...
Found libsqlite in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libs/libsqlite/libsqlite_3.49.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  5  617k    5 32429    0     0  67002      0  0:00:09 --:--:--  0:00:09 67002
100  617k  100  617k    0     0   676k      0 --:--:-- --:--:-- --:--:--  676k
extracting libsqlite to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency sqlite@3.49.2 if necessary...
Found sqlite in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/s/sqlite/sqlite_3.49.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  583k  100  583k    0     0  8350k      0 --:--:-- --:--:-- --:--:-- 8458k
extracting sqlite to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libsqlite-tcl@3.49.2 if necessary...
Found libsqlite-tcl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libs/libsqlite-tcl/libsqlite-tcl_3.49.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 17780  100 17780    0     0   314k      0 --:--:-- --:--:-- --:--:--  315k
extracting libsqlite-tcl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency python@3.12.10 if necessary...
Found python in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/python/python_3.12.10_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 7365k  100 7365k    0     0  81.8M      0 --:--:-- --:--:-- --:--:-- 82.6M
extracting python to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency make@4.4.1 if necessary...
Found make in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/m/make/make_4.4.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  233k  100  233k    0     0  3315k      0 --:--:-- --:--:-- --:--:-- 3340k
extracting make to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency pcre2@10.45 if necessary...
Found pcre2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/pcre2/pcre2_10.45_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  927k  100  927k    0     0   9.8M      0 --:--:-- --:--:-- --:--:--  9.9M
extracting pcre2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency pcre2grep@10.45 if necessary...
Found pcre2grep in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/pcre2grep/pcre2grep_10.45_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 33904  100 33904    0     0   593k      0 --:--:-- --:--:-- --:--:--  601k
extracting pcre2grep to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency resolv-conf@1.3 if necessary...
Found resolv-conf in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/r/resolv-conf/resolv-conf_1.3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   976  100   976    0     0  20508      0 --:--:-- --:--:-- --:--:-- 20765
extracting resolv-conf to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency glib@2.84.1-3 if necessary...
Found glib in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/glib/glib_2.84.1-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2483k  100 2483k    0     0  28.8M      0 --:--:-- --:--:-- --:--:-- 28.8M
extracting glib to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency glib-cross@2.84.1-3 if necessary...
Found glib-cross in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/glib-cross/glib-cross_2.84.1-3_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 11.4M  100 11.4M    0     0  94.9M      0 --:--:-- --:--:-- --:--:-- 95.4M
extracting glib-cross to /home/builder/.termux-build/_cache-all...
Downloading dependency pkg-config@0.29.2-2 if necessary...
Found pkg-config in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/pkg-config/pkg-config_0.29.2-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 31360  100 31360    0     0   612k      0 --:--:-- --:--:-- --:--:--  625k
extracting pkg-config to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency python-pip@25.1.1-1 if necessary...
Found python-pip in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/python-pip/python-pip_25.1.1-1_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2522k  100 2522k    0     0  26.7M      0 --:--:-- --:--:-- --:--:-- 27.0M
extracting python-pip to /home/builder/.termux-build/_cache-all...
Downloading dependency brotli@1.1.0-1 if necessary...
Found brotli in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/brotli/brotli_1.1.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 49  317k   49  157k    0     0  2451k      0 --:--:-- --:--:-- --:--:-- 2454k
100  317k  100  317k    0     0  4497k      0 --:--:-- --:--:-- --:--:-- 4466k
extracting brotli to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency python-brotli@1.1.0-1 if necessary...
Download of python-brotli@1.1.0-1 from https://packages-cf.termux.dev/apt/termux-main failed, building instead
brotli@1.1.0-1 built - skipping (rm /data/data/.built-packages/brotli to force rebuild)
Downloading dependency libpng@1.6.48 if necessary...
Found libpng in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libp/libpng/libpng_1.6.48_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  190k  100  190k    0     0   266k      0 --:--:-- --:--:-- --:--:--  266k
extracting libpng to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency freetype@2.13.3 if necessary...
Found freetype in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/f/freetype/freetype_2.13.3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  399k  100  399k    0     0  6685k      0 --:--:-- --:--:-- --:--:-- 6779k
extracting freetype to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ttf-dejavu@2.37-8 if necessary...
Found ttf-dejavu in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/ttf-dejavu/ttf-dejavu_2.37-8_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2410k  100 2410k    0     0  30.4M      0 --:--:-- --:--:-- --:--:-- 30.5M
extracting ttf-dejavu to /home/builder/.termux-build/_cache-all...
Downloading dependency fontconfig@2.16.2 if necessary...
Found fontconfig in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/f/fontconfig/fontconfig_2.16.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  119k  100  119k    0     0  2000k      0 --:--:-- --:--:-- --:--:-- 2033k
extracting fontconfig to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency fontconfig-utils@2.16.2 if necessary...
Found fontconfig-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/f/fontconfig-utils/fontconfig-utils_2.16.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 14432  100 14432    0     0   210k      0 --:--:-- --:--:-- --:--:--  213k
extracting fontconfig-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xorg-util-macros@1.20.2 if necessary...
Found xorg-util-macros in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/x/xorg-util-macros/xorg-util-macros_1.20.2_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 21948  100 21948    0     0   352k      0 --:--:-- --:--:-- --:--:--  357k
extracting xorg-util-macros to /home/builder/.termux-build/_cache-all...
Downloading dependency xorgproto@2024.1 if necessary...
Found xorgproto in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/x/xorgproto/xorgproto_2024.1_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  243k  100  243k    0     0  3934k      0 --:--:-- --:--:-- --:--:-- 3994k
extracting xorgproto to /home/builder/.termux-build/_cache-all...
Downloading dependency libxau@1.0.12 if necessary...
Found libxau in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxau/libxau_1.0.12_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  9120  100  9120    0     0  23801      0 --:--:-- --:--:-- --:--:-- 23750
extracting libxau to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxdmcp@1.1.5 if necessary...
Found libxdmcp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxdmcp/libxdmcp_1.1.5_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 24352  100 24352    0     0   361k      0 --:--:-- --:--:-- --:--:--  365k
extracting libxdmcp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xcb-proto@1.17.0-1 if necessary...
Found xcb-proto in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/x/xcb-proto/xcb-proto_1.17.0-1_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 78616  100 78616    0     0  1563k      0 --:--:-- --:--:-- --:--:-- 1566k
extracting xcb-proto to /home/builder/.termux-build/_cache-all...
Downloading dependency python-xcbgen@1.17.0-1 if necessary...
Found python-xcbgen in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/python-xcbgen/python-xcbgen_1.17.0-1_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 44572  100 44572    0     0   865k      0 --:--:-- --:--:-- --:--:--  870k
extracting python-xcbgen to /home/builder/.termux-build/_cache-all...
Downloading dependency libxcb@1.17.0 if necessary...
Found libxcb in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxcb/libxcb_1.17.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  913k  100  913k    0     0  10.8M      0 --:--:-- --:--:-- --:--:-- 11.0M
extracting libxcb to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xtrans@1.6.0 if necessary...
Found xtrans in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/x/xtrans/xtrans_1.6.0_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 39892  100 39892    0     0   569k      0 --:--:-- --:--:-- --:--:--  564k
extracting xtrans to /home/builder/.termux-build/_cache-all...
Downloading dependency libx11@1.8.12 if necessary...
Found libx11 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libx11/libx11_1.8.12_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1867k  100 1867k    0     0  20.6M      0 --:--:-- --:--:-- --:--:-- 20.7M
extracting libx11 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxrender@0.9.12 if necessary...
Found libxrender in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxrender/libxrender_0.9.12_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 24568  100 24568    0     0   511k      0 --:--:-- --:--:-- --:--:--  521k
extracting libxrender to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxft@2.3.9 if necessary...
Found libxft in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxft/libxft_2.3.9_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 47884  100 47884    0     0   965k      0 --:--:-- --:--:-- --:--:--  974k
extracting libxft to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxext@1.3.6 if necessary...
Found libxext in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxext/libxext_1.3.6_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 97968  100 97968    0     0  1750k      0 --:--:-- --:--:-- --:--:-- 1771k
extracting libxext to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxss@1.2.4 if necessary...
Found libxss in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxss/libxss_1.2.4_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 11924  100 11924    0     0  24445      0 --:--:-- --:--:-- --:--:-- 24434
100 11924  100 11924    0     0  24440      0 --:--:-- --:--:-- --:--:-- 24434
extracting libxss to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency tk@8.6.14 if necessary...
Found tk in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/tk/tk_8.6.14_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1715k  100 1715k    0     0  18.3M      0 --:--:-- --:--:-- --:--:-- 18.4M
extracting tk to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency python-tkinter@3.12.10 if necessary...
Found python-tkinter in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/python-tkinter/python-tkinter_3.12.10_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1188k  100 1188k    0     0  12.9M      0 --:--:-- --:--:-- --:--:-- 13.0M
extracting python-tkinter to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency python-ensurepip-wheels@3.12.10 if necessary...
Found python-ensurepip-wheels in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/python-ensurepip-wheels/python-ensurepip-wheels_3.12.10_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1759k  100 1759k    0     0  24.1M      0 --:--:-- --:--:-- --:--:-- 24.5M
extracting python-ensurepip-wheels to /home/builder/.termux-build/_cache-all...
Downloading dependency boost@1:1.87.0-1 if necessary...
Found boost in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/boost/boost_1:1.87.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1416k  100 1416k    0     0  3441k      0 --:--:-- --:--:-- --:--:-- 3439k
extracting boost to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency boost-headers@1:1.87.0-1 if necessary...
Found boost-headers in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/boost-headers/boost-headers_1:1.87.0-1_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  9.9M  100  9.9M    0     0  22.7M      0 --:--:-- --:--:-- --:--:-- 22.7M
extracting boost-headers to /home/builder/.termux-build/_cache-all...
Downloading dependency fribidi@1.0.16 if necessary...
Found fribidi in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/f/fribidi/fribidi_1.0.16_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 64536  100 64536    0     0   945k      0 --:--:-- --:--:-- --:--:--  954k
extracting fribidi to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency game-music-emu@0.6.4 if necessary...
Found game-music-emu in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/game-music-emu/game-music-emu_0.6.4_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  129k  100  129k    0     0  2341k      0 --:--:-- --:--:-- --:--:-- 2360k
extracting game-music-emu to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libandroid-selinux@14.0.0.11 if necessary...
Found libandroid-selinux in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libandroid-selinux/libandroid-selinux_14.0.0.11_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 59652  100 59652    0     0   949k      0 --:--:-- --:--:-- --:--:--  954k
extracting libandroid-selinux to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libgmp@6.3.0-1 if necessary...
Found libgmp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libg/libgmp/libgmp_6.3.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  320k  100  320k    0     0  5056k      0 --:--:-- --:--:-- --:--:-- 5086k
extracting libgmp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency coreutils@9.6-1 if necessary...
Found coreutils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/c/coreutils/coreutils_9.6-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  761k  100  761k    0     0  10.8M      0 --:--:-- --:--:-- --:--:-- 10.9M
extracting coreutils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libnghttp2@1.65.0 if necessary...
Found libnghttp2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libnghttp2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libnghttp3@1.9.0 if necessary...
Found libnghttp3 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libnghttp3 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libssh2@1.11.1 if necessary...
Found libssh2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libssh2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libcurl@8.13.0 if necessary...
Found libcurl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting libcurl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency curl@8.13.0 if necessary...
Found curl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting curl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency dash@0.5.12 if necessary...
Found dash in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/d/dash/dash_0.5.12_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 65180  100 65180    0     0   165k      0 --:--:-- --:--:-- --:--:--  165k
extracting dash to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency dialog@1.3-20240307-0 if necessary...
Found dialog in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/d/dialog/dialog_1.3-20240307-0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 48   98k   48 48813    0     0  82545      0  0:00:01 --:--:--  0:00:01 82454
100   98k  100   98k    0     0   140k      0 --:--:-- --:--:-- --:--:--  140k
extracting dialog to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency diffutils@3.12 if necessary...
Found diffutils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/d/diffutils/diffutils_3.12_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  159k  100  159k    0     0  2695k      0 --:--:-- --:--:-- --:--:-- 2742k
extracting diffutils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency findutils@4.10.0 if necessary...
Found findutils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/f/findutils/findutils_4.10.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  245k  100  245k    0     0  3985k      0 --:--:-- --:--:-- --:--:-- 4027k
extracting findutils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libmpfr@4.2.1 if necessary...
Found libmpfr in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libm/libmpfr/libmpfr_4.2.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  264k  100  264k    0     0  4007k      0 --:--:-- --:--:-- --:--:-- 4014k
extracting libmpfr to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency gawk@5.3.1 if necessary...
Found gawk in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/gawk/gawk_5.3.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  767k  100  767k    0     0  8616k      0 --:--:-- --:--:-- --:--:-- 8717k
extracting gawk to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency grep@3.12 if necessary...
Found grep in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/grep/grep_3.12_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  125k  100  125k    0     0  2173k      0 --:--:-- --:--:-- --:--:-- 2197k
extracting grep to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency gzip@1.14 if necessary...
Found gzip in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/gzip/gzip_1.14_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 87792  100 87792    0     0  1230k      0 --:--:-- --:--:-- --:--:-- 1242k
extracting gzip to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency less@668 if necessary...
Found less in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/l/less/less_668_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  122k  100  122k    0     0  2101k      0 --:--:-- --:--:-- --:--:-- 2113k
extracting less to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency procps@3.3.17-5 if necessary...
Found procps in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/procps/procps_3.3.17-5_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  138k  100  138k    0     0  1301k      0 --:--:-- --:--:-- --:--:-- 1305k
extracting procps to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency psmisc@23.7 if necessary...
Found psmisc in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/psmisc/psmisc_23.7_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 41316  100 41316    0     0  69122      0 --:--:-- --:--:-- --:--:-- 69206
extracting psmisc to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency sed@4.9-1 if necessary...
Found sed in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/s/sed/sed_4.9-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  114k  100  114k    0     0  1866k      0 --:--:-- --:--:-- --:--:-- 1872k
extracting sed to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libandroid-glob@0.6-2 if necessary...
Found libandroid-glob in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libandroid-glob/libandroid-glob_0.6-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  6802  100  6802    0     0  17004      0 --:--:-- --:--:-- --:--:-- 17047
extracting libandroid-glob to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency tar@1.35 if necessary...
Found tar in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/tar/tar_1.35_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  332k  100  332k    0     0  4420k      0 --:--:-- --:--:-- --:--:-- 4431k
extracting tar to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency termux-am@0.8.0-1 if necessary...
Found termux-am in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/termux-am/termux-am_0.8.0-1_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  563k  100  563k    0     0  6286k      0 --:--:-- --:--:-- --:--:-- 6334k
extracting termux-am to /home/builder/.termux-build/_cache-all...
Downloading dependency termux-am-socket@1.5.0 if necessary...
Found termux-am-socket in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/termux-am-socket/termux-am-socket_1.5.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 15672  100 15672    0     0   322k      0 --:--:-- --:--:-- --:--:--  325k
extracting termux-am-socket to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency termux-core@0.4.0 if necessary...
Found termux-core in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/termux-core/termux-core_0.4.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  193k  100  193k    0     0  3294k      0 --:--:-- --:--:-- --:--:-- 3335k
extracting termux-core to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency termux-core-static@0.4.0 if necessary...
Found termux-core-static in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/termux-core-static/termux-core-static_0.4.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 20164  100 20164    0     0   409k      0 --:--:-- --:--:-- --:--:--  410k
extracting termux-core-static to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency termux-exec@1:2.4.0 if necessary...
Found termux-exec in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/termux-exec/termux-exec_1:2.4.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  368k  100  368k    0     0  4792k      0 --:--:-- --:--:-- --:--:-- 4850k
extracting termux-exec to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libblkid@2.40.2-3 if necessary...
Found libblkid in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libb/libblkid/libblkid_2.40.2-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  121k  100  121k    0     0   173k      0 --:--:-- --:--:-- --:--:--  173k
extracting libblkid to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libmount@2.40.2-3 if necessary...
Found libmount in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libm/libmount/libmount_2.40.2-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  142k  100  142k    0     0   376k      0 --:--:-- --:--:-- --:--:--  377k
extracting libmount to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libsmartcols@2.40.2-3 if necessary...
Found libsmartcols in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libs/libsmartcols/libsmartcols_2.40.2-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 97932  100 97932    0     0  1861k      0 --:--:-- --:--:-- --:--:-- 1875k
extracting libsmartcols to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libuuid@2.40.2-3 if necessary...
Found libuuid in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libu/libuuid/libuuid_2.40.2-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 14964  100 14964    0     0   230k      0 --:--:-- --:--:-- --:--:--  231k
extracting libuuid to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libfdisk@2.40.2-3 if necessary...
Found libfdisk in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libf/libfdisk/libfdisk_2.40.2-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 27  152k   27 43702    0     0   108k      0  0:00:01 --:--:--  0:00:01  108k
100  152k  100  152k    0     0   382k      0 --:--:-- --:--:-- --:--:--  382k
extracting libfdisk to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libcap-ng@2:0.8.5 if necessary...
Found libcap-ng in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libc/libcap-ng/libcap-ng_2:0.8.5_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 35820  100 35820    0     0   700k      0 --:--:-- --:--:-- --:--:--  713k
extracting libcap-ng to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency util-linux@2.40.2-3 if necessary...
Found util-linux in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/u/util-linux/util-linux_2.40.2-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  688k  100  688k    0     0  7254k      0 --:--:-- --:--:-- --:--:-- 7320k
extracting util-linux to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency uuid-utils@2.40.2-3 if necessary...
Found uuid-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/u/uuid-utils/uuid-utils_2.40.2-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 40676  100 40676    0     0  68352      0 --:--:-- --:--:-- --:--:-- 68363
100 40676  100 40676    0     0  68343      0 --:--:-- --:--:-- --:--:-- 68248
extracting uuid-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency mount-utils@2.40.2-3 if necessary...
Found mount-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/m/mount-utils/mount-utils_2.40.2-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  129k  100  129k    0     0   339k      0 --:--:-- --:--:-- --:--:--  340k
extracting mount-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency fdisk@2.40.2-3 if necessary...
Found fdisk in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/f/fdisk/fdisk_2.40.2-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  109k  100  109k    0     0  1539k      0 --:--:-- --:--:-- --:--:-- 1542k
extracting fdisk to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency blk-utils@2.40.2-3 if necessary...
Found blk-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/blk-utils/blk-utils_2.40.2-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  172k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  172k  100  172k    0     0   243k      0 --:--:-- --:--:-- --:--:--  243k
extracting blk-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency termux-tools@1.45.0 if necessary...
Found termux-tools in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/termux-tools/termux-tools_1.45.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 33560  100 33560    0     0   428k      0 --:--:-- --:--:-- --:--:--  431k
extracting termux-tools to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency bash@5.2.37-2 if necessary...
Found bash in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/bash/bash_5.2.37-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  860k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  860k  100  860k    0     0   853k      0  0:00:01  0:00:01 --:--:--  854k
extracting bash to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency binutils-bin@2.44-3 if necessary...
Found binutils-bin in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/binutils-bin/binutils-bin_2.44-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1724k  100 1724k    0     0  20.7M      0 --:--:-- --:--:-- --:--:-- 21.0M
extracting binutils-bin to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency zstd@1.5.7 if necessary...
Found zstd in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/z/zstd/zstd_1.5.7_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  354k  100  354k    0     0   444k      0 --:--:-- --:--:-- --:--:--  444k
extracting zstd to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency pzstd@1.5.7 if necessary...
Found pzstd in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/pzstd/pzstd_1.5.7_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 42796  100 42796    0     0   549k      0 --:--:-- --:--:-- --:--:--  557k
extracting pzstd to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency binutils-libs@2.44-3 if necessary...
Found binutils-libs in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/binutils-libs/binutils-libs_2.44-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1111k  100 1111k    0     0  1082k      0  0:00:01  0:00:01 --:--:-- 1083k
extracting binutils-libs to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency binutils-gold@2.44-3 if necessary...
Found binutils-gold in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/binutils-gold/binutils-gold_2.44-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  898k  100  898k    0     0  12.9M      0 --:--:-- --:--:-- --:--:-- 13.1M
extracting binutils-gold to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency binutils-cross@2.44-3 if necessary...
Found binutils-cross in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/binutils-cross/binutils-cross_2.44-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2171k  100 2171k    0     0  27.2M      0 --:--:-- --:--:-- --:--:-- 27.5M
extracting binutils-cross to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency binutils@2.44-3 if necessary...
Found binutils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/binutils/binutils_2.44-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1124  100  1124    0     0  21710      0 --:--:-- --:--:-- --:--:-- 22039
extracting binutils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ldd@0.3 if necessary...
Found ldd in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/l/ldd/ldd_0.3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1844  100  1844    0     0  39530      0 --:--:-- --:--:-- --:--:-- 40086
extracting ldd to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency gobject-introspection@1.84.0 if necessary...
Found gobject-introspection in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/gobject-introspection/gobject-introspection_1.84.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  198k  100  198k    0     0  2596k      0 --:--:-- --:--:-- --:--:-- 2610k
extracting gobject-introspection to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency g-ir-scanner@1.84.0 if necessary...
Found g-ir-scanner in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/g-ir-scanner/g-ir-scanner_1.84.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  125k  100  125k    0     0   178k      0 --:--:-- --:--:-- --:--:--  178k
extracting g-ir-scanner to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libandroid-execinfo@0.1-1 if necessary...
Found libandroid-execinfo in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libandroid-execinfo/libandroid-execinfo_0.1-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 14192  100 14192    0     0   225k      0 --:--:-- --:--:-- --:--:--  227k
extracting libandroid-execinfo to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libandroid-shmem@0.5 if necessary...
Found libandroid-shmem in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libandroid-shmem/libandroid-shmem_0.5_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  6960  100  6960    0     0  18714      0 --:--:-- --:--:-- --:--:-- 18709
100  6960  100  6960    0     0  18709      0 --:--:-- --:--:-- --:--:-- 18709
extracting libandroid-shmem to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency liblzo@2.10-3 if necessary...
Found liblzo in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libl/liblzo/liblzo_2.10-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 65316  100 65316    0     0   169k      0 --:--:-- --:--:-- --:--:--  169k
extracting liblzo to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libpixman@0.46.0 if necessary...
Found libpixman in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libp/libpixman/libpixman_0.46.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  152k  100  152k    0     0  2951k      0 --:--:-- --:--:-- --:--:-- 2995k
extracting libpixman to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libcairo@1.18.4-1 if necessary...
Found libcairo in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libc/libcairo/libcairo_1.18.4-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 14  474k   14 68949    0     0   175k      0  0:00:02 --:--:--  0:00:02  175k
100  474k  100  474k    0     0  1190k      0 --:--:-- --:--:-- --:--:-- 1189k
extracting libcairo to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libgraphite@1.3.14-2 if necessary...
Found libgraphite in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libg/libgraphite/libgraphite_1.3.14-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 78600  100 78600    0     0   127k      0 --:--:-- --:--:-- --:--:--  127k
extracting libgraphite to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libicu@77.1-1 if necessary...
Found libicu in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libi/libicu/libicu_77.1-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 9705k  100 9705k    0     0  96.2M      0 --:--:-- --:--:-- --:--:-- 96.7M
extracting libicu to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency icu-devtools@77.1-1 if necessary...
Found icu-devtools in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/i/icu-devtools/icu-devtools_77.1-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  207k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  207k  100  207k    0     0   258k      0 --:--:-- --:--:-- --:--:--  258k
extracting icu-devtools to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency harfbuzz@11.2.0 if necessary...
Found harfbuzz in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/h/harfbuzz/harfbuzz_11.2.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  4  697k    4 32429    0     0  67986      0  0:00:10 --:--:--  0:00:10 67985
100  697k  100  697k    0     0   772k      0 --:--:-- --:--:-- --:--:--  771k
extracting harfbuzz to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency harfbuzz-utils@11.2.0 if necessary...
Found harfbuzz-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/h/harfbuzz-utils/harfbuzz-utils_11.2.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 57472  100 57472    0     0   987k      0 --:--:-- --:--:-- --:--:-- 1002k
extracting harfbuzz-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency harfbuzz-icu@11.2.0 if necessary...
Found harfbuzz-icu in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/h/harfbuzz-icu/harfbuzz-icu_11.2.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  5628  100  5628    0     0   102k      0 --:--:-- --:--:-- --:--:--  103k
extracting harfbuzz-icu to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libandroid-stub@27c-3 if necessary...
Found libandroid-stub in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libandroid-stub/libandroid-stub_27c-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 21024  100 21024    0     0  55685      0 --:--:-- --:--:-- --:--:-- 55619
100 21024  100 21024    0     0  55672      0 --:--:-- --:--:-- --:--:-- 55619
extracting libandroid-stub to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libaom@3.12.1 if necessary...
Found libaom in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libaom/libaom_3.12.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1880k  100 1880k    0     0  25.9M      0 --:--:-- --:--:-- --:--:-- 26.2M
extracting libaom to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency aom-tools@3.12.1 if necessary...
Found aom-tools in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/a/aom-tools/aom-tools_3.12.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  192k  100  192k    0     0   402k      0 --:--:-- --:--:-- --:--:--  403k
extracting aom-tools to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libass@0.17.3 if necessary...
Found libass in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libass/libass_0.17.3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 86052  100 86052    0     0   139k      0 --:--:-- --:--:-- --:--:--  139k
extracting libass to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libudfread@1.1.2 if necessary...
Found libudfread in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libu/libudfread/libudfread_1.1.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 14360  100 14360    0     0  30109      0 --:--:-- --:--:-- --:--:-- 30104
100 14360  100 14360    0     0  30104      0 --:--:-- --:--:-- --:--:-- 30104
extracting libudfread to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxml2@2.14.2-1 if necessary...
Found libxml2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxml2/libxml2_2.14.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  441k  100  441k    0     0  7263k      0 --:--:-- --:--:-- --:--:-- 7359k
extracting libxml2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxml2-utils@2.14.2-1 if necessary...
Found libxml2-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxml2-utils/libxml2-utils_2.14.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 34008  100 34008    0     0   671k      0 --:--:-- --:--:-- --:--:--  677k
extracting libxml2-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxml2-python@2.14.2-1 if necessary...
Found libxml2-python in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxml2-python/libxml2-python_2.14.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  171k  100  171k    0     0   349k      0 --:--:-- --:--:-- --:--:--  349k
extracting libxml2-python to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxml2-python-static@2.14.2-1 if necessary...
Found libxml2-python-static in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxml2-python-static/libxml2-python-static_2.14.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 63816  100 63816    0     0   947k      0 --:--:-- --:--:-- --:--:--  944k
100 63816  100 63816    0     0   946k      0 --:--:-- --:--:-- --:--:--  944k
extracting libxml2-python-static to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libbluray@1.3.4-2 if necessary...
Found libbluray in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libb/libbluray/libbluray_1.3.4-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  106k  100  106k    0     0   152k      0 --:--:-- --:--:-- --:--:--  152k
extracting libbluray to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libbluray-utils@1.3.4-2 if necessary...
Found libbluray-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libb/libbluray-utils/libbluray-utils_1.3.4-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  7276  100  7276    0     0   122k      0 --:--:-- --:--:-- --:--:--  124k
extracting libbluray-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libdav1d@1.5.1 if necessary...
Found libdav1d in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libd/libdav1d/libdav1d_1.5.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  284k  100  284k    0     0  4471k      0 --:--:-- --:--:-- --:--:-- 4514k
extracting libdav1d to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libunistring@1.3 if necessary...
Found libunistring in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libu/libunistring/libunistring_1.3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  535k  100  535k    0     0   587k      0 --:--:-- --:--:-- --:--:--  587k
extracting libunistring to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libidn2@2.3.7 if necessary...
Found libidn2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libi/libidn2/libidn2_2.3.7_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  102k  100  102k    0     0  1480k      0 --:--:-- --:--:-- --:--:-- 1489k
extracting libidn2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libnettle@3.10.1 if necessary...
Found libnettle in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libn/libnettle/libnettle_3.10.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  397k  100  397k    0     0  5473k      0 --:--:-- --:--:-- --:--:-- 5526k
extracting libnettle to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency nettle@3.10.1 if necessary...
Found nettle in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/n/nettle/nettle_3.10.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 18176  100 18176    0     0  45915      0 --:--:-- --:--:-- --:--:-- 46015
extracting nettle to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libevent@2.1.12-2 if necessary...
Found libevent in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libe/libevent/libevent_2.1.12-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  194k  100  194k    0     0  2456k      0 --:--:-- --:--:-- --:--:-- 2464k
extracting libevent to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency swig@4.3.1 if necessary...
Found swig in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/s/swig/swig_4.3.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  911k  100  911k    0     0  2255k      0 --:--:-- --:--:-- --:--:-- 2251k
extracting swig to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libunbound@1.23.0 if necessary...
Found libunbound in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libu/libunbound/libunbound_1.23.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  356k  100  356k    0     0  5089k      0 --:--:-- --:--:-- --:--:-- 5165k
extracting libunbound to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency unbound@1.23.0 if necessary...
Found unbound in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/u/unbound/unbound_1.23.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  599k  100  599k    0     0  8994k      0 --:--:-- --:--:-- --:--:-- 9086k
extracting unbound to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency pyunbound@1.23.0 if necessary...
Found pyunbound in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/pyunbound/pyunbound_1.23.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 39764  100 39764    0     0  66130      0 --:--:-- --:--:-- --:--:-- 66053
100 39764  100 39764    0     0  66120      0 --:--:-- --:--:-- --:--:-- 66053
extracting pyunbound to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libgnutls@3.8.9 if necessary...
Found libgnutls in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libg/libgnutls/libgnutls_3.8.9_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  719k  100  719k    0     0  8614k      0 --:--:-- --:--:-- --:--:-- 8663k
extracting libgnutls to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency gnutls@3.8.9 if necessary...
Found gnutls in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/gnutls/gnutls_3.8.9_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 18  171k   18 32429    0     0  66955      0  0:00:02 --:--:--  0:00:02 66863
100  171k  100  171k    0     0   244k      0 --:--:-- --:--:-- --:--:--  244k
extracting gnutls to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libmp3lame@3.100-6 if necessary...
Found libmp3lame in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libm/libmp3lame/libmp3lame_3.100-6_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  112k  100  112k    0     0  1608k      0 --:--:-- --:--:-- --:--:-- 1632k
extracting libmp3lame to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency lame@3.100-6 if necessary...
Found lame in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/l/lame/lame_3.100-6_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  188k  100  188k    0     0  2483k      0 --:--:-- --:--:-- --:--:-- 2507k
extracting lame to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libopencore-amr@0.1.6 if necessary...
Found libopencore-amr in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libo/libopencore-amr/libopencore-amr_0.1.6_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  108k  100  108k    0     0  1927k      0 --:--:-- --:--:-- --:--:-- 1936k
extracting libopencore-amr to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libogg@1.3.5 if necessary...
Found libogg in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libo/libogg/libogg_1.3.5_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  183k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  183k  100  183k    0     0   260k      0 --:--:-- --:--:-- --:--:--  260k
extracting libogg to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libflac@1.5.0 if necessary...
Found libflac in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libf/libflac/libflac_1.5.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  198k  100  198k    0     0  2551k      0 --:--:-- --:--:-- --:--:-- 2577k
extracting libflac to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency flac@1.5.0 if necessary...
Found flac in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/f/flac/flac_1.5.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 30  103k   30 32429    0     0  66474      0  0:00:01 --:--:--  0:00:01 66452
100  103k  100  103k    0     0   147k      0 --:--:-- --:--:-- --:--:--  147k
extracting flac to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libopus@1.5.2 if necessary...
Found libopus in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libo/libopus/libopus_1.5.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  182k  100  182k    0     0  3107k      0 --:--:-- --:--:-- --:--:-- 3139k
extracting libopus to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libvorbis@1.3.7-2 if necessary...
Found libvorbis in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libv/libvorbis/libvorbis_1.3.7-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  255k  100  255k    0     0  3369k      0 --:--:-- --:--:-- --:--:-- 3413k
extracting libvorbis to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libsndfile@1.2.2-1 if necessary...
Found libsndfile in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libs/libsndfile/libsndfile_1.2.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  211k  100  211k    0     0  2898k      0 --:--:-- --:--:-- --:--:-- 2940k
extracting libsndfile to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libtool@2.5.4-1 if necessary...
Found libtool in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libt/libtool/libtool_2.5.4-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  382k  100  382k    0     0  4866k      0 --:--:-- --:--:-- --:--:-- 4899k
extracting libtool to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libltdl@2.5.4-1 if necessary...
Found libltdl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libl/libltdl/libltdl_2.5.4-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 18020  100 18020    0     0   217k      0 --:--:-- --:--:-- --:--:--  217k
extracting libltdl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libandroid-utimes@0.4 if necessary...
Found libandroid-utimes in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libandroid-utimes/libandroid-utimes_0.4_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3120  100  3120    0     0   7914      0 --:--:-- --:--:-- --:--:--  7918
extracting libandroid-utimes to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency perl@5.38.2-3 if necessary...
Found perl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/perl/perl_5.38.2-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 20 13.5M   20 2783k    0     0  6476k      0  0:00:02 --:--:--  0:00:02 6472k
100 13.5M  100 13.5M    0     0  29.1M      0 --:--:-- --:--:-- --:--:-- 29.1M
extracting perl to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency texinfo@7.2-2 if necessary...
Found texinfo in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/t/texinfo/texinfo_7.2-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1056k  100 1056k    0     0  15.8M      0 --:--:-- --:--:-- --:--:-- 15.6M
extracting texinfo to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency update-info-dir@7.2-2 if necessary...
Found update-info-dir in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/u/update-info-dir/update-info-dir_7.2-2_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2464  100  2464    0     0   6602      0 --:--:-- --:--:-- --:--:--  6605
extracting update-info-dir to /home/builder/.termux-build/_cache-all...
Downloading dependency check@0.15.2-2 if necessary...
Found check in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/c/check/check_0.15.2-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 96468  100 96468    0     0  1660k      0 --:--:-- --:--:-- --:--:-- 1682k
extracting check to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency dbus@1.16.2-1 if necessary...
Found dbus in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/d/dbus/dbus_1.16.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  419k  100  419k    0     0  6943k      0 --:--:-- --:--:-- --:--:-- 6988k
extracting dbus to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libsoxr@0.1.3-7 if necessary...
Found libsoxr in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libs/libsoxr/libsoxr_0.1.3-7_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  276k  100  276k    0     0  3525k      0 --:--:-- --:--:-- --:--:-- 3543k
extracting libsoxr to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libwebrtc-audio-processing@1.3-2 if necessary...
Found libwebrtc-audio-processing in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libw/libwebrtc-audio-processing/libwebrtc-audio-processing_1.3-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  404k  100  404k    0     0   471k      0 --:--:-- --:--:-- --:--:--  470k
extracting libwebrtc-audio-processing to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency speexdsp@1.2.1 if necessary...
Found speexdsp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/s/speexdsp/speexdsp_1.2.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 37104  100 37104    0     0   640k      0 --:--:-- --:--:-- --:--:--  647k
extracting speexdsp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency pulseaudio@17.0-1 if necessary...
Found pulseaudio in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/pulseaudio/pulseaudio_17.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  824k  100  824k    0     0  11.8M      0 --:--:-- --:--:-- --:--:-- 12.0M
extracting pulseaudio to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency pulseaudio-glib@17.0-1 if necessary...
Found pulseaudio-glib in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/pulseaudio-glib/pulseaudio-glib_17.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  6948  100  6948    0     0   143k      0 --:--:-- --:--:-- --:--:--  144k
extracting pulseaudio-glib to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency mpg123@1.32.10 if necessary...
Found mpg123 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/m/mpg123/mpg123_1.32.10_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  256k  100  256k    0     0  4384k      0 --:--:-- --:--:-- --:--:-- 4420k
extracting mpg123 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libopenmpt@0.7.13 if necessary...
Found libopenmpt in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libo/libopenmpt/libopenmpt_0.7.13_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  562k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  562k  100  562k    0     0   621k      0 --:--:-- --:--:-- --:--:--  621k
extracting libopenmpt to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency librav1e@0.7.1-3 if necessary...
Found librav1e in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libr/librav1e/librav1e_0.7.1-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 12  646k   12 81581    0     0   137k      0  0:00:04 --:--:--  0:00:04  137k
100  646k  100  646k    0     0   715k      0 --:--:-- --:--:-- --:--:--  715k
extracting librav1e to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency rav1e@0.7.1-3 if necessary...
Found rav1e in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/r/rav1e/rav1e_0.7.1-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  952k  100  952k    0     0  8946k      0 --:--:-- --:--:-- --:--:-- 8989k
extracting rav1e to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libsrt@1.5.4 if necessary...
Found libsrt in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libs/libsrt/libsrt_1.5.4_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  262k  100  262k    0     0  3747k      0 --:--:-- --:--:-- --:--:-- 3754k
extracting libsrt to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency srt-tools@1.5.4 if necessary...
Found srt-tools in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/s/srt-tools/srt-tools_1.5.4_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  128k  100  128k    0     0  2376k      0 --:--:-- --:--:-- --:--:-- 2423k
extracting srt-tools to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libssh@0.11.1 if necessary...
Found libssh in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libs/libssh/libssh_0.11.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  199k  100  199k    0     0  3496k      0 --:--:-- --:--:-- --:--:-- 3504k
extracting libssh to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libtheora@1.1.1-1 if necessary...
Found libtheora in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libt/libtheora/libtheora_1.1.1-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  135k  100  135k    0     0  1816k      0 --:--:-- --:--:-- --:--:-- 1832k
extracting libtheora to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency argp@1.5.0 if necessary...
Found argp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/a/argp/argp_1.5.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 21164  100 21164    0     0  53221      0 --:--:-- --:--:-- --:--:-- 53309
extracting argp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libjpeg-turbo@3.1.0 if necessary...
Found libjpeg-turbo in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libj/libjpeg-turbo/libjpeg-turbo_3.1.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  372k  100  372k    0     0  5746k      0 --:--:-- --:--:-- --:--:-- 5817k
extracting libjpeg-turbo to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libjpeg-turbo-progs@3.1.0 if necessary...
Found libjpeg-turbo-progs in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libj/libjpeg-turbo-progs/libjpeg-turbo-progs_3.1.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 71 97580   71 70013    0     0   182k      0 --:--:-- --:--:-- --:--:--  182k
100 97580  100 97580    0     0   251k      0 --:--:-- --:--:-- --:--:--  250k
extracting libjpeg-turbo-progs to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libv4l@1.24.1-1 if necessary...
Found libv4l in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libv/libv4l/libv4l_1.24.1-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 94620  100 94620    0     0  1698k      0 --:--:-- --:--:-- --:--:-- 1711k
extracting libv4l to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libvidstab@1.1.1-1 if necessary...
Found libvidstab in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libv/libvidstab/libvidstab_1.1.1-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  253k  100  253k    0     0  3217k      0 --:--:-- --:--:-- --:--:-- 3249k
extracting libvidstab to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libvmaf@3.0.0 if necessary...
Found libvmaf in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libv/libvmaf/libvmaf_3.0.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  157k  100  157k    0     0  2017k      0 --:--:-- --:--:-- --:--:-- 2040k
extracting libvmaf to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libvo-amrwbenc@0.1.3 if necessary...
Found libvo-amrwbenc in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libv/libvo-amrwbenc/libvo-amrwbenc_0.1.3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 52764  100 52764    0     0   677k      0 --:--:-- --:--:-- --:--:--  677k
extracting libvo-amrwbenc to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libvpx@1:1.15.0-1 if necessary...
Found libvpx in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libv/libvpx/libvpx_1:1.15.0-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  828k  100  828k    0     0  12.0M      0 --:--:-- --:--:-- --:--:-- 12.2M
extracting libvpx to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency giflib@5.2.2 if necessary...
Found giflib in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/giflib/giflib_5.2.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 18152  100 18152    0     0   304k      0 --:--:-- --:--:-- --:--:--  305k
extracting giflib to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency giflib-utils@5.2.2 if necessary...
Found giflib-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/g/giflib-utils/giflib-utils_5.2.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 50444  100 50444    0     0   284k      0 --:--:-- --:--:-- --:--:--  283k
extracting giflib-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libtiff@4.7.0 if necessary...
Found libtiff in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libt/libtiff/libtiff_4.7.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  893k  100  893k    0     0  10.7M      0 --:--:-- --:--:-- --:--:-- 10.7M
extracting libtiff to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libtiff-utils@4.7.0 if necessary...
Found libtiff-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libt/libtiff-utils/libtiff-utils_4.7.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 38  249k   38 97965    0     0   138k      0  0:00:01 --:--:--  0:00:01  138k
100  249k  100  249k    0     0   311k      0 --:--:-- --:--:-- --:--:--  311k
extracting libtiff-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libwebp@1.5.0 if necessary...
Found libwebp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libw/libwebp/libwebp_1.5.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  217k  100  217k    0     0  3663k      0 --:--:-- --:--:-- --:--:-- 3681k
extracting libwebp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libx264@1:0.164.3191 if necessary...
Found libx264 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libx264/libx264_1:0.164.3191_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  386k  100  386k    0     0  6257k      0 --:--:-- --:--:-- --:--:-- 6338k
extracting libx264 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency x264@1:0.164.3191 if necessary...
Found x264 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/x/x264/x264_1:0.164.3191_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  401k  100  401k    0     0  6157k      0 --:--:-- --:--:-- --:--:-- 6181k
extracting x264 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libx265@4.1 if necessary...
Found libx265 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libx265/libx265_4.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  689k  100  689k    0     0   9.8M      0 --:--:-- --:--:-- --:--:--  9.9M
extracting libx265 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency x265@4.1 if necessary...
Found x265 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/x/x265/x265_4.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 42208  100 42208    0     0  72398      0 --:--:-- --:--:-- --:--:-- 72397
extracting x265 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libzimg@3.0.5 if necessary...
Found libzimg in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libz/libzimg/libzimg_3.0.5_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  131k  100  131k    0     0  1924k      0 --:--:-- --:--:-- --:--:-- 1936k
extracting libzimg to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libsodium@1.0.20 if necessary...
Found libsodium in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libs/libsodium/libsodium_1.0.20_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  116k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  116k  100  116k    0     0   165k      0 --:--:-- --:--:-- --:--:--  165k
extracting libsodium to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libzmq@4.3.5 if necessary...
Found libzmq in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libz/libzmq/libzmq_4.3.5_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  313k  100  313k    0     0   533k      0 --:--:-- --:--:-- --:--:--  533k
extracting libzmq to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency littlecms@2.17 if necessary...
Found littlecms in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/l/littlecms/littlecms_2.17_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  138k  100  138k    0     0  2652k      0 --:--:-- --:--:-- --:--:-- 2615k
extracting littlecms to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency littlecms-utils@2.17 if necessary...
Found littlecms-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/l/littlecms-utils/littlecms-utils_2.17_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 35036  100 35036    0     0   537k      0 --:--:-- --:--:-- --:--:--  543k
extracting littlecms-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ocl-icd@2.3.3 if necessary...
Found ocl-icd in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting ocl-icd to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency opencl-headers@2024.10.24 if necessary...
Found opencl-headers in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting opencl-headers to /home/builder/.termux-build/_cache-all...
Downloading dependency fftw@3.3.10-3 if necessary...
Found fftw in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/f/fftw/fftw_3.3.10-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  924k  100  924k    0     0  11.4M      0 --:--:-- --:--:-- --:--:-- 11.4M
extracting fftw to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ladspa-sdk@1.17-2 if necessary...
Found ladspa-sdk in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/l/ladspa-sdk/ladspa-sdk_1.17-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 22812  100 22812    0     0   354k      0 --:--:-- --:--:-- --:--:--  359k
extracting ladspa-sdk to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libsamplerate@0.2.2-1 if necessary...
Found libsamplerate in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libs/libsamplerate/libsamplerate_0.2.2-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  949k  100  949k    0     0  11.2M      0 --:--:-- --:--:-- --:--:-- 11.3M
extracting libsamplerate to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libgpg-error@1.55 if necessary...
Found libgpg-error in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libg/libgpg-error/libgpg-error_1.55_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  117k  100  117k    0     0  2155k      0 --:--:-- --:--:-- --:--:-- 2172k
extracting libgpg-error to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libgcrypt@1.11.0 if necessary...
Found libgcrypt in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libg/libgcrypt/libgcrypt_1.11.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 85  478k   85  411k    0     0  5337k      0 --:--:-- --:--:-- --:--:-- 5338k
100  478k  100  478k    0     0  6164k      0 --:--:-- --:--:-- --:--:-- 6130k
extracting libgcrypt to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxslt@1.1.43-1 if necessary...
Found libxslt in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxslt/libxslt_1.1.43-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  219k  100  219k    0     0  3563k      0 --:--:-- --:--:-- --:--:-- 3601k
extracting libxslt to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xsltproc@1.1.43-1 if necessary...
Found xsltproc in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/x/xsltproc/xsltproc_1.1.43-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 11940  100 11940    0     0  72010      0 --:--:-- --:--:-- --:--:-- 72363
extracting xsltproc to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency python-lxml@5.4.0 if necessary...
Found python-lxml in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/python-lxml/python-lxml_5.4.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  934k  100  934k    0     0  13.7M      0 --:--:-- --:--:-- --:--:-- 13.8M
extracting python-lxml to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libzix@0.6.2 if necessary...
Found libzix in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libz/libzix/libzix_0.6.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 36448  100 36448    0     0  95490      0 --:--:-- --:--:-- --:--:-- 95664
extracting libzix to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency serd@0.32.4 if necessary...
Found serd in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/s/serd/serd_0.32.4_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 41800  100 41800    0     0   734k      0 --:--:-- --:--:-- --:--:--  742k
extracting serd to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency sord@0.16.18 if necessary...
Found sord in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/s/sord/sord_0.16.18_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 27064  100 27064    0     0   475k      0 --:--:-- --:--:-- --:--:--  480k
extracting sord to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency lv2@1.18.10-5 if necessary...
Found lv2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/l/lv2/lv2_1.18.10-5_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 98916  100 98916    0     0   251k      0 --:--:-- --:--:-- --:--:--  252k
extracting lv2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency vamp-plugin-sdk@2.10-2 if necessary...
Found vamp-plugin-sdk in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/v/vamp-plugin-sdk/vamp-plugin-sdk_2.10-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  166k  100  166k    0     0  2823k      0 --:--:-- --:--:-- --:--:-- 2876k
extracting vamp-plugin-sdk to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency rubberband@4.0.0 if necessary...
Found rubberband in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/r/rubberband/rubberband_4.0.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  203k  100  203k    0     0  3393k      0 --:--:-- --:--:-- --:--:-- 3450k
extracting rubberband to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency rubberband-vamp@4.0.0 if necessary...
Found rubberband-vamp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/r/rubberband-vamp/rubberband-vamp_4.0.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 94004  100 94004    0     0   236k      0 --:--:-- --:--:-- --:--:--  235k
extracting rubberband-vamp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency rubberband-lv2@4.0.0 if necessary...
Found rubberband-lv2 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/r/rubberband-lv2/rubberband-lv2_4.0.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 99632  100 99632    0     0  1477k      0 --:--:-- --:--:-- --:--:-- 1496k
extracting rubberband-lv2 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency rubberband-ladspa@4.0.0 if necessary...
Found rubberband-ladspa in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/r/rubberband-ladspa/rubberband-ladspa_4.0.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 98636    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 98636  100 98636    0     0   137k      0 --:--:-- --:--:-- --:--:--  137k
extracting rubberband-ladspa to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency svt-av1@3.0.2 if necessary...
Found svt-av1 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/s/svt-av1/svt-av1_3.0.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1379k  100 1379k    0     0  18.3M      0 --:--:-- --:--:-- --:--:-- 18.4M
extracting svt-av1 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xvidcore@1.3.7 if necessary...
Found xvidcore in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/x/xvidcore/xvidcore_1.3.7_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  123k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  123k  100  123k    0     0   174k      0 --:--:-- --:--:-- --:--:--  174k
extracting xvidcore to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ffmpeg@7.1.1-3 if necessary...
Found ffmpeg in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/f/ffmpeg/ffmpeg_7.1.1-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 9621k  100 9621k    0     0  96.1M      0 --:--:-- --:--:-- --:--:-- 96.8M
extracting ffmpeg to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency hicolor-icon-theme@0.18 if necessary...
Found hicolor-icon-theme in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/h/hicolor-icon-theme/hicolor-icon-theme_0.18_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4840  100  4840    0     0  31381      0 --:--:-- --:--:-- --:--:-- 31428
extracting hicolor-icon-theme to /home/builder/.termux-build/_cache-all...
Downloading dependency hunspell-en-us@20240129 if necessary...
Found hunspell-en-us in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/h/hunspell-en-us/hunspell-en-us_20240129_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  158k  100  158k    0     0  2761k      0 --:--:-- --:--:-- --:--:-- 2779k
extracting hunspell-en-us to /home/builder/.termux-build/_cache-all...
Downloading dependency hunspell@1.7.2 if necessary...
Found hunspell in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/h/hunspell/hunspell_1.7.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  235k  100  235k    0     0  3726k      0 --:--:-- --:--:-- --:--:-- 3738k
extracting hunspell to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency jsoncpp@1.9.6 if necessary...
Found jsoncpp in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/j/jsoncpp/jsoncpp_1.9.6_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 94432  100 94432    0     0  1718k      0 --:--:-- --:--:-- --:--:-- 1739k
extracting jsoncpp to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libarchive@3.7.9-1 if necessary...
Found libarchive in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/liba/libarchive/libarchive_3.7.9-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 25  377k   25 97965    0     0   195k      0  0:00:01 --:--:--  0:00:01  195k
100  377k  100  377k    0     0   629k      0 --:--:-- --:--:-- --:--:--  629k
extracting libarchive to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency bsdtar@3.7.9-1 if necessary...
Found bsdtar in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/b/bsdtar/bsdtar_3.7.9-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 54  336k   54  183k    0     0   224k      0  0:00:01 --:--:--  0:00:01  224k
100  336k  100  336k    0     0   409k      0 --:--:-- --:--:-- --:--:--  409k
extracting bsdtar to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libuv@1.51.0 if necessary...
Found libuv in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libu/libuv/libuv_1.51.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 81928  100 81928    0     0  1468k      0 --:--:-- --:--:-- --:--:-- 1481k
extracting libuv to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency rhash@1.4.5 if necessary...
Found rhash in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/r/rhash/rhash_1.4.5_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  154k  100  154k    0     0  2558k      0 --:--:-- --:--:-- --:--:-- 2580k
extracting rhash to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency cmake@3.31.6 if necessary...
Found cmake in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/c/cmake/cmake_3.31.6_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 8335k  100 8335k    0     0  85.5M      0 --:--:-- --:--:-- --:--:-- 85.6M
extracting cmake to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency cmake-curses-gui@3.31.6 if necessary...
Found cmake-curses-gui in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/c/cmake-curses-gui/cmake-curses-gui_3.31.6_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2059k  100 2059k    0     0  23.6M      0 --:--:-- --:--:-- --:--:-- 23.9M
extracting cmake-curses-gui to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency extra-cmake-modules@6.13.0 if necessary...
Found extra-cmake-modules in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/e/extra-cmake-modules/extra-cmake-modules_6.13.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  188k  100  188k    0     0  3208k      0 --:--:-- --:--:-- --:--:-- 3256k
extracting extra-cmake-modules to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency double-conversion@3.3.1 if necessary...
Found double-conversion in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/d/double-conversion/double-conversion_3.3.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 55296  100 55296    0     0   646k      0 --:--:-- --:--:-- --:--:--  650k
extracting double-conversion to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libdrm@2.4.124 if necessary...
Found libdrm in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libd/libdrm/libdrm_2.4.124_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  170k  100  170k    0     0  2123k      0 --:--:-- --:--:-- --:--:-- 2133k
extracting libdrm to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libice@1.1.2 if necessary...
Found libice in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libi/libice/libice_1.1.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 68576  100 68576    0     0  1344k      0 --:--:-- --:--:-- --:--:-- 1339k
extracting libice to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libsm@1.2.6 if necessary...
Found libsm in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libs/libsm/libsm_1.2.6_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 41124  100 41124    0     0   547k      0 --:--:-- --:--:-- --:--:--  550k
extracting libsm to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libwayland@1.23.1-2 if necessary...
Found libwayland in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libw/libwayland/libwayland_1.23.1-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  119k  100  119k    0     0   172k      0 --:--:-- --:--:-- --:--:--  172k
extracting libwayland to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libwayland-cross-scanner@1.23.1-2 if necessary...
Found libwayland-cross-scanner in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libw/libwayland-cross-scanner/libwayland-cross-scanner_1.23.1-2_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 84860    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 84860  100 84860    0     0  1466k      0 --:--:-- --:--:-- --:--:-- 1453k
extracting libwayland-cross-scanner to /home/builder/.termux-build/_cache-all...
Downloading dependency libwayland-protocols@1.41 if necessary...
Found libwayland-protocols in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libw/libwayland-protocols/libwayland-protocols_1.41_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  113k  100  113k    0     0  1767k      0 --:--:-- --:--:-- --:--:-- 1796k
extracting libwayland-protocols to /home/builder/.termux-build/_cache-all...
Downloading dependency libxfixes@6.0.1 if necessary...
Found libxfixes in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxfixes/libxfixes_6.0.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 11244  100 11244    0     0   212k      0 --:--:-- --:--:-- --:--:--  215k
extracting libxfixes to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxi@1.8.2 if necessary...
Found libxi in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxi/libxi_1.8.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  138k  100  138k    0     0  2008k      0 --:--:-- --:--:-- --:--:-- 2031k
extracting libxi to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xkeyboard-config@2.44 if necessary...
Found xkeyboard-config in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/x/xkeyboard-config/xkeyboard-config_2.44_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  343k  100  343k    0     0  4791k      0 --:--:-- --:--:-- --:--:-- 4836k
extracting xkeyboard-config to /home/builder/.termux-build/_cache-all...
Downloading dependency libxkbcommon@1.9.2 if necessary...
Found libxkbcommon in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/libx/libxkbcommon/libxkbcommon_1.9.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  206k  100  206k    0     0  2856k      0 --:--:-- --:--:-- --:--:-- 2869k
extracting libxkbcommon to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libglvnd@1.7.0 if necessary...
Found libglvnd in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libg/libglvnd/libglvnd_1.7.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  171k  100  171k    0     0  2343k      0 --:--:-- --:--:-- --:--:-- 2353k
extracting libglvnd to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libglvnd-dev@1.7.0 if necessary...
Found libglvnd-dev in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libg/libglvnd-dev/libglvnd-dev_1.7.0_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  147k  100  147k    0     0   379k      0 --:--:-- --:--:-- --:--:--  379k
extracting libglvnd-dev to /home/builder/.termux-build/_cache-all...
Downloading dependency opengl@4.5 if necessary...
Found opengl in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/o/opengl/opengl_4.5_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   692  100   692    0     0  11291      0 --:--:-- --:--:-- --:--:-- 11344
extracting opengl to /home/builder/.termux-build/_cache-all...
Downloading dependency vulkan-headers@1.4.314 if necessary...
Found vulkan-headers in https://packages-cf.termux.dev/apt/termux-main/dists/stable
extracting vulkan-headers to /home/builder/.termux-build/_cache-all...
Downloading dependency vulkan-loader@0.0.3 if necessary...
Found vulkan-loader in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/v/vulkan-loader/vulkan-loader_0.0.3_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   732  100   732    0     0  10617      0 --:--:-- --:--:-- --:--:-- 10764
extracting vulkan-loader to /home/builder/.termux-build/_cache-all...
Downloading dependency libxrandr@1.5.4 if necessary...
Found libxrandr in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxrandr/libxrandr_1.5.4_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 21824  100 21824    0     0   372k      0 --:--:-- --:--:-- --:--:--  373k
extracting libxrandr to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency vulkan-loader-generic@1.4.314 if necessary...
Found vulkan-loader-generic in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/v/vulkan-loader-generic/vulkan-loader-generic_1.4.314_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  115k  100  115k    0     0   241k      0 --:--:-- --:--:-- --:--:--  241k
extracting vulkan-loader-generic to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xcb-util@0.4.1 if necessary...
Found xcb-util in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/x/xcb-util/xcb-util_0.4.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  9108  100  9108    0     0   152k      0 --:--:-- --:--:-- --:--:--  153k
extracting xcb-util to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xcb-util-image@0.4.1-1 if necessary...
Found xcb-util-image in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/x/xcb-util-image/xcb-util-image_0.4.1-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 14712  100 14712    0     0   280k      0 --:--:-- --:--:-- --:--:--  281k
extracting xcb-util-image to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xcb-util-renderutil@0.3.10 if necessary...
Found xcb-util-renderutil in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/x/xcb-util-renderutil/xcb-util-renderutil_0.3.10_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  6856  100  6856    0     0  18428      0 --:--:-- --:--:-- --:--:-- 18430
100  6856  100  6856    0     0  18423      0 --:--:-- --:--:-- --:--:-- 18380
extracting xcb-util-renderutil to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xcb-util-cursor@0.1.5-1 if necessary...
Found xcb-util-cursor in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/x/xcb-util-cursor/xcb-util-cursor_0.1.5-1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  8904  100  8904    0     0  23969      0 --:--:-- --:--:-- --:--:-- 24000
extracting xcb-util-cursor to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xcb-util-keysyms@0.4.1 if necessary...
Found xcb-util-keysyms in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/x/xcb-util-keysyms/xcb-util-keysyms_0.4.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  5488  100  5488    0     0  13740      0 --:--:-- --:--:-- --:--:-- 13720
100  5488  100  5488    0     0  13737      0 --:--:-- --:--:-- --:--:-- 13720
extracting xcb-util-keysyms to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency xcb-util-wm@0.4.2 if necessary...
Found xcb-util-wm in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/x/xcb-util-wm/xcb-util-wm_0.4.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 28780  100 28780    0     0   434k      0 --:--:-- --:--:-- --:--:--  439k
extracting xcb-util-wm to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency qt6-qtbase@6.9.0 if necessary...
Found qt6-qtbase in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/q/qt6-qtbase/qt6-qtbase_6.9.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 11.6M  100 11.6M    0     0  78.2M      0 --:--:-- --:--:-- --:--:-- 78.5M
extracting qt6-qtbase to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency qt6-qtbase-cross-tools@6.9.0 if necessary...
Found qt6-qtbase-cross-tools in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/q/qt6-qtbase-cross-tools/qt6-qtbase-cross-tools_6.9.0_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 15.6M  100 15.6M    0     0   136M      0 --:--:-- --:--:-- --:--:--  137M
extracting qt6-qtbase-cross-tools to /home/builder/.termux-build/_cache-all...
Downloading dependency qt6-qtlanguageserver@6.9.0 if necessary...
Found qt6-qtlanguageserver in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/q/qt6-qtlanguageserver/qt6-qtlanguageserver_6.9.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  386k  100  386k    0     0  6017k      0 --:--:-- --:--:-- --:--:-- 6039k
extracting qt6-qtlanguageserver to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency qt6-qtlanguageserver-cross-tools@6.9.0 if necessary...
Found qt6-qtlanguageserver-cross-tools in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/q/qt6-qtlanguageserver-cross-tools/qt6-qtlanguageserver-cross-tools_6.9.0_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 57  300k   57  172k    0     0  2512k      0 --:--:-- --:--:-- --:--:-- 2498k
100  300k  100  300k    0     0  4273k      0 --:--:-- --:--:-- --:--:-- 4233k
extracting qt6-qtlanguageserver-cross-tools to /home/builder/.termux-build/_cache-all...
Downloading dependency qt6-shadertools@6.9.0 if necessary...
Found qt6-shadertools in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/q/qt6-shadertools/qt6-shadertools_6.9.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1169k  100 1169k    0     0  14.0M      0 --:--:-- --:--:-- --:--:-- 14.0M
extracting qt6-shadertools to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency qt6-shadertools-cross-tools@6.9.0 if necessary...
Found qt6-shadertools-cross-tools in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/q/qt6-shadertools-cross-tools/qt6-shadertools-cross-tools_6.9.0_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1173k  100 1173k    0     0  16.0M      0 --:--:-- --:--:-- --:--:-- 16.1M
extracting qt6-shadertools-cross-tools to /home/builder/.termux-build/_cache-all...
Downloading dependency qt6-qtdeclarative@6.9.0 if necessary...
Found qt6-qtdeclarative in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/q/qt6-qtdeclarative/qt6-qtdeclarative_6.9.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 12.7M  100 12.7M    0     0   118M      0 --:--:-- --:--:-- --:--:--  119M
extracting qt6-qtdeclarative to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency qt6-qtdeclarative-cross-tools@6.9.0 if necessary...
Found qt6-qtdeclarative-cross-tools in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/q/qt6-qtdeclarative-cross-tools/qt6-qtdeclarative-cross-tools_6.9.0_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 17 15.0M   17 2655k    0     0  34.0M      0 --:--:-- --:--:-- --:--:-- 33.6M
100 15.0M  100 15.0M    0     0   129M      0 --:--:-- --:--:-- --:--:--  128M
extracting qt6-qtdeclarative-cross-tools to /home/builder/.termux-build/_cache-all...
Downloading dependency qt6-qttools@6.9.0 if necessary...
Found qt6-qttools in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/q/qt6-qttools/qt6-qttools_6.9.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 4659k  100 4659k    0     0  52.2M      0 --:--:-- --:--:-- --:--:-- 52.3M
extracting qt6-qttools to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency qt6-qttools-cross-tools@6.9.0 if necessary...
Found qt6-qttools-cross-tools in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/q/qt6-qttools-cross-tools/qt6-qttools-cross-tools_6.9.0_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 5366k  100 5366k    0     0  64.0M      0 --:--:-- --:--:-- --:--:-- 64.7M
extracting qt6-qttools-cross-tools to /home/builder/.termux-build/_cache-all...
Downloading dependency shared-mime-info@2.4-3 if necessary...
Found shared-mime-info in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/s/shared-mime-info/shared-mime-info_2.4-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  262k  100  262k    0     0  3824k      0 --:--:-- --:--:-- --:--:-- 3858k
extracting shared-mime-info to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency kf6-kcoreaddons@6.13.0 if necessary...
Found kf6-kcoreaddons in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/k/kf6-kcoreaddons/kf6-kcoreaddons_6.13.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  354k  100  354k    0     0  5044k      0 --:--:-- --:--:-- --:--:-- 5060k
extracting kf6-kcoreaddons to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libdispatch@1:6.1 if necessary...
Found libdispatch in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libd/libdispatch/libdispatch_1:6.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 23  135k   23 32429    0     0  66036      0  0:00:02 --:--:--  0:00:02 66046
100  135k  100  135k    0     0   192k      0 --:--:-- --:--:-- --:--:--  192k
extracting libdispatch to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libblocksruntime@1:6.1 if necessary...
Found libblocksruntime in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libb/libblocksruntime/libblocksruntime_1:6.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  5608  100  5608    0     0  14875      0 --:--:-- --:--:-- --:--:-- 14914
extracting libblocksruntime to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency liblz4@1.10.0 if necessary...
Found liblz4 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libl/liblz4/liblz4_1.10.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 90184  100 90184    0     0   234k      0 --:--:-- --:--:-- --:--:--  234k
extracting liblz4 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency lz4@1.10.0 if necessary...
Found lz4 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/l/lz4/lz4_1.10.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 95932  100 95932    0     0  1438k      0 --:--:-- --:--:-- --:--:-- 1441k
extracting lz4 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libminizip@1.3.1 if necessary...
Found libminizip in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libm/libminizip/libminizip_1.3.1_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 24332  100 24332    0     0  63495      0 --:--:-- --:--:-- --:--:-- 63530
extracting libminizip to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency librnnoise@0.2 if necessary...
Found librnnoise in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libr/librnnoise/librnnoise_0.2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1165k  100 1165k    0     0  1150k      0  0:00:01  0:00:01 --:--:-- 1150k
extracting librnnoise to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libsigc++-3.0@3.6.0 if necessary...
Found libsigc++-3.0 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libs/libsigc++-3.0/libsigc++-3.0_3.6.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 56540  100 56540    0     0  95240      0 --:--:-- --:--:-- --:--:-- 95345
extracting libsigc++-3.0 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxcomposite@0.4.6 if necessary...
Found libxcomposite in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/libx/libxcomposite/libxcomposite_0.4.6_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  9468  100  9468    0     0   178k      0 --:--:-- --:--:-- --:--:--  181k
extracting libxcomposite to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxdamage@1.1.6 if necessary...
Found libxdamage in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/libx/libxdamage/libxdamage_1.1.6_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  5120  100  5120    0     0  12966      0 --:--:-- --:--:-- --:--:-- 12962
extracting libxdamage to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libxtst@1.2.5 if necessary...
Found libxtst in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libx/libxtst/libxtst_1.2.5_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 25760  100 25760    0     0   484k      0 --:--:-- --:--:-- --:--:--  493k
extracting libxtst to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency openal-soft@1.24.3 if necessary...
Found openal-soft in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/o/openal-soft/openal-soft_1.24.3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  554k  100  554k    0     0  9024k      0 --:--:-- --:--:-- --:--:-- 9087k
extracting openal-soft to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency openh264@2.6.0 if necessary...
Found openh264 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/o/openh264/openh264_2.6.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  302k  100  302k    0     0  4213k      0 --:--:-- --:--:-- --:--:-- 4257k
extracting openh264 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency liblua54@5.4.7 if necessary...
Found liblua54 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libl/liblua54/liblua54_5.4.7_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 97544    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 97544  100 97544    0     0   237k      0 --:--:-- --:--:-- --:--:--  236k
extracting liblua54 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency lua54@5.4.7 if necessary...
Found lua54 in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/l/lua54/lua54_5.4.7_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  102k  100  102k    0     0   146k      0 --:--:-- --:--:-- --:--:--  147k
extracting lua54 to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency sratom@0.6.18 if necessary...
Found sratom in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/s/sratom/sratom_0.6.18_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 11148  100 11148    0     0  23222      0 --:--:-- --:--:-- --:--:-- 23225
extracting sratom to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency lilv@0.24.26 if necessary...
Found lilv in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/l/lilv/lilv_0.24.26_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 57480    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 57480  100 57480    0     0  96086      0 --:--:-- --:--:-- --:--:-- 95959
extracting lilv to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency pipewire@1.2.7 if necessary...
Found pipewire in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/pipewire/pipewire_1.2.7_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 55 1370k   55  759k    0     0   795k      0  0:00:01 --:--:--  0:00:01  794k
100 1370k  100 1370k    0     0  1336k      0  0:00:01  0:00:01 --:--:-- 1336k
extracting pipewire to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libprotobuf@2:30.0-3 if necessary...
Found libprotobuf in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libp/libprotobuf/libprotobuf_2:30.0-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1255k  100 1255k    0     0  3160k      0 --:--:-- --:--:-- --:--:-- 3162k
extracting libprotobuf to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency protobuf-dev@2:30.0-3 if necessary...
Found protobuf-dev in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/protobuf-dev/protobuf-dev_2:30.0-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3160  100  3160    0     0   8509      0 --:--:-- --:--:-- --:--:--  8494
100  3160  100  3160    0     0   8507      0 --:--:-- --:--:-- --:--:--  8494
extracting protobuf-dev to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency protobuf@2:30.0-3 if necessary...
Found protobuf in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/p/protobuf/protobuf_2:30.0-3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1556k  100 1556k    0     0  3833k      0 --:--:-- --:--:-- --:--:-- 3843k
extracting protobuf to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libjasper@4.2.5 if necessary...
Found libjasper in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libj/libjasper/libjasper_4.2.5_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  397k  100  397k    0     0  5372k      0 --:--:-- --:--:-- --:--:-- 5444k
extracting libjasper to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency libjasper-utils@4.2.5 if necessary...
Found libjasper-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/libj/libjasper-utils/libjasper-utils_4.2.5_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 14768  100 14768    0     0  29636      0 --:--:-- --:--:-- --:--:-- 29595
extracting libjasper-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency qt6-qtimageformats@6.9.0 if necessary...
Found qt6-qtimageformats in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/q/qt6-qtimageformats/qt6-qtimageformats_6.9.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 50212  100 50212    0     0  85533      0 --:--:-- --:--:-- --:--:-- 85540
100 50212  100 50212    0     0  85521      0 --:--:-- --:--:-- --:--:-- 85394
extracting qt6-qtimageformats to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency qt6-qtimageformats-cross-tools@6.9.0 if necessary...
Found qt6-qtimageformats-cross-tools in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/q/qt6-qtimageformats-cross-tools/qt6-qtimageformats-cross-tools_6.9.0_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 52868  100 52868    0     0  89370      0 --:--:-- --:--:-- --:--:-- 89455
extracting qt6-qtimageformats-cross-tools to /home/builder/.termux-build/_cache-all...
Downloading dependency qt6-qtsvg@6.9.0 if necessary...
Found qt6-qtsvg in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/q/qt6-qtsvg/qt6-qtsvg_6.9.0_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  195k  100  195k    0     0  3185k      0 --:--:-- --:--:-- --:--:-- 3204k
extracting qt6-qtsvg to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency qt6-qtsvg-cross-tools@6.9.0 if necessary...
Found qt6-qtsvg-cross-tools in https://packages-cf.termux.dev/apt/termux-x11/dists/x11
Downloading https://packages-cf.termux.dev/apt/termux-x11/pool/main/q/qt6-qtsvg-cross-tools/qt6-qtsvg-cross-tools_6.9.0_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  228k  100  228k    0     0   286k      0 --:--:-- --:--:-- --:--:--  286k
extracting qt6-qtsvg-cross-tools to /home/builder/.termux-build/_cache-all...
Downloading dependency xxhash@0.8.3 if necessary...
Found xxhash in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/x/xxhash/xxhash_0.8.3_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 76552  100 76552    0     0   127k      0 --:--:-- --:--:-- --:--:--  127k
extracting xxhash to /home/builder/.termux-build/_cache-aarch64...
Downloading telegram-desktop@5.14.2 source from 'https://github.com/telegramdesktop/tdesktop/releases/download/v5.14.2/tdesktop-5.14.2-full.tar.gz' if necessary...
Downloading https://github.com/telegramdesktop/tdesktop/releases/download/v5.14.2/tdesktop-5.14.2-full.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 69.4M  100 69.4M    0     0   208M      0 --:--:-- --:--:-- --:--:--  208M
~/.termux-build/telegram-desktop/cache ~/.termux-build/telegram-desktop/src
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'develoso;/usr/local/lib/libxcb-dri3.so;/usr/local/lib/libxcb-ewmh.so;/usr/local/lib/libxcb-glx.so;/usr/local/lib/libxcb-icccm.so;/usr/local/lib/libxcb-image.so;/usr/local/lib/libxcb-keysyms.so;/usr/local/lib/libxcb-present.so;/usr/local/lib/libxcb-randr.so;/usr/local/lib/libxcb-record.so;/usr/local/lib/libxcb-render-util.so;/usr/local/lib/libxcb-res.so;/usr/local/lib/libxcb-screensaver.so;/usr/local/lib/libxcb-sync.so;/usr/local/lib/libxcb-xf86dri.so;/usr/local/lib/libxcb-xinerama.so;/usr/local/lib/libxcb-xinput.so;/usr/local/lib/libxcb-xkb.so;/usr/local/lib/libxcb-xtest.so;/usr/local/lib/libxcb-xv.so;/usr/local/lib/libxcb-xvmc.so (found version "1.16") found components: XFIXES 
-- XCB: XKB requires XCB
-- Found XCB: /usr/local/lib/libxcb.so;/usr/local/lib/libxcb-render.so;/usr/local/lib/libxcb-shape.so;/usr/local/lib/libxcb-xfixes.so;/usr/local/lib/libxcb-shm.so;/usr/local/lib/libxcb-util.so;/usr/local/lib/libxcb-composite.so;/usr/local/lib/libxcb-cursor.so;/usr/local/lib/libxcb-damage.so;/usr/local/lib/libxcb-dpms.so;/usr/local/lib/libxcb-dri2.so;/usr/local/lib/libxcb-dri3.so;/usr/local/lib/libxcb-ewmh.so;/usr/local/lib/libxcb-glx.so;/usr/local/lib/libxcb-icccm.so;/usr/local/lib/libxcb-image.so;/usr/local/lib/libxcb-keysyms.so;/usr/local/lib/libxcb-present.so;/usr/local/lib/libxcb-randr.so;/usr/local/lib/libxcb-record.so;/usr/local/lib/libxcb-render-util.so;/usr/local/lib/libxcb-res.so;/usr/local/lib/libxcb-screensaver.so;/usr/local/lib/libxcb-sync.so;/usr/local/lib/libxcb-xf86dri.so;/usr/local/lib/libxcb-xinerama.so;/usr/local/lib/libxcb-xinput.so;/usr/local/lib/libxcb-xkb.so;/usr/local/lib/libxcb-xtest.so;/usr/local/lib/libxcb-xv.so;/usr/local/lib/libxcb-xvmc.so (found version "1.16") found components: XKB 
-- XCB: GLX requires XCB
-- Found XCB: /usr/local/lib/libxcb.so;/usr/local/lib/libxcb-render.so;/usr/local/lib/libxcb-shape.so;/usr/local/lib/libxcb-xfixes.so;/usr/local/lib/libxcb-shm.so;/usr/local/lib/libxcb-util.so;/usr/local/lib/libxcb-composite.so;/usr/local/lib/libxcb-cursor.so;/usr/local/lib/libxcb-damage.so;/usr/local/lib/libxcb-dpms.so;/usr/local/lib/libxcb-dri2.so;/usr/local/lib/libxcb-dri3.so;/usr/local/lib/libxcb-ewmh.so;/usr/local/lib/libxcb-glx.so;/usr/local/lib/libxcb-icccm.so;/usr/local/lib/libxcb-image.so;/usr/local/lib/libxcb-keysyms.so;/usr/local/lib/libxcb-present.so;/usr/local/lib/libxcb-randr.so;/usr/local/lib/libxcb-record.so;/usr/local/lib/libxcb-render-util.so;/usr/local/lib/libxcb-res.so;/usr/local/lib/libxcb-screensaver.so;/usr/local/lib/libxcb-sync.so;/usr/local/lib/libxcb-xf86dri.so;/usr/local/lib/libxcb-xinerama.so;/usr/local/lib/libxcb-xinput.so;/usr/local/lib/libxcb-xkb.so;/usr/local/lib/libxcb-xtest.so;/usr/local/lib/libxcb-xv.so;/usr/local/lib/libxcb-xvmc.so (found version "1.16") found components: GLX 
CMake Warning at /usr/local/Qt-6.9.0/lib/cmake/Qt6QuickDialogs2QuickImplPrivate/Qt6QuickDialogs2QuickImplPrivateConfig.cmake:50 (message):
  This project is using headers of the QuickDialogs2QuickImplPrivate module
  and will therefore be tied to this specific Qt module build version.
  Running this project against other versions of the Qt modules may crash at
  any arbitrary point.  This is not a bug, but a result of using Qt
  internals.  You have been warned!

  You can disable this warning by setting QT_NO_PRIVATE_MODULE_WARNING to ON.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  /usr/local/Qt-6.9.0/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:137 (find_dependency)
  /usr/local/Qt-6.9.0/lib/cmake/Qt6QuickControlsTestUtilsPrivate/Qt6QuickControlsTestUtilsPrivateDependencies.cmake:45 (_qt_internal_find_qt_dependencies)
  /usr/local/Qt-6.9.0/lib/cmake/Qt6QuickControlsTestUtilsPrivate/Qt6QuickControlsTestUtilsPrivateConfig.cmake:43 (include)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  /usr/local/Qt-6.9.0/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:137 (find_dependency)
  /usr/local/Qt-6.9.0/lib/cmake/Qt6Qml/QmlPlugins/Qt6QuickControlsTestUtilsPrivatepluginDependencies.cmake:19 (_qt_internal_find_qt_dependencies)
  /usr/local/Qt-6.9.0/lib/cmake/Qt6Qml/QmlPlugins/Qt6QuickControlsTestUtilsPrivatepluginConfig.cmake:55 (include)
  /usr/local/Qt-6.9.0/lib/cmake/Qt6/QtPublicPluginHelpers.cmake:683 (include)
  /usr/local/Qt-6.9.0/lib/cmake/Qt6Qml/Qt6QmlPlugins.cmake:6 (__qt_internal_include_qml_plugin_packages)
  /usr/local/Qt-6.9.0/lib/cmake/Qt6Qml/Qt6QmlConfig.cmake:204 (include)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  /usr/local/Qt-6.9.0/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:137 (find_dependency)
  /usr/local/Qt-6.9.0/lib/cmake/Qt6Quick/Qt6QuickDependencies.cmake:45 (_qt_internal_find_qt_dependencies)
  /usr/local/Qt-6.9.0/lib/cmake/Qt6Quick/Qt6QuickConfig.cmake:43 (include)
  /usr/local/Qt-6.9.0/lib/cmake/Qt6/Qt6Config.cmake:212 (find_package)
  cmake/external/qt/package.cmake:68 (find_package)
  CMakeLists.txt:52 (include)


-- Found Boost: /usr/lib64/cmake/Boost-1.78.0/BoostConfig.cmake (found version "1.78.0") found components: regex 
-- Found Threads: TRUE  
-- Performing Test DESKTOP_APP__Wno_implicit_fallthrough_EXISTS
-- Performing Test DESKTOP_APP__Wno_implicit_fallthrough_EXISTS - Success
-- The C compiler identification is Clang 18.1.8
-- The CXX compiler identification is Clang 18.1.8
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test LINKER_SUPPORTS_BUILD_ID
-- Performing Test LINKER_SUPPORTS_BUILD_ID - Success
-- Looking for __GNU_LIBRARY__
-- Looking for __GNU_LIBRARY__ - found
-- Performing Test __BUILTIN_TRAP
-- Performing Test __BUILTIN_TRAP - Success
-- Found LibRT: /usr/lib64/librt.so  
-- Looking for _pthread_workqueue_init
-- Looking for _pthread_workqueue_init - not found
-- Looking for getprogname
-- Looking for getprogname - not found
-- Looking for mach_absolute_time
-- Looking for mach_absolute_time - not found
-- Looking for mach_approximate_time
-- Looking for mach_approximate_time - not found
-- Looking for mach_port_construct
-- Looking for mach_port_construct - not found
-- Looking for malloc_create_zone
-- Looking for malloc_create_zone - not found
-- Looking for posix_fadvise
-- Looking for posix_fadvise - found
-- Looking for posix_spawnp
-- Looking for posix_spawnp - found
-- Looking for pthread_key_init_np
-- Looking for pthread_key_init_np - not found
-- Looking for pthread_attr_setcpupercent_np
-- Looking for pthread_attr_setcpupercent_np - not found
-- Looking for pthread_yield_np
-- Looking for pthread_yield_np - not found
-- Looking for pthread_main_np
-- Looking for pthread_main_np - not found
-- Looking for pthread_workqueue_setdispatch_np
-- Looking for pthread_workqueue_setdispatch_np - not found
-- Looking for strlcpy
-- Looking for strlcpy - not found
-- Looking for sysconf
-- Looking for sysconf - found
-- Looking for arc4random
-- Looking for arc4random - not found
-- Looking for include file TargetConditionals.h
-- Looking for include file TargetConditionals.h - not found
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file libkern/OSAtomic.h
-- Looking for include file libkern/OSAtomic.h - not found
-- Looking for include file libkern/OSCrossEndian.h
-- Looking for include file libkern/OSCrossEndian.h - not found
-- Looking for include file libproc_internal.h
-- Looking for include file libproc_internal.h - not found
-- Looking for include file mach/mach.h
-- Looking for include file mach/mach.h - not found
-- Looking for include file malloc/malloc.h
-- Looking for include file malloc/malloc.h - not found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file pthread/qos.h
-- Looking for include file pthread/qos.h - not found
-- Looking for include file pthread/workqueue_private.h
-- Looking for include file pthread/workqueue_private.h - not found
-- Looking for include file pthread_machdep.h
-- Looking for include file pthread_machdep.h - not found
-- Looking for include file pthread_np.h
-- Looking for include file pthread_np.h - not found
-- Looking for include file pthread_workqueue.h
-- Looking for include file pthread_workqueue.h - not found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file sys/guarded.h
-- Looking for include file sys/guarded.h - not found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for include file objc/objc-internal.h
-- Looking for include file objc/objc-internal.h - not found
-- Looking for sem_init in pthread
-- Looking for sem_init in pthread - found
-- Looking for CLOCK_UPTIME
-- Looking for CLOCK_UPTIME - not found
-- Looking for CLOCK_UPTIME_FAST
-- Looking for CLOCK_UPTIME_FAST - not found
-- Looking for CLOCK_MONOTONIC
-- Looking for CLOCK_MONOTONIC - found
-- Looking for CLOCK_REALTIME
-- Looking for CLOCK_REALTIME - found
-- Looking for CLOCK_MONOTONIC_COARSE
-- Looking for CLOCK_MONOTONIC_COARSE - found
-- Looking for FD_COPY
-- Looking for FD_COPY - not found
-- Looking for NOTE_LOWAT
-- Looking for NOTE_LOWAT - not found
-- Looking for NOTE_NONE
-- Looking for NOTE_NONE - not found
-- Looking for NOTE_REAP
-- Looking for NOTE_REAP - not found
-- Looking for NOTE_REVOKE
-- Looking for NOTE_REVOKE - not found
-- Looking for NOTE_SIGNAL
-- Looking for NOTE_SIGNAL - not found
-- Looking for POSIX_SPAWN_START_SUSPENDED
-- Looking for POSIX_SPAWN_START_SUSPENDED - not found
-- Looking for SIGEMT
-- Looking for SIGEMT - not found
-- Looking for VQ_DESIRED_DISK
-- Looking for VQ_DESIRED_DISK - not found
-- Looking for VQ_NEARLOWDISK
-- Looking for VQ_NEARLOWDISK - not found
-- Looking for VQ_QUOTA
-- Looking for VQ_QUOTA - not found
-- Looking for VQ_UPDATE
-- Looking for VQ_UPDATE - not found
-- Looking for VQ_VERYLOWDISK
-- Looking for VQ_VERYLOWDISK - not found
-- Looking for VQ_FREE_SPACE_CHANGE
-- Looking for VQ_FREE_SPACE_CHANGE - not found
-- Looking for program_invocation_name
-- Looking for program_invocation_name - found
-- Looking for __printflike
-- Looking for __printflike - not found
-- Performing Test C_SUPPORTS_OMIT_LEAF_FRAME_POINTER
-- Performing Test C_SUPPORTS_OMIT_LEAF_FRAME_POINTER - Success
-- Configuring done (23.3s)
-- Generating done (0.1s)
-- Build files have been written to: /usr/src/tdesktop/out/cmake/external/dispatch/dispatch-prefix/src/dispatch-build
[1/29] Building C object src/CMakeFiles/dispatch.dir/introspection.c.o
[2/29] Building C object src/CMakeFiles/dispatch.dir/data.c.o
[3/29] Building C object src/CMakeFiles/dispatch.dir/init.c.o
[4/29] Building C object src/CMakeFiles/dispatch.dir/benchmark.c.o
[5/29] Building C object src/CMakeFiles/dispatch.dir/mach.c.o
[6/29] Building C object src/CMakeFiles/dispatch.dir/once.c.o
[7/29] Building C object src/CMakeFiles/dispatch.dir/apply.c.o
[8/29] Building C object src/CMakeFiles/dispatch.dir/object.c.o
[9/29] Building C object src/CMakeFiles/dispatch.dir/io.c.o
[10/29] Building C object src/CMakeFiles/dispatch.dir/allocator.c.o
[11/29] Building C object src/CMakeFiles/dispatch.dir/time.c.o
[12/29] Building C object src/CMakeFiles/dispatch.dir/semaphore.c.o
[13/29] Building C object src/CMakeFiles/dispatch.dir/source.c.o
[14/29] Building C object src/CMakeFiles/dispatch.dir/voucher.c.o
[15/29] Building C object src/CMakeFiles/dispatch.dir/shims.c.o
[16/29] Building C object src/CMakeFiles/dispatch.dir/transform.c.o
[17/29] Building C object src/CMakeFiles/dispatch.dir/event/event_kevent.c.o
[18/29] Building C object src/CMakeFiles/dispatch.dir/event/event_windows.c.o
[19/29] Building C object src/CMakeFiles/dispatch.dir/shims/lock.c.o
[20/29] Building C object src/CMakeFiles/dispatch.dir/event/event_epoll.c.o
[21/29] Building C object src/BlocksRuntime/CMakeFiles/BlocksRuntime.dir/data.c.o
[22/29] Building C object src/CMakeFiles/dispatch.dir/shims/yield.c.o
[23/29] Building C object src/CMakeFiles/dispatch.dir/event/event.c.o
[24/29] Building C object src/CMakeFiles/dispatch.dir/event/workqueue.c.o
[25/29] Building C object src/BlocksRuntime/CMakeFiles/BlocksRuntime.dir/runtime.c.o
[26/29] Building CXX object src/CMakeFiles/dispatch.dir/block.cpp.o
[27/29] Linking C static library src/BlocksRuntime/libBlocksRuntime.a
[28/29] Building C object src/CMakeFiles/dispatch.dir/queue.c.o
[29/29] Linking CXX static library src/libdispatch.a
-- Found Python3: /usr/bin/python3.11 (found version "3.11.11") found components: Interpreter 
-- Found Boost: /usr/lib64/cmake/Boost-1.78.0/BoostConfig.cmake (found suitable version "1.78.0", minimum required is "1.58")  
-- fmtlib available status: ON
-- std::format available status: FALSE
-- Performing Test NEEDS_LARGE_GOT
-- Performing Test NEEDS_LARGE_GOT - Failed
-- example programs: 
-- ronn manpage processor not found; not building manpage
-- Checking for modules 'glib-2.0;gobject-2.0;gio-2.0;gio-unix-2.0'
--   Found glib-2.0, version 2.78.1
--   Found gobject-2.0, version 2.78.1
--   Found gio-2.0, version 2.78.1
--   Found gio-unix-2.0, version 2.78.1
-- Checking for module 'gio-2.0'
--   Found gio-2.0, version 2.78.1
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Checking for module 'xkbcommon'
--   Found xkbcommon, version 1.6.0
-- Checking for module 'x11'
--   Found x11, version 1.6.8
-- Performing Test DESKTOP_APP__Wno_deprecated_volatile_EXISTS
-- Performing Test DESKTOP_APP__Wno_deprecated_volatile_EXISTS - Success
-- Performing Test DESKTOP_APP__Wno_ambiguous_reversed_operator_EXISTS
-- Performing Test DESKTOP_APP__Wno_ambiguous_reversed_operator_EXISTS - Success
-- Performing Test DESKTOP_APP__Wno_deprecated_declarations_EXISTS
-- Performing Test DESKTOP_APP__Wno_deprecated_declarations_EXISTS - Success
-- Performing Test DESKTOP_APP__Wno_unqualified_std_cast_call_EXISTS
-- Performing Test DESKTOP_APP__Wno_unqualified_std_cast_call_EXISTS - Success
-- Performing Test DESKTOP_APP__Wno_unused_function_EXISTS
-- Performing Test DESKTOP_APP__Wno_unused_function_EXISTS - Success
-- Configuring done (75.1s)
-- Generating done (6.9s)
-- Build files have been written to: /usr/src/tdesktop/out
Choosing Qt 6.9.0
 
 ****************************************************************************** 
 *                                                                            * 
 *               STARTING e4f065ad-8067-3b3f-bb93-515bc4f3d765                * 
 *                                                                            * 
 ****************************************************************************** 
 executing: bash
[1/255] Building CXX object cmake/external/glib/cppgir/CMakeFiles/cppgir.dir/Release/tools/genutils.cpp.o
[2/255] Generating dlopen helper for libwayland-egl.so
[3/255] Building C object cmake/external/qt/CMakeFiles/implib_wayland_egl.dir/Release/gen/libwayland-egl.so.init.c.o
[4/255] Building ASM object cmake/external/qt/CMakeFiles/implib_wayland_egl.dir/Release/gen/libwayland-egl.so.tramp.S.o
[5/255] Linking C static library cmake/external/qt/Release/libimplib_wayland_egl.a
[6/255] Generating dlopen helper for libwayland-cursor.so
[7/255] Building C object cmake/external/qt/CMakeFiles/implib_wayland_cursor.dir/Release/gen/libwayland-cursor.so.init.c.o
[8/255] Building ASM object cmake/external/qt/CMakeFiles/implib_wayland_cursor.dir/Release/gen/libwayland-cursor.so.tramp.S.o
[9/255] Linking C static library cmake/external/qt/Release/libimplib_wayland_cursor.a
[10/255] Generating dlopen helper for libwayland-client.so
implib-gen.py: warning: library '/usr/lib64/libwayland-client.so' contains data symbols which won't be intercepted: wl_touch_interface, wl_compositor_interface, wl_keyboard_interface, wl_subcompositor_interface, wl_data_offer_interface, wl_data_device_interface, wl_callback_interface, wl_shm_interface, wl_pointer_interface, wl_registry_interface, wl_data_device_manager_interface, wl_surface_interface, wl_buffer_interface, wl_shell_interface, wl_shell_surface_interface, wl_data_source_interface, wl_output_interface, wl_region_interface, wl_display_interface, wl_shm_pool_interface, wl_seat_interface, wl_subsurface_interface
[11/255] Building C object cmake/external/qt/CMakeFiles/implib_wayland_client.dir/Release/gen/libwayland-client.so.init.c.o
[12/255] Building ASM object cmake/external/qt/CMakeFiles/implib_wayland_client.dir/Release/gen/libwayland-client.so.tramp.S.o
[13/255] Linking C static library cmake/external/qt/Release/libimplib_wayland_client.a
[14/255] Generating dlopen helper for libwayland-server.so
implib-gen.py: warning: library '/usr/lib64/libwayland-server.so' contains data symbols which won't be intercepted: wl_touch_interface, wl_data_device_interface, wl_shm_pool_interface, wl_compositor_interface, wl_shell_surface_interface, wl_data_source_interface, wl_surface_interface, wl_region_interface, wl_subsurface_interface, wl_seat_interface, wl_subcompositor_interface, wl_keyboard_interface, wl_data_offer_interface, wl_output_interface, wl_pointer_interface, wl_registry_interface, wl_buffer_interface, wl_shm_interface, wl_callback_interface, wl_data_device_manager_interface, wl_display_interface, wl_shell_interface
[15/255] Building CXX object cmake/external/glib/cppgir/CMakeFiles/cppgir.dir/Release/tools/genbase.cpp.o
[16/255] Building ASM object cmake/external/qt/CMakeFiles/implib_wayland_server.dir/Release/gen/libwayland-server.so.tramp.S.o
[17/255] Building C object cmake/external/qt/CMakeFiles/implib_wayland_server.dir/Release/gen/libwayland-server.so.init.c.o
[18/255] Linking C static library cmake/external/qt/Release/libimplib_wayland_server.a
[19/255] Generating dlopen helper for libgtk-3.so
implib-gen.py: warning: library '/usr/lib64/libgtk-3.so' contains data symbols which won't be intercepted: type_wayland, gtk_text_input_manager_interface, gtk_text_input_interface
[20/255] Generating dlopen helper for libgdk-3.so
[21/255] Building C object cmake/external/qt/CMakeFiles/implib_gtk_3.dir/Release/gen/libgtk-3.so.init.c.o
[22/255] Building ASM object cmake/external/qt/CMakeFiles/implib_gtk_3.dir/Release/gen/libgtk-3.so.tramp.S.o
[23/255] Linking C static library cmake/external/qt/Release/libimplib_gtk_3.a
[24/255] Building C object cmake/external/qt/CMakeFiles/implib_gdk_3.dir/Release/gen/libgdk-3.so.init.c.o
[25/255] Building ASM object cmake/external/qt/CMakeFiles/implib_gdk_3.dir/Release/gen/libgdk-3.so.tramp.S.o
[26/255] Linking C static library cmake/external/qt/Release/libimplib_gdk_3.a
[27/255] Generating dlopen helper for libgdk_pixbuf-2.0.so
implib-gen.py: warning: library '/usr/lib64/libgdk_pixbuf-2.0.so' contains data symbols which won't be intercepted: gdk_pixbuf_major_version, gdk_pixbuf_minor_version, gdk_pixbuf_version, gdk_pixbuf_micro_version
[28/255] Generating dlopen helper for libpango-1.0.so
[29/255] Building ASM object cmake/external/qt/CMakeFiles/implib_gdk_pixbuf_2_0.dir/Release/gen/libgdk_pixbuf-2.0.so.tramp.S.o
[30/255] Building C object cmake/external/qt/CMakeFiles/implib_gdk_pixbuf_2_0.dir/Release/gen/libgdk_pixbuf-2.0.so.init.c.o
[31/255] Building C object cmake/external/qt/CMakeFiles/implib_pango_1_0.dir/Release/gen/libpango-1.0.so.init.c.o
[32/255] Linking C static library cmake/external/qt/Release/libimplib_gdk_pixbuf_2_0.a
[33/255] Building ASM object cmake/external/qt/CMakeFiles/implib_pango_1_0.dir/Release/gen/libpango-1.0.so.tramp.S.o
[34/255] Linking C static library cmake/external/qt/Release/libimplib_pango_1_0.a
[35/255] Generating dlopen helper for libEGL.so
[36/255] Building C object cmake/external/qt/CMakeFiles/implib_EGL.dir/Release/gen/libEGL.so.init.c.o
[37/255] Generating dlopen helper for libGL.so
[38/255] Building ASM object cmake/external/qt/CMakeFiles/implib_EGL.dir/Release/gen/libEGL.so.tramp.S.o
[39/255] Linking C static library cmake/external/qt/Release/libimplib_EGL.a
[40/255] Building C object cmake/external/qt/CMakeFiles/implib_GL.dir/Release/gen/libGL.so.init.c.o
[41/255] Building ASM object cmake/external/qt/CMakeFiles/implib_GL.dir/Release/gen/libGL.so.tramp.S.o
[42/255] Building CXX object cmake/external/glib/cppgir/CMakeFiles/cppgir.dir/Release/tools/repository.cpp.o
[43/255] Linking C static library cmake/external/qt/Release/libimplib_GL.a
[44/255] Generating dlopen helper for libX11-xcb.so
[45/255] Generating dlopen helper for libxcb.so
implib-gen.py: warning: library '/usr/local/lib/libxcb.so' contains data symbols which won't be intercepted: xcb_xc_misc_id, xcb_big_requests_id
[46/255] Building ASM object cmake/external/qt/CMakeFiles/implib_X11_xcb.dir/Release/gen/libX11-xcb.so.tramp.S.o
[47/255] Building C object cmake/external/qt/CMakeFiles/implib_xcb.dir/Release/gen/libxcb.so.init.c.o
[48/255] Building ASM object cmake/external/qt/CMakeFiles/implib_xcb.dir/Release/gen/libxcb.so.tramp.S.o
[49/255] Building C object cmake/external/qt/CMakeFiles/implib_X11_xcb.dir/Release/gen/libX11-xcb.so.init.c.o
[50/255] Linking C static library cmake/external/qt/Release/libimplib_xcb.a
[51/255] Linking C static library cmake/external/qt/Release/libimplib_X11_xcb.a
[52/255] Generating org.freedesktop.portal.FileTransfer.cpp, org.freedesktop.portal.FileTransfer.h
[53/255] Generating moc_org.freedesktop.portal.FileTransfer.cpp
[54/255] Generating org.kde.KIOFuse.VFS.cpp, org.kde.KIOFuse.VFS.h
[55/255] Generating moc_org.kde.KIOFuse.VFS.cpp
[56/255] Building CXX object cmake/external/glib/cppgir/CMakeFiles/cppgir.dir/Release/tools/cppgir.cpp.o
[57/255] Building CXX object cmake/external/glib/cppgir/CMakeFiles/cppgir.dir/Release/tools/function.cpp.o
[58/255] Building CXX object cmake/external/kcoreaddons/CMakeFiles/external_kcoreaddons_bundled.dir/Release/__/__/__/Telegram/ThirdParty/kcoreaddons/src/lib/util/ksandbox.cpp.o
[59/255] Automatic MOC for target external_qt_static_plugins_kimageformats
[60/255] Building CXX object cmake/external/glib/cppgir/CMakeFiles/cppgir.dir/Release/tools/genns.cpp.o
[61/255] Building CXX object cmake/external/kcoreaddons/CMakeFiles/external_kcoreaddons_bundled.dir/Release/__/__/__/Telegram/ThirdParty/kcoreaddons/src/lib/io/kurlmimedata.cpp.o
[62/255] Linking CXX executable cmake/external/glib/cppgir/Release/cppgir
[63/255] Building CXX object cmake/external/kcoreaddons/CMakeFiles/external_kcoreaddons_bundled.dir/Release/__/__/__/Telegram/ThirdParty/kcoreaddons/src/lib/util/kshell_unix.cpp.o
[64/255] Generating C++ wrapper for Gio-2.0 (external_glib)
[65/255] Building CXX object cmake/external/kcoreaddons/CMakeFiles/external_kcoreaddons_bundled.dir/Release/__/__/__/Telegram/ThirdParty/kcoreaddons/src/lib/util/kshell.cpp.o
[66/255] Building CXX object cmake/external/qt/qt_static_plugins/kimageformats/CMakeFiles/external_qt_static_plugins_kimageformats.dir/Release/external_qt_static_plugins_kimageformats_autogen/mocs_compilation_Release.cpp.o
[67/255] Building CXX object cmake/external/qt/qt_static_plugins/kimageformats/CMakeFiles/external_qt_static_plugins_kimageformats.dir/Release/__/__/__/__/__/Telegram/ThirdParty/kimageformats/src/imageformats/heif.cpp.o
[68/255] Building CXX object cmake/external/qt/qt_static_plugins/kimageformats/CMakeFiles/external_qt_static_plugins_kimageformats_init.dir/Release/init.cpp.o
[69/255] Building CXX object cmake/external/qt/qt_static_plugins/kimageformats/CMakeFiles/external_qt_static_plugins_kimageformats.dir/Release/__/__/__/__/__/Telegram/ThirdParty/kimageformats/src/imageformats/avif.cpp.o
[70/255] Building CXX object cmake/external/kcoreaddons/CMakeFiles/external_kcoreaddons_bundled.dir/Release/org.kde.KIOFuse.VFS.cpp.o
[71/255] Building CXX object cmake/external/kcoreaddons/CMakeFiles/external_kcoreaddons_bundled.dir/Release/org.freedesktop.portal.FileTransfer.cpp.o
[72/255] Building CXX object cmake/external/qt/qt_static_plugins/kimageformats/CMakeFiles/external_qt_static_plugins_kimageformats.dir/Release/__/__/__/__/__/Telegram/ThirdParty/kimageformats/src/imageformats/scanlineconverter.cpp.o
[73/255] Building CXX object cmake/external/qt/qt_static_plugins/nimf/CMakeFiles/external_qt_static_plugins_nimf_init.dir/Release/init.cpp.o
[74/255] Automatic MOC for target external_qt_static_plugins_nimf
[75/255] Building CXX object cmake/external/qt/qt_static_plugins/kimageformats/CMakeFiles/external_qt_static_plugins_kimageformats.dir/Release/__/__/__/__/__/Telegram/ThirdParty/kimageformats/src/imageformats/qoi.cpp.o
[76/255] Building CXX object cmake/external/qt/qt_static_plugins/nimf/CMakeFiles/external_qt_static_plugins_nimf.dir/Release/external_qt_static_plugins_nimf_autogen/mocs_compilation_Release.cpp.o
[77/255] Automatic MOC for target external_qt_static_plugins_fcitx5_dbusaddons
[78/255] Building CXX object cmake/external/qt/qt_static_plugins/nimf/CMakeFiles/external_qt_static_plugins_nimf.dir/Release/__/__/__/__/__/Telegram/ThirdParty/nimf/modules/clients/qt5/im-nimf-qt5.cpp.o
[79/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5_init.dir/Release/init.cpp.o
[80/255] Linking CXX static library cmake/external/qt/qt_static_plugins/nimf/Release/libexternal_qt_static_plugins_nimf.a
[81/255] Building CXX object cmake/external/qt/qt_static_plugins/hime/CMakeFiles/external_qt_static_plugins_hime_init.dir/Release/init.cpp.o
[82/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/fcitx5_qt_dbusaddons/CMakeFiles/external_qt_static_plugins_fcitx5_dbusaddons.dir/Release/__/__/__/__/__/__/Telegram/ThirdParty/fcitx5-qt/qt6/dbusaddons/fcitxqtwatcher.cpp.o
[83/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/fcitx5_qt_dbusaddons/CMakeFiles/external_qt_static_plugins_fcitx5_dbusaddons.dir/Release/__/__/__/__/__/__/Telegram/ThirdParty/fcitx5-qt/qt6/dbusaddons/fcitxqtdbustypes.cpp.o
[84/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/fcitx5_qt_dbusaddons/CMakeFiles/external_qt_static_plugins_fcitx5_dbusaddons.dir/Release/__/__/__/__/__/__/Telegram/ThirdParty/fcitx5-qt/qt6/dbusaddons/fcitxqtinputcontextproxy.cpp.o
[85/255] Building CXX object cmake/external/kcoreaddons/CMakeFiles/external_kcoreaddons_bundled.dir/Release/__/__/__/Telegram/ThirdParty/kcoreaddons/src/lib/util/kuser_unix.cpp.o
[86/255] Linking CXX static library cmake/external/kcoreaddons/Release/libexternal_kcoreaddons_bundled.a
[87/255] Building CXX object Telegram/lib_crl/CMakeFiles/lib_crl.dir/Release/crl/common/crl_common_fp_exceptions.cpp.o
[88/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/fcitx5_qt_dbusaddons/CMakeFiles/external_qt_static_plugins_fcitx5_dbusaddons.dir/Release/__/__/__/__/__/__/Telegram/ThirdParty/fcitx5-qt/qt6/dbusaddons/fcitxqtinputmethodproxy.cpp.o
[89/255] Building CXX object Telegram/lib_crl/CMakeFiles/lib_crl.dir/Release/crl/common/crl_common_list.cpp.o
[90/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/fcitx5_qt_dbusaddons/CMakeFiles/external_qt_static_plugins_fcitx5_dbusaddons.dir/Release/__/__/__/__/__/__/Telegram/ThirdParty/fcitx5-qt/qt6/dbusaddons/fcitxqtcontrollerproxy.cpp.o
[91/255] Building CXX object cmake/external/qt/qt_static_plugins/kimageformats/CMakeFiles/external_qt_static_plugins_kimageformats.dir/Release/__/__/__/__/__/Telegram/ThirdParty/kimageformats/src/imageformats/jxl.cpp.o
[92/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/fcitx5_qt_dbusaddons/CMakeFiles/external_qt_static_plugins_fcitx5_dbusaddons.dir/Release/__/__/__/__/__/__/Telegram/ThirdParty/fcitx5-qt/qt6/dbusaddons/fcitxqtinputcontextproxyimpl.cpp.o
[93/255] Building CXX object Telegram/lib_crl/CMakeFiles/lib_crl.dir/Release/crl/dispatch/crl_dispatch_async.cpp.o
[94/255] Linking CXX static library cmake/external/qt/qt_static_plugins/kimageformats/Release/libexternal_qt_static_plugins_kimageformats.a
[95/255] Building CXX object Telegram/lib_crl/CMakeFiles/lib_crl.dir/Release/crl/dispatch/crl_dispatch_queue.cpp.o
[96/255] Building CXX object Telegram/lib_crl/CMakeFiles/lib_crl.dir/Release/crl/linux/crl_linux_time.cpp.o
[97/255] Building CXX object Telegram/lib_crl/CMakeFiles/lib_crl.dir/Release/crl/winapi/crl_winapi_async.cpp.o
[98/255] Building CXX object Telegram/lib_crl/CMakeFiles/lib_crl.dir/Release/crl/winapi/crl_winapi_list.cpp.o
[99/255] Building CXX object Telegram/lib_crl/CMakeFiles/lib_crl.dir/Release/crl/winapi/crl_winapi_fp_exceptions.cpp.o
[100/255] Building CXX object Telegram/lib_crl/CMakeFiles/lib_crl.dir/Release/crl/common/crl_common_queue.cpp.o
[101/255] Building CXX object Telegram/lib_crl/CMakeFiles/lib_crl.dir/Release/crl/winapi/crl_winapi_semaphore.cpp.o
[102/255] Building CXX object Telegram/lib_crl/CMakeFiles/lib_crl.dir/Release/crl/winapi/crl_winapi_time.cpp.o
[103/255] Building CXX object Telegram/lib_crl/CMakeFiles/lib_crl.dir/Release/crl/crl_time.cpp.o
[104/255] Generating D-Bus C code for XdgDBus (lib_base)
[105/255] Generating D-Bus C code for XdpInhibit (lib_base)
[106/255] Building CXX object Telegram/lib_crl/CMakeFiles/lib_crl.dir/Release/crl/crl_object_on_thread.cpp.o
[107/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/fcitx5_qt_dbusaddons/CMakeFiles/external_qt_static_plugins_fcitx5_dbusaddons.dir/Release/external_qt_static_plugins_fcitx5_dbusaddons_autogen/mocs_compilation_Release.cpp.o
[108/255] Generating D-Bus C code for XdpOpenURI (lib_base)
[109/255] Linking CXX static library cmake/external/qt/qt_static_plugins/fcitx5/fcitx5_qt_dbusaddons/Release/libexternal_qt_static_plugins_fcitx5_dbusaddons.a
[110/255] Building C object Telegram/lib_base/CMakeFiles/lib_base_XdpInhibit_dbus.dir/Release/gen/dbus/lib_base_XdpInhibit_dbus.c.o
[111/255] Linking C static library Telegram/lib_base/Release/liblib_base_XdpInhibit_dbus.a
[112/255] Building C object Telegram/lib_base/CMakeFiles/lib_base_XdgDBus_dbus.dir/Release/gen/dbus/lib_base_XdgDBus_dbus.c.o
[113/255] Linking C static library Telegram/lib_base/Release/liblib_base_XdgDBus_dbus.a
[114/255] Generating GIR (lib_base_XdgDBus)
[115/255] Generating GIR (lib_base_XdpInhibit)
[116/255] Building CXX object Telegram/lib_crl/CMakeFiles/lib_crl.dir/Release/crl/common/crl_common_on_main.cpp.o
[117/255] Generating D-Bus C code for XdpRequest (lib_base)
[118/255] Generating C++ wrapper for /usr/src/tdesktop/out/Telegram/lib_base/gen/lib_base_XdgDBus.gir (lib_base_XdgDBus)
[119/255] Generating D-Bus C code for XdpSettings (lib_base)
[120/255] Building C object Telegram/lib_base/CMakeFiles/lib_base_XdpSettings_dbus.dir/Release/gen/dbus/lib_base_XdpSettings_dbus.c.o
[121/255] Linking C static library Telegram/lib_base/Release/liblib_base_XdpSettings_dbus.a
[122/255] Building C object Telegram/lib_base/CMakeFiles/lib_base_XdpOpenURI_dbus.dir/Release/gen/dbus/lib_base_XdpOpenURI_dbus.c.o
[123/255] Linking C static library Telegram/lib_base/Release/liblib_base_XdpOpenURI_dbus.a
[124/255] Generating GIR (lib_base_XdpOpenURI)
[125/255] Generating C++ wrapper for /usr/src/tdesktop/out/Telegram/lib_base/gen/lib_base_XdpInhibit.gir (lib_base_XdpInhibit)
[126/255] Generating D-Bus C code for XdgFileManager1 (lib_base)
[127/255] Generating GIR (lib_base_XdpSettings)
[128/255] Generating C++ wrapper for /usr/src/tdesktop/out/Telegram/lib_base/gen/lib_base_XdpOpenURI.gir (lib_base_XdpOpenURI)
[129/255] Generating D-Bus C code for MutterIdleMonitor (lib_base)
[130/255] Building C object Telegram/lib_base/CMakeFiles/lib_base_MutterIdleMonitor_dbus.dir/Release/gen/dbus/lib_base_MutterIdleMonitor_dbus.c.o
[131/255] Linking C static library Telegram/lib_base/Release/liblib_base_MutterIdleMonitor_dbus.a
[132/255] Generating C++ wrapper for /usr/src/tdesktop/out/Telegram/lib_base/gen/lib_base_XdpSettings.gir (lib_base_XdpSettings)
[133/255] Generating D-Bus C code for SigxcpuFeedback (lib_base)
[134/255] Building C object Telegram/lib_base/CMakeFiles/lib_base_SigxcpuFeedback_dbus.dir/Release/gen/dbus/lib_base_SigxcpuFeedback_dbus.c.o
[135/255] Automatic MOC for target external_qt_static_plugins_fcitx5
[136/255] Linking C static library Telegram/lib_base/Release/liblib_base_SigxcpuFeedback_dbus.a
[137/255] Building C object Telegram/lib_base/CMakeFiles/lib_base_XdpRequest_dbus.dir/Release/gen/dbus/lib_base_XdpRequest_dbus.c.o
[138/255] Building C object Telegram/lib_base/CMakeFiles/lib_base_XdgFileManager1_dbus.dir/Release/gen/dbus/lib_base_XdgFileManager1_dbus.c.o
[139/255] Generating GIR (lib_base_MutterIdleMonitor)
[140/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5.dir/Release/__/__/__/__/__/Telegram/ThirdParty/fcitx5-qt/qt6/platforminputcontext/fcitx4inputcontextproxyimpl.cpp.o
[141/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5.dir/Release/__/__/__/__/__/Telegram/ThirdParty/fcitx5-qt/qt6/platforminputcontext/fcitx4watcher.cpp.o
[142/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5.dir/Release/__/__/__/__/__/Telegram/ThirdParty/fcitx5-qt/qt6/platforminputcontext/fcitx4inputcontextproxy.cpp.o
[143/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5.dir/Release/__/__/__/__/__/Telegram/ThirdParty/fcitx5-qt/qt6/platforminputcontext/fcitx4inputmethodproxy.cpp.o
[144/255] Building CXX object Telegram/lib_crl/CMakeFiles/lib_crl.dir/Release/crl/dispatch/crl_dispatch_semaphore.cpp.o
[145/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5.dir/Release/__/__/__/__/__/Telegram/ThirdParty/fcitx5-qt/qt6/platforminputcontext/fcitxcandidatewindow.cpp.o
[146/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5.dir/Release/__/__/__/__/__/Telegram/ThirdParty/fcitx5-qt/qt6/platforminputcontext/qfcitxplatforminputcontext.cpp.o
[147/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5.dir/Release/__/__/__/__/__/Telegram/ThirdParty/fcitx5-qt/qt6/platforminputcontext/hybridinputcontext.cpp.o
[148/255] Linking C static library Telegram/lib_base/Release/liblib_base_XdpRequest_dbus.a
[149/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5.dir/Release/__/__/__/__/__/Telegram/ThirdParty/fcitx5-qt/qt6/platforminputcontext/qtkey.cpp.o
[150/255] Linking C static library Telegram/lib_base/Release/liblib_base_XdgFileManager1_dbus.a
[151/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5.dir/Release/__/__/__/__/__/Telegram/ThirdParty/fcitx5-qt/qt6/platforminputcontext/font.cpp.o
[152/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5.dir/Release/__/__/__/__/__/Telegram/ThirdParty/fcitx5-qt/qt6/platforminputcontext/main.cpp.o
[153/255] Generating C++ wrapper for /usr/src/tdesktop/out/Telegram/lib_base/gen/lib_base_MutterIdleMonitor.gir (lib_base_MutterIdleMonitor)
[154/255] Generating GIR (lib_base_XdgFileManager1)
[155/255] Generating D-Bus C code for Mpris (lib_base)
[156/255] Generating GIR (lib_base_XdpRequest)
[157/255] Generating C++ wrapper for /usr/src/tdesktop/out/Telegram/lib_base/gen/lib_base_XdgFileManager1.gir (lib_base_XdgFileManager1)
[158/255] Generating C++ wrapper for /usr/src/tdesktop/out/Telegram/lib_base/gen/lib_base_XdpRequest.gir (lib_base_XdpRequest)
[159/255] Generating D-Bus C code for Snapcraft (lib_base)
[160/255] Building C object Telegram/lib_base/CMakeFiles/lib_base_Mpris_dbus.dir/Release/gen/dbus/lib_base_Mpris_dbus.c.o
[161/255] Linking C static library Telegram/lib_base/Release/liblib_base_Mpris_dbus.a
[162/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5.dir/Release/__/__/__/__/__/Telegram/ThirdParty/fcitx5-qt/qt6/platforminputcontext/fcitxtheme.cpp.o
[163/255] Generating GIR (lib_base_SigxcpuFeedback)
[164/255] Building C object Telegram/lib_base/CMakeFiles/lib_base_Snapcraft_dbus.dir/Release/gen/dbus/lib_base_Snapcraft_dbus.c.o
[165/255] Linking C static library Telegram/lib_base/Release/liblib_base_Snapcraft_dbus.a
[166/255] Generating GIR (lib_base_Mpris)
[167/255] Generating C++ wrapper for /usr/src/tdesktop/out/Telegram/lib_base/gen/lib_base_SigxcpuFeedback.gir (lib_base_SigxcpuFeedback)
[168/255] Generating C++ wrapper for /usr/src/tdesktop/out/Telegram/lib_base/gen/lib_base_Mpris.gir (lib_base_Mpris)
[169/255] Generating GIR (lib_base_Snapcraft)
[170/255] Building CXX object Telegram/codegen/codegen/common/CMakeFiles/codegen_common.dir/Release/checked_utf8_string.cpp.o
[171/255] Generating C++ wrapper for /usr/src/tdesktop/out/Telegram/lib_base/gen/lib_base_Snapcraft.gir (lib_base_Snapcraft)
[172/255] Building CXX object Telegram/codegen/codegen/common/CMakeFiles/codegen_common.dir/Release/clean_file.cpp.o
[173/255] Building CXX object cmake/external/qt/qt_static_plugins/hime/hime_im_client/CMakeFiles/external_qt_static_plugins_hime_im_client.dir/Release/hime_im_client_helper.cpp.o
[174/255] Building CXX object Telegram/codegen/codegen/common/CMakeFiles/codegen_common.dir/Release/cpp_file.cpp.o
[175/255] Building CXX object Telegram/codegen/codegen/common/CMakeFiles/codegen_common.dir/Release/logging.cpp.o
[176/255] Building CXX object Telegram/codegen/codegen/lang/CMakeFiles/codegen_lang.dir/Release/main.cpp.o
[177/255] Building CXX object Telegram/codegen/codegen/lang/CMakeFiles/codegen_lang.dir/Release/generator.cpp.o
[178/255] Building CXX object Telegram/codegen/codegen/lang/CMakeFiles/codegen_lang.dir/Release/options.cpp.o
[179/255] Building CXX object Telegram/codegen/codegen/lang/CMakeFiles/codegen_lang.dir/Release/parsed_file.cpp.o
[180/255] Building CXX object Telegram/codegen/codegen/lang/CMakeFiles/codegen_lang.dir/Release/processor.cpp.o
[181/255] Building CXX object Telegram/codegen/codegen/style/CMakeFiles/codegen_style.dir/Release/generator.cpp.o
[182/255] Building CXX object Telegram/codegen/codegen/common/CMakeFiles/codegen_common.dir/Release/basic_tokenized_file.cpp.o
[183/255] Building CXX object Telegram/codegen/codegen/style/CMakeFiles/codegen_style.dir/Release/module.cpp.o
[184/255] Building CXX object Telegram/codegen/codegen/style/CMakeFiles/codegen_style.dir/Release/options.cpp.o
[185/255] Building CXX object Telegram/codegen/codegen/style/CMakeFiles/codegen_style.dir/Release/main.cpp.o
[186/255] Building CXX object Telegram/codegen/codegen/style/CMakeFiles/codegen_style.dir/Release/parsed_file.cpp.o
[187/255] Building CXX object Telegram/codegen/codegen/style/CMakeFiles/codegen_style.dir/Release/processor.cpp.o
[188/255] Building CXX object Telegram/codegen/codegen/style/CMakeFiles/codegen_style.dir/Release/structure_types.cpp.o
[189/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/cmake_pch.hxx.gch
[190/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_info_linux.cpp.o
[191/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_battery_saving_linux.cpp.o
[192/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_layout_switch_linux.cpp.o
[193/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_linux_allocation_tracer.cpp.o
[194/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_global_shortcuts_linux.cpp.o
[195/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_last_input_linux.cpp.o
[196/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_linux_library.cpp.o
[197/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_linux_xdg_activation_token.cpp.o
[198/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_linux_xcb_utilities.cpp.o
[199/255] Building CXX object cmake/external/qt/qt_static_plugins/fcitx5/CMakeFiles/external_qt_static_plugins_fcitx5.dir/Release/external_qt_static_plugins_fcitx5_autogen/mocs_compilation_Release.cpp.o
[200/255] Linking CXX static library cmake/external/qt/qt_static_plugins/fcitx5/Release/libexternal_qt_static_plugins_fcitx5.a
[201/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_network_reachability_linux.cpp.o
[202/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_linux_xsettings.cpp.o
[203/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_process_linux.cpp.o
[204/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_linux_dbus_utilities.cpp.o
[205/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_system_unlock_linux.cpp.o
[206/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_power_save_blocker_linux.cpp.o
[207/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/base_platform_info.cpp.o
[208/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_system_media_controls_linux.cpp.o
[209/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/algorithm.cpp.o
[210/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/assertion.cpp.o
[211/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/base_file_utilities.cpp.o
[212/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/battery_saving.cpp.o
[213/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/bytes.cpp.o
[214/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/call_delayed.cpp.o
[215/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/crc32hash.cpp.o
[216/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/debug_log.cpp.o
[217/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/concurrent_timer.cpp.o
[218/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/event_filter.cpp.o
[219/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/file_lock_posix.cpp.o
[220/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/global_shortcuts_generic.cpp.o
[221/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/last_user_input.cpp.o
[222/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/integration.cpp.o
[223/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/network_reachability.cpp.o
[224/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/parse_helper.cpp.o
[225/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/options.cpp.o
[226/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/power_save_blocker.cpp.o
[227/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/qthelp_url.cpp.o
[228/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/random.cpp.o
[229/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_linux_xdp_utilities.cpp.o
[230/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/runtime_composer.cpp.o
[231/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/timer.cpp.o
[232/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/unixtime.cpp.o
[233/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/single_instance.cpp.o
[234/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/qt/qt_tab_key.cpp.o
[235/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_file_utilities_linux.cpp.o
[236/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_url_scheme_linux.cpp.o
[237/255] Building CXX object Telegram/lib_base/CMakeFiles/lib_base.dir/Release/base/platform/linux/base_haptic_linux.cpp.o
[238/255] Linking CXX static library Telegram/lib_base/Release/liblib_base.a
[239/255] Linking CXX static library cmake/external/qt/qt_static_plugins/hime/hime_im_client/Release/libexternal_qt_static_plugins_hime_im_client.a
[240/255] Linking CXX executable Telegram/codegen/codegen/style/Release/codegen_style
[241/255] Linking CXX executable Telegram/codegen/codegen/lang/Release/codegen_lang
[242/255] Automatic MOC for target external_qt_static_plugins_hime
[243/255] Building CXX object cmake/external/qt/qt_static_plugins/hime/CMakeFiles/external_qt_static_plugins_hime.dir/Release/external_qt_static_plugins_hime_autogen/mocs_compilation_Release.cpp.o
[244/255] Building CXX object Telegram/codegen/codegen/emoji/CMakeFiles/codegen_emoji.dir/Release/data.cpp.o
[245/255] Building CXX object cmake/external/qt/qt_static_plugins/CMakeFiles/external_qt_static_plugins.dir/Release/qt_static_plugins.cpp.o
[246/255] Building CXX object Telegram/codegen/codegen/emoji/CMakeFiles/codegen_emoji.dir/Release/data_read.cpp.o
[247/255] Building CXX object cmake/external/qt/qt_static_plugins/hime/CMakeFiles/external_qt_static_plugins_hime.dir/Release/__/__/__/__/__/Telegram/ThirdParty/hime/src/qt5-im/hime-qt.cpp.o
[248/255] Building CXX object Telegram/codegen/codegen/emoji/CMakeFiles/codegen_emoji.dir/Release/main.cpp.o
[249/255] Building CXX object Telegram/codegen/codegen/emoji/CMakeFiles/codegen_emoji.dir/Release/options.cpp.o
[250/255] Building CXX object Telegram/codegen/codegen/emoji/CMakeFiles/codegen_emoji.dir/Release/generator.cpp.o
[251/255] Building CXX object cmake/external/qt/qt_static_plugins/hime/CMakeFiles/external_qt_static_plugins_hime.dir/Release/__/__/__/__/__/Telegram/ThirdParty/hime/src/qt5-im/hime-imcontext-qt.cpp.o
[252/255] Linking CXX static library cmake/external/qt/qt_static_plugins/hime/Release/libexternal_qt_static_plugins_hime.a
[253/255] Building CXX object Telegram/codegen/codegen/emoji/CMakeFiles/codegen_emoji.dir/Release/data_old.cpp.o
[254/255] Building CXX object Telegram/codegen/codegen/emoji/CMakeFiles/codegen_emoji.dir/Release/replaces.cpp.o
[255/255] Linking CXX executable Telegram/codegen/codegen/emoji/Release/codegen_emoji
 
 ****************************************************************************** 
 *                                                                            * 
 *               STARTING e4f065ad-8067-3b3f-bb93-515bc4f3d765                * 
 *                                                                            * 
 ****************************************************************************** 
 executing: cmake
Info: deleting container: e4f065ad-8067-3b3f-bb93-515bc4f3d765
~/.termux-build/telegram-desktop/host-build ~/.termux-build/telegram-desktop/host-build
~/.termux-build/telegram-desktop/host-build
Applying patch: 0001-use-prebuilt-cppgir.patch
Applying patch: 0002-webrtc-clang20.patch
Applying patch: 0003-argument-deduction.patch
Applying patch: 0004-libtgvoip-no-android.patch
Applying patch: 0005-memfd-create.patch
Applying patch: 0006-allow-use-external-libtd.patch
1 out of 1 hunk FAILED -- saving rejects to file Telegram/SourceFiles/tde2e/tde2e_api.cpp.rej
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2025-05-09 12:40:36 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/14928426571">14928426571</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

### PR DESCRIPTION
**Pull request by licy183**
Closes #24662

### CODE REVIEW

File: x11-packages/telegram-desktop/build.sh [hunk 1]
```diff
@@ -134,18 +143,13 @@ __tg_codegen_build() {
 	cp -Rf $TERMUX_PKG_SRCDIR/* ./
 	udocker pull --platform=linux/amd64 ghcr.io/telegramdesktop/tdesktop/centos_env:latest
 	udocker create --name=tg-container --force ghcr.io/telegramdesktop/tdesktop/centos_env:latest
```
Comment (robertkirkman) [inline x11-packages/telegram-desktop/build.sh:145]: hi I have a question, do you happen to know, why does this package fail to build always except for a short window of time during which you bump it, and then it starts to fail to build again in both GitHub Actions and in local containers shortly after your update is merged?

Is it because the `tdesktop/centos_env:latest` image receives independent updates, which proceed on after the update releases and become incompatible?

If you do not know then that is ok.

Comment (licy183) [reply x11-packages/telegram-desktop/build.sh:145]: Yes, this docker image may have some updates that will make the compilation fails. I don't think that there is any need to pin it on a specific commit anyway.

From 5.14.1 to 5.14.2, the failure comes from that there is no `/usr/src/Libraries/td/out/Debug` and it is fixed by passing `-DCMAKE_CONFIGURATION_TYPES=Release`.

From 5.13 to 5.14, the failure comes from that there is no `/usr/src/Libraries/td/*` and it is fixed by building it manually using `maybe-compile-libtd-for-host.sh`.

Comment (robertkirkman) [reply x11-packages/telegram-desktop/build.sh:145]: Well, the problem is that it can make it difficult for some people who would like to noninteractively compile a custom Termux that includes this package, because it may have a high chance of failure and require a lot of intervention in such cases.

However if that is not a priority, then it doesn't matter. I will try to figure out some way to solve this for that use-case and you don't have to worry about this.

Comment (licy183) [reply x11-packages/telegram-desktop/build.sh:145]: Pinning the image on a specific commit will definitely solve it, but I really don't think that there is any need to do this. The image commit should be updated with the version when auto-updating. If the build fails and they don't know what to do, they could report an issue here, but I think they will have the ability to solve it if they really want to maintain this package anyway.
