### PR TITLE
chromium: bump to 146.0.7680.164

### LINKED ISSUE #29160: [Bug]: Chromium 146 `.desktop` file contains substitution errors.
### Problem description

```desktop
[Desktop Entry]
Version=1.0
Name=@@MENUNAME
# [...]
Exec=/data/data/com.termux/files/usr/bin/@@usr_bin_symlink_name %U
# [...]
Icon=@@PACKAGE
# [...]
MimeType=application/pdf;application/rdf+xml;application/rss+xml;application/xhtml+xml;application/xhtml_xml;application/xml;image/gif;image/jpeg;image/png;image/webp;text/html;text/xml;x-scheme-handler/http;x-scheme-handler/https;@@uri_scheme

# [...]

[Desktop Action new-private-window]
Name=New Incognito Window
# [...]
Exec=/data/data/com.termux/files/usr/bin/@@usr_bin_symlink_name --incognito
```

Issue screenshot from KDE Plasma, courtesy of @BullyMaguire-lol.
Image

### What steps will reproduce the bug?

Open `$PREFIX/share/applications/chromium.desktop` in any editor or load it in an application menu.

Copy of the broken `.desktop` file from `chromium_146.0.7680.153_aarch64.deb`.
[chromium_146.desktop.txt](https://github.com/user-attachments/files/26340101/chromium_146.desktop.txt)
### What is the expected behavior?

```desktop
[Desktop Entry]
Version=1.0
Name=Chromium
# [...]
Exec=/data/data/com.termux/files/usr/bin/chromium-browser %U
# [...]
Icon=chromium
# [...]
MimeType=application/pdf;application/rdf+xml;application/rss+xml;application/xhtml+xml;application/xhtml_xml;application/xml;image/gif;image/jpeg;image/png;image/webp;text/html;text/xml;x-scheme-handler/http;x-scheme-handler/https;@@URI_SCHEME@@

# [...]

[Desktop Action new-private-window]
Name=New Incognito Window
# [...]
Exec=/data/data/com.termux/files/usr/bin/chromium-browser --incognito
```

Correct `.desktop` file from earlier version (`chromium_145.0.7632.75+really144.0.7559.132_aarch64.deb`)
[chromium_144.desktop.txt](https://github.com/user-attachments/files/26340130/chromium_144.desktop.txt)
### System information

```shell
N/A
```

### PR DESCRIPTION
**Pull request by licy183**
Closes #29160

### CODE REVIEW

File: x11-packages/chromium/build.sh [hunk 1]
```diff
@@ -478,9 +478,11 @@ termux_step_make_install() {
...
 		"$TERMUX_PREFIX/share/applications/chromium.desktop"
 	sed -i \
-		-e 's/@@MENUNAME@@/Chromium/g' \
-		-e 's/@@PACKAGE@@/chromium/g' \
-		-e 's/@@USR_BIN_SYMLINK_NAME@@/chromium-browser/g' \
+		-e 's/@@MENUNAME/Chromium/g' \
+		-e 's/@@PACKAGE/chromium/g' \
+		-e 's/@@usr_bin_symlink_name/chromium/g' \
+		-e 's|@@uri_scheme|x-scheme-handler/chromium;|g' \
+		-e 's/@@extra_desktop_entries//g' \
```
Comment (TomJo2000) [inline x11-packages/chromium/build.sh:485]: I'm guessing the missing `@@` at the end of these placeholders is a temporary oversight, so it may be best to keep both the correct and erroneous versions around as substitutions and also output the unprocessed and processed desktop files to a log (e.g `$GITHUB_STEP_SUMMARY`) for debugging purposes.
###### https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#adding-a-job-summary

Comment (TomJo2000) [reply x11-packages/chromium/build.sh:485]: We could also output a diff of the unprocessed and processed desktop files.
That would make spotting changes and missed substitutions even easier, and result in a shorter summary by omitting identical content.

Comment (licy183) [reply x11-packages/chromium/build.sh:485]: It doesn't look like it. Judging by the commit message, this was intentional.

https://github.com/chromium/chromium/commit/db3d1a330291474e4d7b5001f89e0440e297f0df

Comment (TomJo2000) [reply x11-packages/chromium/build.sh:485]: Oh well if they feel like it.
