### PR TITLE
enhance(main/neovim): Add tree sitter parsers

### LINKED ISSUE #20617: [Bug]: Neovim default parsers are missing.
### Problem description

Neovim wiki states it includes parsers for Vimdoc and Lua by default (source: https://neovim.io/doc/user/treesitter.html#treesitter-parsers).
Parsers are libraries that treesitter will search for in the parser runtime directory.
Currently,
```
/data/data/com.termux/files/usr/share/nvim/runtime/ftplugin/help.lua
/data/data/com.termux/files/usr/share/nvim/runtime/ftplugin/lua.lua
/data/data/com.termux/files/usr/share/nvim/runtime/ftplugin/query.lua
```
are forcing treesitter over syntax, and since there are no parsers available for treesitter to be using it causes errors like these :
```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: ...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:35: Error executing lua: ...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:36: BufReadPost Autocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[20]..script /data/data/com.termux/files/usr/share/nvim/runtime/ftplugin/help.lua: Vim(runtime):E5113: Error while calling lua chunk: ...s/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:107: no parser for 'vimdoc' language, see :help treesitter-parsers
stack traceback:
        [C]: in function 'error'
        ...s/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:107: in function 'add'
        ...r/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:111: in function 'new'
        ...rmux/files/usr/share/nvim/runtime/lua/vim/treesitter.lua:41: in function '_create_parser'
        ...rmux/files/usr/share/nvim/runtime/lua/vim/treesitter.lua:108: in function 'get_parser'
        ...rmux/files/usr/share/nvim/runtime/lua/vim/treesitter.lua:416: in function 'start'
        ...om.termux/files/usr/share/nvim/runtime/ftplugin/help.lua:2: in main chunk
        [C]: in function 'nvim_cmd'
        ...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:36: in function <...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:35>
        [C]: in function 'nvim_buf_call'
        ...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:35: in function <...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_cmd'
        ...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:36: in function <...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:35>
        [C]: in function 'nvim_buf_call'
        ...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:35: in function <...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:35: in function <...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:10>
Press ENTER or type command to continue
```
this particular error shown above appears when opening Neovim help page inside Neovim by running Neovim command `:h`, similar errors appears when opening any lua file.

### What steps will reproduce the bug?

1. opening Neovim help page from inside of Neovim via `:h` or `:help`.
2. opening any lua file.

### What is the expected behavior?

No errors should appear when opening Neovim help page or opening any lua file.

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=18045
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.42.4
Android version:
10
Kernel build information:
Linux localhost 4.4.192-perf+ #1 SMP PREEMPT Fri Nov 5 12:30:40 CST 2021 aarch64 Android
Device manufacturer:
HMD Global
Device model:
Nokia 7.1
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes #20617

### CODE REVIEW

**Comment by TomJo2000** [comment]
This would mirror more of an Arch Linux approach, with separate packages for each parser.

**Comment by Biswa96** [comment]
> This would mirror more of an Arch Linux approach, with separate packages for each parser.

Other Linux distributions also approached in similar way https://repology.org/project/tree-sitter-vimdoc/versions

File: packages/tree-sitter-lua/build.sh [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+PARSER_URL="${TERMUX_PKG_HOMEPAGE}"
+"
+
+termux_step_pre_configure() {
+	rm setup.py pyproject.toml
+}
+
+termux_step_post_make_install() {
+	install -d "${TERMUX_PREFIX}"/share/nvim/runtime/parser/
+	ln -s "${TERMUX_PREFIX}"/lib/libtree-sitter-lua.so "${TERMUX_PREFIX}"/share/nvim/runtime/parser/lua.so
```
Comment (TomJo2000) [inline packages/tree-sitter-lua/build.sh:20]: > [!IMPORTANT]
> It should probably be the `neovim` package's responsibility to link the `tree-sitter-${filetype}` parsers into its runtime.
>
> #### *The parsers should exist independently of Neovim.*

<details><summary>Here is the contents of Arch's `tree-sitter-lua` package.</summary>
<p>

```styl
tree-sitter-lua /usr/
tree-sitter-lua /usr/include/
tree-sitter-lua /usr/include/tree_sitter/
tree-sitter-lua /usr/include/tree_sitter/tree-sitter-lua.h
tree-sitter-lua /usr/lib/
tree-sitter-lua /usr/lib/libtree-sitter-lua.so
tree-sitter-lua /usr/lib/libtree-sitter-lua.so.0
tree-sitter-lua /usr/lib/libtree-sitter-lua.so.0.1
tree-sitter-lua /usr/lib/pkgconfig/
tree-sitter-lua /usr/lib/pkgconfig/tree-sitter-lua.pc
tree-sitter-lua /usr/lib/tree_sitter/
tree-sitter-lua /usr/lib/tree_sitter/lua.so
tree-sitter-lua /usr/share/
tree-sitter-lua /usr/share/doc/
tree-sitter-lua /usr/share/doc/tree-sitter-lua/
tree-sitter-lua /usr/share/doc/tree-sitter-lua/README.md
tree-sitter-lua /usr/share/licenses/
tree-sitter-lua /usr/share/licenses/tree-sitter-lua/
tree-sitter-lua /usr/share/licenses/tree-sitter-lua/LICENSE.md
```

</p>
</details> 

- `/usr/lib/libtree-sitter-lua.so` is a symlink to `/usr/lib/libtree-sitter-lua.so.0`
- `/usr/lib/libtree-sitter-lua.so.0` is a symlink to `/usr/lib/libtree-sitter-lua.so.0.1`
We can probably skip doing that and just do `.so` or `.so.${MAJOR_VERSION}`
- LICENSE is already handled.
- We can decide if we wanna ship the README's for the parsers.
- I'm not sure about if we want to do `/usr/lib/tree_sitter/${filetype}.so`
(`/usr/lib/tree_sitter/lua.so` is a symlink to `/usr/lib/libtree-sitter-lua.so`)
- We probably wanna ship the header and pkgconfig files.
(`/usr/include/tree_sitter/tree-sitter-lua.h`)
(`/usr/lib/pkgconfig/tree-sitter-lua.pc`)

**Review by TomJo2000 — CHANGES_REQUESTED** [review]

File: packages/tree-sitter-lua/build.sh (hunk 1 above)
Comment (Biswa96) [reply packages/tree-sitter-lua/build.sh:20]: ok, I shall change the build scripts to follow ArchLinux's style.

Comment (TomJo2000) [reply packages/tree-sitter-lua/build.sh:20]: Since we seem to be following that model, that seems like the most sensible choice.

File: packages/neovim/build.sh [hunk 2]
```diff
@@ -79,6 +80,9 @@ termux_step_post_make_install() {
 	local _CONFIG_DIR=$TERMUX_PREFIX/share/nvim
 	mkdir -p $_CONFIG_DIR
 	cp $TERMUX_PKG_BUILDER_DIR/sysinit.vim $_CONFIG_DIR/
+
+	# Tree-sitter grammars are packaged separately and installed into TERMUX_PREFIX/lib/tree_sitter.
+	ln -s "${TERMUX_PREFIX}"/lib/tree_sitter "${TERMUX_PREFIX}"/share/nvim/runtime/parser
```
Comment (TomJo2000) [inline packages/neovim/build.sh:85]: Oh nice, this way if we add more parsers they end up in the runtime automatically.

**Review by TomJo2000 — APPROVED** [review]
