### PR TITLE
fix: do not imply platform independent for metapackages

### LINKED ISSUE #25417: Repository Health Check Failed
### Errors found for aarch64
<details>
  <summary>Errors:</summary>

```
"liboggz-static" "1.1.2" != 1.1.3 as expected by parent package. The -static package probably stopped existing after an update.
"libwebp" "1.6.0-rc1-0" (in apt repository) != "1.6.0" (in termux-packages)

```
</details>

<details>
  <summary>Proposed Automated fixes:</summary>

```sh
aptly repo remove "termux-main" "liboggz-static (=1.1.2) {aarch64}"

```
</details>

<details>
  <summary>Proposed Manual fixes:</summary>

```
The package "libwebp" in "termux-main" may not be up to date on the apt repository or a bogus version may be present

```
</details>

### Errors found for arm
<details>
  <summary>Errors:</summary>

```
"dotnet-host" "9.0-1" does not exist in termux-packages
"liboggz-static" "1.1.2" != 1.1.3 as expected by parent package. The -static package probably stopped existing after an update.
"libwebp" "1.6.0-rc1-0" (in apt repository) != "1.6.0" (in termux-packages)
"netstandard-targeting-pack-2.1" "9.0-1" does not exist in termux-packages

```
</details>

<details>
  <summary>Proposed Automated fixes:</summary>

```sh
aptly repo remove "termux-main" "dotnet-host (=9.0-1) {arm}"
aptly repo remove "termux-main" "liboggz-static (=1.1.2) {arm}"
aptly repo remove "termux-main" "netstandard-targeting-pack-2.1 (=9.0-1) {arm}"

```
</details>

<details>
  <summary>Proposed Manual fixes:</summary>

```
The package "libwebp" in "termux-main" may not be up to date on the apt repository or a bogus version may be present

```
</details>

### Errors found for i686
<details>
  <summary>Errors:</summary>

```
"liboggz-static" "1.1.2" != 1.1.3 as expected by parent package. The -static package probably stopped existing after an update.
"libwebp" "1.6.0-rc1-0" (in apt repository) != "1.6.0" (in termux-packages)

```
</details>

<details>
  <summary>Proposed Automated fixes:</summary>

```sh
aptly repo remove "termux-main" "liboggz-static (=1.1.2) {i686}"

```
</details>

<details>
  <summary>Proposed Manual fixes:</summary>

```
The package "libwebp" in "termux-main" may not be up to date on the apt repository or a bogus version may be present

```
</details>

### Errors found for x86_64
<details>
  <summary>Errors:</summary>

```
"liboggz-static" "1.1.2" != 1.1.3 as expected by parent package. The -static package probably stopped existing after an update.
"libwebp" "1.6.0-rc1-0" (in apt repository) != "1.6.0" (in termux-packages)

```
</details>

<details>
  <summary>Proposed Automated fixes:</summary>

```sh
aptly repo remove "termux-main" "liboggz-static (=1.1.2) {x86_64}"

```
</details>

<details>
  <summary>Proposed Manual fixes:</summary>

```
The package "libwebp" in "termux-main" may not be up to date on the apt repository or a bogus version may be present

```
</details>

### PR DESCRIPTION
**Pull request by thunder-coding**
All the build.sh files in the repository for metapackages are also
setting TERMUX_PKG_PLATFORM_INDEPENDENT=true, so this does not need any
changes at all in any of the build.sh files

The only exception are dotnet-host and netstandard-targeting-pack-2.1
due to 2c2daf3987cdb8639299698682a4a929d33e3b63 and
07d53e5b3e78ebb14b73a9c6074b7c11b011824b

Closes #25417

### CODE REVIEW

File: scripts/build/termux_step_start_build.sh [hunk 1]
```diff
@@ -5,9 +5,12 @@ termux_step_start_build() {
...
 
 	if [ "$TERMUX_PKG_METAPACKAGE" = "true" ]; then
-		# Metapackage has no sources and therefore platform-independent.
+		# Metapackage has no sources
 		TERMUX_PKG_SKIP_SRC_EXTRACT=true
-		TERMUX_PKG_PLATFORM_INDEPENDENT=true
+		# Usually metapackages are also platform dependent but it is not always the
+		# right decision to mark them as such when they depend on packages which may
+		# not be available for all architectures
+		# TERMUX_PKG_PLATFORM_INDEPENDENT=true
```
Comment (robertkirkman) [inline scripts/build/termux_step_start_build.sh:13]: I agree with this. Technically, any package which depends on a package that does not exist on some (OS-supported) architectures is not architecture independent - it is dependent on the existence of the dependency package, which does not exist on some architectures.

Since it is convenient to post it here for reference by anyone reading this PR in the future, the reason why this ends up mattering and is necessary is because the folder organization patterns of the mirrors can vary, and in at least some cases, packages marked as platform-independent are placed into the same folder for all architectures and cannot be "hidden" from the `apt install` commands of devices that have an architecture that is not supported by one of the dependencies of the package marked as architecture-independent, which is why it is necessary to use this specific definition of "architecture independent".

https://github.com/termux/termux-packages/blob/a9ced23022da21a718b796eec1c70239a3348856/scripts/build/termux_download_deb_pac.sh#L69-L70

**Review by robertkirkman — APPROVED** [review]
