### PR TITLE
scripts: add termux_setup_gnu_as_23c for NDK r25

### LINKED ISSUE #11587: [Bug]: libgcrypt build failed ndk25
### Problem description

configure:3882: aarch64-linux-android-clang  -fstack-protector-strong -Oz -no-integrated-as  -I/data/data/com.termux/files/usr/include -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now conftest.c  >&5
/usr/bin/as: unrecognized option '-EL'
clang-14: error: assembler command failed with exit code 1 (use -v to see invocation)
configure:3886: $? = 1
configure:3924: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "libgcrypt"
| #define PACKAGE_TARNAME "libgcrypt"
| #define PACKAGE_VERSION "1.10.1"
| #define PACKAGE_STRING "libgcrypt 1.10.1"
| #define PACKAGE_BUGREPORT "https://bugs.gnupg.org"
| #define PACKAGE_URL ""
| #define PACKAGE "libgcrypt"
| #define VERSION "1.10.1"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;

|   return 0;
| }
configure:3929: error: in `/home/builder/.termux-build/libgcrypt/build':
configure:3931: error: C compiler cannot create executables

[libgcrypt.txt](https://github.com/termux/termux-packages/files/9333772/libgcrypt.txt)

### What steps will reproduce the bug?

build

### What is the expected behavior?

_No response_

### System information

termux-info:

```

```

### LINKED ISSUE #11614: [Bug]: libpixman build failed for [arm] ndk25
### Problem description

configure:3627: checking whether the C compiler works
configure:3649: arm-linux-androideabi-clang  -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -fstack-protector-strong -Oz -fno-integrated-as  -I/data/data/com.termux/files/usr/include -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -march=armv7-a -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now conftest.c  >&5
/usr/bin/as: unrecognized option '-EL'
clang-14: error: assembler command failed with exit code 1 (use -v to see invocation)
configure:3653: $? = 1
configure:3691: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "pixman"
| #define PACKAGE_TARNAME "pixman"
| #define PACKAGE_VERSION "0.40.0"
| #define PACKAGE_STRING "pixman 0.40.0"
| #define PACKAGE_BUGREPORT "pixman@lists.freedesktop.org"
| #define PACKAGE_URL ""
| #define PACKAGE "pixman"
| #define VERSION "0.40.0"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:3696: error: in `/home/builder/.termux-build/libpixman/build':
configure:3698: error: C compiler cannot create executables

[libpixman.txt](https://github.com/termux/termux-packages/files/9340112/libpixman.txt)

### What steps will reproduce the bug?

build

### What is the expected behavior?

_No response_

### System information

termux-info:

```

```

### PR DESCRIPTION
**Pull request by truboxl**
Fixes #11614
Fixes #11587

### CODE REVIEW

**Comment by truboxl** [comment]
Not building Arm with custom assembly might have performance penalty... Next step either choose:

1. Go ahead build without custom assembly
2. Patch all the assembly files to be LLVM compatible
3. Bring back GAS from NDK r23c or another source (can be from Ubuntu package or static build)

**Comment by truboxl** [comment]
I added back GAS from NDK r23c... Seems to work fine with NDK r25...

File: scripts/build/setup/termux_setup_gnu_as.sh [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+		sed -i "$TERMUX_SCRIPTDIR/scripts/properties.sh" \
+			-e "s|^TERMUX_NDK_VERSION_NUM=.*|TERMUX_NDK_VERSION_NUM=$CURRENT_TERMUX_NDK_VERSION_NUM|" \
+			-e "s|^TERMUX_NDK_REVISION=.*|TERMUX_NDK_REVISION=\"$CURRENT_TERMUX_NDK_REVISION\"|"
+		# https://github.com/android/ndk/issues/1569
+		# https://android-review.googlesource.com/c/platform/ndk/+/1817218
+		# these must be present for clang -fno-integrated-as to work correctly
+		# 1. bin/*-linux-android*-as
+		# 2. *-linux-android*/bin/as (symlink to #1)
+		# 3. lib/gcc/*-linux-android*/4.9.x/crtbegin.o (dummy file)
+		cp -f "$NDK"/toolchains/llvm/prebuilt/linux-x86_64/bin/{arm-linux-androideabi,{aarch64,i686,x86_64}-linux-android}-as \
```
Comment (Grimler91) [inline scripts/build/setup/termux_setup_gnu_as.sh:44]: I think it would be better to add this stuff to a separate folder (maybe something like `~/.termux-build/_cache/android-r23c-gas-api-24-v0`) to make it similar to what we do for the ndk toolchain.

**Review by Grimler91 — COMMENTED** [review]
Thanks for looking into this! 

Editing/enhancing the ndk really should only be dons as a last resort I think, would be better to fix the assembly in the affected packages, but obviously that isn't trivial. 

So, this seems like a good approach for me where we would otherwise have to disable assembly and get massive penalties

**Comment by truboxl** [comment]
Ok renamed the function to be more clear that it setups and uses another toolchain with GAS added
while leaving the current toolchain untouched

**Comment by Grimler91** [comment]
Here's an alternative idea which puts the the gnu as in a separate folder, and updates PATH so as is found. 

I also skipped installing `lib/gcc/*-linux-android*/4.9.x/crtbegin.o`, because I couldn't figure out what it was needed for (please enlighten me).

Works fine for libpixman, but not libgcrypt due to hostbuild of some tools failing (see commit message). 
Needs to be tidied up, and the issue preventing hostbuilds fixed in any case

**Comment by truboxl** [comment]
It's likely because of using the wrong "as" though. I will refine this.

**Comment by Grimler91** [comment]
> It's likely because of using the wrong "as" though.

Definitely, but I couldn't figure out how to tell it to use another `as` just for hostbuild >.> also interesting that it doesn't fail with the same error when building with the normal android-ndk-23c, I guess it has to do with that we do not add `$TERMUX_STANDALONE_TOOLCHAIN/$TERMUX_HOST_PLATFORM/bin` to PATH in that case. Maybe we need a wrapper that determines if we are cross-compiling, and calls `$TERMUX_HOST_PLATFORM-as` if yes, and `/usr/bin/as` if not

> I will refine this.

Thanks!

**Comment by licy183** [comment]
Setting `--gcc-toolchain=` in `CFLAGS` seems working fine. I'll push a commit. Please test if it is convenient for you. Thanks!

**Comment by truboxl** [comment]
Apparently openssl has a typo ASLAGS instead of ASFLAGS which supposedly should be CFLAGS and fno-integrated-as never worked 😅

Remove it since its no longer needed

**Comment by truboxl** [comment]
Added a small repro case to determine clang does detect the GCC toolchain (in this case GAS only) so it should clear up the confusion whether the path is needed in the first place.

Will squash all this into one commit if everybody agrees.

File: scripts/build/toolchain/termux_setup_gnu_as_23c.sh [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+			fi
+			exit 1
+		fi
+		return
+	fi
+
+	local GAS_TOOLCHAIN_REVISION="-v0"
+	local GAS_TOOLCHAIN_DIR="$TERMUX_COMMON_CACHEDIR/android-r23c-gas-api-${TERMUX_PKG_API_LEVEL}${GAS_TOOLCHAIN_REVISION}"
+	local NDK="$(dirname "$NDK")"/android-ndk-r23c
+	if [ ! -d "$NDK" ]; then
```
Comment (Grimler91) [inline scripts/build/toolchain/termux_setup_gnu_as_23c.sh:25]: this `if` (that I added) is unnecessary, setup-android-sdk.sh already checks if folder exists

**Review by Grimler91 — COMMENTED** [review]
Nice work, looks good to me!

`if [ ! -d "$NDK" ]; then`, that I added, can be removed as well, as setup-android-sdk already checks the same thing (see comment)

**Comment by truboxl** [comment]
Gah... messed up the commit message... welp
