### PR TITLE
addpkg(x11/dolphin): 25.12.0

### LINKED ISSUE #25725: [Package]: dolphin
### Why is it worth to add this package?

Dolphin is KDE's file manager that lets you navigate and browse the contents of your hard drives, USB sticks, SD cards, and more. Creating, moving, or deleting files and folders is simple and fast.

I guess this can be included into x11-packages.

### Home page URL

https://apps.kde.org/dolphin/

### Source code URL

https://invent.kde.org/system/dolphin

### Packaging policy acknowledgement

- [x] The project is actively developed.
- [x] The project has [existing packages](https://repology.org/projects/) and is "well known".
- [x] Licensed under an [open source license](https://spdx.org/licenses/).
- [x] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [x] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [x] Not duplicating the functionality of existing packages.
- [x] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [x] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by BullyMaguire-lol**
This PR adds Dolphin 25.12.0.

New dependencies required by Dolphin:
- kf6-kcmutils 6.21.0
- kf6-baloo 6.21.0 (disabled by default)
- baloo-widgets 25.12.0
- kf6-kdnssd 6.21.0
- kde-cli-tools 6.5.4
- plasma-activities 6.5.4
- plasma-activities-stats 6.5.4
- libproxy 0.5.12
- libkexiv2 25.12.0
- kio-extras 25.12.0

* Fixes #25725

### CODE REVIEW

File: x11-packages/kf6-baloo/build.sh [hunk 1]
```diff
@@ -0,0 +1,22 @@
+TERMUX_PKG_HOMEPAGE="https://invent.kde.org/frameworks/baloo"
+TERMUX_PKG_DESCRIPTION="A framework for searching and managing metadata"
+TERMUX_PKG_LICENSE="LGPL-2.0-only, LGPL-3.0-only"
+TERMUX_PKG_MAINTAINER="@termux"
+TERMUX_PKG_VERSION="6.21.0"
+_KF6_MINOR_VERSION="${TERMUX_PKG_VERSION%.*}"
+TERMUX_PKG_SRCURL="https://download.kde.org/stable/frameworks/${_KF6_MINOR_VERSION}/baloo-${TERMUX_PKG_VERSION}.tar.xz"
```
Comment (TomJo2000) [inline x11-packages/kf6-baloo/build.sh]: I'd prefer not adding a global helper variable for this.
```suggestion
TERMUX_PKG_SRCURL="https://download.kde.org/stable/frameworks/${TERMUX_PKG_VERSION%.*}/baloo-${TERMUX_PKG_VERSION}.tar.xz"
```
Especially when it's only that one instance where it ends up getting used.

File: x11-packages/kf6-kcmutils/build.sh [hunk 2]
```diff
@@ -0,0 +1,50 @@
+TERMUX_PKG_HOMEPAGE="https://invent.kde.org/frameworks/kcmutils"
+TERMUX_PKG_DESCRIPTION="Utilities for interacting with KCModules"
+TERMUX_PKG_LICENSE="LGPL-2.0-only, LGPL-3.0-only"
+TERMUX_PKG_MAINTAINER="@termux"
+TERMUX_PKG_VERSION="6.21.0"
+_KF6_MINOR_VERSION="${TERMUX_PKG_VERSION%.*}"
+TERMUX_PKG_SRCURL="https://download.kde.org/stable/frameworks/${_KF6_MINOR_VERSION}/kcmutils-${TERMUX_PKG_VERSION}.tar.xz"
```
Comment (TomJo2000) [inline x11-packages/kf6-kcmutils/build.sh]: Same as above.
```suggestion
TERMUX_PKG_SRCURL="https://download.kde.org/stable/frameworks/${TERMUX_PKG_VERSION%.*}/kcmutils-${TERMUX_PKG_VERSION}.tar.xz"
```

File: x11-packages/kf6-kcmutils/build.sh [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+TERMUX_PKG_SHA256="9c1808153d9c16aaa08e68b6353ce5c9af67b2e24b9a0cd7587c46a4a81e8edc"
+TERMUX_PKG_AUTO_UPDATE=true
+TERMUX_PKG_HOSTBUILD=true
+TERMUX_PKG_DEPENDS="kf6-kconfig, kf6-kconfigwidgets, kf6-kcoreaddons, kf6-kguiaddons, kf6-ki18n, kf6-kio, kf6-kirigami, kf6-kitemviews, kf6-kservice, kf6-kwidgetsaddons, kf6-kxmlgui, libc++, qt6-qtbase, qt6-qtdeclarative"
+TERMUX_PKG_BUILD_DEPENDS="extra-cmake-modules (>= ${_KF6_MINOR_VERSION}), qt6-qttools"
```
Comment (TomJo2000) [inline x11-packages/kf6-kcmutils/build.sh]: In this case there is a second instance but it's probably still preferable to not introduce a global helper variable to the build.
```suggestion
TERMUX_PKG_BUILD_DEPENDS="extra-cmake-modules (>= ${TERMUX_PKG_VERSION%.*}), qt6-qttools"
```

File: x11-packages/kf6-kdnssd/build.sh [hunk 4]
```diff
@@ -0,0 +1,16 @@
+TERMUX_PKG_HOMEPAGE="https://invent.kde.org/frameworks/kdnssd"
+TERMUX_PKG_DESCRIPTION="Abstraction to system DNSSD features"
+TERMUX_PKG_LICENSE="LGPL-2.0-only, LGPL-3.0-only"
+TERMUX_PKG_MAINTAINER="@termux"
+TERMUX_PKG_VERSION="6.21.0"
+_KF6_MINOR_VERSION="${TERMUX_PKG_VERSION%.*}"
+TERMUX_PKG_SRCURL="https://download.kde.org/stable/frameworks/${_KF6_MINOR_VERSION}/kdnssd-${TERMUX_PKG_VERSION}.tar.xz"
```
Comment (TomJo2000) [inline x11-packages/kf6-kdnssd/build.sh]: Same as above.
```suggestion
TERMUX_PKG_SRCURL="https://download.kde.org/stable/frameworks/${TERMUX_PKG_VERSION%.*}/kdnssd-${TERMUX_PKG_VERSION}.tar.xz"
```

File: x11-packages/kf6-kidletime/build.sh [hunk 5]
```diff
@@ -0,0 +1,16 @@
+TERMUX_PKG_HOMEPAGE="https://invent.kde.org/frameworks/kidletime"
+TERMUX_PKG_DESCRIPTION="Monitoring user activity"
+TERMUX_PKG_LICENSE="LGPL-2.0-only, LGPL-3.0-only"
+TERMUX_PKG_MAINTAINER="@termux"
+TERMUX_PKG_VERSION="6.21.0"
+_KF6_MINOR_VERSION="${TERMUX_PKG_VERSION%.*}"
+TERMUX_PKG_SRCURL="https://download.kde.org/stable/frameworks/${_KF6_MINOR_VERSION}/kidletime-${TERMUX_PKG_VERSION}.tar.xz"
```
Comment (TomJo2000) [inline x11-packages/kf6-kidletime/build.sh]: Same as above.
```suggestion
TERMUX_PKG_SRCURL="https://download.kde.org/stable/frameworks/${TERMUX_PKG_VERSION%.*}/kidletime-${TERMUX_PKG_VERSION}.tar.xz"
```

File: x11-packages/kf6-kidletime/build.sh [hunk 6]
```diff
@@ -0,0 +1,16 @@
+TERMUX_PKG_HOMEPAGE="https://invent.kde.org/frameworks/kidletime"
+TERMUX_PKG_DESCRIPTION="Monitoring user activity"
```
Comment (TomJo2000) [inline x11-packages/kf6-kidletime/build.sh]: I think the more common description fits better here.
https://repology.org/project/kidletime/information
```suggestion
TERMUX_PKG_DESCRIPTION="Reporting of idle time of user and system"
```

**Review by robertkirkman — APPROVED** [review]

**Comment by robertkirkman** [comment]
It is working for me. I will merge it in 20 hours if no problems are found.
