### PR TITLE
fix(main/libllvm): Implement all executables named after triplets with scripts

### LINKED ISSUE #25622: [Bug] `$PREFIX/bin/*-clang` has different target API behavior from `clang` on 64-bit but not 32-bit
### Problem description

This is a behavior difference I have noticed between 32-bit ARM Termux and all other kinds of Termux that is difficult to explain and understand,

and unfortunately, I'm not 100% sure what the correct choice should be for the solution (should 32-bit ARM Termux be changed to behave how other kinds of Termux do, or vice versa?)

so I am posting a minimal reproducible example of the difference, and hopefully I can use this example to find out some feedback about what should be done to make the behavior more similar to each other.

### What steps will reproduce the bug?

These commands have different behavior on 32-bit ARM Termux from other kinds of Termux.

```bash
clang --version
$PREFIX/bin/*-clang --version
cat <<-EOF > test.c
#include <stdio.h>

int main(void)
{
    FILE *stream;
    stream = fopen("file", "w");
    printf("File number is %d\n", fileno_unlocked(stream));
    fclose(stream);
    return 0;
}
EOF
clang test.c
$PREFIX/bin/*-clang test.c
```

Output on 32-bit ARM Termux:

```
clang version 20.1.8
Target: armv7a-unknown-linux-android24
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
clang version 20.1.8
Target: armv7a-unknown-linux-android24
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
```

Output on 64-bit ARM Termux:

```
clang version 20.1.8
Target: aarch64-unknown-linux-android24
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
clang version 20.1.8
Target: aarch64-unknown-linux-android
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
test.c:7:35: error: call to undeclared function 'fileno_unlocked'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    7 |     printf("File number is %d\n", fileno_unlocked(stream));
      |                                   ^
test.c:7:35: note: did you mean 'getc_unlocked'?
/data/data/com.termux/files/usr/bin/../../usr/include/stdio.h:317:17: note: 'getc_unlocked' declared here
  317 | __nodiscard int getc_unlocked(FILE* _Nonnull __fp);
      |                 ^
1 error generated.
```

This **did not change recently**, and has been the case for quite a while.

Output on a 64-bit x86 Termux that has not been updated since _before_ the update to NDK r28c:

```
ndk-sysroot:
  Installed: 27c
  Candidate: 27c
  Version table:
 *** 27c 500
        500 https://packages-cf.termux.dev/apt/termux-main stable/main x86_64 Packages
        100 /data/data/com.termux/files/usr/var/lib/dpkg/status
clang version 20.1.6
Target: x86_64-unknown-linux-android24
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
clang version 20.1.6
Target: x86_64-unknown-linux-android
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
```

### What is the expected behavior?

I expected that no error should occur, so **maybe, this should be fixed by applying the same exact "wrapper" that 32-bit ARM Termux uses which results in the behavior difference, from**:

- https://github.com/termux/termux-packages/pull/7856

**to all other Termux architectures as well?**

### System information

```shell
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__APK_FILE=/data/app/~~gVwKanLEt3onhDQBKcUZQA==/com.termux-Jepd-I809CuxEnnuONZ6_Q==/base.apk
TERMUX_APP__APK_RELEASE=F_DROID
TERMUX_APP__APP_VERSION_CODE=1020
TERMUX_APP__APP_VERSION_NAME=0.119.0-beta.1
TERMUX_APP__DATA_DIR=/data/user/0/com.termux
TERMUX_APP__IS_DEBUGGABLE_BUILD=false
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PID=12106
TERMUX_APP__TARGET_SDK=28
TERMUX_VERSION=0.119.0-beta.1
TERMUX__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c237,c256,c512,c768
TERMUX__SE_INFO=default:targetSdkVersion=28:complete
TERMUX__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c237,c256,c512,c768
TERMUX__UID=10237
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# apt(sources.list) [legacy]
deb https://packages.termux.dev/apt/termux-main stable main
# glibc-repo(sources.list.d/glibc.list) [legacy]
# The glibc termux repository, with cloudflare cache
deb https://packages-cf.termux.dev/apt/termux-glibc/ glibc stable
# The glibc termux repository, without cloudflare cache
# deb https://packages.termux.dev/apt/termux-glibc/ glibc stable
# root-repo(sources.list.d/root.list) [legacy]
deb https://packages.termux.dev/apt/termux-root root stable
# sources.list.d/termux-adb.list [legacy]
deb https://nohajc.github.io termux extras
# x11-repo(sources.list.d/x11.list) [legacy]
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
audacity-ffmpeg/x11 3.7.5 aarch64 [upgradable from: 3.7.4-1]
audacity/x11 3.7.5 aarch64 [upgradable from: 3.7.4-1]
chezmoi/stable 2.64.0 aarch64 [upgradable from: 2.63.1]
cmake-curses-gui/stable 4.1.0 aarch64 [upgradable from: 4.0.3]
cmake/stable 4.1.0 aarch64 [upgradable from: 4.0.3]
dpkg-perl/stable 1.22.6-4 all [upgradable from: 1.22.6-3]
dpkg-scanpackages/stable 1.22.6-4 all [upgradable from: 1.22.6-3]
dpkg/stable 1.22.6-4 aarch64 [upgradable from: 1.22.6-3]
ed/stable 1.22.1 aarch64 [upgradable from: 1.22]
firefox/x11 141.0.2 aarch64 [upgradable from: 141.0]
flameshot/x11 13.0.1 aarch64 [upgradable from: 13.0.0]
frida-dev/root 17.2.14-1 aarch64 [upgradable from: 17.2.14]
frida-python/root 17.2.14-1 aarch64 [upgradable from: 17.2.14]
frida/root 17.2.14-1 aarch64 [upgradable from: 17.2.14]
gtk-update-icon-cache/x11 3.24.50 aarch64 [upgradable from: 3.24.49-3]
gtk3/x11 3.24.50 aarch64 [upgradable from: 3.24.49-3]
krb5/stable 1.22 aarch64 [upgradable from: 1.21.3]
libapt-pkg-perl/stable 0.1.40-11 aarch64 [upgradable from: 0.1.40-10]
libheif-progs/stable 1.20.2 aarch64 [upgradable from: 1.20.1]
libheif/stable 1.20.2 aarch64 [upgradable from: 1.20.1]
libjasper-utils/stable 4.2.8 aarch64 [upgradable from: 4.2.7]
libjasper/stable 4.2.8 aarch64 [upgradable from: 4.2.7]
libraqm/stable 0.10.3 aarch64 [upgradable from: 0.10.2]
libregexp-assemble-perl/stable 0.38-7 all [upgradable from: 0.38-6]
libxmlb/stable 0.3.23 aarch64 [upgradable from: 0.3.22]
luanti-common/x11 1:5.13.0-1 all [upgradable from: 1:5.13.0]
luanti-server/x11 1:5.13.0-1 aarch64 [upgradable from: 1:5.13.0]
lux-cli/stable 0.13.1 aarch64 [upgradable from: 0.13.0]
oh-my-posh/stable 26.18.0 aarch64 [upgradable from: 26.17.3]
ollama/stable 0.11.3 aarch64 [upgradable from: 0.10.1]
oxc-language-server/stable 1.11.0 aarch64 [upgradable from: 1.9.0]
oxlint/stable 1.11.0 aarch64 [upgradable from: 1.9.0]
perl/stable 5.40.3 aarch64 [upgradable from: 5.40.3]
python-cryptography/stable 45.0.6 aarch64 [upgradable from: 45.0.5]
strace/stable 6.16 aarch64 [upgradable from: 6.15]
subversion-perl-static/stable 1.14.5-1 aarch64 [upgradable from: 1.14.5]
subversion-perl/stable 1.14.5-1 aarch64 [upgradable from: 1.14.5]
subversion/stable 1.14.5-1 aarch64 [upgradable from: 1.14.5]
w3m-img/stable 0.5.4 aarch64 [upgradable from: 0.5.3.20230121-3]
w3m/stable 0.5.4 aarch64 [upgradable from: 0.5.3.20230121-3]
yosys/stable 0.56 aarch64 [upgradable from: 0.55-1]
termux-tools version:
1.46.0
Android version:
13
Kernel build information:
Linux localhost 4.14.190-lineage-gef0cb31b13 #4 SMP PREEMPT Fri Jun 23 13:11:47 CEST 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A705FN
Supported ABIs:
SUPPORTED_ABIS: arm64-v8a,armeabi-v7a,armeabi
SUPPORTED_32_BIT_ABIS: armeabi-v7a,armeabi
SUPPORTED_64_BIT_ABIS: arm64-v8a
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec-ld-preload.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.x11 versionCode:15
```

### PR DESCRIPTION
**Pull request by robertkirkman**
- Fixes termux#25622, which is an error that began occurring after the update to NDK r28c

- Also makes Termux's `clang` package behave more similarly to how Termux's `TERMUX_ON_DEVICE_BUILD=false` cross-compiling toolchain behaves

### CODE REVIEW

**Comment by fornwall** [comment]
I think this makes sense.

The issue seems to come from NDK r27 having:

```c
#if __ANDROID_API__ >= 24
int fileno_unlocked(FILE* _Nonnull __fp) __INTRODUCED_IN(24);
#endif /* __ANDROID_API__ >= 24 */
```

while NDK r28 updates to:

```c
#if __BIONIC_AVAILABILITY_GUARD(24)
__nodiscard int fileno_unlocked(FILE* _Nonnull __fp) __INTRODUCED_IN(24);
#endif /* __BIONIC_AVAILABILITY_GUARD(24) */
```

Where the `__BIONIC_AVAILABILITY_GUARD` is defined in `<android/versioning.h>`:

```
#define __BIONIC_AVAILABILITY_GUARD(api_level) (__ANDROID_MIN_SDK_VERSION__ >= (api_level))
```

About `__ANDROID_MINSDK_VERSION__` vs ` __ANDROID_API__`, see https://developer.android.com/ndk/guides/sdk-versions:

> The minSdkVersion of your application is made available to the preprocessor via the __ANDROID_MIN_SDK_VERSION__ macro (the legacy __ANDROID_API__ is identical, but prefer the former because its meaning is clearer). This macro is defined automatically by Clang, so no header needs to be included to use it. For NDK builds, this macro is always defined.

When invoked through a symlink without the api level (such as `aarch64-linux-android-clang`) clang _will not_ define `__ANDROID_MIN_SDK_VERSION__` or `__ANDROID_API__` - see https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/Targets/OSTargets.h#L346-L351.

In Termux we do however get `__ANDROID_API__` defined in `<android/api-level.h>` since [we patch that file](https://github.com/termux/termux-packages/blob/master/scripts/build/toolchain/termux_setup_toolchain_28c.sh#L221C19-L222) to contain:

```c
#ifndef __ANDROID_API__
#define __ANDROID_API__ 24
#endif
```

We do not however get the more modern `__ANDROID_MIN_SDK_VERSION__` macro defined there, which causes the breakage as NDK r28 switches to use that more modern variant.

But we shouldn't need to define that ourself there - clang should AFAIK define both `__ANDROID_MIN_SDK_VERSION__` and `__ANDROID_API__`, and this PR makes that happen.

**Review by fornwall — APPROVED** [review]

File: packages/libllvm/build.sh [hunk 1]
```diff
@@ -134,43 +135,34 @@ termux_step_post_make_install() {
...
-				\`dirname \$0\`/clang++ "\$@"
-			fi
-			EOF
-			chmod u+x $tool
-		done
+	# Instead of symlinks, for executables named after target triplets, create the same type of
+	# wrapper that the cross-compiling NDK uses to choose the correct target, including the API level
+	local target="$CCTERMUX_HOST_PLATFORM"
+	if [[ "$TERMUX_ARCH" == "arm" ]]; then
+		target="armv7a-linux-androideabi$TERMUX_PKG_API_LEVEL"
```
Comment (fornwall) [inline packages/libllvm/build.sh:149]: This needs to be generalized now (shouldn't be only for `armv7a`).

**Review by fornwall — CHANGES_REQUESTED** [review]

**Review by fornwall — APPROVED** [review]

**Comment by robertkirkman** [comment]
Thank you very much for writing a more detailed explanation of why the error started occurring only after the update to NDK r28c, and didn't happen with NDK r27c! I did not understand it to that level of detail, so it is very helpful.

**Comment by robertkirkman** [comment]
> When invoked through a **symlink** without the api level (such as `aarch64-linux-android-clang`) clang will not define `__ANDROID_MIN_SDK_VERSION__` or `__ANDROID_API__`

I assume that specifically this condition is restricted to "symlinks that **contain a triplet in their name**", because `clang` is itself a symbolic link to `clang-20`, and when I tested the **`cc` and `gcc` commands**, which are also symbolic links, but which don't have a triplet in their names, they don't seem to be affected by the problem.

> https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/Targets/OSTargets.h#L346-L351

Thank you for showing where this problem's root cause is inside the code of llvm!

While planning this PR, I thought about trying to do that as well, and whether or not I should try to fix the problem by editing code inside llvm rather than wrapper code, but It occurred to me that **implementing this change using wrappers allows users to easily customize or remove the wrapper if they need to revert to the previous behavior**, while if I were to edit this inside the code of llvm before recompiling it, it would be much more difficult for users to locally revert this change if they ever have to.

**Comment by robertkirkman** [comment]
@licy183 I noticed now, after searching around for code that is similar to code that I'm editing in this PR, that you have implemented (from scratch by inventing Flang for Android?) the command `aarch64-linux-android-flang-new`, and you make this available for `build-package.sh` in `termux_setup_flang()`,

https://github.com/termux/termux-packages/blob/210cf16e36268a18e169d99ff463932c7331aac5/scripts/build/setup/termux_setup_flang.sh#L70-L74

however, what I noticed is that, unlike, for example, the command `pkg install clang`, the command `pkg install flang` does not provide a `$PREFIX/bin/aarch64-linux-android-flang-new` , only `$PREFIX/bin/flang-new`.

Do you think that providing `$PREFIX/bin/aarch64-linux-android-flang-new` with `pkg install flang`, and not only the one in `~/.termux-build/_cache/`, is something that would be a good idea, or would it just be unnecessary in the case of Flang?

Unfortunately, I am very inexperienced with Fortran, so I don't know what is idiomatic for that language.

**Comment by licy183** [comment]
There is no need to provide `$PLATFORM_TRIPLE-flang-new` for on-device build. It exists here just to make `cmake` happy. `cmake` will not work as intended without it when cross-compiling.

**Comment by robertkirkman** [comment]
I was not sure at first whether this would be the best way to solve the problem, but it does appear to be and others have agreed that this makes sense, so I will merge this in 24 hours if no problems are found.

At first, I was slightly worried about my implementation of `$PREFIX/bin/aarch64-linux-android-cpp` not being quite exactly the same as `~/.termux-build/_cache/android-r28c-api-24-v1/bin/aarch64-linux-android-cpp` (`cpp --target=...` instead of `clang -E --target=...`),

but I tested building `grep` on-device with this, which printed:

```
checking how to run the C preprocessor... aarch64-linux-android-cpp
```

and it seemed to build `grep` normally with no errors, so I think it is working completely fine.

**Comment by robertkirkman** [comment]
Biswa96 recommended that the commit message should be simplified, so I have revised it accordingly.

**Comment by Manamama** [comment]
@robertkirkman (and others who worked on #25627)
 
Disclaimer: me no coder, just a humble end-user, so below may be partly wrong in the IT analysis of the causes:
 
Thanks for that old PR. However, some Rust + maturin packages (e.g. `tokenizers` / `esaxx-rs`) still require an explicit flag (a different one to what I had thought as the right one, some weeks ago even):
```bash
export CXXFLAGS="$CXXFLAGS -D__ANDROID_MIN_SDK_VERSION__=$(getprop ro.build.version.sdk)"
```

This is  because bionic/libc++ gates functions like pthread_cond_clockwait on __ANDROID_MIN_SDK_VERSION__ (not just __ANDROID_API__), and the Rust build system sometimes doesn't pick up the default value properly. (Most probably this be the cause, see the "how much time I have spent to think if it be so indeed" here: https://github.com/huggingface/tokenizers/issues/1902#issuecomment-4968772208) 

Yes, I know that: 
`pip show tokenizers
Name: tokenizers
Version: 0.22.2
` exists, but then, at least as of now, this version clashes with `transformers`, not only cosmetically (one could `pip install -U transformers --no-deps`, I know), but also with some Roberta `cls` imports, which I have discovered by chance, only now, with yet another upgrade). 
 
 
Ref, what happens with default (none) Termux C(XX)FLAGs: 
```
     Compiling anstyle-parse v0.2.7
  warning: esaxx-rs@0.1.10: In file included from src/esaxx.cpp:621:
  warning: esaxx-rs@0.1.10: In file included from src/esa.hxx:30:
  warning: esaxx-rs@0.1.10: In file included from /data/data/com.termux/files/usr/bin/../../usr/include/c++/v1/vector:363:
  warning: esaxx-rs@0.1.10: In file included from /data/data/com.termux/files/usr/bin/../../usr/include/c++/v1/locale:209:
  warning: esaxx-rs@0.1.10: In file included from /data/data/com.termux/files/usr/bin/../../usr/include/c++/v1/__locale_dir/pad_and_output.h:16:
  warning: esaxx-rs@0.1.10: In file included from /data/data/com.termux/files/usr/bin/../../usr/include/c++/v1/ios:888:
  warning: esaxx-rs@0.1.10: In file included from /data/data/com.termux/files/usr/bin/../../usr/include/c++/v1/mutex:194:
  warning: esaxx-rs@0.1.10: /data/data/com.termux/files/usr/bin/../../usr/include/c++/v1/__condition_variable/condition_variable.h:226:14: error: use of undeclared identifier 'pthread_cond_clockwait'
  warning: esaxx-rs@0.1.10:   226 |   int __ec = pthread_cond_clockwait(&__cv_, __lk.mutex()->native_handle(), CLOCK_MONOTONIC, &__ts);
  warning: esaxx-rs@0.1.10:       |              ^~~~~~~~~~~~~~~~~~~~~~
  warning: esaxx-rs@0.1.10: 1 error generated.
  error: failed to run custom build command for `esaxx-rs v0.1.10`
```

**Comment by robertkirkman** [comment]
@Manamama , in your linked post, you show this at one point,

> `ANDROID_API_LEVEL=$(getprop ro.build.version.sdk)`


I believe that this might be part of your problem, because I do _not_ recommend setting that variable to that!

image

This is not my original advice!

I recommended, if you recall precisely from one of my earlier posts, 

image

- https://github.com/termux/termux-packages/issues/30428#issuecomment-4885610268

> `export ANDROID_API_LEVEL=24`

In my opinion, that might be quite important, because I do **not** recommend attempting to use a **higher Android API level than the global _`TERMUX_PKG_API_LEVEL`_ (24)** in anything in Termux that is not specifically set to that on a per-package level in a limited and controlled way (examples `termux-x11-nightly`, `pulseaudio`-`module-aaudio-sink`)

If you find yourself struggling with errors involving **`pthread_cond_clockwait()`**, I highly recommend to instead try to **remove the entire code chunk which uses that from the software using patches** because there is no other reliable way, because Termux currently globally uses **API level 24**.

**Comment by robertkirkman** [comment]
See these preexisting issues for more in-depth information:

- https://github.com/termux/termux-packages/issues/2469
- https://github.com/termux/termux-packages/issues/23401

In your case, **@Manamama I don't recommend attempting to follow any workarounds I posted for others in the above two issues ^ , and they should be used for historical reference only, because for your case I recommend attempting to remove `pthread_cond_clockwait()`-depending code from your desired software**.

**Comment by robertkirkman** [comment]
@Manamama to be completely clear, I do _not_ mean to edit the `condition_variable.h` header manually,

image

I mean that you should stop continuing to try to use `getprop ro.build.version.sdk` **anywhere**, and only use **24** instead, and only in the `ANDROID_API_LEVEL` variable as I instructed, and stop using `-D__ANDROID_API__` and `-D__ANDROID_MIN_SDK_VERSION__` manually, and only if _then_ you still see an error involving `pthread_cond_clockwait()`, the instance of that function name in the error should be in the application code and not in the header, and in that case you would remove it from the application code.

Do you understand what I mean yet?

**Comment by finagolfin** [comment]
I think this might be caused by this issue of _not_ setting an API level, android/ndk#2206, so simply setting one should make it work.

**Comment by Manamama** [comment]
Ah, indeed, some months or .bash_aliases versions ago I had set this variable unduly in two places , then removed it in one place only, and (as I see only now) wrote even, self-quote from  these FYI aliases not to touch it: `# Note:  -D__ANDROID_API__=${ANDROID_API_LEVEL} --target=aarch64-linux-android${ANDROID_API_LEVEL} errors nowadays , so do not use:  export ANDROID_API_LEVEL=$(getprop ro.build.version.sdk)` and ... forgot about the second place therein. 

And then I spent today 2 hours fighting my own mistake or my bad memory (as my aliases are hundreds of lines by now, mostly nifty functions: today's random two fingered addition thereto:  ... https://github.com/HSF/prmon/issues/315#issuecomment-4966690690)

Sorry for the bother then! And than for the help, yet again.

**Comment by robertkirkman** [comment]
> I think this might be caused by this issue of _not_ setting an API level, [android/ndk#2206](https://github.com/android/ndk/issues/2206), so simply setting one should make it work.

When I use `clang++ test.cpp` and `aarch64-linux-android-clang++ test.cpp` on your example shown in that issue, I'm not able to reproduce your error,

```
#include <iostream>

int main() {
  // Ensure that template instantiations inside C++
  // standard library in this call don't cause any new diagnostics
  // because of the generated header.
  std::cout << "test invoke std::cout\n" << std::endl;

  return 0;
}
```


I only see an error if I copy the `-target aarch64-unknown-linux-android` from your issue, which in my opinion, just personally, is not a correct argument and is not supposed to work on Android (even in Android NDK r27 I think it was only working by coincidence), though I understand that you expected that it should which is why you opened the issue upstream, and upstream's discussion explained valid tradeoffs one way or the other for whether or not that should be considered something that is supposed to work on Android.

Generally in my opinion, at least for as long as upstream has that issue marked as closed as not planned, any software which has `-target aarch64-unknown-linux-android` in it should be considered the broken software and `-target aarch64-unknown-linux-android` should be removed from it in favor of something else like `--target=aarch64-linux-android24`, or preferably nothing at all and allowing the Termux `clang` package to handle it.

**Comment by robertkirkman** [comment]
Reemphasizing for @Manamama that `--target=aarch64-linux-android24` should as well _not_ be necessary for anyone to _manually_ specify when building software inside Termux, because it is supposed to be internally set automatically,

you should only need to specify, for now, `export ANDROID_API_LEVEL=24` for Maturin, and that's it.

**Comment by Manamama** [comment]
Below is for the record only.  I know how to reinstall the lot (using yours or one of my own tips in transformers), but for the record, unsetting all (?) the relevant variable(s) causes below, at least on my end. The error even says why so, thus `export ANDROID_API_LEVEL=24` helps indeed. 

```

  Successfully uninstalled tokenizers-0.22.2
~ $ pip uninstall tokenizers
WARNING: Skipping tokenizers as it is not installed.
~ $ pip uninstall transformers
Found existing installation: transformers 5.13.1
Uninstalling transformers-5.13.1:
  Would remove:
    /data/data/com.termux/files/usr/bin/transformers
    /data/data/com.termux/files/usr/lib/python3.14/site-packages/transformers-5.13.1.dist-info/*
    /data/data/com.termux/files/usr/lib/python3.14/site-packages/transformers/*
Proceed (Y/n)? y
  Successfully uninstalled transformers-5.13.1
~ $ pip uninstall transformers
WARNING: Skipping transformers as it is not installed.


~ $ echo $ANDROID_API_LEVEL                                                                               ~ $ pip install transformers -v
Using pip 26.1.2 from /data/data/com.termux/files/usr/lib/python3.14/site-packages/pip (python 3.14)
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu
Collecting transformers
  Obtaining dependency information for transformers from https://files.pythonhosted.org/packages/29/47/54eacf96b5c835bbd6ca631aa2740e7705ed63d9e3a8afd2d2cc6d09cae5/transformers-5.13.1-py3-none-any.whl.metadata
  Using cached transformers-5.13.1-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (1.23.0)
Requirement already satisfied: numpy>=1.17 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (2.5.1)
Requirement already satisfied: packaging>=20.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (2026.6.28)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Using cached tokenizers-0.22.2.tar.gz (372 kB)
  Running command installing build dependencies for tokenizers
  Using pip 26.1.2 from /data/data/com.termux/files/usr/lib/python3.14/site-packages/pip (python 3.14)
  Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu, https://download.pytorch.org/whl/cpu
  Collecting maturin<2.0,>=1.0
    Using cached maturin-1.14.1-cp314-cp314-android_24_arm64_v8a.whl
  Installing collected packages: maturin
  Successfully installed maturin-1.14.1
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  🍹 Building a mixed python/rust project
  🐍 Found CPython 3.14 at /data/data/com.termux/files/usr/bin/python3.14
  🔗 Found pyo3 bindings with abi3-py3.9 support
  📡 Using build options features, bindings from pyproject.toml
  💥 maturin failed
    Caused by: Failed to determine Android API level. Please set the ANDROID_API_LEVEL environment variable.
  Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-ur_9w8no', '--interpreter', '/data/data/com.termux/files/usr/bin/python3.14']' returned non-zero exit status 1.
  Checking for Rust toolchain....
  Running `maturin pep517 write-dist-info --metadata-directory /data/data/com.termux/files/usr/tmp/pip-modern-metadata-ur_9w8no --interpreter /data/data/com.termux/files/usr/bin/python3.14`
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> No available output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /data/data/com.termux/files/usr/bin/python3.14 /data/data/com.termux/files/usr/lib/python3.14/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /data/data/com.termux/files/usr/tmp/tmpx4vw_i8r
  cwd: /data/data/com.termux/files/usr/tmp/pip-install-xwvjcqmk/tokenizers_e970b6e1b6b840daaecf29e329a76ab5
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> tokenizers

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
~ $ echo $BUILD_VAR
aarch64-unknown-linux-android
~ $ unset BUILD_VAR
~ $ pip install transformers -v
Using pip 26.1.2 from /data/data/com.termux/files/usr/lib/python3.14/site-packages/pip (python 3.14)
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu
Collecting transformers
  Obtaining dependency information for transformers from https://files.pythonhosted.org/packages/29/47/54eacf96b5c835bbd6ca631aa2740e7705ed63d9e3a8afd2d2cc6d09cae5/transformers-5.13.1-py3-none-any.whl.metadata
  Using cached transformers-5.13.1-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (1.23.0)
Requirement already satisfied: numpy>=1.17 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (2.5.1)
Requirement already satisfied: packaging>=20.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (2026.6.28)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Using cached tokenizers-0.22.2.tar.gz (372 kB)
  Running command installing build dependencies for tokenizers
  Using pip 26.1.2 from /data/data/com.termux/files/usr/lib/python3.14/site-packages/pip (python 3.14)
  Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu, https://download.pytorch.org/whl/cpu
  Collecting maturin<2.0,>=1.0
    Using cached maturin-1.14.1-cp314-cp314-android_24_arm64_v8a.whl
  Installing collected packages: maturin
  Successfully installed maturin-1.14.1
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  🍹 Building a mixed python/rust project
  🐍 Found CPython 3.14 at /data/data/com.termux/files/usr/bin/python3.14
  🔗 Found pyo3 bindings with abi3-py3.9 support
  📡 Using build options features, bindings from pyproject.toml
  💥 maturin failed
    Caused by: Failed to determine Android API level. Please set the ANDROID_API_LEVEL environment variable.
  Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-wla4ng4j', '--interpreter', '/data/data/com.termux/files/usr/bin/python3.14']' returned non-zero exit status 1.
  Checking for Rust toolchain....
  Running `maturin pep517 write-dist-info --metadata-directory /data/data/com.termux/files/usr/tmp/pip-modern-metadata-wla4ng4j --interpreter /data/data/com.termux/files/usr/bin/python3.14`
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> No available output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /data/data/com.termux/files/usr/bin/python3.14 /data/data/com.termux/files/usr/lib/python3.14/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /data/data/com.termux/files/usr/tmp/tmpi11kbgde
  cwd: /data/data/com.termux/files/usr/tmp/pip-install-yafccmbp/tokenizers_f22362795549477884c31a34882dbcb3
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> tokenizers

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
~ $ env | grep aarch64-unknown-linux-android
~ $ env | grep LEVEL
CARGO_PROFILE_RELEASE_OPT_LEVEL=2
~ $
```

that is: no such variables or flags (I guess status quo for default Termux users) and then it errors. 
vs. `export ANDROID_API_LEVEL=24` and all maturin stuff works again: 
```
...
Compiling tokenizers v0.22.2 (/data/data/com.termux/files/usr/tmp/pip-install-8utexig0/tokenizers_970152f30cd74d7894aebae58291b378/tokenizers)
     Compiling pyo3-async-runtimes v0.26.0                Compiling tokenizers-python v0.22.2 (/data/data/com.termux/files/usr/tmp/pip-install-8utexig0/tokenizers_970152f30cd74d7894aebae58291b378/bindings/python)
...
Successfully built tokenizers
Installing collected packages: tokenizers, transformers
...
Successfully installed tokenizers-0.22.2 transformers-5.13.1
```

**Comment by finagolfin** [comment]
> I only see an error if I copy the -target aarch64-unknown-linux-android from your issue, which in my opinion, just personally, is not a correct argument and is not supposed to work on Android

Right, that is my point: since he got the same error I got, I speculated that his build config was incorrectly specifying a triple without an API level.

**Comment by robertkirkman** [comment]
Thanks for clarifying, I was just confused for a little while when you said that it might be caused by _not_ setting an API level, which could be interpreted, if not clarified, as applying to several different situations.

In summary, when Maturin says this:

```
Caused by: Failed to determine Android API level. Please set the ANDROID_API_LEVEL environment variable.
```

the solution is to set `export ANDROID_API_LEVEL=24` like it says and not mess with any other variables at the same time.

**Comment by Manamama** [comment]
Update some days later to my report about the recondite flags (still) needed. 

After yet another forced reinstall of `transformers` (and thus `tokenizers`), for unrelated reason, with compiling anew (not from wheels) from scratch, and also finally rationalizing all the FLAGS to zero (the fewer the better, indeed), I still stand by the need of `export CXXFLAGS="$CFXXLAGS -D__ANDROID_MIN_SDK_VERSION__=$(getprop ro.build.version.sdk)"` or a closely related, somewhat recondite to regular user, flag now and then. 
To prove it formally, I have prepared the minimally reproducible set of flags, toggled on and off, in attached, which I hope it is clear: 
[test_transformers.sh](https://github.com/user-attachments/files/30053131/test_transformers.sh)
The log of both of these test to show how the flag is indeed needed is also attached: 
[tokenizers_flags_test_20260715_161452.log](https://github.com/user-attachments/files/30053165/tokenizers_flags_test_20260715_161452.log)
(longish, I know). 

For the record, as for   https://github.com/termux/termux-packages/pull/25627#issuecomment-4971485668 , I did not have this in `env`  during the tests, proof:   
```
~/Downloads $ env | grep  aarch64-unknown-linux-android
~/Downloads $ 
```
 All other weird flags or other `env` stuff had been zeroed (I hope and have checked also by `grrep`ing for any) for these tests. 

Am curious: is this test for this error reproducible on your Termuxes or is due to  it e.g. my API is too old by now?  


Update 1: 
the same flag seems also needed for installing also this, which speeds up some `transformers` stuff 2 times, also on pure Termux (and not only in prooted Debian):
```
pip show onnx
Name: onnx
Version: 1.22.0
Summary: Open Neural Network Exchange
Home-page: https://onnx.ai/
Author: 
Author-email: ONNX Contributors <onnx-technical-discuss@lists.lfaidata.foundation>
License-Expression: Apache-2.0
Location: /data/data/com.termux/files/usr/lib/python3.14/site-packages
Requires: ml_dtypes, numpy, protobuf, typing_extensions
Required-by: optimum-onnx
```

**Comment by robertkirkman** [comment]
@Manamama unfortunately, I'm not able to reproduce your problem in clean Termux when I run your script; I had to remove some of the extra arguments that you added to the `pip install` commands, because one of them was causing `maturin` and `setuptools` to not get automatically  installed (maybe `--no-build-isolation`) and so I would see errors like `pip._vendor.pyproject_hooks._impl.BackendUnavailable: Cannot import 'setuptools.build_meta'` (with both tests) if I don't remove those arguments, so you already have some things previously installed in your Termux before running the script that you sent,

when I use this version of your script,

```bash
#!/bin/bash
# Tokenizers Minimal Flags Test - A vs B
# Logs everything for easy GitHub attachment

LOGFILE="tokenizers_flags_test_$(date +%Y%m%d_%H%M%S).log"

echo "=== Tokenizers Minimal Flags Test ===" | tee -a "$LOGFILE"
echo "Log file: $LOGFILE" | tee -a "$LOGFILE"
echo "====================================" | tee -a "$LOGFILE"

# Uninstall only relevant packages
pip uninstall -y transformers tokenizers 2>&1 | tee -a "$LOGFILE"

echo -e "\n=== Test A: Only ANDROID_API_LEVEL=24 (guru recommended) ===" | tee -a "$LOGFILE"
export ANDROID_API_LEVEL=24
unset CFLAGS
unset CXXFLAGS

time pip install transformers 2>&1 | tee -a "$LOGFILE"

echo -e "\n=== Test A finished ===\n" | tee -a "$LOGFILE"

# Clean for Test B
pip uninstall -y transformers tokenizers 2>&1 | tee -a "$LOGFILE"

echo -e "\n=== Test B: ANDROID_API_LEVEL + minimal macro (your version) ===" | tee -a "$LOGFILE"
export ANDROID_API_LEVEL=24
export CFLAGS="-D__ANDROID_MIN_SDK_VERSION__=$(getprop ro.build.version.sdk)"
export CXXFLAGS="$CFLAGS"

time pip install transformers 2>&1 | tee -a "$LOGFILE"

echo -e "\n=== Test B finished ===\n" | tee -a "$LOGFILE"

# Summary
echo "=== SUMMARY ===" | tee -a "$LOGFILE"
echo "ANDROID_API_LEVEL = $ANDROID_API_LEVEL" | tee -a "$LOGFILE"
echo "CFLAGS  = $CFLAGS" | tee -a "$LOGFILE"
echo "CXXFLAGS = $CXXFLAGS" | tee -a "$LOGFILE"
echo "Full log saved to: $LOGFILE" | tee -a "$LOGFILE"

echo -e "\nTest completed. Attach $LOGFILE to your GitHub comment."
```

I see this, with both tests passing successfully without errors:

```
=== Tokenizers Minimal Flags Test ===
Log file: tokenizers_flags_test_20260715_151722.log
====================================
WARNING: Skipping transformers as it is not installed.
WARNING: Skipping tokenizers as it is not installed.

=== Test A: Only ANDROID_API_LEVEL=24 (guru recommended) ===
Collecting transformers
  Downloading transformers-5.13.1-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (1.22.0)
Requirement already satisfied: numpy>=1.17 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (2.4.4)
Requirement already satisfied: packaging>=20.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (6.0.3)
Collecting regex>=2025.10.22 (from transformers)
  Downloading regex-2026.7.10.tar.gz (416 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Downloading tokenizers-0.22.2.tar.gz (372 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting typer (from transformers)
  Downloading typer-0.26.8-py3-none-any.whl.metadata (15 kB)
Collecting safetensors>=0.8.0 (from transformers)
  Downloading safetensors-0.8.0.tar.gz (325 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: tqdm>=4.60 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (4.68.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.5)
Requirement already satisfied: fsspec>=2023.5.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.16.0)
Requirement already satisfied: anyio in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.14.1)
Requirement already satisfied: certifi in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Collecting shellingham>=1.3.0 (from typer->transformers)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer->transformers)
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->transformers)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer->transformers)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=13.8.0->typer->transformers)
  Using cached pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading transformers-5.13.1-py3-none-any.whl (11.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 44.4 MB/s  0:00:00
Downloading typer-0.26.8-py3-none-any.whl (122 kB)
Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading rich-15.0.0-py3-none-any.whl (310 kB)
Using cached pygments-2.20.0-py3-none-any.whl (1.2 MB)
Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Building wheels for collected packages: tokenizers, regex, safetensors
  Building wheel for tokenizers (pyproject.toml): started
  Building wheel for tokenizers (pyproject.toml): finished with status 'done'
  Created wheel for tokenizers: filename=tokenizers-0.22.2-cp39-abi3-android_24_x86_64.whl size=3237042 sha256=3d669a428a3f3db90d44c70f136bedff5e8ffa1f92a328ab71be5712284c8ffe
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/bb/5d/d6/f495f90169a6d039a1667b4d1e9978c927bf28c6bfb69a4b28
  Building wheel for regex (pyproject.toml): started
  Building wheel for regex (pyproject.toml): finished with status 'done'
  Created wheel for regex: filename=regex-2026.7.10-cp314-cp314-android_24_x86_64.whl size=576847 sha256=39021b58dd722d7beda02b1261a1b1ff86ea446e1115aa094eeca19be8253f3e
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/80/20/75/28673a46ad0faad8892fa6226251c0b72db011c6527ebfad50
  Building wheel for safetensors (pyproject.toml): started
  Building wheel for safetensors (pyproject.toml): finished with status 'done'
  Created wheel for safetensors: filename=safetensors-0.8.0-cp310-abi3-android_24_x86_64.whl size=537873 sha256=e260addacee6d5115457cfcb5e15fecce3014ba9040a0655de73248f56b98825
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/17/82/e6/5781ab28fc4532980d6b6733dbb5e4ad38c5633e3f9d1e58a7
Successfully built tokenizers regex safetensors
Installing collected packages: shellingham, safetensors, regex, pygments, mdurl, annotated-doc, markdown-it-py, rich, typer, tokenizers, transformers

Successfully installed annotated-doc-0.0.4 markdown-it-py-4.2.0 mdurl-0.1.2 pygments-2.20.0 regex-2026.7.10 rich-15.0.0 safetensors-0.8.0 shellingham-1.5.4 tokenizers-0.22.2 transformers-5.13.1 typer-0.26.8

=== Test A finished ===

Found existing installation: transformers 5.13.1
Uninstalling transformers-5.13.1:
  Successfully uninstalled transformers-5.13.1
Found existing installation: tokenizers 0.22.2
Uninstalling tokenizers-0.22.2:
  Successfully uninstalled tokenizers-0.22.2

=== Test B: ANDROID_API_LEVEL + minimal macro (your version) ===
Collecting transformers
  Using cached transformers-5.13.1-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (1.22.0)
Requirement already satisfied: numpy>=1.17 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (2.4.4)
Requirement already satisfied: packaging>=20.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (2026.7.10)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-android_24_x86_64.whl
Requirement already satisfied: typer in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (4.68.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.5)
Requirement already satisfied: fsspec>=2023.5.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.16.0)
Requirement already satisfied: anyio in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.14.1)
Requirement already satisfied: certifi in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Using cached transformers-5.13.1-py3-none-any.whl (11.5 MB)
Installing collected packages: tokenizers, transformers

Successfully installed tokenizers-0.22.2 transformers-5.13.1

=== Test B finished ===

=== SUMMARY ===
ANDROID_API_LEVEL = 24
CFLAGS  = -D__ANDROID_MIN_SDK_VERSION__=
CXXFLAGS = -D__ANDROID_MIN_SDK_VERSION__=
Full log saved to: tokenizers_flags_test_20260715_151722.log
```

so I don't know exactly how to reproduce your issue, without other steps given for what you installed in your Termux before running this.

@Manamama also, could you tell me the `termux-info` of your device again, or, just what version of Android you have, such as 13, 14, 15, 16 or 17?

**Comment by Manamama** [comment]
Mysteriouser and mysteriouser! I need to understand whence this pesky error as I use a series of such low-cost Droids for signals processing, using some these python modules, too. Maybe because of this left there indeed? : `ANDROID_API_LEVEL` ? Or I hand compiled some CLANG level .so file years ago and it is affecting compilation?  Or e.g. maturin is too old or too new? 
 Voila, as requested plus some more: 
```
Swap info:

Filename				Type		Size		Used		Priority
/dev/block/zram0                        partition	3145724		1420284		-2
/data/swapfile                          file		6291452		0		-3
To disable, use:  sudo swapoff /dev/block/zram0

Filename				Type		Size		Used		Priority
/dev/block/zram0                        partition	3145724		1420284		-2
/data/swapfile                          file		6291452		0		-3

Run termux-info or lscpu to learn more
...
The internal and external SD Cards volumes may be available at below (testing the access thereto now, as the regular user). Try with 'sudo' as per below, if the listing below fail (nothing is shown):
Internal SD card: sudo ls /storage/self/primary
Android
AppManager
External SD card, path #1: sudo ls /storage/sdcard1
 or this path #2: sudo ls ~/storage/external_SD
AA_Realme_Flash
Android

... 
D: [pulseaudio] conf-parser.c: Parsing configuration file '/data/data/com.termux/files/usr/etc/pulse/client.conf'
W: [pulseaudio] conf-parser.c: scandir("/data/data/com.termux/files/usr/etc/pulse/client.conf.d") failed: Unknown error 20
I: [pulseaudio] main.c: Daemon startup successful.

Starting processing 🤹 Termux bash aliases

=== Clean Termux build environment loaded ===
Environment at system:
Linux localhost 4.14.186+ #1 SMP PREEMPT Thu Mar 17 16:28:22 CST 2022 aarch64 Android
PATH: /data/data/com.termux/files/usr/home/.local/bin:/data/data/com.termux/files/usr/home/.cargo/bin:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/sbin:/data/data/com.termux/files/home/.local/bin:/data/data/com.termux/files/home/.cargo/bin:/data/data/com.termux/files/usr/usr/bin:/system/bin/:/data/data/com.termux/files/usr/home/.local/bin:/data/data/com.termux/files/usr/home/.cargo/bin:/data/data/com.termux/files/usr/home/.local/bin://data/data/com.termux/files/usr/home/.cargo/bin:/data/data/com.termux/files/usr/home/.local/bin://data/data/com.termux/files/usr/home/.cargo/bin:/data/data/com.termux/files/usr/home/.local/bin://data/data/com.termux/files/usr/home/.cargo/bin:/data/data/com.termux/files/usr/home/.local/bin://data/data/com.termux/files/usr/home/.cargo/bin:/data/data/com.termux/files/usr/home/.local/bin://data/data/com.termux/files/usr/home/.cargo/bin:/data/data/com.termux/files/home/.bun/bin:/data/data/com.termux/files/home/.opencode/bin:/data/data/com.termux/files/usr/home/.local/bin://data/data/com.termux/files/usr/home/.cargo/bin:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/sbin:/data/data/com.termux/files/home/.local/bin:/data/data/com.termux/files/home/.cargo/bin:/data/data/com.termux/files/usr/usr/bin:/system/bin/:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/home/Downloads/GitHub/depot_tools
LD_PRELOAD: /data/data/com.termux/files/usr/lib/libtermux-exec-direct-ld-preload.so
CFLAGS:  -D__ANDROID_MIN_SDK_VERSION__=30
CXXFLAGS:  -D__ANDROID_MIN_SDK_VERSION__=30
LDFLAGS: -llog -largp -lm -lpthread
CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Release   -DCMAKE_POSITION_INDEPENDENT_CODE=ON   -DONNX_BUILD_TESTS=OFF -DONNX_BUILD_BENCHMARKS=OFF   -DOPENMP_RUNTIME=COMP -DOPENBLAS_INCLUDE_DIR=/data/data/com.termux/files/usr/include/openblas   -DUSE_EXTERNAL_SPDLOG=ON -DUSE_EXTERNAL_NLOHMANN_JSON=ON -DPYBIND11_FINDPYTHON=ON
JAVA_HOME: /data/data/com.termux/files/usr/lib/jvm/java-21-openjdk/
ANDROID_API_LEVEL: 24

End of processing 🤹 Termux bash aliases #1.

Environment at system:
Linux localhost 4.14.186+ #1 SMP PREEMPT Thu Mar 17 16:28:22 CST 2022 aarch64 Android
... 

ro.build.version.security_patch: 2020-02-05
getprop ro.build.display.id: RMX3085_11_A.26
u0_a278@localhost
-----------------
OS: Android REL 11 aarch64
Host: realme 8 (RMX3085)
Kernel: Linux 4.14.186+
Uptime: 1 day, 8 hours, 40 mins
Packages: 940 (dpkg), 142 (pacman)
Shell: bash 5.3.9
DE: RMX3085_11_A.26
WM: WindowManager (SurfaceFlinger)
Terminal: /dev/pts/28 10.4p1
CPU: MT6785V/CD (2+6) @ 2.05 GHz
GPU: ARM Mali-G76 MC4 r0p0 (4) @ 0.01 GHz [Integrated]
Memory: 2.83 GiB / 5.51 GiB (51%)
Swap: 1.35 GiB / 9.00 GiB (15%)
Disk (/): 1.97 GiB / 1.97 GiB (100%) - ext4 [Read-only]
Disk (/storage/emulated): 98.18 GiB / 108.01 GiB (91%) - fuse
```
plus: 
```
~ $ termux-info 
Termux Variables:
TERMUX_API_VERSION=0.53.0
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=14082
TERMUX_APP__DATA_DIR=/data/user/0/com.termux
TERMUX_APP__LEGACY_DATA_DIR=/data/data/com.termux
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c22,c257,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.3
TERMUX__HOME=/data/data/com.termux/files/home
TERMUX__PREFIX=/data/data/com.termux/files/usr
TERMUX__ROOTFS_DIR=/data/data/com.termux/files
TERMUX__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c22,c257,c512,c768
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
# sources.list.d/x11.list
deb https://packages.termux.dev/apt/termux-x11 x11 main
# sources.list.d/tur.list
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# sources.list.d/root.list
deb https://packages.termux.dev/apt/termux-root root stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24  termux extras
# sources.list.d/termux-adb.list
deb https://nohajc.github.io termux extras
# sources.list.d/glibc.list
deb https://packages-cf.termux.dev/apt/termux-glibc/ glibc stable
Updatable packages:
qt6-qtbase-gtk-platformtheme/x11 6.11.1-2 aarch64 [upgradable from: 6.11.1-1]
qt6-qtbase/x11 6.11.1-2 aarch64 [upgradable from: 6.11.1-1]
termux-tools version:
1.45.0
Android version:
11
Kernel build information:
Linux localhost 4.14.186+ #1 SMP PREEMPT Thu Mar 17 16:28:22 CST 2022 aarch64 Android
Device manufacturer:
realme
Device model:
RMX3085
Supported ABIs:
SUPPORTED_ABIS: arm64-v8a,armeabi-v7a,armeabi
SUPPORTED_32_BIT_ABIS: armeabi-v7a,armeabi
SUPPORTED_64_BIT_ABIS: arm64-v8a
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec-direct-ld-preload.so
Installed termux plugins:
com.termux.api versionCode:1002
com.termux.gui versionCode:7
com.termux.x11 versionCode:14
com.termux.boot versionCode:1000
com.termux.styling versionCode:1000
com.termux.widget versionCode:1001
com.termux.window versionCode:1001
[1]+  Done                       updatedb
~ $ 
```

**Comment by robertkirkman** [comment]
Hmm, you have aarch64 Android 11, and I don't have that exact version of Android unfortunately, but earlier I was testing on x86_64 Android 9, so now I have tested on aarch64 Android 16, so since I can't reproduce the problem with versions of android that are both older and newer than the version of Android that you are using, and one with the same architecture as yours, I think it is unlikely that the version of Android or the architecture of the CPU has anything to do with this, and can probably be ruled out,

On aarch64 Android 16 just now, I just used `export ANDROID_API_LEVEL=24` and then `pip install transformers` and it worked, and here is my log:

```
~ $ export ANDROID_API_LEVEL=24
~ $ pip install transformers
Collecting transformers
  Using cached transformers-5.13.1-py3-none-any.whl.metadata (32 kB)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Using cached huggingface_hub-1.23.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (2.4.4)
Collecting packaging>=20.0 (from transformers)
  Using cached packaging-26.2-py3-none-any.whl.metadata (3.5 kB)
Collecting pyyaml>=5.1 (from transformers)
  Using cached pyyaml-6.0.3.tar.gz (130 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting regex>=2025.10.22 (from transformers)
  Using cached regex-2026.7.10.tar.gz (416 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Using cached tokenizers-0.22.2.tar.gz (372 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typer in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from transformers) (0.15.4)
Collecting safetensors>=0.8.0 (from transformers)
  Downloading safetensors-0.8.0.tar.gz (325 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting tqdm>=4.60 (from transformers)
  Downloading tqdm-4.68.4-py3-none-any.whl.metadata (57 kB)
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.5)
Requirement already satisfied: fsspec>=2023.5.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.0)
Collecting hf-xet<2.0.0,>=1.5.1 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading hf_xet-1.5.1.tar.gz (876 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 876.6/876.6 kB 9.0 MB/s  0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: httpx<1,>=0.23.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.16.0)
Requirement already satisfied: anyio in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.14.1)
Requirement already satisfied: certifi in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
INFO: pip is looking at multiple versions of typer to determine which version is compatible with other requirements. This could take a while.
Collecting typer (from transformers)
  Downloading typer-0.26.8-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: shellingham>=1.3.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from typer->transformers) (13.9.4)
Collecting annotated-doc>=0.0.2 (from typer->transformers)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /data/data/com.termux/files/usr/lib/python3.14/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Downloading transformers-5.13.1-py3-none-any.whl (11.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.5/11.5 MB 17.0 MB/s  0:00:00
Downloading huggingface_hub-1.23.0-py3-none-any.whl (770 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 770.3/770.3 kB 14.1 MB/s  0:00:00
Downloading click-8.4.2-py3-none-any.whl (119 kB)
Using cached packaging-26.2-py3-none-any.whl (100 kB)
Downloading tqdm-4.68.4-py3-none-any.whl (676 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 676.6/676.6 kB 12.4 MB/s  0:00:00
Downloading typer-0.26.8-py3-none-any.whl (122 kB)
Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Building wheels for collected packages: hf-xet, tokenizers, pyyaml, regex, safetensors
  Building wheel for hf-xet (pyproject.toml) ... done
  Created wheel for hf-xet: filename=hf_xet-1.5.1-cp37-abi3-android_24_arm64_v8a.whl size=4488142 sha256=00e2b9074958eafdd1d7dfdf34ad82bb53edfc5a26815b750e148d8438b94568
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/b9/55/63/6e73ee334043ac7994b992d86e232b15a27901200e9a9c04a1
  Building wheel for tokenizers (pyproject.toml) ... done
  Created wheel for tokenizers: filename=tokenizers-0.22.2-cp39-abi3-android_24_arm64_v8a.whl size=3220387 sha256=ca36c25a923b31e31939d70d7233029b39e8587d6c364086d5d73b6cabdf0560
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/bb/5d/d6/f495f90169a6d039a1667b4d1e9978c927bf28c6bfb69a4b28
  Building wheel for pyyaml (pyproject.toml) ... done
  Created wheel for pyyaml: filename=pyyaml-6.0.3-cp314-cp314-android_24_arm64_v8a.whl size=373212 sha256=f78b357a095e6c5be608a2562ee12958cfcb1b6ee40c1f9a1f7eee0de81f0dec
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/5c/15/7e/fe0ae6dcc91614d09e03950315089c18fc7cb20913d1334f2b
  Building wheel for regex (pyproject.toml) ... done
  Created wheel for regex: filename=regex-2026.7.10-cp314-cp314-android_24_arm64_v8a.whl size=554841 sha256=aa7810d500774c96ac005e9bfd5c1ab69f3f949275aa2003cbe598e1ff7fbcb9
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/80/20/75/28673a46ad0faad8892fa6226251c0b72db011c6527ebfad50
  Building wheel for safetensors (pyproject.toml) ... done
  Created wheel for safetensors: filename=safetensors-0.8.0-cp310-abi3-android_24_arm64_v8a.whl size=532650 sha256=74e9b3f5cb57daaa19ddeac0f8ea530e3d2da60e8ac291c34b7b587c51945404
  Stored in directory: /data/data/com.termux/files/home/.cache/pip/wheels/17/82/e6/5781ab28fc4532980d6b6733dbb5e4ad38c5633e3f9d1e58a7
Successfully built hf-xet tokenizers pyyaml regex safetensors
Installing collected packages: tqdm, safetensors, regex, pyyaml, packaging, hf-xet, click, annotated-doc, typer, huggingface-hub, tokenizers, transformers
  Attempting uninstall: click
    Found existing installation: click 8.1.8
    Uninstalling click-8.1.8:
      Successfully uninstalled click-8.1.8
  Attempting uninstall: typer
    Found existing installation: typer 0.15.4
    Uninstalling typer-0.15.4:
      Successfully uninstalled typer-0.15.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nala 0.16.0 requires typer<0.16.0,>=0.15.2, but you have typer 0.26.8 which is incompatible.
Successfully installed annotated-doc-0.0.4 click-8.4.2 hf-xet-1.5.1 huggingface-hub-1.23.0 packaging-26.2 pyyaml-6.0.3 regex-2026.7.10 safetensors-0.8.0 tokenizers-0.22.2 tqdm-4.68.4 transformers-5.13.1 typer-0.26.8
~ $ 
```

however, something I have noticed is that you have a huge `PATH` in your Termux "clean environment" that looks as though many things are installed in folders under the home folder and added to `PATH`; have you taken that into consideration and tried tests with a purely clean `env` environment in Termux, including a clean `PATH` only including `/data/data/com.termux/files/usr/bin`?

image


also, your idea about the Maturin version is good, have you checked it using `pip show maturin`? when I use `pip install maturin` and `pip show maturin`, I see this:

```
~ $ pip install maturin
Collecting maturin
  Using cached maturin-1.14.1-cp314-cp314-android_24_arm64_v8a.whl
Installing collected packages: maturin
Successfully installed maturin-1.14.1
~ $ pip show maturin
Name: maturin
Version: 1.14.1
Summary: Build and publish crates with pyo3, cffi and uniffi bindings as well as rust binaries as python packages
Home-page: 
Author: 
Author-email: konstin <konstin@mailbox.org>
License-Expression: MIT OR Apache-2.0
Location: /data/data/com.termux/files/usr/lib/python3.14/site-packages
Requires: 
Required-by: 
~ $ 
```

**Comment by Manamama** [comment]
Thanks. Will try to look into it one day, maybe also after a test full `mv` of $PREFIX and  then a test reinstall of Termux too, or doing it on  my parallel Droids 11 (same hardware, but more automated, default `apt upgrades`, no `git clone` of some bespoke pesky torch-level tools there). Both tries should take hours, so not that soon. Take care! 

PS. I love your work, as e.g. running full `onnx`, allowing for some weights instant recompilation to local cache, now sped up my `transformers` based rhetorics pipelines by 2, let me show you in the meantime, and sorry for that huge off topic: 
Screenshot_2026-07-16-08-14-34-33
- that 19th c. encyclic takes now, more or less: 
```
Loading weights: 100%|█| 103/103 [00:00<00:00, 423.57i
  [1/4] Running subjectivity analysis...
  Subjectivity Analysis finished in 60.81s
  [2/4] Running media bias analysis...
  Media Bias Analysis finished in 89.56s
  [3/4] Running propaganda detection...
  Propaganda Detection finished in 33.77s
  [4/4] Running universal archetype analysis...
BLAS : Bad memory unallocation! :   50  0x7a4ede2000
Batches: 100%|██████████| 1/1 [00:11<00:00, 11.07s/it]
  Universal Archetype Analysis finished in 12.71s
...
Total analysis time: 345.96 seconds
        Command being timed: "python /data/data/com.termux/files/home/Downloads/GitHub/Ubuntu_Scripts_1/ai_ml/rhetoric_analysis.py /root/storage/downloads/2026-07-15_pope.txt"
        User time (seconds): 969.25
        System time (seconds): 27.66

``
over a sip of coffee...

**Comment by Manamama** [comment]
Quick, morning coffee, informal update re: 

> doing it on my parallel Droids 11 (same hardware and system image, but more automated, default apt upgrades, ...

This other parallel Droid, same hardware as the main Droid where the A/B .sh test still fails, but virgin almost .bashrc and aliases and exports, and this being thus empty: `env | grep MIN`  (minimal SDK etc), and this works there: 
* `~/Downloads $ env | grep LEVEL                         CARGO_PROFILE_RELEASE_OPT_LEVEL=2                      ANDROID_API_LEVEL=24                                   ~/Downloads $`
* then just `/data/data/com.termux/files/usr/bin/time -v pip install --no-build-isolation -v --ignore-requires-python --retries 10 --resume-retries 50 --timeout 60 --no-binary :all: --extra-index-url https://termux-user-repository.github.io/pypi/ --no-cache` with `transformers` and `onnx` 
both work, no `maturin` error. 
Now I noticed that the main Droid where the A/B test still fails has: 
```
pip show maturin                         Name: maturin
Version: 1.14.1
Summary: Build and publish crates with pyo3, cffi and uniffi bindings as well as rust binaries as python packages
Home-page: https://github.com/pyo3/maturin
``` 

(not any special edition, just `pip -U install`-ed some weeks ago) while the parallel Droid where the above works with defaults has indeed lower: `Name: maturin
Version: 1.13.3` . Hm. Maybe I have indeed some weird maturin or cargo switches (or even had miscompiled some material `.so` component years ago) off github repo on the 'bad' Droid, e.g. when installing tensorflow (yes, as I can remember:  I had managed to do so, about two years ago, and some python version back, directly on Droid, as an experiment....) and unwittingly tweaking too much some "cannot be done in Termux" stuff thereby ? Wild guesses by now...
