### PR TITLE
libllvm: Build gold plugin

### LINKED ISSUE #14616: [Bug]: LLVMgold.so missing in binutils-gold or llvm
### Problem description

LLVMgold.so is missing in binutils-gold or libllvm.
It had existed when #4987.
Is it no longer provided?

build log:
```
/data/data/com.termux/files/usr/bin/ld.gold: error: 
/data/data/com.termux/files/usr/bin/../lib/LLVMgold.so: could not load plugin library: 
dlopen failed: library "/data/data/com.termux/files/usr/bin/../lib/LLVMgold.so" not found
```

### What steps will reproduce the bug?

Install `binutils-gold` from apt and build something application which uses LLVM Gold plugin in build (e.g. [vvenc](https://github.com/fraunhoferhhi/vvenc))

### What is the expected behavior?

Exists

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=25099
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.cbrx.io/apt/termux/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://mirrors.cbrx.io/apt/termux/termux-root root stable
deb https://mirrors.cbrx.io/apt/termux/termux-x11 x11 main
Updatable packages:
libvips/stable 8.14.1 aarch64 [upgradable from: 8.13.3-3]
termux-tools version:
1.35.0
Android version:
11
Kernel build information:
Linux localhost 4.14.190-perf+ #1 SMP PREEMPT Wed Oct 6 08:08:41 JST 2021 aarch64 Android
Device manufacturer:
Sony
Device model:
SO-01M

```

### PR DESCRIPTION
**Pull request by xtkoba**
Closes #14616.

### CODE REVIEW

File: packages/libllvm/llvmgold.subpackage.sh [hunk 1]
```diff
@@ -0,0 +1,4 @@
+TERMUX_SUBPKG_INCLUDE="
+lib/LLVMgold.so
+"
+TERMUX_SUBPKG_DESCRIPTION="LLVM gold plugin"
```
Comment (buttaface) [inline packages/libllvm/llvmgold.subpackage.sh:4]: Does this depend on clang or can gcc use it too? Add gold and whatever other dependencies are needed.

Comment (xtkoba) [reply packages/libllvm/llvmgold.subpackage.sh:4]: Depends on `libllvm` (the parent package) and `libc++` (which is also a dependency of `libllvm`.) `llvmgold` itself does not hard-depend on other packages such as `binutils-gold`.

Comment (xtkoba) [reply packages/libllvm/llvmgold.subpackage.sh:4]: Then rather I suppose `bunutils-gold` should depend on (or recommend) `llvmgold`.

Comment (buttaface) [reply packages/libllvm/llvmgold.subpackage.sh:4]: Yeah, recommending this sounds right, plus I think this should depend on the gold package, since it won't work without it. It's similar to how `gst-plugins-base` depends on `gstreamer`.

Comment (xtkoba) [reply packages/libllvm/llvmgold.subpackage.sh:4]: But it should be noted that `gst-plugins-base` actually hard-depends on `gstreamer`, links against some shared libs in it. Not much similar.
