### PR TITLE
addpkg(x11/okular): 25.12.0

### LINKED ISSUE #25898: [Package]: Okular
### Why is it worth to add this package?

Okular is a universal document viewer developed by KDE. Okular works on multiple platforms, including but not limited to Linux, Windows, Mac OS X, *BSD, etc.

Maybe it can add into termux-packages in the future.
I'm too lazy to compile and test it.

### Home page URL

https://apps.kde.org/okular/

### Source code URL

https://invent.kde.org/graphics/okular

### Packaging policy acknowledgement

- [x] The project is actively developed.
- [x] The project has [existing packages](https://repology.org/projects/) and is "well known".
- [x] Licensed under an [open source license](https://spdx.org/licenses/).
- [x] Not available through a language package manager: cargo, cpan, dotnet tool, gem, npm, pip, etc.

- [x] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [x] Not duplicating the functionality of existing packages.
- [x] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [x] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by BullyMaguire-lol**
This PR adds Okular 25.12.0.

Okular is a document viewer that supports PDF, EPUB, images, and other document formats.

New dependencies required by Okular:
- phonon-qt6 4.12.0
- phonon-qt6-vlc 0.12.0
- discount 3.0.1.2
- kf6-threadweaver 6.21.0

* Fixes #25898

### CODE REVIEW

**Comment by robertkirkman** [comment]
Yeah just add the `discount` i sent you and this is probably ready after that

File: x11-packages/phonon-qt6-vlc/build.sh [hunk 1]
```diff
@@ -0,0 +1,17 @@
+TERMUX_PKG_HOMEPAGE="https://invent.kde.org/libraries/phonon-vlc"
+TERMUX_PKG_DESCRIPTION="Phonon VLC backend"
+TERMUX_PKG_LICENSE="LGPL-2.1-or-later"
+TERMUX_PKG_MAINTAINER="@termux"
+TERMUX_PKG_VERSION="0.12.0"
+TERMUX_PKG_SRCURL="https://download.kde.org/stable/phonon/phonon-backend-vlc/${TERMUX_PKG_VERSION}/phonon-backend-vlc-${TERMUX_PKG_VERSION}.tar.xz"
+TERMUX_PKG_SHA256="338479dc451e4b94b3ca5b578def741dcf82f5c626a2807d36235be2dce7c9a5"
+TERMUX_PKG_AUTO_UPDATE=true
+TERMUX_PKG_DEPENDS="libc++, phonon-qt6, pulseaudio, qt6-qtbase, vlc"
```
Comment (robertkirkman) [inline x11-packages/phonon-qt6-vlc/build.sh]: Probably this should depend on `vlc-qt` instead of `vlc`

File: x11-packages/okular/build.sh [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+TERMUX_PKG_VERSION="25.12.0"
+TERMUX_PKG_SRCURL="https://download.kde.org/stable/release-service/${TERMUX_PKG_VERSION}/src/okular-${TERMUX_PKG_VERSION}.tar.xz"
+TERMUX_PKG_SHA256="cf05a515bba78ee5e7fb5aa09e67ac42fe796f3f645a4353c6b6e555e61c8490"
+TERMUX_PKG_AUTO_UPDATE=true
+TERMUX_PKG_DEPENDS="djvulibre, freetype, kf6-karchive, kf6-kbookmarks, kf6-kcolorscheme, kf6-kcompletion, kf6-kconfig, kf6-kconfigwidgets, kf6-kcoreaddons, kf6-kcrash, kf6-ki18n, kf6-kiconthemes, kf6-kio, kf6-kparts, kf6-ktextwidgets, kf6-kwallet, kf6-kwidgetsaddons, kf6-kwindowsystem, kf6-kxmlgui, kf6-purpose, kf6-threadweaver, libc++, libkexiv2, libspectre, libtiff, phonon-qt6, poppler-qt, qt6-qtbase, qt6-qtdeclarative, qt6-qtspeech, qt6-qtsvg, unrar, zlib"
+TERMUX_PKG_BUILD_DEPENDS="ebook-tools, extra-cmake-modules, kdegraphics-mobipocket"
+TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
+-DCMAKE_SYSTEM_NAME=Linux
+-DKDE_INSTALL_QTPLUGINDIR=lib/qt6/plugins
+-DFORCE_NOT_REQUIRED_DEPENDENCIES=KF6DocTools;Discount
```
Comment (robertkirkman) [inline x11-packages/okular/build.sh]: and remove the `Discount` here when  you add `discount` so that it can become linked to `libmarkdown.so`
