### PR TITLE
fix(main/golang): Workaround crash due to pidfd_open syscall

### LINKED ISSUE #21265: [Bug]: golang 3:1.23.0 is broken on some devices (SIGSYS: bad system call)
### Problem description

Today I tried to build [tailscale](https://github.com/tailscale/tailscale) from source using the latest go version in the termux repo. While downloading the first depency, `go install` crashed with a similar error to this simplified test case:

<details><summary>`go' command crash</summary>

```
~ $ go tool link --help
SIGSYS: bad system call
PC=0x61800a1700 m=0 sigcode=1

goroutine 1 gp=0x40000021c0 m=0 mp=0x6180c77b20 [syscall]:
syscall.Syscall(0x1b2, 0x459f, 0x0, 0x0)
	syscall/syscall_linux.go:73 +0x20 fp=0x40001473d0 sp=0x4000147370 pc=0x61800ba2b0
internal/syscall/unix.PidFDOpen(0xac?, 0x0?)
	internal/syscall/unix/pidfd_linux.go:18 +0x2c fp=0x4000147400 sp=0x40001473d0 pc=0x618010f93c
os.checkPidfd()
	os/pidfd_linux.go:139 +0x48 fp=0x40001474b0 sp=0x4000147400 pc=0x6180121c38
os.init.OnceValue[...].func2()
	sync/oncefunc.go:57 +0x74 fp=0x4000147510 sp=0x40001474b0 pc=0x618011a054
sync.(*Once).doSlow(0x378?, 0x35?)
	sync/once.go:76 +0xf8 fp=0x4000147570 sp=0x4000147510 pc=0x61800a9bf8
sync.(*Once).Do(0x5?, 0x0?)
	sync/once.go:67 +0x24 fp=0x4000147590 sp=0x4000147570 pc=0x61800a9ad4
os.init.OnceValue[...].func3()
	sync/oncefunc.go:62 +0x3c fp=0x40001475d0 sp=0x4000147590 pc=0x6180119f9c
os.pidfdWorks(...)
	os/pidfd_linux.go:124
os.ensurePidfd(0x0)
	os/pidfd_linux.go:23 +0x2c fp=0x4000147610 sp=0x40001475d0 pc=0x618012141c
os.startProcess({0x40001500a0, 0x42}, {0x40000c20e0, 0x2, 0x2}, 0x4000147830)
	os/exec_posix.go:41 +0xb8 fp=0x4000147700 sp=0x4000147610 pc=0x618011c2f8
os.StartProcess({0x40001500a0, 0x42}, {0x40000c20e0, 0x2, 0x2}, 0x4000147830)
	os/exec.go:319 +0x50 fp=0x4000147740 sp=0x4000147700 pc=0x618011bfa0
os/exec.(*Cmd).Start(0x4000108180)
	os/exec/exec.go:709 +0x4ac fp=0x40001478d0 sp=0x4000147740 pc=0x61801566dc
cmd/go/internal/tool.runTool({0x61808da2f0?, 0x6180c9e300?}, 0x40000ee300?, {0x40000c20e0, 0x2, 0x2})
	cmd/go/internal/tool/tool.go:118 +0x50c fp=0x40001479b0 sp=0x40001478d0 pc=0x618055655c
main.invoke(0x6180c69380, {0x40000c20d0, 0x3, 0x3})
	cmd/go/main.go:299 +0x674 fp=0x4000147cc0 sp=0x40001479b0 pc=0x6180569254
main.main()
	cmd/go/main.go:213 +0xdb4 fp=0x4000147f40 sp=0x4000147cc0 pc=0x6180568884
runtime.main()
	runtime/proc.go:272 +0x288 fp=0x4000147fd0 sp=0x4000147f40 pc=0x618005d558
runtime.goexit({})
	runtime/asm_arm64.s:1223 +0x4 fp=0x4000147fd0 sp=0x4000147fd0 pc=0x618009ce24

goroutine 2 gp=0x4000002700 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:424 +0xc8 fp=0x400004ef90 sp=0x400004ef70 pc=0x6180094c08
runtime.goparkunlock(...)
	runtime/proc.go:430
runtime.forcegchelper()
	runtime/proc.go:337 +0xb8 fp=0x400004efd0 sp=0x400004ef90 pc=0x618005d8b8
runtime.goexit({})
	runtime/asm_arm64.s:1223 +0x4 fp=0x400004efd0 sp=0x400004efd0 pc=0x618009ce24
created by runtime.init.7 in goroutine 1
	runtime/proc.go:325 +0x24

goroutine 3 gp=0x4000002c40 m=nil [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:424 +0xc8 fp=0x400004f760 sp=0x400004f740 pc=0x6180094c08
runtime.goparkunlock(...)
	runtime/proc.go:430
runtime.bgsweep(0x4000070000)
	runtime/mgcsweep.go:277 +0xa0 fp=0x400004f7b0 sp=0x400004f760 pc=0x6180048050
runtime.gcenable.gowrap1()
	runtime/mgc.go:203 +0x28 fp=0x400004f7d0 sp=0x400004f7b0 pc=0x618003c018
runtime.goexit({})
	runtime/asm_arm64.s:1223 +0x4 fp=0x400004f7d0 sp=0x400004f7d0 pc=0x618009ce24
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:203 +0x6c

goroutine 4 gp=0x4000002e00 m=nil [GC scavenge wait]:
runtime.gopark(0x4000070000?, 0x618068bc68?, 0x1?, 0x0?, 0x4000002e00?)
	runtime/proc.go:424 +0xc8 fp=0x400004ff60 sp=0x400004ff40 pc=0x6180094c08
runtime.goparkunlock(...)
	runtime/proc.go:430
runtime.(*scavengerState).park(0x6180c75ce0)
	runtime/mgcscavenge.go:425 +0x5c fp=0x400004ff90 sp=0x400004ff60 pc=0x6180045a7c
runtime.bgscavenge(0x4000070000)
	runtime/mgcscavenge.go:653 +0x44 fp=0x400004ffb0 sp=0x400004ff90 pc=0x6180045fa4
runtime.gcenable.gowrap2()
	runtime/mgc.go:204 +0x28 fp=0x400004ffd0 sp=0x400004ffb0 pc=0x618003bfb8
runtime.goexit({})
	runtime/asm_arm64.s:1223 +0x4 fp=0x400004ffd0 sp=0x400004ffd0 pc=0x618009ce24
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:204 +0xac

goroutine 17 gp=0x4000084380 m=nil [finalizer wait]:
runtime.gopark(0x400004e5b8?, 0x6180037bb4?, 0x0?, 0x20?, 0x33?)
	runtime/proc.go:424 +0xc8 fp=0x400004e580 sp=0x400004e560 pc=0x6180094c08
runtime.runfinq()
	runtime/mfinal.go:193 +0x108 fp=0x400004e7d0 sp=0x400004e580 pc=0x618003b118
runtime.goexit({})
	runtime/asm_arm64.s:1223 +0x4 fp=0x400004e7d0 sp=0x400004e7d0 pc=0x618009ce24
created by runtime.createfing in goroutine 1
	runtime/mfinal.go:163 +0x80

goroutine 18 gp=0x4000084540 m=nil [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:424 +0xc8 fp=0x400004a6f0 sp=0x400004a6d0 pc=0x6180094c08
runtime.chanrecv(0x4000098150, 0x0, 0x1)
	runtime/chan.go:639 +0x414 fp=0x400004a770 sp=0x400004a6f0 pc=0x618002b664
runtime.chanrecv1(0x0?, 0x0?)
	runtime/chan.go:489 +0x14 fp=0x400004a7a0 sp=0x400004a770 pc=0x618002b214
runtime.unique_runtime_registerUniqueMapCleanup.func1(...)
	runtime/mgc.go:1732
runtime.unique_runtime_registerUniqueMapCleanup.gowrap1()
	runtime/mgc.go:1735 +0x3c fp=0x400004a7d0 sp=0x400004a7a0 pc=0x618003f0fc
runtime.goexit({})
	runtime/asm_arm64.s:1223 +0x4 fp=0x400004a7d0 sp=0x400004a7d0 pc=0x618009ce24
created by unique.runtime_registerUniqueMapCleanup in goroutine 1
	runtime/mgc.go:1730 +0xa0

r0      0x459f
r1      0x0
r2      0x0
r3      0x0
r4      0x0
r5      0x0
r6      0x0
r7      0x2
r8      0x1b2
r9      0x2
r10     0x0
r11     0x0
r12     0x40001521b8
r13     0x1f
r14     0x4000026060
r15     0x1f
r16     0x40001463a0
r17     0x4000147480
r18     0x7408130000
r19     0x8d6dd8b5d3e2f3f4
r20     0x4000147530
r21     0x4000147b80
r22     0x4000004000
r23     0x3cb9d69707
r24     0x8e41dc0be9fcd734
r25     0x0
r26     0x61808cf578
r27     0x1
r28     0x40000021c0
r29     0x4000147308
lr      0x61800ba26c
sp      0x4000147310
pc      0x61800a1700
fault   0x0
```

</details>

It seems this always happens when pipes or network sockets are involved.
I did not have this issue 5 weeks ago when I built tailscale using <code>go1.22.5</code>.

On my second android device (Android 12 instead of 10), go is working fine:

<details><summary>Expected output</summary>

```
~ $ go tool link --help
usage: link [options] main.o
  -B note
    	add an ELF NT_GNU_BUILD_ID note when using ELF; use "gobuildid" to generate it from the Go build ID
  -E entry
    	set entry symbol name
  -H type
    	set header type
  -I linker
    	use linker as ELF dynamic linker
  -L directory
    	add specified directory to library path
  -R quantum
    	set address rounding quantum (default -1)
  -T int
    	set the start address of text symbols (default -1)
  -V	print version and exit
  -X definition
    	add string value definition of the form importpath.name=value
  -a	no-op (deprecated)
  -asan
    	enable ASan interface
  -aslr
    	enable ASLR for buildmode=c-shared on windows (default true)
  -benchmark string
    	set to 'mem' or 'cpu' to enable phase benchmarking
  -benchmarkprofile base
    	emit phase profiles to base_phase.{cpu,mem}prof
  -bindnow
    	mark a dynamically linked ELF object for immediate function binding
  -buildid id
    	record id as Go toolchain build id
  -buildmode mode
    	set build mode
  -c	dump call graph
  -capturehostobjs string
    	capture host object files loaded during internal linking to specified dir
  -checklinkname
    	check linkname symbol references (default true)
  -compressdwarf
    	compress DWARF if possible (default true)
  -cpuprofile file
    	write cpu profile to file
  -d	disable dynamic executable
  -debugnosplit
    	dump nosplit call graph
  -debugtextsize int
    	debug text section max size
  -debugtramp int
    	debug trampolines
  -dumpdep
    	dump symbol dependency graph
  -extar string
    	archive program for buildmode=c-archive
  -extld linker
    	use linker when linking in external mode
  -extldflags flags
    	pass flags to external linker
  -f	ignore version mismatch
  -g	disable go package data checks
  -h	halt on error
  -importcfg file
    	read import configuration from file
  -installsuffix suffix
    	set package directory suffix
  -k symbol
    	set field tracking symbol
  -libgcc string
    	compiler support lib for internal linking; use "none" to disable
  -linkmode mode
    	set link mode
  -linkshared
    	link against installed Go shared libraries
  -memprofile file
    	write memory profile to file
  -memprofilerate rate
    	set runtime.MemProfileRate to rate
  -msan
    	enable MSan interface
  -n	no-op (deprecated)
  -o file
    	write output to file
  -pluginpath string
    	full path name for plugin
  -pruneweakmap
    	prune weak mapinit refs (default true)
  -r path
    	set the ELF dynamic linker search path to dir1:dir2:...
  -race
    	enable race detector
  -randlayout int
    	randomize function layout
  -s	disable symbol table
  -strictdups int
    	sanity check duplicate symbol contents during object file reading (1=warn 2=err).
  -tmpdir directory
    	use directory for temporary files
  -v	print link trace
  -w	disable DWARF generation
```

</details>

On this device, I can successfully build a working version of tailscale. However, if I copy the newly built executable back to the first device, it too crashes with a <code>SIGSYS: bad system call</code> error:

<details><summary>Crash of an executable built using this go version (tailscaled)</summary>

```
2024/08/26 12:07:23 logtail started
2024/08/26 12:07:23 Program starting: v1.73.0-dev20240825-tb78df4d48, Go 1.23.0: []string{"go/bin/tailscaled", "--tun=userspace-networking", "--socks5-server=localhost:1055", "--statedir", "/data/data/com.termux/files/home/.config/tailscale/", "-socket", "/data/data/com.termux/files/usr/run/tailscaled.sock"}
2024/08/26 12:07:23 LogID: d6d3c1a1e07ede6eb7fe5f473d7f25e67d3f0ca9975e5ddd858e9748139229b7
2024/08/26 12:07:23 logpolicy: using UserCacheDir, "/data/data/com.termux/files/home/.cache/Tailscale"
2024/08/26 12:07:23 dns: [rc=missing ret=direct]
2024/08/26 12:07:23 dns: using "direct" mode
2024/08/26 12:07:23 dns: using *dns.directManager
2024/08/26 12:07:23 dns: inotify addwatch: context canceled
2024/08/26 12:07:23 wgengine.NewUserspaceEngine(tun "userspace-networking") ...
2024/08/26 12:07:23 dns: using dns.noopManager
2024/08/26 12:07:23 link state: interfaces.State{defaultRoute= ifs={rmnet_r_ims00:[2a02:303e:2816:a5a1:3ed6:21a7:9a5b:72c0/64 llu6] rmnet_tun00:[2a02:303e:2816:a5a1:3ed6:21a7:9a5b:72cd/64 llu6] tun0:[26.26.26.1/24 fdfe:dcba:9876::1/126 llu6] wlan0:[192.168.5.82/24 llu6]} v4=true v6=true}
2024/08/26 12:07:23 onPortUpdate(port=36901, network=udp6)
2024/08/26 12:07:23 magicsock: [warning] failed to force-set UDP read buffer size to 7340032: operation not permitted; using kernel default values (impacts throughput only)
2024/08/26 12:07:23 magicsock: [warning] failed to force-set UDP write buffer size to 7340032: operation not permitted; using kernel default values (impacts throughput only)
2024/08/26 12:07:23 onPortUpdate(port=54995, network=udp4)
2024/08/26 12:07:23 magicsock: [warning] failed to force-set UDP read buffer size to 7340032: operation not permitted; using kernel default values (impacts throughput only)
2024/08/26 12:07:23 magicsock: [warning] failed to force-set UDP write buffer size to 7340032: operation not permitted; using kernel default values (impacts throughput only)
2024/08/26 12:07:23 magicsock: disco key = d:298e07999a12f143
2024/08/26 12:07:23 Creating WireGuard device...
2024/08/26 12:07:23 Bringing WireGuard device up...
2024/08/26 12:07:23 Bringing router up...
2024/08/26 12:07:23 Clearing router settings...
2024/08/26 12:07:23 Starting network monitor...
2024/08/26 12:07:23 Engine created.
2024/08/26 12:07:23 pm: using backend prefs for "profile-a764": Prefs{ra=false dns=true want=true host="termux" update=check Persist{lm=, o=[L+FQk], n=[0x7ut] u="redacted@live.com"}}
2024/08/26 12:07:23 logpolicy: using UserCacheDir, "/data/data/com.termux/files/home/.cache/Tailscale"
2024/08/26 12:07:23 got LocalBackend in 7ms
2024/08/26 12:07:23 Start
2024/08/26 12:07:23 portlist warning; ignoring: open /proc/net/tcp: permission denied
2024/08/26 12:07:23 portlist warning; ignoring: open /proc/net/tcp6: permission denied
2024/08/26 12:07:23 portlist warning; ignoring: open /proc/net/udp: permission denied
2024/08/26 12:07:23 portlist warning; ignoring: open /proc/net/udp6: permission denied
2024/08/26 12:07:24 timeout waiting for initial portlist
2024/08/26 12:07:24 Backend: logs: be:d6d3c1a1e07ede6eb7fe5f473d7f25e67d3f0ca9975e5ddd858e9748139229b7 fe:
2024/08/26 12:07:24 control: client.Login(0)
2024/08/26 12:07:24 control: doLogin(regen=false, hasUrl=false)
2024/08/26 12:07:24 health(warnable=is-using-unstable-version): error: This is an unstable version of Tailscale meant for testing and development purposes. Please report any issues to Tailscale.
2024/08/26 12:07:24 health(warnable=warming-up): error: Tailscale is starting. Please wait.
2024/08/26 12:07:24 control: control server key from https://controlplane.tailscale.com: ts2021=[fSeS+], legacy=[nlFWp]
2024/08/26 12:07:24 control: RegisterReq: onode=[L+FQk] node=[0x7ut] fup=false nks=false
2024/08/26 12:07:24 control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
2024/08/26 12:07:24 health(warnable=not-in-map-poll): ok
2024/08/26 12:07:24 control: netmap: got new dial plan from control
2024/08/26 12:07:24 active login: redacted@live.com
2024/08/26 12:07:24 Switching ipn state NoState -> Starting (WantRunning=true, nm=true)
SIGSYS: bad system call
PC=0x63d71b6a90 m=7 sigcode=1

goroutine 153 gp=0x400071b500 m=7 mp=0x4000081c08 [syscall]:
syscall.Syscall(0x1b2, 0x3b2c, 0x0, 0x0)
	/data/data/com.termux/files/usr/lib/go/src/syscall/syscall_linux.go:73 +0x20 fp=0x40003b92e0 sp=0x40003b9280 pc=0x63d71cd8f0
internal/syscall/unix.PidFDOpen(0xac?, 0x0?)
	/data/data/com.termux/files/usr/lib/go/src/internal/syscall/unix/pidfd_linux.go:18 +0x2c fp=0x40003b9310 sp=0x40003b92e0 pc=0x63d72395ec
os.checkPidfd()
	/data/data/com.termux/files/usr/lib/go/src/os/pidfd_linux.go:139 +0x48 fp=0x40003b93c0 sp=0x40003b9310 pc=0x63d72484e8
os.init.OnceValue[...].func2()
	/data/data/com.termux/files/usr/lib/go/src/sync/oncefunc.go:57 +0x74 fp=0x40003b9420 sp=0x40003b93c0 pc=0x63d7240f94
sync.(*Once).doSlow(0x1c0?, 0x1a?)
	/data/data/com.termux/files/usr/lib/go/src/sync/once.go:76 +0xf8 fp=0x40003b9480 sp=0x40003b9420 pc=0x63d71bdac8
sync.(*Once).Do(0x5?, 0x0?)
	/data/data/com.termux/files/usr/lib/go/src/sync/once.go:67 +0x24 fp=0x40003b94a0 sp=0x40003b9480 pc=0x63d71bd9a4
os.init.OnceValue[...].func3()
	/data/data/com.termux/files/usr/lib/go/src/sync/oncefunc.go:62 +0x3c fp=0x40003b94e0 sp=0x40003b94a0 pc=0x63d7240edc
os.pidfdWorks(...)
	/data/data/com.termux/files/usr/lib/go/src/os/pidfd_linux.go:124
os.ensurePidfd(0x0)
	/data/data/com.termux/files/usr/lib/go/src/os/pidfd_linux.go:23 +0x2c fp=0x40003b9520 sp=0x40003b94e0 pc=0x63d7247ccc
os.startProcess({0x63d6f86e89, 0xe}, {0x4000328000, 0x5, 0x5}, 0x40003b9740)
	/data/data/com.termux/files/usr/lib/go/src/os/exec_posix.go:41 +0xb8 fp=0x40003b9610 sp=0x40003b9520 pc=0x63d7242ac8
os.StartProcess({0x63d6f86e89, 0xe}, {0x4000328000, 0x5, 0x5}, 0x40003b9740)
	/data/data/com.termux/files/usr/lib/go/src/os/exec.go:319 +0x50 fp=0x40003b9650 sp=0x40003b9610 pc=0x63d7242930
os/exec.(*Cmd).Start(0x400001e180)
	/data/data/com.termux/files/usr/lib/go/src/os/exec/exec.go:709 +0x4ac fp=0x40003b97e0 sp=0x40003b9650 pc=0x63d746024c
tailscale.com/net/netmon.likelyHomeRouterIPHelper()
	/data/data/com.termux/files/home/tailscale/net/netmon/interfaces_android.go:142 +0xb8 fp=0x40003b98e0 sp=0x40003b97e0 pc=0x63d74f2dd8
tailscale.com/net/netmon.likelyHomeRouterIPAndroid()
	/data/data/com.termux/files/home/tailscale/net/netmon/interfaces_android.go:53 +0x1e0 fp=0x40003b99a0 sp=0x40003b98e0 pc=0x63d74f2910
tailscale.com/net/netmon.likelyHomeRouterIPAndroid()
	/data/data/com.termux/files/home/tailscale/net/netmon/interfaces_android.go:94 +0x1ac fp=0x40003b9a60 sp=0x40003b99a0 pc=0x63d74f28dc
tailscale.com/net/netmon.LikelyHomeRouterIP()
	/data/data/com.termux/files/home/tailscale/net/netmon/state.go:564 +0x40 fp=0x40003b9ad0 sp=0x40003b9a60 pc=0x63d74f93c0
tailscale.com/net/netmon.(*Monitor).GatewayAndSelfIP(0x40001ec1c0)
	/data/data/com.termux/files/home/tailscale/net/netmon/netmon.go:191 +0xd8 fp=0x40003b9b70 sp=0x40003b9ad0 pc=0x63d74f38c8
tailscale.com/net/netmon.(*Monitor).GatewayAndSelfIP-fm()
	<autogenerated>:1 +0x28 fp=0x40003b9b90 sp=0x40003b9b70 pc=0x63d791b288
tailscale.com/net/portmapper.(*Client).gatewayAndSelfIP(0x40000b4140)
	/data/data/com.termux/files/home/tailscale/net/portmapper/portmapper.go:277 +0x44 fp=0x40003b9c10 sp=0x40003b9b90 pc=0x63d77f8884
tailscale.com/net/portmapper.(*Client).createOrGetMapping(0x40000b4140, {0x63d7d5c970, 0x40005180e0})
	/data/data/com.termux/files/home/tailscale/net/portmapper/portmapper.go:492 +0xe0 fp=0x40003b9f40 sp=0x40003b9c10 pc=0x63d77f9f00
tailscale.com/net/portmapper.(*Client).createMapping(0x40000b4140)
	/data/data/com.termux/files/home/tailscale/net/portmapper/portmapper.go:470 +0x88 fp=0x40003b9fb0 sp=0x40003b9f40 pc=0x63d77f9b88
tailscale.com/net/portmapper.(*Client).maybeStartMappingLocked.gowrap1()
	/data/data/com.termux/files/home/tailscale/net/portmapper/portmapper.go:456 +0x28 fp=0x40003b9fd0 sp=0x40003b9fb0 pc=0x63d77f9ac8
runtime.goexit({})
	/data/data/com.termux/files/usr/lib/go/src/runtime/asm_arm64.s:1223 +0x4 fp=0x40003b9fd0 sp=0x40003b9fd0 pc=0x63d71b2a44
created by tailscale.com/net/portmapper.(*Client).maybeStartMappingLocked in goroutine 152
	/data/data/com.termux/files/home/tailscale/net/portmapper/portmapper.go:456 +0x6c

[...]

r0      0x3b2c
r1      0x0
r2      0x0
r3      0x0
r4      0x0
r5      0x0
r6      0x0
r7      0x5
r8      0x1b2
r9      0x5
r10     0x0
r11     0x0
r12     0x40005ca2a0
r13     0x19
r14     0x4000042020
r15     0x2
r16     0x40003b83a0
r17     0x40003b9390
r18     0x78596f6000
r19     0x381f63fda3129f18
r20     0x40003b9440
r21     0x7859c01a98
r22     0x1
r23     0x563f0a6ad3
r24     0x97dd899214c069d2
r25     0xbf46638f73
r26     0x63d7d447e8
r27     0x0
r28     0x400071b500
r29     0x40003b9218
lr      0x63d71cd8ac
sp      0x40003b9220
pc      0x63d71b6a90
fault   0x0
```

</details>

The tailscale version built using the previous go version is working fine to this day on both devices.

As far as I can tell, the only difference in Termux setup between the two devices is the first being a debug version, while the second device is running an fdroid release.
I tried reinstalling + downgrading Termux to the latest stable release, to no effect.

### What steps will reproduce the bug?

* `pkg install golang`
* `go tool link --help`

This immediately results in a crash on the Android 10 device.

### What is the expected behavior?

Go prints out the usage for `go tool link` and does not crash.

### System information

```shell
Bad Syscall Error occurs on this Android 10 device (Huawei Mate 20 Pro):
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=7557
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://ftp.fau.de/termux/termux-main stable main
# sources.list.d/rendiix.list
deb https://rendiix.github.io android-tools termux
# x11-repo (sources.list.d/x11.list)
deb https://ftp.fau.de/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.43.4
Android version:
10
Kernel build information:
Linux localhost 4.14.116 #1 SMP PREEMPT Tue Nov 21 16:26:23 CST 2023 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
LYA-L29
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51


Everything works fine on this Android 12 device (Samsung Galaxy A21s):
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=5039
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.autkin.net/termux/termux-main stable main
# sources.list.d/rendiix.list
deb https://rendiix.github.io android-tools termux
Updatable packages:
All packages up to date
termux-tools version:
1.43.3
Android version:
12
Kernel build information:
Linux localhost 4.19.132-24202344 #1 SMP PREEMPT Tue May 14 14:47:01 +07 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A217F
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
```

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes #21265

### CODE REVIEW

File: packages/golang/src-os-pidfd_linux.go.patch [hunk 1]
```diff
@@ -0,0 +1,11 @@
+--- a/src/os/pidfd_linux.go
++++ b/src/os/pidfd_linux.go
+@@ -121,7 +121,7 @@
+ }
+ 
+ func pidfdWorks() bool {
+-	return checkPidfdOnce() == nil
```
Comment (licy183) [inline packages/golang/src-os-pidfd_linux.go.patch:7]: This patch only affect the binary compiled with golang in Termux, and will not work if the golang binary is cross-compiled.

This should use the same way as `/etc/resolv.conf`, see https://github.com/termux/termux-packages/blob/master/packages/golang/fix-hardcoded-etc-resolv-conf.sh

Comment (Biswa96) [reply packages/golang/src-os-pidfd_linux.go.patch:7]: Thank you for the review. Sadly, I'm not familiar with golang. Please feel free to create a separate pull request with my patch.
