### PR TITLE
racket: avoid `AI_V4MAPPED` on Android

### LINKED ISSUE #22202: [Bug]: racket fails to make tcp connections
### Problem description

Version 8.15 of racket has a bug on Android. It was failing to make tcp connections. I'm not asking y'all to solve this, just to try out a patch, see if it solves the bug and do an update for the racket package if so.

This post has details on the bug and how to reproduce it https://racket.discourse.group/t/tcp-connect-failing-since-upgrade-to-8-15-on-termux/3298/6

Here's the patch: https://github.com/racket/racket/commit/78fbcab276ffdfd8525a00e320dff81ffcbae4ce

### What steps will reproduce the bug?

See link above 

### What is the expected behavior?

To successfully make a tcp connection 

### System information

```shell
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=2271
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.fcix.net/termux/termux-main stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/21 termux extras
# x11-repo (sources.list.d/x11.list)
deb https://mirror.fcix.net/termux/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://mirror.fcix.net/termux/termux-root root stable
Updatable packages:
libexpat/stable 2.6.4 aarch64 [upgradable from: 2.6.3]
unrar/stable 7.1.1 aarch64 [upgradable from: 7.0.9]
termux-tools version:
1.44.3
Android version:
10
Kernel build information:
Linux localhost 4.9.206-perf+ #1 SMP PREEMPT Tue Feb 2 00:54:33 CST 2021 aarch64 Android
Device manufacturer:
motorola
Device model:
moto g(7) power
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.styling versionCode:1000
com.termux.widget versionCode:13
```

### PR DESCRIPTION
**Pull request by licy183**
Closes #22202

### CODE REVIEW

File: packages/racket/rktio_network.c.patch [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+diff --git a/racket/src/rktio/rktio_network.c b/racket/src/rktio/rktio_network.c
+index 2a1d6731fa3..c73fc32977f 100644
+--- a/src/rktio/rktio_network.c
++++ b/src/rktio/rktio_network.c
+@@ -727,10 +727,10 @@ rktio_addrinfo_lookup_t *rktio_start_addrinfo_lookup(rktio_t *rktio,
+   /* On modern systems, `AI_ADDRCONFIG` and `AI_V4MAPPED` tend to be
+      the defaults when `hints` is NULL, so add them if they seem
+      available. */
+-#ifdef AI_ADDRCONFIG
++#if defined(AI_ADDRCONFIG)
```
Comment (TomJo2000) [inline packages/racket/rktio_network.c.patch:21]: Isn't `#ifdef` equivalent to `#if defined()`,
why do we patch this here as well if this is not checking for Android?

**Review by TomJo2000 — APPROVED** [review]

File: packages/racket/rktio_network.c.patch (hunk 1 above)
Comment (licy183) [reply packages/racket/rktio_network.c.patch:21]: This is an upstream patch. Maybe it makes them happy...

Comment (TomJo2000) [reply packages/racket/rktio_network.c.patch:21]: Oh I didn't realize it came from upstream.
Best to just use it as is in that case.
