### PR TITLE
fix(main/emscripten): i686 build

### LINKED ISSUE #12221: [Bug]: emscripten build failed [i686]
### Problem description

[emscripten.txt](https://github.com/termux/termux-packages/files/9685202/emscripten.txt)

/llvm/ADT/PointerUnion.h:19:
/home/builder/.termux-build/emscripten/cache/llvm-project-8b587113b746f31b63fd6473083df78cef30a72e/llvm/include/llvm/ADT/PointerIntPair.h:60:47: error: no member named 'getPointer' in 'llvm::PointerIntPairInfo<clang::Module *, 3, llvm::PointerLikeTypeTraits<clang::Module *>>'
  PointerTy getPointer() const { return Info::getPointer(Value); }
                                              ^
/home/builder/.termux-build/emscripten/cache/llvm-project-8b587113b746f31b63fd6473083df78cef30a72e/clang/include/clang/Lex/ModuleMap.h:172:48: note: in instantiation of member function 'llvm::PointerIntPair<clang::Module *, 3, clang::ModuleMap::ModuleHeaderRole>::getPointer' requested here
    Module *getModule() const { return Storage.getPointer(); }
                                               ^
In file included from /home/builder/.termux-build/emscripten/cache/llvm-project-8b587113b746f31b63fd6473083df78cef30a72e/clang/lib/Lex/PPDirectives.cpp:15:
In file included from /home/builder/.termux-build/emscripten/cache/llvm-project-8b587113b746f31b63fd6473083df78cef30a72e/clang/include/clang/Basic/FileManager.h:18:
In file included from /home/builder/.termux-build/emscripten/cache/llvm-project-8b587113b746f31b63fd6473083df78cef30a72e/clang/include/clang/Basic/FileEntry.h:21:
In file included from /home/builder/.termux-build/emscripten/cache/llvm-project-8b587113b746f31b63fd6473083df78cef30a72e/llvm/include/llvm/ADT/PointerUnion.h:19:
/home/builder/.termux-build/emscripten/cache/llvm-project-8b587113b746f31b63fd6473083df78cef30a72e/llvm/include/llvm/ADT/PointerIntPair.h:62:50: error: no member named 'getInt' in 'llvm::PointerIntPairInfo<clang::Module *, 3, llvm::PointerLikeTypeTraits<clang::Module *>>'
  IntType getInt() const { return (IntType)Info::getInt(Value); }
                                                 ^
/home/builder/.termux-build/emscripten/cache/llvm-project-8b587113b746f31b63fd6473083df78cef30a72e/clang/include/clang/Lex/ModuleMap.h:175:55: note: in instantiation of member function 'llvm::PointerIntPair<clang::Module *, 3, clang::ModuleMap::ModuleHeaderRole>::getInt' requested here
    ModuleHeaderRole getRole() const { return Storage.getInt(); }
                                                      ^
1 warning and 4 errors generated.

### What steps will reproduce the bug?

build

### What is the expected behavior?

_No response_

### System information

termux-info:

```

```

### PR DESCRIPTION
**Pull request by truboxl**
Closes #12221

It seems like latest tip of tree has fixed the build issue so use that
Tip of tree is what usually emscripten uses for their emsdk "build from source" releases

The build was first broken in commit llvm/llvm-project@f35230ae0a69bbdd74a4faa3ae0b69a46796dc12
The last known working is commit llvm/llvm-project@46525fee812343b5e603a77893dfe2983768ca56
I have yet to determine which commit fix the build, ideally should use that instead

### CODE REVIEW

File: packages/emscripten/build.sh [hunk 1]
```diff
@@ -147,6 +148,7 @@ termux_pkg_auto_update() {
 }
 
 termux_step_post_get_source() {
+	#curl -LC - "https://github.com/llvm/llvm-project/archive/$_LLVM_COMMIT.tar.gz" -o "$TERMUX_PKG_CACHEDIR/llvm.tar.gz"
```
Comment (Grimler91) [inline packages/emscripten/build.sh:151]: Forgotten debugging line here?

Comment (truboxl) [reply packages/emscripten/build.sh:151]: 😅
