### PR TITLE
build-packages.sh: improvement and bug fixes

### LINKED ISSUE #8523: [Bug]: build-package.sh (when re-compiling a specific package) and clean.sh does not work on termux
### Problem description

Hi all.  
I noticed one strange thing about the compiler.  When a package is compiled and when you repeat the compilation of the same package, the compiler does not start and `clean.sh` stops working with it (if you run the compiler for another package, it works).  
**For example curl:**  
Screenshot_20220110-223849_Termux

I've debugged scripts and noticed one common line that might be the cause:

- [build-packages.sh](https://github.com/termux/termux-packages/blob/master/scripts/build/termux_step_setup_build_folders.sh#L5)
- [clean.sh](https://github.com/termux/termux-packages/blob/master/clean.sh#L38)

Because of this, you have to manually remove `~/.termux-build` in order for the compiler to work again.

### What steps will reproduce the bug?

`build-package.sh` - recompiling specific packages
`clean.sh` - after compiling certain packages

### What is the expected behavior?

successful work

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# /data/data/com.termux/files/usr/etc/pacman.conf
[main]
Server = https://s3.amazonaws.com/termux-main.pacman/aarch64
[x11]
Server = https://s3.amazonaws.com/termux-x11.pacman/aarch64
[root]
Server = https://s3.amazonaws.com/termux-root.pacman/aarch64
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.190-20995430-abT860XXU3CUB7 #2 SMP PREEMPT Thu Feb 25 18:11:04 +07 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T860
```

### PR DESCRIPTION
**Pull request by Maxython**
Change list:
1. The value of `TERMUX_PACKAGE_FORMAT` will have the same value as `TERMUX_MAIN_PACKAGE_FORMAT` if it exists.
2. Changed the logic definition of the package manager to a more stable one.
3. Bug fix #8523.

### CODE REVIEW

File: build-package.sh [hunk 1]
```diff
@@ -273,10 +273,17 @@ source "$TERMUX_SCRIPTDIR/scripts/build/termux_step_finish_build.sh"
...
-	TERMUX_ARCH=$(dpkg --print-architecture 2>/dev/null || pacman-conf | grep Architecture | sed 's/Architecture = //g')
+	case "$TERMUX_MAIN_PACKAGE_FORMAT" in
+		"debian") TERMUX_ARCH=$(dpkg --print-architecture);;
+		"pacman") TERMUX_ARCH=$(pacman-conf | grep Architecture | sed 's/Architecture = //g');;
+	esac
 	export TERMUX_ARCH
 fi
 
+if [ -n "$TERMUX_MAIN_PACKAGE_FORMAT" ]; then
+	TERMUX_PACKAGE_FORMAT="$TERMUX_MAIN_PACKAGE_FORMAT"
```
Comment (Grimler91) [inline build-package.sh:284]: Why is two parameters, TERMUX_PACKAGE_FORMAT and TERMUX_MAIN_PACKAGE_FORMAT, with the same value needed? 

What's the difference between the two parameters?

File: scripts/build/setup/termux_setup_cmake.sh [hunk 2]
```diff
@@ -25,8 +25,8 @@ termux_setup_cmake() {
 
 		export PATH=$TERMUX_CMAKE_FOLDER/bin:$PATH
 	else
-		if [[ "$(dpkg --version 2>/dev/null)" && "$(dpkg-query -W -f '${db:Status-Status}\n' cmake 2>/dev/null)" != "installed" ]] ||
-                   [[ "$(pacman -V 2>/dev/null)" && ! "$(pacman -Q cmake 2>/dev/null)" ]]; then
+		if [[ "$TERMUX_MAIN_PACKAGE_FORMAT" = "debian" && "$(dpkg-query -W -f '${db:Status-Status}\n' cmake 2>/dev/null)" != "installed" ]] ||
```
Comment (Grimler91) [inline scripts/build/setup/termux_setup_cmake.sh:28]: So with these changes TERMUX_MAIN_PACKAGE_FORMAT is used in scripts/build and TERMUX_PACKAGE_FORMAT in packages/?

Can't the same parameter be used?

**Review by Grimler91 — CHANGES_REQUESTED** [review]
Thanks for the PR, changing the check for dpkg / pacman looks reasonable.

> The value of `TERMUX_PACKAGE_FORMAT` will have the same value as `TERMUX_MAIN_PACKAGE_FORMAT` if it exists.

Why are two variables, with the same value, needed?

Please update the commit messages:

First one says "bug fix https://github.com/termux/termux-packages/issues/8523", add a short description about what the commit changes and what bug it fixes, for example
```
build-package: ignore return status of chmod

It seem to return error when there is nothing to chmod.

Fixes https://github.com/termux/termux-packages/issues/8523.
```

Second one says "changing the logic defining packages". PR description is better: "Changed the logic definition of the package manager to a more stable one.", though please prefix the message with for example `scripts/build: ` and keep the subject line (first line) of the commit below 70 chars

Third message says: "build-packages.sh: improvement and bug fixes". This doesn't seem to describe what the commit does do

File: build-package.sh (hunk 1 above)
Comment (Maxython) [reply build-package.sh:284]: TERMUX_PACKAGE_FORMAT - this value specifies which package format will be compiled
TERMUX_MAIN_PACKAGE_FORMAT - this is a value that indicates which basic packet format the device is using  

This change will allow the device to compile the recommended package format, that is, the format that the device uses.

File: scripts/build/setup/termux_setup_cmake.sh (hunk 2 above)
Comment (Maxython) [reply scripts/build/setup/termux_setup_cmake.sh:28]: No, because TERMUX_PACKAGE_FORMAT can be changed via --format, this may cause compilation errors.

File: build-package.sh (hunk 1 above)
Comment (Grimler91) [reply build-package.sh:284]: Ok, thanks for explaining, seems reasonable!

What is 
```
if [ -n "$TERMUX_MAIN_PACKAGE_FORMAT" ]; then
	TERMUX_PACKAGE_FORMAT="$TERMUX_MAIN_PACKAGE_FORMAT"
fi
```
suppose to do though? Right now it overrides TERMUX_PACKAGE_FORMAT if TERMUX_MAIN_PACKAGE_FORMAT is set. Seems like that would break the `--format` flag

Comment (Grimler91) [reply build-package.sh:284]: Please explain what the code is suppose to do. 

To me it seems like it will override the --format arg given by user.

Comment (Maxython) [reply build-package.sh:284]: First, the value of TERMUX_PACKAGE_FORMAT is set, then after that the --format flag is checked (and the value changes even if it has already been set).

Comment (Grimler91) [reply build-package.sh:282]: Alright, please change so that it defaults to TERMUX_PACKAGE_MAIN_FORMAT for on device builds in [termux_step_setup_variables](https://github.com/termux/termux-packages/blob/master/scripts/build/termux_step_setup_variables.sh#L2) instead, to gather (most) of the defaults values there

Comment (Maxython) [reply build-package.sh]: Check, please

**Comment by Maxython** [comment]
Check, please.

**Comment by Grimler91** [comment]
Looks good. Any reason this is still a draft?

Please rebase as well

File: scripts/build/setup/termux_setup_cmake.sh (hunk 2 above)
Comment (thunder-coding) [inline scripts/build/setup/termux_setup_cmake.sh:28]: Why don't you also consider adding support for Pacman here?

**Review by thunder-coding — CHANGES_REQUESTED** [review]

File: scripts/build/setup/termux_setup_cmake.sh (hunk 2 above)
Comment (thunder-coding) [reply scripts/build/setup/termux_setup_cmake.sh:28]: Oops, seems like I didn't check that line properly. My mistake!

**Review by thunder-coding — APPROVED** [review]
