### PR TITLE
upgpkg(main/vifm): 0.13

### LINKED ISSUE #15953: Auto update failing for vifm
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the vifm package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating vifm [Current version: 0.12.1]
INFO: package being updated to 0.13.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2166k    0 2166k    0     0  2453k      0 --:--:-- --:--:-- --:--:-- 4323k

You are about to commit these changes:

--------------------
diff --git a/packages/vifm/build.sh b/packages/vifm/build.sh
index e0c6b44ce..cd7317bcf 100644
--- a/packages/vifm/build.sh
+++ b/packages/vifm/build.sh
@@ -2,9 +2,9 @@ TERMUX_PKG_HOMEPAGE=https://vifm.info/
 TERMUX_PKG_DESCRIPTION="File manager with vi like keybindings"
 TERMUX_PKG_LICENSE="GPL-2.0"
 TERMUX_PKG_MAINTAINER="@termux"
-TERMUX_PKG_VERSION=0.12.1
+TERMUX_PKG_VERSION="0.13"
 TERMUX_PKG_SRCURL=https://github.com/vifm/vifm/archive/v${TERMUX_PKG_VERSION}.tar.gz
-TERMUX_PKG_SHA256=410b2f183e9fdefb145cf6811c106e9297c9d8f7ddfe38f8840869c63e089f95
+TERMUX_PKG_SHA256=8379397b2824cc74a91f5cfa00b5496f5d08cdcec18e3d13b64c480151225ca8
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_ENABLE_CLANG16_PORTING=false
 TERMUX_PKG_DEPENDS="ncurses, file"
--------------------

bump(main/vifm): 0.13

Not committing to Git!

INFO: Trying to build package.
INFO: Package vifm exists in main repo.
Running container 'termux-package-builder' from image 'ghcr.io/termux/package-builder'...
termux - building vifm for arch aarch64...
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13133  100 13133    0     0   108k      0 --:--:-- --:--:-- --:--:--  109k
Downloading https://packages-cf.termux.dev/apt/termux-main/dists/stable/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   7178      0 --:--:-- --:--:-- --:--:--  7181
gpg: Signature made Tue 04 Apr 2023 12:24:27 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13320  100 13320    0     0   104k      0 --:--:-- --:--:-- --:--:--  104k
Downloading https://packages-cf.termux.dev/apt/termux-root/dists/root/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   1329      0 --:--:-- --:--:-- --:--:--  1330
gpg: Signature made Thu 30 Mar 2023 09:06:04 PM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13119  100 13119    0     0  40746      0 --:--:-- --:--:-- --:--:-- 40742
Downloading https://packages-cf.termux.dev/apt/termux-x11/dists/x11/Release.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   833  100   833    0     0   6888      0 --:--:-- --:--:-- --:--:--  6941
gpg: Signature made Tue 04 Apr 2023 11:05:16 AM UTC
gpg:                using RSA key CC72CF8BA7DBFA0182877D045A897D96E57CF20C
gpg: Good signature from "Termux Releases (Termux automatic builds) <contact@termux.dev>" [ultimate]
gpg:                 aka "Termux Releases (Termux automatic builds) <contact@termux.org>" [ultimate]
Downloading dependency zlib@1.2.13 if necessary...
Found zlib in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/z/zlib/zlib_1.2.13_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 60060  100 60060    0     0   520k      0 --:--:-- --:--:-- --:--:--  523k
extracting zlib to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency file@5.44 if necessary...
Found file in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/f/file/file_5.44_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  352k  100  352k    0     0   371k      0 --:--:-- --:--:-- --:--:--  371k
extracting file to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses@6.4-2 if necessary...
Found ncurses in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/n/ncurses/ncurses_6.4-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  502k  100  502k    0     0  3449k      0 --:--:-- --:--:-- --:--:-- 3462k
extracting ncurses to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-utils@6.4-2 if necessary...
Found ncurses-utils in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/n/ncurses-utils/ncurses-utils_6.4-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 86024  100 86024    0     0   587k      0 --:--:-- --:--:-- --:--:--  591k
extracting ncurses-utils to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-ui-libs@6.4-2 if necessary...
Found ncurses-ui-libs in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/n/ncurses-ui-libs/ncurses-ui-libs_6.4-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 32276  100 32276    0     0   254k      0 --:--:-- --:--:-- --:--:--  256k
extracting ncurses-ui-libs to /home/builder/.termux-build/_cache-aarch64...
Downloading dependency ncurses-ui-libs-static@6.4-2 if necessary...
Found ncurses-ui-libs-static in https://packages-cf.termux.dev/apt/termux-main/dists/stable
Downloading https://packages-cf.termux.dev/apt/termux-main/pool/main/n/ncurses-ui-libs-static/ncurses-ui-libs-static_6.4-2_aarch64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 39044  100 39044    0     0   249k      0 --:--:-- --:--:-- --:--:--  250k
extracting ncurses-ui-libs-static to /home/builder/.termux-build/_cache-aarch64...
Downloading https://github.com/vifm/vifm/archive/v0.13.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 2166k    0 2166k    0     0  2768k      0 --:--:-- --:--:-- --:--:-- 2768k
Applying patch: cmd_completion.c.patch
Applying patch: configure.ac.patch
2 out of 2 hunks FAILED -- saving rejects to file configure.ac.rej
ERROR: failed to build.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2023-04-04 18:16:14 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/4610878822">4610878822</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

### PR DESCRIPTION
**Pull request by 2096779623**
Close #15953 .

image

### CODE REVIEW

File: packages/vifm/build.sh [hunk 1]
```diff
@@ -2,11 +2,15 @@ TERMUX_PKG_HOMEPAGE=https://vifm.info/
...
+TERMUX_PKG_VERSION=0.13
 TERMUX_PKG_SRCURL=https://github.com/vifm/vifm/archive/v${TERMUX_PKG_VERSION}.tar.gz
-TERMUX_PKG_SHA256=410b2f183e9fdefb145cf6811c106e9297c9d8f7ddfe38f8840869c63e089f95
+TERMUX_PKG_SHA256=8379397b2824cc74a91f5cfa00b5496f5d08cdcec18e3d13b64c480151225ca8
 TERMUX_PKG_AUTO_UPDATE=true
 TERMUX_PKG_DEPENDS="ncurses, file"
+# https://github.com/termux/termux-packages/issues/15889
+TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
+ac_cv_func_getpwuid=yes
+"
```
Comment (xtkoba) [inline packages/vifm/build.sh:13]: Do not do this for individual package *unnecessarily*.

Comment (xtkoba) [reply packages/vifm/build.sh:13]: Rather `getpwuid()` should be disabled in this package for backward-compatibility.

Comment (xtkoba) [reply packages/vifm/build.sh]: Note that in #15889 there is no conclusion as to what is the expected behavior. There is a probability that disabling `getpwuid()` is.
