### PR TITLE
fix(main/binutils): remove leftover `termux_step_post_massage()`

### LINKED ISSUE #28554: [Bug]: binutils installs tools outside $PATH
### Problem description

Starting version 2.46.0 (also 2.46.0-1). binutils tools are installed in `/data/data/com.termux/files/usr/libexec/binutils`, where the default Termux $PATH isn't picking it up.

### What steps will reproduce the bug?

```bash
~ $ apt install binutils
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
binutils is already the newest version (2.46.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
~ $ ar
The program ar is not installed. Install it by executing:
 pkg install binutils
or
 pkg install binutils-is-llvm
```

### finding ar
```bash
~ $ find $PREFIX -name ar
/data/data/com.termux/files/usr/libexec/binutils/ar
~ $ ls /data/data/com.termux/files/usr/libexec/binutils/
addr2line  ar  as  c++filt  elfedit  gprof  ld  ld.bfd  nm  objcopy  objdump  ranlib  readelf  size  strings  strip
```
### What is the expected behavior?

Tools should be installed or at least symlinked to `$PREFIX/bin`. Unless I have missed an important change and my PATH is configured entirely wrong.

I am adding `/data/data/com.termux/files/usr/libexec/binutils` to my PATH as a workaround.

### System information

```shell
~ $ termux-info
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__APK_FILE=/data/app/~~yGzn-wsFOqUrnGMPufVzFg==/com.termux-BLU7EGYZ72vQ0LocDkbAug==/base.apk
TERMUX_APP__APK_RELEASE=F_DROID
TERMUX_APP__APP_VERSION_CODE=1022
TERMUX_APP__APP_VERSION_NAME=0.119.0-beta.3
TERMUX_APP__BUILD_DATA_DIR=
TERMUX_APP__DATA_DIR=/data/user/0/com.termux
TERMUX_APP__IS_DEBUGGABLE_BUILD=false
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__LEGACY_DATA_DIR=/data/data/com.termux
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PID=14283
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c182,c256,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__TARGET_SDK=28
TERMUX_VERSION=0.119.0-beta.3
TERMUX__APPS_DIR=/data/user/0/com.termux/termux/apps
TERMUX__HOME=/data/data/com.termux/files/home
TERMUX__PREFIX=/data/data/com.termux/files/usr
TERMUX__ROOTFS=
TERMUX__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c182,c256,c512,c768
TERMUX__UID=10182
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.45.0
Android version:
16
Kernel build information:
Linux localhost 5.4.302-qgki-g4db6e0b85171 #1 SMP PREEMPT Tue Feb 17 15:13:23 UTC 2026 aarch64 Android
Device manufacturer:
Fairphone
Device model:
FP5
Supported ABIs:
SUPPORTED_ABIS: arm64-v8a,armeabi-v7a,armeabi
SUPPORTED_32_BIT_ABIS: armeabi-v7a,armeabi
SUPPORTED_64_BIT_ABIS: arm64-v8a
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec-ld-preload.so
Installed termux plugins:
com.termux.widget versionCode:1001
com.termux.window versionCode:1001
com.termux.api versionCode:1002
com.termux.styling versionCode:1000
com.termux.boot versionCode:1000
com.termux.x11 versionCode:15
```

### PR DESCRIPTION
**Pull request by TomJo2000**
- closes #28554

- Now that there's plenty of egg on my face from the oversights in #28438 and #28542, let's triple check everything is where it should be this time around.

### CODE REVIEW

**Comment by TomJo2000** [comment]
image

Looks good on my end.
Everything seems to be accounted for.

**Comment by TomJo2000** [comment]
I'm not sure what's up with the `2.46.0.20260210` SO version on `libbdf` and `libopcodes`.
That isn't consistent with the Arch or Debian packages.

**Comment by robertkirkman** [comment]
It looks like this controls that:

https://gitlab.archlinux.org/archlinux/packaging/packages/binutils/-/blob/6eaff778d84df5038cd10eb464d0cf7c0f6b6592/PKGBUILD#L78

**Comment by TomJo2000** [comment]
Added that now, works as expected.

At severe risk of jinxing it...
*There's no way that possibly comes back to bite us in the ass later, right?*

**Comment by robertkirkman** [comment]
> Added that now, works as expected.
> 
> At severe risk of jinxing it... _There's no way that possibly comes back to bite us in the ass later, right?_

Now that you've done this, you will also need to recompile `lua-language-server` in order to avoid this error:

```
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/share/lua-language-server/bin/lua-language-server": library "libbfd-2.46.0.20260210.so" not found: needed by main executable
```

**Comment by TomJo2000** [comment]
Right.
Welp, I did say I was gonna jinx it...

**Comment by TomJo2000** [comment]
`lua-language-server` was the only previous reverse dependency for specifically `binutils-libs`.
I surmise from that that it's the only package depending on `binutils`  that we need to rebuild to ensure it links correctly.

I will also add a note about this in both build scripts.

**Review by netceil — COMMENTED** [review]
line 44 of build.sh there is a typo, "every the time" instead of "every time"

**Comment by TomJo2000** [comment]
Thanks, fixing that now.

File: packages/binutils/build.sh [hunk 1]
```diff
@@ -91,7 +98,3 @@ termux_step_post_make_install() {
 			"$TERMUX_PREFIX/bin/$TERMUX_HOST_PLATFORM-$bin"
 	done
 }
-
-termux_step_post_massage() {
-	rm -rf bin
```
Comment (robertkirkman) [inline packages/binutils/build.sh:96]: If `binutils-bin` will now not be possible to install without uninstalling `binutils-is-llvm`, then the purpose of the `binutils-bin` package will not exist anymore, so that subpackage could also be removed.

Comment (robertkirkman) [reply packages/binutils/build.sh:96]: I have an idea for what I can do. For now, merge this PR and then I will fix the conflict between `binutils` and `binutils-is-llvm` later.

Comment (TomJo2000) [reply packages/binutils/build.sh:96]: Will do, I didn't get time to look into it today unfortunately.
